### ISSUE TITLE
Always says "passphrases do not match"

### ISSUE THREAD

**Issue by Mrodent** [duplicati/duplicati#4281] opened 2020-08-09 10:57 UTC
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
W10, ordinary desktop.

- **Duplicati version**: 2.0.5.1 beta
- **Operating system**: W10
- **Backend**: ??
- Browser: Firefox... but I also tried Chrome: same (non) result

## Description
Completely new user here: trying Duplicati out.  Very disappointed that *whatever* "passphrase" I use, long or short, or even a generated one, it says "passphrases do not match".

Maybe the beta version is the wrong one to use... but when you go to your website this is the one which is proposed (heavily). Intend to try now with an older version.

## Steps to reproduce

1. Replace me
2. Replace me
3. ...

- **Actual result**:
Replace me
- **Expected result**:
Replace me

**Comment by warwickmm** [comment] 2020-08-09 18:12
2.0.5.1 is the right version to use.  I haven't heard of this issue before.  You'll might have better luck asking this in the forums.

https://forum.duplicati.com/

**Comment by warwickmm** [comment] 2020-08-09 18:14
I'm going to close this since we can't reproduce it.  Feel free to put a link here to your forum post to help others that might encounter this issue.  If we find that there's something that we can fix in the code, we can reopen this.

**Closed by warwickmm** 2020-08-09 18:14 UTC

**Comment by fe60** [comment] 2021-11-21 16:17
I faced this issue, trying to run `Duplicati.CommandLine.exe` in **Git Bash** on Windows.
Switching to Windows **Command Prompt** or **PowerShell** solved the problem.
