### ISSUE TITLE
Fresh install in Fedora doesn’t start service (solution included)

### ISSUE THREAD

**Issue by plusterkopp** [duplicati/duplicati#5596] opened 2024-10-21 16:03 UTC
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.8.1_beta_2024-05-07
- **Operating system**: Fedora 40
- **Backend**: none yet

## Description

After installation, we get the three shell scripts in /usr/bin/, all of which are rw-------- After I chmod +x the three scripts, I was able to start the service. 

## Steps to reproduce

1. Download rpm from website
2. dnf install rpm
3. edit duplicati.service file according to installation instruction for Debian
4. enable and start service

- **Actual result**:
duplicati.service: Main process exited, code=exited, status=203/EXEC
- **Expected result**:
Started duplicati.service - Duplicati web-server.

**Comment by ts678** [comment] 2024-10-21 18:50
This looks like a duplicate of [Fedora package executables do not have the correct mode #5122](https://github.com/duplicati/duplicati/issues/5122) which is fixed in Canary test.

**Comment by kenkendk** [comment] 2024-12-19 09:23
Closing issue as this is fixed in new beta.

**Closed by kenkendk** 2024-12-19 09:23 UTC
Labels: bug
