### ISSUE TITLE
Suspected memory leak

### ISSUE THREAD

**Issue by fred-cardoso** [duplicati/duplicati#4108] opened 2020-02-18 13:03 UTC
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.5.101
- **Operating system**: Linux
- **Backend**: OneDrive v2
## Description
Hello guys,

I wanted to message someone before I opened this ticket so I could point more directly to the supposed bug. So the issue is the following. I was doing a backup whenit failed with this error:
`2020-02-18 12:51:18 +00 - [Error-Duplicati.Library.Main.Operation.TestHandler-FailedToProcessFile]: Failed to process file duplicati-....`

A more detailed analysis returned the following information:
`"Key": "Error", "Value": "Insufficient memory to continue the execution of the program."`

At this point I went on I checked the RAM usage:
![image](https://user-images.githubusercontent.com/32043667/74738153-38acd900-524e-11ea-8fd8-bf5419379206.png)

At the end of the graph, you can see that there are "two steps". This steps were two tries of backing up some data, where you can see that the memory keeps going up and so forth.

This is not the first time I see this error, actually it's the 3rd. I know that is related to duplicati because it only happens when I run duplicati, where the memory usage keeps increasing. Also, after restarting duplicati docker instance, the free memory increases in more than 1GB.
![image](https://user-images.githubusercontent.com/32043667/74738515-fc2dad00-524e-11ea-93a3-10a71e5d27d3.png)

How can I try to debug this even further to find the culprit?

## Debug log
`{
  "DeletedFiles": 0,
  "DeletedFolders": 0,
  "ModifiedFiles": 0,
  "ExaminedFiles": 640,
  "OpenedFiles": 0,
  "AddedFiles": 0,
  "SizeOfModifiedFiles": 0,
  "SizeOfAddedFiles": 0,
  "SizeOfExaminedFiles": 665451250,
  "SizeOfOpenedFiles": 0,
  "NotProcessedFiles": 0,
  "AddedFolders": 0,
  "TooLargeFiles": 0,
  "FilesWithError": 0,
  "ModifiedFolders": 0,
  "ModifiedSymlinks": 0,
  "AddedSymlinks": 0,
  "DeletedSymlinks": 0,
  "PartialBackup": false,
  "Dryrun": false,
  "MainOperation": "Backup",
  "CompactResults": null,
  "VacuumResults": null,
  "DeleteResults": {
    "DeletedSetsActualLength": 0,
    "DeletedSets": [],
    "Dryrun": false,
    "MainOperation": "Delete",
    "CompactResults": null,
    "ParsedResult": "Success",
    "Version": "2.0.5.101 (2.0.5.101_canary_2020-01-23)",
    "EndTime": "2020-02-18T12:49:54.451689Z",
    "BeginTime": "2020-02-18T12:49:54.41959Z",
    "Duration": "00:00:00.0320990",
    "MessagesActualLength": 0,
    "WarningsActualLength": 0,
    "ErrorsActualLength": 0,
    "Messages": null,
    "Warnings": null,
    "Errors": null,
    "BackendStatistics": {
      "RemoteCalls": 9,
      "BytesUploaded": 0,
      "BytesDownloaded": 69866,
      "FilesUploaded": 0,
      "FilesDownloaded": 2,
      "FilesDeleted": 0,
      "FoldersCreated": 0,
      "RetryAttempts": 4,
      "UnknownFileSize": 0,
      "UnknownFileCount": 0,
      "KnownFileCount": 10,
      "KnownFileSize": 237451890,
      "LastBackupDate": "2020-02-18T11:25:05+00:00",
      "BackupListCount": 2,
      "TotalQuotaSpace": 1104880336896,
      "FreeQuotaSpace": 369315255643,
      "AssignedQuotaSpace": -1,
      "ReportedQuotaError": false,
      "ReportedQuotaWarning": false,
      "MainOperation": "Backup",
      "ParsedResult": "Success",
      "Version": "2.0.5.101 (2.0.5.101_canary_2020-01-23)",
      "EndTime": "0001-01-01T00:00:00",
      "BeginTime": "2020-02-18T12:49:39.279659Z",
      "Duration": "00:00:00",
      "MessagesActualLength": 0,
      "WarningsActualLength": 0,
      "ErrorsActualLength": 0,
      "Messages": null,
      "Warnings": null,
      "Errors": null
    }
  },
  "RepairResults": null,
  "TestResults": {
    "MainOperation": "Test",
    "VerificationsActualLength": 3,
    "Verifications": [
      {
        "Key": "duplicati-20200218T112505Z.dlist.zip.aes",
        "Value": []
      },
      {
        "Key": "duplicati-i40347f0a0cb44c1f90da53a9f0fd2923.dindex.zip.aes",
        "Value": []
      },
      {
        "Key": "duplicati-b69425c1293cc4481993cedd83b87cbe4.dblock.zip.aes",
        "Value": [
          {
            "Key": "Error",
            "Value": "Insufficient memory to continue the execution of the program."
          }
        ]
      }
    ],
    "ParsedResult": "Success",
    "Version": "2.0.5.101 (2.0.5.101_canary_2020-01-23)",
    "EndTime": "2020-02-18T12:51:18.731577Z",
    "BeginTime": "2020-02-18T12:49:55.950327Z",
    "Duration": "00:01:22.7812500",
    "MessagesActualLength": 0,
    "WarningsActualLength": 0,
    "ErrorsActualLength": 0,
    "Messages": null,
    "Warnings": null,
    "Errors": null,
    "BackendStatistics": {
      "RemoteCalls": 9,
      "BytesUploaded": 0,
      "BytesDownloaded": 69866,
      "FilesUploaded": 0,
      "FilesDownloaded": 2,
      "FilesDeleted": 0,
      "FoldersCreated": 0,
      "RetryAttempts": 4,
      "UnknownFileSize": 0,
      "UnknownFileCount": 0,
      "KnownFileCount": 10,
      "KnownFileSize": 237451890,
      "LastBackupDate": "2020-02-18T11:25:05+00:00",
      "BackupListCount": 2,
      "TotalQuotaSpace": 1104880336896,
      "FreeQuotaSpace": 369315255643,
      "AssignedQuotaSpace": -1,
      "ReportedQuotaError": false,
      "ReportedQuotaWarning": false,
      "MainOperation": "Backup",
      "ParsedResult": "Success",
      "Version": "2.0.5.101 (2.0.5.101_canary_2020-01-23)",
      "EndTime": "0001-01-01T00:00:00",
      "BeginTime": "2020-02-18T12:49:39.279659Z",
      "Duration": "00:00:00",
      "MessagesActualLength": 0,
      "WarningsActualLength": 0,
      "ErrorsActualLength": 0,
      "Messages": null,
      "Warnings": null,
      "Errors": null
    }
  },
  "ParsedResult": "Error",
  "Version": "2.0.5.101 (2.0.5.101_canary_2020-01-23)",
  "EndTime": "2020-02-18T12:51:18.75452Z",
  "BeginTime": "2020-02-18T12:49:39.279649Z",
  "Duration": "00:01:39.4748710",
  "MessagesActualLength": 20,
  "WarningsActualLength": 0,
  "ErrorsActualLength": 1,
  "Messages": [
    "2020-02-18 12:49:39 +00 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started",
    "2020-02-18 12:49:39 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  ()",
    "2020-02-18 12:49:50 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (10 bytes)",
    "2020-02-18 12:49:54 +00 - [Information-Duplicati.Library.Main.Operation.DeleteHandler-DeleteResults]: No remote filesets were deleted",
    "2020-02-18 12:49:54 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  ()",
    "2020-02-18 12:49:55 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (10 bytes)",
    "2020-02-18 12:49:55 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-20200218T112505Z.dlist.zip.aes (64,78 KB)",
    "2020-02-18 12:50:01 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-20200218T112505Z.dlist.zip.aes (64,78 KB)",
    "2020-02-18 12:50:01 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-i40347f0a0cb44c1f90da53a9f0fd2923.dindex.zip.aes (3,45 KB)",
    "2020-02-18 12:50:02 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-i40347f0a0cb44c1f90da53a9f0fd2923.dindex.zip.aes (3,45 KB)",
    "2020-02-18 12:50:02 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b69425c1293cc4481993cedd83b87cbe4.dblock.zip.aes (181,86 MB)",
    "2020-02-18 12:50:09 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-b69425c1293cc4481993cedd83b87cbe4.dblock.zip.aes (181,86 MB)",
    "2020-02-18 12:50:19 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b69425c1293cc4481993cedd83b87cbe4.dblock.zip.aes (181,86 MB)",
    "2020-02-18 12:50:27 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-b69425c1293cc4481993cedd83b87cbe4.dblock.zip.aes (181,86 MB)",
    "2020-02-18 12:50:37 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b69425c1293cc4481993cedd83b87cbe4.dblock.zip.aes (181,86 MB)",
    "2020-02-18 12:50:47 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-b69425c1293cc4481993cedd83b87cbe4.dblock.zip.aes (181,86 MB)",
    "2020-02-18 12:50:57 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b69425c1293cc4481993cedd83b87cbe4.dblock.zip.aes (181,86 MB)",
    "2020-02-18 12:51:04 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-b69425c1293cc4481993cedd83b87cbe4.dblock.zip.aes (181,86 MB)",
    "2020-02-18 12:51:14 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b69425c1293cc4481993cedd83b87cbe4.dblock.zip.aes (181,86 MB)",
    "2020-02-18 12:51:18 +00 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Failed: duplicati-b69425c1293cc4481993cedd83b87cbe4.dblock.zip.aes (181,86 MB)"
  ],
  "Warnings": [],
  "Errors": [
    "2020-02-18 12:51:18 +00 - [Error-Duplicati.Library.Main.Operation.TestHandler-FailedToProcessFile]: Failed to process file duplicati-b69425c1293cc4481993cedd83b87cbe4.dblock.zip.aes"
  ],
  "BackendStatistics": {
    "RemoteCalls": 9,
    "BytesUploaded": 0,
    "BytesDownloaded": 69866,
    "FilesUploaded": 0,
    "FilesDownloaded": 2,
    "FilesDeleted": 0,
    "FoldersCreated": 0,
    "RetryAttempts": 4,
    "UnknownFileSize": 0,
    "UnknownFileCount": 0,
    "KnownFileCount": 10,
    "KnownFileSize": 237451890,
    "LastBackupDate": "2020-02-18T11:25:05+00:00",
    "BackupListCount": 2,
    "TotalQuotaSpace": 1104880336896,
    "FreeQuotaSpace": 369315255643,
    "AssignedQuotaSpace": -1,
    "ReportedQuotaError": false,
    "ReportedQuotaWarning": false,
    "MainOperation": "Backup",
    "ParsedResult": "Success",
    "Version": "2.0.5.101 (2.0.5.101_canary_2020-01-23)",
    "EndTime": "0001-01-01T00:00:00",
    "BeginTime": "2020-02-18T12:49:39.279659Z",
    "Duration": "00:00:00",
    "MessagesActualLength": 0,
    "WarningsActualLength": 0,
    "ErrorsActualLength": 0,
    "Messages": null,
    "Warnings": null,
    "Errors": null
  }
}`

**Comment by tygill** [comment] 2020-02-20 23:41
I've hit the same problem - I'm running Duplicati in Docker on a Raspberry Pi, and when I first started I was getting these crashes periodically. I have been able to avoid the memory leak now somehow by setting the `--backup-test-percentage=0` and `--backup-test-samples=0` parameters. (Effectively disabling Duplicati's logic to download a few sample files and verify that their contents match what it expects.)

With those settings, Duplicati seems to be stable (its currently at 12 days of uptime, and I believe that was when I last updated the container).

As for actually finding and fixing the memory leak, I've so far been at a loss (I don't know how to take a memory dump in Mono or otherwise examine the process state to see what is actually leaking). I made at least one PR (#3989) attempting to clean up how some of the Disposable objects are disposed, but that didn't seem to help. At the moment, I wonder if there's some sort of memory leak in Mono itself, or some different behavior that it has about reclaiming memory than the .NET framework which is causing something to not be garbage collected. Since this is the only backend using the OAuthHttpClient (based on HttpClient) instead of the JSONWebHelper (based on HttpWebRequest), that could explain why only this backend is affected. If that is the case, I'm curious to see if moving to .NET Core would resolve this or not.

(I was the one who wrote the new OneDrive v2 backend, which is why I want to figure out why it is leaking memory.)

**Comment by drwtsn32x** [comment] 2020-02-21 00:59
@tygill - what version of Duplicati are you using?  I just checked 2.0.5.1 on my Debian Linux system and noticed it is using 2.2GB of RAM, so yeah it seems like there's a leak going on.

**Comment by drwtsn32x** [comment] 2020-02-21 01:05
Seems like it's only on non-Windows platforms, maybe.  I see it on Debian Linux and also Docker version of Duplicati.  Restarting the service/container brings memory usage back down.  Not seeing high memory usage on Windows machines though.

**Comment by tygill** [comment] 2020-02-21 01:13
I'm currently using 2.0.5.101_canary_2020-01-23, but I haven't tested this memory leak in a long while (and haven't seen any problems with the backup test disabled).

**Comment by drwtsn32x** [comment] 2020-02-21 04:47
I'm less confident there's a leak now.  When I first restarted Duplicati on Linux and docker, the memory usage was lower (like 800MB).  But now it's back up to ~2GB.  Same place it was after running for several days.  Hmmmm

**Comment by warwickmm** [comment] 2020-02-22 05:10
Perhaps the versions of mono may be relevant here.  

How are people measuring the memory usage?

**Comment by tygill** [comment] 2020-02-22 06:58
As I'm running duplicati in Docker, I've been monitoring memory usage via `docker stats duplicati`, which right now shows an idle memory usage of the container as being 34.32MiB, after being up for 13 days. (With the backup tests disabled in all backup jobs.) When I opened up the web Ui that jumped to 61.16MiB. I then enabled backup tests and ran one backup, during which I didn't see memory usage pass 300 MiB until it hit the verifying files stage (no new files needed to be backed up), at which point it hit 1. 2 Gib. Memory usage stayed at 1.2 Gib even after the job completed and showed the results in the web Ui.

My mono version in that container was:

```
Mono JIT compiler version 5.20.1.34 (tarball Tue Jul 16 22:57:45 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
```

**Comment by warwickmm** [comment] 2020-02-22 18:00
Definitely sounds like something during the verification state.  How many files (and what size) are being tested?  If you run another backup, do you see any indication of garbage collection or does the memory usage increase even more?

**Comment by fred-cardoso** [comment] 2020-02-22 18:28
@warwickmm 

I am measuring memory usage using OpenMediaVault GUI where you can study the graphics. So, not really sure about how that memory is measured.

I tried running @tygill command `docker stats duplicati` which returned this:
![image](https://user-images.githubusercontent.com/32043667/75097247-55c00f80-55a0-11ea-9d4c-d0421ab5d2b5.png)

I have been running duplicati for 4 days now, will see how much time it can go without crashing. Actually I am only running two backups a day, but the data don't change that much and there is no real differences (neither new versions on duplicati).

To be more precise, what happened when I opened this ticket, was this. I have a backup which is 300+ GB, which takes a lot of time to backup (3+ days). But, unfortunatly my internet failed two times during those days and I had to restart the backup a few times. Each time increasing even more the memory. Which makes sense on you idea of a possible leak during the verification stage.

About the files/size... Size is easy, total around 370 GB one backup and 600 MB the other. The files number... I would say something 100k files on the biggest. No idea on the other. But I can dig this further if this can help you.

**Comment by warwickmm** [comment] 2020-02-22 18:31
Thanks @fred-cardoso.  I'm also curious about any custom verification options so we can get an idea of how much data is downloaded for the verification stage.  If I recall correctly, I think it downloads 1 dblock, 1 dlist, and 1 dindex file.  With the default options, this amounts to slightly over 50 MB.

**Comment by fred-cardoso** [comment] 2020-02-22 18:35
You're welcome :-) About custom verification options, I have nothing. My backup configuration is quite simple.

- 1 - Name/Description/AES-256 enc./Key
- 2 - OneDrive V2/Destination folder/Respective API key 
- 3 - Origin path
- 4 - Scheduling, everyday, 2am
- 5 - General options: volume size: 100MB; Retention: 2 backups. No Advanced options whatsoever.

**Comment by tygill** [comment] 2020-02-28 05:19
To add another note - I recently re-enabled a retention policy on one of my backups, and that backup has been crashing with out of memory issues again. So the memory leak might also be affected by that logic as well (I suspect that it is something about the code that downloads the remote files that is causing the leak.)

**Comment by warwickmm** [comment] 2020-02-28 05:26
Hmm...I spent some time with the retention code a few months ago but don't recall any part of it that requires downloading remote files.  Do you know if any compact operations were involved in any of these out of memory examples?

**Comment by tygill** [comment] 2020-02-28 05:55
Looks like the crash was during compact (which is what I suspected). I want monitoring memory usage then, so I don't know if it was a leak or just something using too much memory (I have the 4GB model with 8GB of swap configured though, which should generally be plenty of memory I imagine).

```
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
  at (wrapper alloc) System.Object.AllocVector(intptr,intptr)
  at SharpCompress.Compressors.Deflate.InflateBlocks..ctor (SharpCompress.Compressors.Deflate.ZlibCodec codec, System.Object checkfn, System.Int32 w) [0x0003b] in <5717dfb1db2745ffb30a27e1fee78b19>:0 
  at SharpCompress.Compressors.Deflate.InflateManager.Initialize (SharpCompress.Compressors.Deflate.ZlibCodec codec, System.Int32 w) [0x00044] in <5717dfb1db2745ffb30a27e1fee78b19>:0 
  at SharpCompress.Compressors.Deflate.ZlibCodec.InitializeInflate (System.Int32 windowBits, System.Boolean expectRfc1950Header) [0x00026] in <5717dfb1db2745ffb30a27e1fee78b19>:0 
  at SharpCompress.Compressors.Deflate.ZlibCodec.InitializeInflate (System.Boolean expectRfc1950Header) [0x00000] in <5717dfb1db2745ffb30a27e1fee78b19>:0 
  at SharpCompress.Compressors.Deflate.ZlibBaseStream.get_z () [0x0002a] in <5717dfb1db2745ffb30a27e1fee78b19>:0 
  at SharpCompress.Compressors.Deflate.ZlibBaseStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00028] in <5717dfb1db2745ffb30a27e1fee78b19>:0 
  at SharpCompress.Compressors.Deflate.DeflateStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00013] in <5717dfb1db2745ffb30a27e1fee78b19>:0 
  at Duplicati.Library.Utility.Utility.ForceStreamRead (System.IO.Stream stream, System.Byte[] buf, System.Int32 count) [0x00002] in <d1f08dca12584f5088216ab591ea6345>:0 
  at Duplicati.Library.Main.Volumes.BlockVolumeReader.ReadBlock (System.String hash, System.Byte[] blockbuffer) [0x00012] in <a367a82b62d24ca192b817b089bf6436>:0 
  at Duplicati.Library.Main.Operation.CompactHandler.DoCompact (Duplicati.Library.Main.Database.LocalDeleteDatabase db, System.Boolean hasVerifiedBackend, System.Data.IDbTransaction& transaction, Duplicati.Library.Main.BackendManager sharedBackend) [0x0030c] in <a367a82b62d24ca192b817b089bf6436>:0 
  at Duplicati.Library.Main.Operation.DeleteHandler.DoRun (Duplicati.Library.Main.Database.LocalDeleteDatabase db, System.Data.IDbTransaction& transaction, System.Boolean hasVerifiedBacked, System.Boolean forceCompact, Duplicati.Library.Main.BackendManager sharedManager) [0x003ad] in <a367a82b62d24ca192b817b089bf6436>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired (Duplicati.Library.Main.BackendManager backend, System.Int64 lastVolumeSize) [0x000a5] in <a367a82b62d24ca192b817b089bf6436>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.RunAsync (System.String[] sources, Duplicati.Library.Utility.IFilter filter, System.Threading.CancellationToken token) [0x01033] in <a367a82b62d24ca192b817b089bf6436>:0 
  at CoCoL.ChannelExtensions.WaitForTaskOrThrow (System.Threading.Tasks.Task task) [0x00050] in <9a758ff4db6c48d6b3d4d0e5c2adf6d1>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter, System.Threading.CancellationToken token) [0x00009] in <a367a82b62d24ca192b817b089bf6436>:0 
  at Duplicati.Library.Main.Controller+<>c__DisplayClass14_0.<Backup>b__0 (Duplicati.Library.Main.BackupResults result) [0x0004b] in <a367a82b62d24ca192b817b089bf6436>:0 
  at Duplicati.Library.Main.Controller.RunAction[T] (T result, System.String[]& paths, Duplicati.Library.Utility.IFilter& filter, System.Action`1[T] method) [0x0026f] in <a367a82b62d24ca192b817b089bf6436>:0 
  at Duplicati.Library.Main.Controller.Backup (System.String[] inputsources, Duplicati.Library.Utility.IFilter filter) [0x00074] in <a367a82b62d24ca192b817b089bf6436>:0 
  at Duplicati.Server.Runner.Run (Duplicati.Server.Runner+IRunnerData data, System.Boolean fromQueue) [0x00349] in <e69e4c0173384a62bf88cae30cea7f3d>:0
```

**Comment by tygill** [comment] 2020-03-25 21:57
Some preliminary results from #4145 seem good - I have the latest canary which includes that change to use the older HttpWenRequest infra instead of HttpClient running on my Raspberry Pi (where I had previously been seeing memory increase when backup test settings were enabled) and after several backup runs memory usage remains consistently around 100-200 MiB. I'm currently running another backup which is deleting some old versions and doing some compaction (which was another case I was seeing memory issues), and memory usage is still constant.

It might be too early to say for sure, but it looks like avoiding the HttpClient on Mono (the new default as of this canary) helps or avoids this memory leak.

**Comment by warwickmm** [comment] 2020-03-25 23:35
If the older implementation works better, is there any reason for keeping both implementations around?  It would be nice to have just a single client for both Mono and Windows.

**Comment by tygill** [comment] 2020-03-26 00:45
There is a chance that one performs better than the other. But that might not be worth keeping both versions around.

I'd lean towards keeping the OAuthHttpClient class possibly, since it could be used for other backends in the future, but it could be removed from the Microsoft backends.

**Comment by fred-cardoso** [comment] 2020-03-27 19:25
There is clearly a difference on memory usage. I will wait a few more days to give a more precise feedback. But it seems very good.

**Comment by tygill** [comment] 2020-03-27 19:36
I've seen a positive difference in memory usage over the last few days on Mono as well, so good to hear I'm not alone.

Back to the question about keeping the HttpClient version around, one reason to keep it around is if the HttpClient and related classes are getting more performance improvements in .NET Core, since Duplicati will hopefully be able to move to that at some point.

**Comment by warwickmm** [comment] 2020-03-27 21:01
Ideally it would be nice to find out what's causing the memory leak in the HttpClient.

**Comment by tygill** [comment] 2020-03-27 21:43
I agree, but I wonder if its something specific to Mono, given that it hasn't reproed on .NET Framework as far as I know. I've looked for a way to debug memory usage in Mono, but haven't been able to find any good / maintained options unfortunately...

**Comment by warwickmm** [comment] 2020-03-27 22:40
Good point.  @fred-cardoso, can you comment on the version of mono you're using?

**Comment by fred-cardoso** [comment] 2020-03-27 22:45
@warwickmm I am not sure if its this but here it goes:

```Mono JIT compiler version 5.20.1.34 (tarball Tue Jul 16 22:57:45 UTC 2019)```

Don't forget I am running Duplicati in Docker :-)

**Comment by warwickmm** [comment] 2020-03-27 22:59
Thanks.  I believe that's exactly the same (mono 5.20.1.34 and Duplicati in Docker) as @tygill?

**Comment by tygill** [comment] 2020-03-27 23:32
Yes, that does look like the same version. I'm using the linuxserver.io duplicati image on Docker hub. (I've been meaning to switch over to the official Docker image, but haven't gotten around to that yet.)

When I last looked at Mono versions, it seemed like Debian (which most Raspberry Pi stuff seems to be based on) only supported Mono 5.x, and I think 5.20.x is the most recent 5.x version.

**Comment by fred-cardoso** [comment] 2020-03-27 23:49
I am also using linuxserver.io image.

**Comment by XstreamGit** [comment] 2020-04-09 18:49
I can confirm that this issue no longer persists for me after updating to the latest 2.0.5.104_canary_2020-03-25

**Comment by fred-cardoso** [comment] 2020-04-19 19:36
Been running a backup for almost 15 days (2+TB...) and it's still going strong! Might be fixed.

**Comment by warwickmm** [comment] 2020-08-15 22:18
Sounds like this might be fixed.  I'm going to close this, but feel free to reopen if it's still an issue.

**Closed by warwickmm** 2020-08-15 22:18 UTC
Labels: performance issue
