### ISSUE TITLE
Backup to OneDrive v2 triggers UnsupportedOption: --auth-password every time

### ISSUE THREAD

**Issue by habakuk007** [duplicati/duplicati#4099] opened 2020-02-12 21:41 UTC
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- Duplicati version: 2.0.5.1_beta_2020-01-18
- Operating system: Windows 10, 64 bit
- Backend: OneDrive v2

## Description

Every time I run the backup job I get this warning "[Warning-Duplicati.Library.Main.Controller-UnsupportedOption]: Die angegebene Option --auth-password ist nicht unterstützt und wird daher ignoriert" (The specified --auth-password option is not supported and is therefore ignored) in the result mail and as warning in the UI. And the protocol is not green but yellow.

I did not set any custom `auth-password` option.

## Steps to reproduce

1. Create a backup job with target "OneDrive v2"
2. Set option `http-operation-timeout` to 5 hours (because of [this](https://github.com/duplicati/duplicati/issues/4073))

- **Actual result**:
Get the warning on every run.
- **Expected result**:
Won't get a warning regarding an `auth-password` option

## Screenshots

![2020-02-12 22_37_05- Duplicati](https://user-images.githubusercontent.com/2253878/74379562-51e5fd80-4de8-11ea-9398-e7c162a265b4.png)

**Comment by ts678** [comment] 2020-02-13 17:53
One common way this happens is when switching from a different storage type which takes a password. Password clearing should happen IMO, but apparently does not. Manual investigation can be done with the three-dot menu on the right of the `Backup destination` line. Copy, inspect, edit if necessary, import back in, Save on final screen.

![image](https://user-images.githubusercontent.com/40771998/74462565-711f7200-4e5e-11ea-9f75-166373bee6b5.png)

What I got when I had Google Chrome save my web UI password (with me helping on username) is this:

![image](https://user-images.githubusercontent.com/40771998/74462789-c9ef0a80-4e5e-11ea-8d7d-b751449fe78c.png)

and I don't know if you have any auto-fillers enabled, or how they work. Chrome isn't the only problem.

**Comment by habakuk007** [comment] 2020-02-13 20:16
Ok, so all fields are always there but they are not visible and my browser (firefox) added a password somewhere and then this field is used... (maybe because the password field has the same name as the password field for encryption on the page before?)

Sounds strange.

I changed to another backend (FTP), deleted the password and saved everything. --> Now it works without warning

**Comment by ts678** [comment] 2020-02-13 23:21
Yes, changing to a backend with a password is the other way to make it visible so it can be removed. Potentially that loses some info you'd want for OneDrive, so I suggested editing it right on the page.

With my Chrome test, it was way too eager to autofill fields. I don't know why. It recorded login URL, then put things into _other_ pages. It also filled out job's `Name` and `Passphrase` on Screen 1  `General`.

Screen 2 `Destination` starts at `Local folder or drive`, and it filled `Username` and `Password` which presumably remained internally somewhere, after moving the dropdown to `Microsoft OneDrive v2`.

[–auth-password is not supported](https://forum.duplicati.com/t/auth-password-is-not-supported/7129/11?u=ts678)

[Duplicati keeps changin Backup Name](https://forum.duplicati.com/t/duplicati-keeps-changin-backup-name/7606/3?u=ts678)

[Backup Warnings - The supplied option –auth-password is not supported and will be ignored](https://forum.duplicati.com/t/backup-warnings-the-supplied-option-auth-password-is-not-supported-and-will-be-ignored/7687/14?u=ts678)

and some other similar reports that were not completely understood at the time might be this issue.
There didn't seem to be much in GitHub issues, but the [forum](https://forum.duplicati.com/) topics on problems like this are many.

Maybe this issue can be kept open in hopes of trying to reduce damage from eager autofill systems.
There's at least a little research available on how they work. This one is an older example of a report:

[Password Managers:  Risks, Pitfalls, and Improvements](https://forum.stanford.edu/events/2014/2014slides/security/Suman%20pwdmgr.pdf)

The possible other part of full solurion is the cleaning-when-changing-storage-types question. Some fields make more sense to carry in than others do. There might be an open issue on this part already.

**Comment by habakuk007** [comment] 2020-02-14 07:56
Thanks for your answer!

For me this is fixed now.

**Comment by warwickmm** [comment] 2020-02-15 05:30
Closing this as a duplicate of issue #3082.

**Closed by warwickmm** 2020-02-15 05:30 UTC

**Comment by ts678** [comment] 2020-02-15 22:19
> Closing this as a duplicate of issue #3082.

Only part of this relates to changing backend type. The other part is looking into autofill confusion.

**Comment by warwickmm** [comment] 2020-02-16 00:57
We should probably create a separate ticket for the autofill issue, with a description of how to reproduce the issue.
