### ISSUE TITLE
Duplicati 2.0 is not capable of reading files with path name larger than 256 characters

### ISSUE THREAD

**Issue by mickmm** [duplicati/duplicati#1451] opened 2015-09-02 14:51 UTC
I'm using duplicati 2.0 preview and i'm having an error like this with files larger than 256 characters:

2015-07-03 02:06:38Z - Warning: Failed to process path: h:\some_large _path.JPG
System.ArgumentException: Nombre no válido.
Nombre del parámetro: name
   en System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   en System.Security.AccessControl.NativeObjectSecurity..ctor(Boolean isContainer, ResourceType resourceType, String name, AccessControlSections includeSections, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   en System.Security.AccessControl.DirectorySecurity..ctor(String name, AccessControlSections includeSections)
   en Duplicati.Library.Snapshots.SystemIOWindows.GetAccessControlFile(String path)
   en Duplicati.Library.Snapshots.SystemIOWindows.GetMetadata(String path)
   en Duplicati.Library.Snapshots.WindowsSnapshot.GetMetadata(String file)
   en Duplicati.Library.Main.Operation.BackupHandler.GenerateMetadata(String path, FileAttributes attributes)
   en Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(String path, FileAttributes attributes)

2015-07-03 02:06:38Z - Warning: Failed to process path: h:\some_large _path.JPG
System.ArgumentException: Nombre no válido.
Nombre del parámetro: name
   en System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   en System.Security.AccessControl.NativeObjectSecurity..ctor(Boolean isContainer, ResourceType resourceType, String name, AccessControlSections includeSections, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   en System.Security.AccessControl.DirectorySecurity..ctor(String name, AccessControlSections includeSections)
   en Duplicati.Library.Snapshots.SystemIOWindows.GetAccessControlFile(String path)
   en Duplicati.Library.Snapshots.SystemIOWindows.GetMetadata(String path)
   en Duplicati.Library.Snapshots.WindowsSnapshot.GetMetadata(String file)
   en Duplicati.Library.Main.Operation.BackupHandler.GenerateMetadata(String path, FileAttributes attributes)
   en Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(String path, FileAttributes attributes)

This error makes the backup useless.

Maybe, the program may be must use \?\ to read the file. https://msdn.microsoft.com/en-us/library/aa365247.aspx.

Greetings

**Comment by mickmm** [comment] 2015-09-02 16:15
Maybe this also can help to solve the problem http://zetalongpaths.codeplex.com/

**Comment by agrajaghh** [comment] 2015-09-02 18:55
duplicate of #1380 ?

**Comment by kenkendk** [comment] 2015-09-04 11:12
Yes, this is a duplicate of #1380.

Duplicati is actually using AlphaFS to overcome the path limitation.

The problem here is that the exception is supposed to be a "System.IO.PathTooLongExeception", but instead the .Net library throws a "System.ArgumentException".

**Closed by kenkendk** 2015-09-04 11:12 UTC
Labels: duplicate
