### ISSUE TITLE
Rebuild of database fails - Bare metal recovery not working

### ISSUE THREAD

**Issue by PrismaComputer** [duplicati/duplicati#1218] opened 2014-12-01 12:21 UTC
Hello,

a previously interrupted backup can be restored locally without missing files if the backup has completed twice after interruption, see #1214. But it is not possible to restore this backup bare metal. Once an interruption occurred, bare metal recovery is never possible again.

Reason: Rebuild of database fails within "RecreateDatabaseHandler".
Testscenario: Do a backup and interrupt it (e.g. kill commandline EXE). Afterwards start the backup again twice. First backup set is still incomplete, second backup should be restoreable without missing files at least locally (not bare metal).

But a bare metal recovery fails always. Debugging the code while doing a bare metal recovery we noticed 2 different cases:
* case 1: table "File" doesn't contain any files
* case 2: inconsistencies regarding lengths appeared within "LocalDatabase.VerifyConsistency"

We assume both cases are a consequential error of #1214.

We hope issue #1214 could be solved as soon as possible. Please let us know if you need further information.

Cheers Gregor

**Comment by kenkendk** [comment] 2015-01-01 19:31
The problem was that there is a temporary lookup table in use.

This lookup table was created before removing the interrupted volumes, causing the the run to use an outdated lookup table. This caused the restore to fail in various ways.

I have fixed this and added some extra fixes for more robust handling of backups.

Can you verify that the problem is now fixed?

**Closed** 2015-03-05 08:48 UTC
Labels: bug
