### ISSUE TITLE
install fails on synology dsm

### ISSUE THREAD

**Issue by junkb** [duplicati/duplicati#2406] opened 2017-03-27 04:37 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.53
**Operating System:** synology dsm 6.1-15047 update 2
**Backend:** n/a

### Bug description
i am unable to install the spk file.  during the install process, the confirm settings window displays the package details, and indicates there is 8.8 gb of available space on the volume.  upon clicking "apply", a message is shown which states "the available disk space of this system is insufficient."

on the system itself, df -hl confirms there is 8.8 gb of available space:

```bash
df -hl /dev/vg1/volume_4
Filesystem         Size  Used Avail Use% Mounted on
/dev/vg1/volume_4  9.7G  808M  8.8G   9% /volume4
```

### Steps to reproduce
- attempt to install the software on a synology nas
![screen shot 2017-03-27 at 00 33 20](https://cloud.githubusercontent.com/assets/7424193/24341131/0710e56a-12a7-11e7-8a29-a087974a46fa.png)
![screen shot 2017-03-26 at 19 22 51](https://cloud.githubusercontent.com/assets/7424193/24341137/14072d7e-12a7-11e7-958f-0b7a7eb58cb3.png)

**Comment by kenkendk** [comment] 2017-03-27 19:55
That is odd, as the installer should only request the size of the extracted files, which is waaay less than 8GB.

**Comment by junkb** [comment] 2017-03-28 03:54
what can i do to help troubleshoot?

**Comment by kenkendk** [comment] 2017-08-11 08:12
I have made an updated .spk, is this still an issue?

**Comment by MartinRohrbach** [comment] 2017-09-08 16:22
Just tried to install "duplicati-2.0.2.1_beta_2017-08-01" and it fails the same way despite ~ 11 GB being free. Then found "duplicati-2.0.2.3_canary_2017-09-08" which is newer than your last comment, same error though.

**Comment by MartinRohrbach** [comment] 2017-09-08 16:37
Update, found this:

https://global.download.synology.com/download/Document/DeveloperGuide/DSM_Developer_Guide.pdf

And the note on extractsize property:

Note:
1. In DSM 5.2 or order, the size based on byte unit.
2. In DSM 6.0 or newer, the size based on kilobyte unit.
Value: Size unit
Default Value: The byte size of SPK file of package

It looks like the packages use bytes rather than kilobytes. Can't verify as I don't (yet) know how to package the changed INFO file again. Or maybe I'm completely on the wrong track ...

**Comment by MartinRohrbach** [comment] 2017-09-08 21:10
And another update: dividing the extractsize by 1024 indeed fixes the issue. Makes sense, the problem only shows if you install on a volume with < 25 GB free space and not < 25 MB as intended, and most people will have more free space than that.

**Comment by junkb** [comment] 2018-01-29 05:20
thanks for this - i can confirm the same works for me.  adjusting extractsize in INFO fixes the issue.  can this be corrected in the official download?

**Comment by kenkendk** [comment] 2018-01-29 13:44
Good find! I have updated the build script such that this is fixed in the next build.

**Closed** 2018-01-29 13:44 UTC
Labels: Synology, bug, installer issue, pending user feedback

**Comment by junkb** [comment] 2018-02-17 22:30
i've just installed 2.0.2.19 and i can confirm that this issue is now gone - thanks!
