### ISSUE TITLE
file and folder starting with period, folder skipped

### ISSUE THREAD

**Issue by basaran** [duplicati/duplicati#3195] opened 2018-04-27 15:44 UTC
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: Duplicati - 2.0.2.1_beta_2017-08-01
- **Operating system**: Windows 10
- **Backend**: All

## Description

Duplicati does not list/restore a folder starting with period, when a file with a similar name exists in the same folder.

## Steps to reproduce

1. Create a folder c:\test
2. Go to command prompt
3. input "mkdir c:\test\.special.d
3. Input "type nul > c:\test\.special"

Go to duplicati, and backup the folder as a new job.

- **Actual result**:
Try to restore the backup and you won't see the folder, but only the file.

- **Expected result**:
Both the folder and the file should exist

## Debug log

No errors are shown

**Comment by warwickmm** [comment] 2018-05-20 22:45
I'm unable to reproduce this with Duplicati 2.0.3.5 on Linux.  After creating the file and folder as described above, they both show up in the restore list.

However, the steps to reproduce appear to be different than described, since the folder name does not start with a period?

1. Are the "steps to reproduce" correct?
2. Are you able to reproduce this with a newer version of Duplicati?

**Comment by warwickmm** [comment] 2019-03-21 04:22
Closing since we are unable to reproduce this issue.  If you are able to provide more details on how to reproduce this, please feel free to reopen this issue.

**Closed by warwickmm** 2019-03-21 04:22 UTC
Labels: not reproducible, pending user feedback, windows
