### ISSUE TITLE
Debian mono version

### ISSUE THREAD

**Issue by a1ezzz** [duplicati/duplicati#2131] opened 2016-11-18 15:38 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.32
**Operating System:** Debian 8.6

### Bug description
I've found that recent debian distributives have old mono version (3.2.8), and that leads to many errors. For example:
 - debian can't update mono SSL certificates (so duplicati won't work with servers over SSL and it isn't possible to build duplicati since nuget can't download dependencies)
 - debian doesn't connect to webdav servers. The following error is raised:

```
Invalid type System.Net.HttpWebRequest for instance field Amazon.Runtime.Internal.HttpRequest:_request                                         
Invalid type System.Net.HttpWebRequest for instance field System.Data.Services.Client.HttpWebRequestMessage:httpRequest                        
Invalid type System.Net.HttpWebRequest for instance field Microsoft.SharePoint.Client.SharePointOnlineCredentialsWebRequestEventArgs:m_webRequest                                                                                                                                             
Invalid type System.Net.HttpWebRequest for instance field Microsoft.SharePoint.Client.RequestForwarder:m_webRequest                            
Invalid type System.Net.HttpWebRequest for instance field Microsoft.WindowsAzure.Storage.Table.DataServices.TableServiceContext:currentRequest 
Invalid type Microsoft.WindowsAzure.Storage.Table.DataServices.TableServiceContext for instance field Microsoft.WindowsAzure.Storage.Table.DataServices.TableServiceQuery`1[TElement]:<Context>k__BackingField                                                                                
Invalid type System.Net.HttpWebRequest for instance field Microsoft.WindowsAzure.Storage.RequestEventArgs:<Request>k__BackingField             
System.TypeLoadException: Failure has occurred while loading a type.                                                                           
  at Duplicati.Library.Backend.WEBDAV.Test () [0x00000] in <666fa144a0a34a21841342ca91f735f7>:0 
  at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection (System.String url, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) [0x000cb] in <25af83a2e86c42b8b2999c0abefb744a>:0 
  at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.POST (System.String key, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) [0x000af] in <25af83a2e86c42b8b2999c0abefb744a>:0 
  at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) [0x002ad] in <25af83a2e86c42b8b2999c0abefb744a>:0 
```

If I update previously installed mono as it is described here http://www.mono-project.com/docs/getting-started/install/linux/ and mix mono that comes from official repositories with mono from mono-project.com, then only some bugs are fixed. For example, the following error appears if I test webdav connection: "Failed to connect: Failure has occurred while loading a type." Call stack:

```
Invalid type System.Net.HttpWebRequest for instance field Amazon.Runtime.Internal.HttpRequest:_request                                         
Invalid type System.Net.HttpWebRequest for instance field System.Data.Services.Client.HttpWebRequestMessage:httpRequest                        
Invalid type System.Net.HttpWebRequest for instance field Microsoft.SharePoint.Client.SharePointOnlineCredentialsWebRequestEventArgs:m_webRequest                                                                                                                                             
Invalid type System.Net.HttpWebRequest for instance field Microsoft.SharePoint.Client.RequestForwarder:m_webRequest                            
Invalid type System.Net.HttpWebRequest for instance field Microsoft.WindowsAzure.Storage.Table.DataServices.TableServiceContext:currentRequest 
Invalid type Microsoft.WindowsAzure.Storage.Table.DataServices.TableServiceContext for instance field Microsoft.WindowsAzure.Storage.Table.DataServices.TableServiceQuery 1[TElement]:<Context>k__BackingField                                                                                
Invalid type System.Net.HttpWebRequest for instance field Microsoft.WindowsAzure.Storage.RequestEventArgs:<Request>k__BackingField             
System.TypeLoadException: Failure has occurred while loading a type.                                                                           
  at Duplicati.Library.Backend.WEBDAV.Test () [0x00000] in <666fa144a0a34a21841342ca91f735f7>:0 
  at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection (System.String url, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) [0x000cb] in <25af83a2e86c42b8b2999c0abefb744a>:0 
  at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.POST (System.String key, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) [0x000af] in <25af83a2e86c42b8b2999c0abefb744a>:0 
  at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) [0x002ad] in <25af83a2e86c42b8b2999c0abefb744a>:0 
```

I've fixed previous error by updating ibmono-security4.0-cil from 3.2.8+dfsg-10 version to 4.6.2.7-0xamarin2. But I don't know how many bugs are still there.

If I install mono from mono-project.com on a fresh system, then everythin works great. The Latest Ubuntu version 16.10 and the latest LTS Ubuntu version (16.04) comes with mono version 4.2.1 and duplicati works normal. The easiest way to resolve this issue is to update required mono version, but debian users won't be able to install duplicati easily and won't be able to do simple backup to a local drive.

**Comment by kenkendk** [comment] 2017-01-20 08:47
Is this still an issue? I raised the mono dependency to >= 3.0 with bd661268f827754681971da3042596a62ed80bfd.

For the SSL stuff, that is a mess. You can install `ca-certificates-mono` and that should fix it.

Most often the `TypeLoadException` is caused by a missing package.
You can use the environment variables:

```
export MONO_LOG_MASK=asm 
export MONO_LOG_LEVEL=debug
```

To get more information about what it is looking for that it could not find.
If there is something missing, we can add that to the dependency list.

**Comment by a1ezzz** [comment] 2017-01-25 16:38
I've tested and everything works the same way. There is mono-runtime-3.2.8 in default debian repositories and there is no ca-certificates-mono package. So, duplicati (2.0.1.44) was installed without any error, but without required SSL certificates.

**Comment by ts678** [comment] 2021-04-02 22:34
[cert-sync](https://www.mono-project.com/docs/about-mono/releases/3.12.0/#cert-sync) was added in mono 3.12.0, and "Mono users on Linux no longer need to run mozroots to get SSL working." makes me think that was the thing to do for mono 3.2.8 certificates. But that's long ago, and mono requirement is now 5.0.0 for Beta and 5.10.0 soon. Debian 10 Buster has a new enough mono, but Debian 9 Stretch does not (so it needs a mono-project.com one). Is issue still relevant?

**Comment by warwickmm** [comment] 2021-04-15 17:03
Closing this since it's out of date.

**Closed by warwickmm** 2021-04-15 17:03 UTC
Labels: pending user feedback
