### ISSUE TITLE
Backup to google drive doesn't work again

### ISSUE THREAD

**Issue by b00nish** [duplicati/duplicati#1398] opened 2015-06-23 11:32 UTC
Hi

Some weeks ago, we saw this issue that the BackUp to Google drive stopped working. A bit later it 'magically' started working again, but since today, it seems to be broken once more.

I get tons of errors like this:

***
Fehler: Dateiauflistung nicht aufrufbar: Execution of authentication request returned unexpected result: 404

Error: System.Exception: Dateiauflistung nicht aufrufbar: Execution of authentication request returned unexpected result: 404 ---> Google.GData.Client.GDataRequestException: Execution of authentication request returned unexpected result: 404
***

Did Google change something with their authentication again?

**Comment by agrajaghh** [comment] 2015-06-23 12:09
yes, have a look at #1347

**Comment by kenkendk** [comment] 2015-07-02 20:07
This has been fixed in source code.

If you want to test the preview that is not yet released for automatic update, you can find it here:
http://updates.duplicati.com/preview/duplicati-2.0.0.86_preview_2015-07-02.zip

**Closed by kenkendk** 2015-07-02 20:07 UTC

**Comment by b00nish** [comment] 2015-07-07 11:03
I guess this will not be fixed in Duplicati 1.3.x?

If I guess right: Is the 2.0 preview fit for 'productive' use?

**Comment by kenkendk** [comment] 2015-07-07 12:49
I am not able to spend the time making the updated 1.3.x build.

There are a few reports of a local database meltdown in 2.0 (check the backup-corruption label in the issues list). I have not followed up on all of them, but it seems they were caused by an older version of Duplicati combined with an upgrade.

Duplicati 2.0 is designed to be more durable, but it has not seen extensive use yet, so I am reluctant to label it beta.
