### ISSUE TITLE
New feature: GUI custom command

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#2403] opened 2017-03-26 11:45 UTC
It would be great to have in GUI in advanced section "Custom command feature".
For example when I wanted to run these commands https://github.com/duplicati/duplicati/issues/1122#issuecomment-53686217 I need to drop to CommandLine version of Duplicati.
But when there is no access on that PC via RDP/VNC - WEB GUI is only option these commands cannot be run.
Feature could look like plain text box where eg. "delete webdav://abc/ --version=1,3,5 --no-auto-compact" are entered and then executed as is.
Or second version where eg. "delete webdav://abc/ --version=1,3,5 --no-auto-compact" is entered, but then additional properties from config are appended like logging, snapshot policy, mail....

These would allow complete remote management even for advanced tasks - at least until each command will have proper GUI (if this is a strategy).

**Comment by kenkendk** [comment] 2017-03-27 14:16
Yes, I have looked into it and hope to get it done soon.

The problem is piping the output to the web-page.

**Comment by kenkendk** [comment] 2017-04-05 07:36
Fixed with c99b23c1d5649fc7ef101cd5aed8023de856dbe9

**Closed by kenkendk** 2017-04-05 07:36 UTC
Labels: enhancement
