### ISSUE TITLE
Unwanted change of  start time

### ISSUE THREAD

**Issue by ccastello** [duplicati/duplicati#2863] opened 2017-11-03 10:53 UTC
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Ubuntu 16.04.3 LTS
- **Backend**: Google Drive

## Description

My computer is in the timezone Europe/Paris. Last week (before the time change), a planned work start at 12:31 (Europe/Paris). After the time change, without change by the user, the work start at 11:31 (Europe/Paris).

## Debug log

Extract of the history
- 31 oct. 2017 11:34: Result
- 31 oct. 2017 11:34: Message
- 30 oct. 2017 11:35: Result
- 30 oct. 2017 11:34: Message
- 30 oct. 2017 11:34: Message
- 30 oct. 2017 11:34: Message
- 27 oct. 2017 12:42: Result
- 27 oct. 2017 12:40: Message
- 26 oct. 2017 12:35: Result
- 26 oct. 2017 12:34: Message
- 26 oct. 2017 12:33: Message
- 25 oct. 2017 12:34: Result
- 25 oct. 2017 12:32: Message
- 25 oct. 2017 12:32: Message
- 25 oct. 2017 12:32: Message
- 25 oct. 2017 12:32: Message
- 25 oct. 2017 12:32: Message
- 24 oct. 2017 12:33: Result
- 24 oct. 2017 12:33: Message
- 24 oct. 2017 12:33: Message

**Comment by slurdge** [comment] 2017-11-03 11:06
I'm on the same timezone, but I didn't have such a change. Maybe it's related to some locale options?

**Comment by slurdge** [comment] 2017-11-03 11:46
@ccastello Unfortunately I'm not intimate yet with Duplicati. However, my testing OS is Windows. One reason would be that on Linux, times are stored as UTC whereas on Windows as local time. If time is stored as UTC, you will see this behavior (because from Duplicati POV, this is the "same" time).

**Comment by kenkendk** [comment] 2017-11-19 16:53
This happens because of Daylight Savings Time. The time for "when should backup run" is stored internally in UTC (which does not use DST), so when your local time changes, it is a different time.
I am closing this as it is a duplicate of #1364

**Closed by kenkendk** 2017-11-19 16:53 UTC
