### ISSUE TITLE
Execlude not works with "/" as last character

### ISSUE THREAD

**Issue by DaWe35** [duplicati/duplicati#3961] opened 2019-10-24 16:51 UTC
- **Duplicati version**: 2.0.4.32_canary_2019-10-24
- **Operating system**: Ubuntu 18.04
- **Backend**: Any

## Description

There is an inconsistency on the backup source editor page. When I add a backup path directory, I need to put a "/" at the end of the path - otherwise, it's just a file (the GUI warns for this).
But when I want to exclude a directory, I need to remove the "/' - for example, "/var/cache/" won't work,  need to use "/var/cache". Why? And why the GUI didn't warns me??

- **Actual result**:
Exclude /var/cache/ not works
- **Expected result**:
Gui warning or just remove the last character if it is a "/"

## Reproduce
https://youtu.be/oUWyPOUIzQk

## Screenshots
When adding a path, GUI warns me:
![2](https://user-images.githubusercontent.com/10603822/67507215-c573cb80-f68e-11e9-9455-60cacba02546.jpg)

The only way it works, untraceable where I need to put "/" as the last character:
![1](https://user-images.githubusercontent.com/10603822/67507214-c573cb80-f68e-11e9-8c39-6b618a59f3a8.jpg)

**Comment by drok** [comment] 2019-12-08 02:16
I think this behaviour is correct. The trailing slash should be used in ambiguous cases, ie "path", which can be either a directory or a file. However, when you "`exclude folder`" or "`exclude file`", there is nothing ambiguous about your intention.

There is no need to allow sloppy syntax in this case, especially since the UI gives immediate feedback by showing the effect of the "`exclude folder`" and "`exclude file`" filters.

However, if the user **wants to be sloppy**, they can choose the option "`exclude directories/files whose names contain`" or one of the regexes.

Please don't change the behaviour of the UI.

**Comment by DaWe35** [comment] 2019-12-08 07:02
> 
> 
> I think this behaviour is correct. The trailing slash should be used in ambiguous cases, ie "path", which can be either a directory or a file. However, when you "`exclude folder`" or "`exclude file`", there is nothing ambiguous about your intention.
> 
> There is no need to allow sloppy syntax in this case, especially since the UI gives immediate feedback by showing the effect of the "`exclude folder`" and "`exclude file`" filters.
> 
> However, if the user **wants to be sloppy**, they can choose the option "`exclude directories/files whose names contain`" or one of the regexes.
> 
> Please don't change the behaviour of the UI.

Have you read my description? Have you watched my youtube video?
I accidentally created a recursive backup (backup in backup in backup... every day), because exclude does not work with "*/", because **the immediate feedback is hidden** (an alert can help me, but not a red X after I opened my all fucking subfolders). I'm not a stupid user, this is a clear bug, please watch my video.

**Comment by drok** [comment] 2019-12-08 08:35
Hi DaWe35,

Yes, I read your description and watched your youtube video, several times, before replying.

When you type your exclude filters blind, without your "Source Data" expanded, there is always a chance you'll mistype something and your config won't work as intended. I would suggest expanding your folders so you can see your excludes in action, it's very useful for debugging your configuration as you type it.

Alternately, if you do not want to use the immediate feedback feature, run your first backup as a test, and check that it contains exactly what you intended.

You are arguing that the UI should either auto-correct your typed excludes, or pop a warning, all because you don't want to use the immediate feedback feature (to avoid expanding the folder structure). I don't think your expectation is reasonable.

Furthermore, if the UI were to auto-correct blindly-typed excludes, this would no doubt lead to unexpected behaviours. Likewise, warning popup spam is annoying.

I still think the way the UI is implemented, by providing immediate feedback on the filters is brilliant. Immediate feedback appears to only work for "exclude folder" and "exclude file", but not for regexes, extensions, etc (I'm using 2.0.4.5, maybe this was fixed in a later version)

**Comment by DaWe35** [comment] 2019-12-08 10:22
In Linux, `a/b/c/` is a valid folder path. Repertory needs to be compatible with this, or warn me, if not because I pasted my path from somewhere.

![kép](https://user-images.githubusercontent.com/10603822/70388026-cba6d880-19ac-11ea-84b7-b1981788fb2d.png)
So if you include a folder, you need to add / to the end of the path. If you exclude, you need to enter the path without /. And you say that's not a bug?

**Closed** 2023-12-09 23:22 UTC
Labels: bug, filters
