### ISSUE TITLE
OD4B - password?

### ISSUE THREAD

**Issue by zappe** [duplicati/duplicati#1813] opened 2016-06-15 14:43 UTC
How is the password stored?
When I edit the backup I see it in cleartext, is it possible to hide that?
##

**Comment by zappeee** [comment] 2016-09-06 10:36
Any updates?

**Comment by zappeee** [comment] 2016-09-06 11:24
Another thing.
After adding the connection the password is shown in clear text under step 1, General, and under "Backup to >"

**Comment by kenkendk** [comment] 2017-02-02 08:47
Sorry about the labels, this is actually a duplicate of #2024

**Closed by kenkendk** 2017-02-02 08:47 UTC
Labels: duplicate
