### ISSUE TITLE
Support marker file for excluding directories

### ISSUE THREAD

**Issue by mdekstrand** [duplicati/duplicati#1482] opened 2015-10-27 12:22 UTC
Right now, there is the `--exclude-files-attributes` option to exclude files based on attributes.

It would be useful to add a feature present in some other backup systems, such as burp, to exclude directories (and their descendants) based on the presence of a marker file such as `_nobackup`. Then a user could exclude content just by going and creating marker files rather than figuring out how to write exclude lines that match those files.
##

**Comment by kenkendk** [comment] 2015-10-28 09:22
Yes, that makes sense.

**Comment by ironjohn** [comment] 2015-11-06 01:43
I would like to add a recommendation to format the marker file specifically for duplicati because something generic like _nobackup could be used by other software.  You could adopt ".dpcignore" (like .gitignore for git) to keep from stepping on the toes of dev's that did not consider the possibility.

**Comment by ts678** [comment] 2018-08-12 22:33
2.0.3.7 canary change log says "Added option to exclude folders based on the existence of a marker file".

2.0.3.9 help text shows how the issue about the marker name was resolved:

  --ignore-filenames
    Use this option to set a filename, or list of filenames, that indicate
    exclusion of a folder which contains it. A common use would be to have a
    file named something like ".nobackup" and place this file into folders
    that should not be backed up.

**Comment by seerickcode** [comment] 2018-10-01 13:51
So this is in the main documentation, but not currently implemented ? 

`Warnings: [
    The supplied option --ignore-filenames is not supported and will be ignored,
    Failed to process path: /run/snapd/ns/lxd.mnt => Win32 IO returned 25. Path: /run/snapd/ns/lxd.mnt
]
`

( 2.0.3.3_beta_2018-04-02)

**Comment by ts678** [comment] 2018-10-01 17:36
I assume it's more like "not currently released in beta" because "( 2.0.3.3_beta_2018-04-02)" is the latest.
Perhaps that will change soon, however until then, anyone who is willing to change to canary can do so.

[Settings in Duplicati](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#settings-in-duplicati) describes update channels, however downgrading Duplicati (e.g. back to 2.0.3.3) is sometimes complicated by the need to manually downgrade the database format. Using a separate test system for canary can avoid this, as well as keeping any unexpected canary bugs away from production.

Easier still would be to wait for a new beta, however if canary really has an issue it'd be nice to hear now.

**Comment by jstasiak** [comment] 2020-06-21 20:47
Driveby comment:

> I would like to add a recommendation to format the marker file specifically for duplicati because something generic like _nobackup could be used by other software. You could adopt ".dpcignore" (like .gitignore for git) to keep from stepping on the toes of dev's that did not consider the possibility.

`CACHEDIR.TAG` (from https://bford.info/cachedir/, mentioned in #3250) seems like it's both generic enough (it's supported by other software) and not particularly risky.

**Comment by warwickmm** [comment] 2020-08-16 17:45
I believe the `--ignore-filenames` option provides the desired functionality.  This was released in versions 2.0.3.7 (canary) and 2.0.4.5 (beta).  I tested this and it appears to work as intended.  If that's not the case, feel free to reopen this.

**Closed by warwickmm** 2020-08-16 17:45 UTC
Labels: core logic, enhancement, minor change

**Comment by vlsi** [comment] 2024-03-11 16:19
> I believe `--ignore-filenames` is a different feature.

It would be great to treat `CACHEDIR.TAG` as a default file that excludes the directory from backups though. Otherwise everybody has to configure it explicitly.
