### ISSUE TITLE
List large folder in Onedrive for business (od4b)

### ISSUE THREAD

**Issue by Bruceforce** [duplicati/duplicati#2580] opened 2017-07-01 16:41 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.69
**Operating System:** Debian 8.8 (Kernel 3.16.0-4-amd64)
**Mono Version:** Mono JIT compiler version 5.0.1.1 (2017-02/5077205 Thu May 25 09:19:47 UTC 2017)

### Bug description
When I try to list the files of a failed Onedrive for business Backup with ~112 GB (50 MB per file) the command returns an empty list. If I run the same command on a different folder with just a single file in it's working and listing that single file.

It could be related to #2474 because I got a lot of these messages during backup and hat to restart over and over again until it finally can't list the files anymore. 

I also tried to create a whole new Backup with the same result. After a few crashes and restarts with the error mentioned in #2474 it also couldn't list the files anymore. 

If I look in the Onedrive for business webinterface the files are all there.

I was thinking about trying it again with a larger filesize. If that's the root of the error it may be added to #1788

### Steps to reproduce
- run `mono Duplicati.CommandLine.BackendTool.exe LIST "od4b://...` on a od4b backup with ~112 GB (50 MB per file)

**Actual result:** 

> Name    Dir/File        LastChange      Size

(no files listed)

**Expected result:** 
> Name    Dir/File        LastChange      Size
... ... ... ...
... ... ... ...

(files in that folder get listed)
### debug log
If I try to run `mono Duplicati.CommandLine.exe repair "od4b://...` I get:

>   Listing remote folder ...
Duplicati.Library.Interface.UserInformationException: No files were found at the remote location, perhaps the target url is incorrect?
  at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.DoRun (Duplicati.Library.Main.Database.LocalDatabase dbparent, System.Boolean updating, Duplicati.Library.Utility.IFilter filter, Duplicati.Library.Main.Operation.RecreateDatabaseHandler+NumberedFilterFilelistDelegate filelistfilter, Duplicati.Library.Main.Operation.RecreateDatabaseHandler+BlockVolumePostProcessor blockprocessor) [0x000dc] in <265b26535dcf483587ba8737e917cffa>:0
  at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.Run (System.String path, Duplicati.Library.Utility.IFilter filter, Duplicati.Library.Main.Operation.RecreateDatabaseHandler+NumberedFilterFilelistDelegate filelistfilter, Duplicati.Library.Main.Operation.RecreateDatabaseHandler+BlockVolumePostProcessor blockprocessor) [0x00032] in <265b26535dcf483587ba8737e917cffa>:0
  at Duplicati.Library.Main.Operation.RepairHandler.RunRepairLocal (Duplicati.Library.Utility.IFilter filter) [0x000b0] in <265b26535dcf483587ba8737e917cffa>:0
  at Duplicati.Library.Main.Operation.RepairHandler.Run (Duplicati.Library.Utility.IFilter filter) [0x00138] in <265b26535dcf483587ba8737e917cffa>:0
  at Duplicati.Library.Main.Controller+<>c__DisplayClass20_0.<Repair>b__0 (Duplicati.Library.Main.RepairResults result) [0x0001c] in <265b26535dcf483587ba8737e917cffa>:0
  at Duplicati.Library.Main.Controller.RunAction[T] (T result, System.String[]& paths, Duplicati.Library.Utility.IFilter& filter, System.Action`1[T] method) [0x0014b] in <265b26535dcf483587ba8737e917cffa>:0
  at Duplicati.Library.Main.Controller.RunAction[T] (T result, Duplicati.Library.Utility.IFilter& filter, System.Action`1[T] method) [0x00007] in <265b26535dcf483587ba8737e917cffa>:0
  at Duplicati.Library.Main.Controller.Repair (Duplicati.Library.Utility.IFilter filter) [0x0001a] in <265b26535dcf483587ba8737e917cffa>:0
  at Duplicati.CommandLine.Commands.Repair (System.IO.TextWriter outwriter, System.Action`1[T] setup, System.Collections.Generic.List`1[T] args, System.Collections.Generic.Dictionary`2[TKey,TValue] options, Duplicati.Library.Utility.IFilter filter) [0x0002e] in <f566379fc0a94d07a41b0130b5bb2c13>:0
  at (wrapper delegate-invoke) System.Func`6[System.IO.TextWriter,System.Action`1[Duplicati.Library.Main.Controller],System.Collections.Generic.List`1[System.String],System.Collections.Generic.Dictionary`2[System.String,System.String],Duplicati.Library.Utility.IFilter,System.Int32]:invoke_TResult_T1_T2_T3_T4_T5 (System.IO.TextWriter,System.Action`1<Duplicati.Library.Main.Controller>,System.Collections.Generic.List`1<string>,System.Collections.Generic.Dictionary`2<string, string>,Duplicati.Library.Utility.IFilter)
  at Duplicati.CommandLine.Program.RunCommandLine (System.IO.TextWriter outwriter, System.IO.TextWriter errwriter, System.Action`1[T] setup, System.String[] args) [0x003fb] in <f566379fc0a94d07a41b0130b5bb2c13>:0

**Comment by kenkendk** [comment] 2017-07-11 09:43
Unfortunately, I do not have a OD4B account for testing, so I cannot debug this further.

**Comment by Bruceforce** [comment] 2017-07-11 11:29
Is there no way to get a debug log which I can send to you?

**Comment by sffetlio** [comment] 2017-09-01 06:58
### Version info

**Duplicati Version:** 2.0.2.1_beta_2017-08-01
**Operating System:** Windows 10 64bit 1703 build 15063.540
**Backend:** Local folder and then OneDrive for Business

### Bug description
I believe I have the same issue so I'll put it here. I have a backup on OneDrive for Business. It contains 6758 files (volume size 100 MB) that are 329 GB total. See "Steps to reproduce" for my workflow. I am sure it is the correct path because I tried created a fresh backup with the same folder url and Duplicati had no issues and uploaded files to the correct folder.

### Steps to reproduce
- Create a backup to the local OneDrive for Business folder using 100 MB volumes.
- Wait for the OneDrive for Business client to upload everything (I do it this way because I get way better upload speed: it uploads several files at a time saturating my 100 Mbps up link).
- Create a new backup with destination the OneDrive for Business server using the files in the uploaded folder.
- Recreate the database

**Actual result:** Recreating the database fails with the following error:
```
Error while running My Backup
No files were found at the remote location, perhaps the target url is incorrect?
```
and the log shows:
```
Sep 1, 2017 9:21 AM: list
[

]
```
**Expected result:** It should recreate the database and be able to continue backing up from now on.

### debug log

```
Sep 1, 2017 9:21 AM: Failed while executing "Repair" with id: 12
Duplicati.Library.Interface.UserInformationException: No files were found at the remote location, perhaps the target url is incorrect?
   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.DoRun(LocalDatabase dbparent, Boolean updating, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.Run(String path, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   at Duplicati.Library.Main.Operation.RepairHandler.RunRepairLocal(IFilter filter)
   at Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Repair(IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

**Comment by Bruceforce** [comment] 2017-09-18 12:30
In the initial comment I wrote
> I was thinking about trying it again with a larger filesize.

I tested the same backup job with 500 MB per file and it worked. So I think od4b can't list large folders. Of course this isn't a good workaround - with more revisions there will be more files inside the backup and the error will occur again.

**Comment by jma89** [comment] 2018-02-08 03:26
@Bruceforce are you still seeing this with OD4B backup destinations?

I think I'm running into the same problem right now with one of my backup sets. (I have two working ones with 2959 files and 2810 files in them, and a broken one with 7039 files. All three use the default volume size of 50 MB.)

For what it's worth: I was trying to get counts through the Storage Metrics section of the site settings panel, but it would keep erroring out for the folder with 7000+ files. This may indicate that Sharepoint itself (what OD4B runs atop of) can't handle such large folders. (I got the final count by going page-of-30 at a time through the folder in the new interface.)

@kenkendk I'll try to get some captures of the interaction with Fiddler. Do you have the API documentation that was used to build the original implementation?

As a workaround we could map OD4B using WebDAV instead of the native handler. I'll do some tests and see if that works better for my largest backup set.

**Comment by jma89** [comment] 2018-02-08 03:51
WebDAV is disabled on my company's account (and for good reason, really. Just a bummer for testing.) so I can't verify if that would have worked or not.

Digging around further: Turns out the old client had a limit of 5,000 files per folder (if I'm interpreting the limits correctly), whereas the new sync client bumps that to 100,000: [https://support.office.com > SharePoint Online limits](https://support.office.com/en-us/article/sharepoint-online-limits-8f34ff47-b749-408b-abc0-b605e1f6d498?ui=en-US&rs=en-US&ad=US)

I'm assuming there's a different API beneath the surface that enables this behavior.

**Comment by Bruceforce** [comment] 2018-02-08 08:33
@jma89 Yeah I just tested it with 2.0.2.17 and it's still the same error. Thought about using some third party sync client to try to sync my local backup with od4b. Unfortunately Microsoft doesn't care much about Linux users and they didn't even publish an official client.

**Comment by veljko** [comment] 2018-04-18 16:46
Same issue here with 6046 files (150MB dblock size). It is not only Linux they do not care about as this is the same problem on Windows :( I've spent two days trying to move some of the files (as I have 4 index files in the backup). In one moment repair started to work (Duplicati.CommandLine.exe repair od4b://...) but then I thought things will work for all the files and moved other files to the same folder. Now, I am back to square one where Duplicati.commandline.BackEndtool.exe" LIST od4b://... returns No filesets found on remote target :(

**Comment by Bruceforce** [comment] 2018-04-18 16:49
@veljko have you tried with the new onedrive v2 backend? I don't know if that can help in your situation but it's worth a try.

**Comment by veljko** [comment] 2018-04-18 19:52
@Bruceforce I am not sure what exactly you mean. How should I try it? Thanks

**Comment by Bruceforce** [comment] 2018-04-18 22:07
@veljko
Update to the newest duplicati version. Try to make a new backup job and select OneDrive v2 as Backend. Get an AuthID and set the destination folder as your corrupt path. Try the list command again with the new od4bv2 backend.

**Comment by veljko** [comment] 2018-04-19 04:56
All good on Debian too! Backup that I couldn't resume is happily working again with more consistent transfer rate. Nice touch with adding per file progress to UI! Thanks again for your help @Bruceforce

**Comment by ts678** [comment] 2020-12-19 00:10
FYI

The Microsoft limit on list using certain APIs is 5000. When calculating, keep in mind that each dblock has a dindex, and versions add additional files. You can search for "list view limit" of "onedrive" or "sharepoint" to see this value. In Duplicati, your job log's Complete log --> BackendStatistics --> KnownFiles will show where you are. If you suddenly stop seeing files, see if that value went past 5000.

Changing to a destination documented in [Storage Providers](https://duplicati.readthedocs.io/en/latest/05-storage-providers/) as `Microsoft Graph API` experimentally avoids the limit, as it has here. Microsoft had not made such a claim that anyone could find, so time will tell. Hopefully `OneDrive v2` and similar will keep working...

**Comment by ts678** [comment] 2024-01-24 13:32
A solution was suggested (and confirmed) above in 2018, but I'll issue a last call for any additional comments before closing this.
We can't change the Microsoft limit, but a user can use the newer Microsoft Graph API that so far seems to handle large folders.

Copying from another issue...

Currently, I think Microsoft is encouraging people to use better authentication than username/password. There are benefits from [Microsoft OneDrive v2 (Microsoft Graph API)](https://duplicati.readthedocs.io/en/latest/05-storage-providers/#microsoft-onedrive-v2-microsoft-graph-api) such as avoiding the 5000 file list view limit that makes backups "disappear" if large.

If that method works well, then you're all set. On the other hand, this might not be of interest any more. Asking for any feedback.

**Comment by Bruceforce** [comment] 2024-01-24 18:20
Damn. I didn't know that this was still open after all these years. I can just tell, that I'm still using Duplicati and this issue is long gone for me.

**Comment by ts678** [comment] 2024-01-25 00:57
> I'm still using Duplicati and this issue is long gone for me.

Thanks. I guess that means close.

**Closed** 2024-01-25 00:57 UTC
Labels: bug, backend issue
