### ISSUE TITLE
restored files truncated 

### ISSUE THREAD

**Issue by helmutdux** [duplicati/duplicati#1623] opened 2016-03-13 18:59 UTC
When restoring files from a cloud backup, some files are truncated.
I tried to rebuild the complete data from the  backup to a different location under win 7 with duplicati 2.0.0.99.
After very short time, the amount of data reached the estimated value (app 10 GB). But it lasted a much longer Period to finish the job, but much much faster than in the versions before !!!
A first compare signalized success, but  several files have been truncated, eg. text files,second half was missing, images buildt up only the first quater. On the other side Windows shows he correct file size and date.
It seems that at first complete correct directory informations are buildt up, but filling the contents is buggy.
I did find the problems only be comparing files with windiff, simple dir compare did not give any error information.

Helmut

**Comment by kenkendk** [comment] 2016-03-13 20:55
That does not sound nice.

There is a check at the end of the restore, it should notify you if the files were not correctly restored.
Was this a full restore or a partial restore?

**Comment by kenkendk** [comment] 2016-03-13 21:14
Re-reading, you write "the complete data". I assume that is a full restore.

Did you have a local database, or did you rebuild the database as well?
Can you reproduce with a smaller backup set? E.g. take some of the pictures and txt files that were not correctly restored (in the original version) and put a copy in a new folder. Then make a backup of that folder and try to restore it.

**Comment by FootStark** [comment] 2016-03-13 21:38
At first, it would be important to find out if the file verification ran. It should report wrong files that have been restored incorrectly in any case. If verification ran and did not report errors, the scrambling must have occured somewhere else, either on backup or after the verification (maybe a file system issue?). Or the restore process was killed completely and block restore ended early. Is that possible? Are there still logs available? Maybe the windows event viewer can help to identify an app crash.
@helmutdux Do I assume correctly that reaching the desired amount of data - as you described - was measured in the file system via properties? Duplicati restores blocks in a "wild" order, so if the end of a file is written, it is filled with NULL-data in between and reaches its size fast. If you still have the broken files on disk, could you look up if the very end of the files contains data and only the middle is missing?

**Comment by helmutdux** [comment] 2016-03-14 10:10
Hi!
First, thanks for your quick response. Please find attached a log-file 
with added information which I generated this morning.

Answers:
No Information from the Windows event viewer.
The Problems seem to be independent of any existing lokal database and 
partial or full restore.
The truncated files are really truncaded, means from a certain position, 
the rest of the file content is missing.
The Problem occurs with files, which are existing in the restore 
directory and have to be overwritten.
Some minutes ago, I repeated the same  restore as from the log and 
deleted the "wrong" files in the target directory before.
In this case, nor error was reported today !!

Hope this helps

Helmut





Am 13.03.2016 um 22:38 schrieb Stefan Lück:

**Comment by FootStark** [comment] 2016-03-14 10:54
Thank you for the info, that really sounds strange and I should look into it. AFAIK Github does not Support attachments for issue conversations, so would you please resend the logs to use.2de4.once@lueck-senses.de for that purpose.

**Comment by FootStark** [comment] 2016-03-14 11:29
Thank you for the log excerpt @helmutdux.
Duplicati found that approx. 8 GB of data were already correct, and says it restored the rest of the data (1,6 GB) from local blocks, that is from the files in their original Location (which I assume are thus available). The downloads were only necessary for metadata.
At the end Duplicati reports 13 files being broken. Are these exactly the truncated files you found or are there other broken files as well? 
Are there other programs working on the files while duplicati restores them? The path indicates there could by some cloud syncing and caching happening.
Is it OK if I contact you directly via email for further Investigation? The final restore size reported also seems to low.

**Comment by helmutdux** [comment] 2016-03-14 11:44
Hi 
Answers:
I assume, that duplicati doesn`t know the original location, at least in the restore commands, there is no original location, only backup-url and target directory only.
All truncated files are within the duplicati broken file list, but there are some, I cannot simply compare the content.
The target directory was created exclusively for restore with duplicati, i assume no other activities
My assumption is: Duplicati writes updated File headers (time stamp,size)  back to the target, but makes errors during filling up the new content.

**Comment by FootStark** [comment] 2016-03-14 15:18
I believe I have identified the cause. The bug lies in restoring blocks from local files (original pathes are stored in the db, so yes, duplicati knows about it). Issue should be fixed in the next build.
Please use Option "--no-local-blocks" for your restore to verify that this was the cause. It will download missing blocks instead of looking them up locally. You should also use this option as a Workaround until next build is out.
Thank you for reporting the bug and helping improve Duplicati. A short Feedback if the Workaround is fixing your issue would be appreciated.

**Comment by FootStark** [comment] 2016-03-14 15:30
To make sure your issue is completely dealt with, could you please also confirm:
The log you sent strongly indicates that most of the files were already existing at the restore location. That would explain your issue with the bug found.
In your first comment you wrote you set up a new target dir and restored from scratch. For that scenario there would *not* yet be an explanation. 
So, did you partially restore files and then restarted a second restore Operation before the broken files showed up?

**Comment by helmutdux** [comment] 2016-03-14 15:38
Yes it is as you assumed, it happend when I made a second check some 
days and backups later.
Helmut
Am 14.03.2016 um 16:30 schrieb Stefan Lück:

**Comment by helmutdux** [comment] 2016-03-15 04:45
Hi
I checked the workaround over night -- and it works ---
Thanks for the help, now I can really use the backup, its now the best choice for cloud storage, fast, secure and reliable, so thanks
Helmut

**Closed** 2016-03-15 19:38 UTC
