### ISSUE TITLE
[UI] Restoring folder does not re-create the top seleced folder... (Windows)

### ISSUE THREAD

**Issue by MatzeDE** [duplicati/duplicati#4246] opened 2020-07-03 16:08 UTC
- [ ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: v2.0.5.1-2.0.5.1_beta_2020-01-18
- **Operating system**: Windows 10 Pro x64 1909
- **Backend**: Windows Minio RELEASE.2019-12-24T23-41-36Z

## Description

Restoring folder does not re-create the top seleced folder in case of restoring to another location. Restoring to the original location works.

## Steps to reproduce

1. Create a backup of folder "root_folder" with e.g. the following sub-folder structure:
```
root_folder
	folder1
	folder2
	folder3
		1.jpg
		2.jpg
		3.jpg
		folder3.1
			a.jpg
			b.jpg
			c.jpg
```
2. Try to restore folder "folder3" and all its sub-folder by selecting "folder3" in the UI and restore it to another location, e.g. D:\tmp
3. Restoring "folder3" to destination folder D:\tmp\ does not create D:\tmp\folder3\... 

- **Actual result**:
Instead Duplicati re-creates the structure:

```
D:\tmp
	1.jpg
	2.jpg
	3.jpg
	folder3.1
		a.jpg
		b.jpg
		c.jpg
```
- **Expected result**:
```
D:\tmp
	folder3
		1.jpg
		2.jpg
		3.jpg
		folder3.1
			a.jpg
			b.jpg
			c.jpg

```

**Comment by warwickmm** [comment] 2020-07-03 17:41
Thanks.  I think this is a duplicate of issue #3340.

**Closed by warwickmm** 2020-07-03 17:41 UTC
Labels: duplicate
