### ISSUE TITLE
No executable permissions on Fedora 40

### ISSUE THREAD

**Issue by NjlsShade** [duplicati/duplicati#5249] opened 2024-06-28 08:44 UTC
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

Only reference I can find is here: https://www.reddit.com/r/Duplicati/comments/1d84as6/duplicati_not_executable_after_installation_on/

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.8.1
- **Operating system**: Fedora 40 Kinoite

## Description

Installing the RPM file for Fedora/RHEL results in the duplicati binary not having executable permissions

```
$ ls -lh /usr/bin/duplicati
-rw-------. 2 root root 277 Dec 31  1969 /usr/bin/duplicati
```

## Steps to reproduce

1. Install the RPM package for duplicati on Fedora 40
2. Observe that the binary does not have the proper permissions applied

**Comment by ts678** [comment] 2024-06-28 11:55
[duplicati-2.0.8.1-2.0.8.1_beta_20240507 rpm package executables do not have the correct mode #5206](https://github.com/duplicati/duplicati/issues/5206) shows the cause.
It's closed now, but there is not yet a Beta with its fix. If you are willing to test a Canary, I'd guess that it's now fixed there.
Alternatively, manual fix should be simple.

**Comment by NjlsShade** [comment] 2024-06-28 14:58
Shoot, sorry for missing that issue. As the problem is known and resolved we can close this out.

Thanks for the info!!

**Closed** 2024-06-28 14:58 UTC
