### ISSUE TITLE
changing schedule hasn´t effect

### ISSUE THREAD

**Issue by netnotix** [duplicati/duplicati#1935] opened 2016-09-21 09:48 UTC
I have:
- [x] searched open and closed issues for duplicates

---
### Version info

**Duplicati Version:** 2.0.1.23_canary_2016-09-16
**Operating System:** Win10 pro 1607
**Backend:** local folder and googledrive sync
### Bug description

editing an existing job and changing the schedule has no effect.
### Steps to reproduce
- configuration edit
- change date and time
- save

**Actual result:** new date and time will be saved. But the job will run at the old date and time settings.
**Expected result:** job should run at the new time and date settings.
##

**Comment by milux** [comment] 2016-09-21 10:56
Same problem here, and it definitely exists since at least 2.0.1.22, think I've seen this the first time in 2.0.1.21.
The schedule also seems somewhat random, I've seen backups 3 hours after the last backup, but sometimes it's also 2 hours... kinda weird... my setup says every hour.

**Comment by milux** [comment] 2016-10-09 06:53
I don't know if "mini issue" is the right name for it.
It should backup my data every hour, instead, it backups every 3 hours... (Hey, at least that is reliable from what I can tell. ^^)
But if "mini issues" means "will be fixed soon" than I am quite happy with it. ;)

**Comment by Nutomic** [comment] 2016-10-12 11:40
I noticed the same problem (on Linux). However, I noticed that the scheduled time is shown correctly, if I kill Duplicati via task manager and start it again. So that seems to be a good workaround for now.

**Comment by milux** [comment] 2016-10-12 15:32
I wish there would be some easy workaround for me as well, but
unfortunately, the suggested one doesn't work for me.

**Comment by vitekf** [comment] 2016-11-06 10:58
The same problem. 
Partial solution: after saving configuration and restarting Duplicati, the good time is showed and backup start at the right time.

But my settings for next run - 1 hour - is ignored:

Initial settings:
_Next time 11:30
Run again every 1 hour_

After first run (at 11:31):
_Last successful run:today at 11:30 (took 00:00:12)
Next scheduled run:today at 13:30_

duplicati-2.0.1.30_experimental_2016-11-03-x64
Windows 7

**Comment by danizobin** [comment] 2016-11-16 19:19
Same here:

https://drive.google.com/open?id=0B-AYNM0o3u9PZ1FkX3pRbWdaMjA
https://drive.google.com/open?id=0B-AYNM0o3u9PR3lFTjlfQlM2aG8
The first link is to the setting. The second is to the result.
Currently it's set to run every 20 minutes. Actually runs every 2 hours + 20 minutes

Windows 7 64, 2.0.1.30_experimental_2016-11-03

With google drive as a backend

**Comment by danizobin** [comment] 2016-11-17 18:30
Ok I have new data on this:

Somebody on the chat spechulated that it might be related somehow to timezones.

I took it to the test.

And quite amazingly, indeed:

When I schedule a run of duplicati every X time, what actually happens is a schedule for a run every X + [my timezone [hours]]

I tried it with X = 20 minutes, X = 1 hour.

Also played with different timezones : UTC +2 (my natural), UTC 0 (and the scheduler worked correctly!), UTC +6.

The formula above held true on all values of X and timezone.

**Comment by danizobin** [comment] 2016-11-17 18:41
Another issue, that might be unrelated, is this:

Whenever a new schedule is set, after having an existing one, it takes reset of Duplicati, for the new schedule to start being actual

**Comment by milux** [comment] 2016-11-19 19:44
@danizobin Thanks man, at least it's clear now what causes this stupid mistake.
Let's hope that there will be some fix soon, changing my timezone to get my backup working properly is not really an option. :wink:

**Comment by kenkendk** [comment] 2016-11-26 12:16
This should be fixed with #2130, I will see if I can make a new canay build today

**Comment by kenkendk** [comment] 2016-11-26 12:57
For the problem with "changing schedule has no effect", it is caused by a delay.

When the scheduler has nothing to do, it waits for 5 minutes.
If you change the schedule, the scheduler will wait for 5 minutes before re-checking the schedules.
Restarting the service stops the scheduler and then starts it again, thus removing the delay.

I will see if I can get the scheduler to re-run if a schedule has been updated.

**Closed** 2016-11-27 11:07 UTC
Labels: bug

**Comment by danizobin** [comment] 2016-12-05 18:38
@kenkendk 

Is there a stable compiled code package, that includes this fix?

**Comment by agrajaghh** [comment] 2016-12-12 20:41
> Is there a stable compiled code package, that includes this fix?

you can try 2.0.1.34 from https://github.com/duplicati/duplicati/releases or wait for the next experimental or even beta release (in the next few weeks)
