### ISSUE TITLE
Clean install of 2.0.1.18 or upgrading from 2.0.1.17 to 2.0.1.18 on Windows 7 x64 is broken

### ISSUE THREAD

**Issue by andy012345** [duplicati/duplicati#1895] opened 2016-08-18 19:36 UTC
Tested on Windows 7 VMs through evening (to figure out why backup tests at work were not working).

Fresh install on W7 SP1 (with .net 4.5 installed) on 2.0.17 works fine. On upgrading to 2.0.18 trying to open any folder on the web UI fails, and trying to run a backup appears to work but 0 files are found.

The same issue occurs when you upgrade from 2.0.17 to 2.0.18.

Downgrading back to 2.0.17 makes duplicati no longer open (it appears to crash from a pending WER upload). You must delete %APPDATA%./Duplicati/Duplicati-server.sqlite before it will open again.

**Comment by andy012345** [comment] 2016-08-18 19:39
Fixed title, I am a bit tired but have a workaround for now (not using release 18).

**Comment by milux** [comment] 2016-08-19 09:51
Same problem here. Backup fails, Restore of old backups fails as well, saying something about incompatible Manifest.
OS is Windows 10 x64, most recent version. Duplicati is started by the Scheduler (on logon), running with Administrator privileges.

**Comment by NickPyz** [comment] 2016-08-19 17:36
@andy012345 
@milux 

2.0.1.18 has numerous issues - including failure to backup +/or restore. The most recent issues threads describe these issues. 

You might want to consider a downgrade to version 2.0.1.17 until a fixed release is available. The method to do this is discussed in thread #1891

**Comment by gandalfk7** [comment] 2016-08-21 21:34
hi, 
I can confirm this issue, I am running 2.0.1.18 on Win 7 Professional SP1

**Comment by nameanyone** [comment] 2016-08-24 23:53
> trying to open any folder on the web UI fails, and trying to run a backup appears to work but 0 files are found

This part is a duplicate of #1888.

The part about downgrade being problematic is covered in #1891.

**Comment by kenkendk** [comment] 2016-08-27 13:39
I have uploaded a new version 2.0.1.19 that should fix the problem.

**Closed by kenkendk** 2016-08-27 13:39 UTC
