### ISSUE TITLE
No connection to the program

### ISSUE THREAD

**Issue by lsmobile** [duplicati/duplicati#3616] opened 2019-01-20 15:46 UTC
Thanks in advance for your reply.

- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.4.5, 2.0.4.12
- **Operating system**: Windows 10
- **Backend**: WebDAV

## Description
After installing the program, the web browser cannot connect to localhost: 8200. A few days ago everything worked. Overload and reinstallation of the program did not give any result.

## Steps to reproduce
1. I have changed the Remote Volume Size to 100MByte

## Screenshots

![image](https://user-images.githubusercontent.com/28897141/51441497-a3e64d80-1cd2-11e9-91cd-aeb8dc841090.png)

**Comment by warwickmm** [comment] 2019-02-01 05:56
Did you have any luck resolving this?  Are you able to see if the Duplicati (or mono) process is running?

**Comment by warwickmm** [comment] 2020-08-17 02:35
Closing this since it can't be reproduced.  If you're still having this issue, try posting in the forums (https://forum.duplicati.com/).

**Closed by warwickmm** 2020-08-17 02:35 UTC
