### ISSUE TITLE
duplicate warning for files that exceed filesize constraint

### ISSUE THREAD

**Issue by grinsted** [duplicati/duplicati#2083] opened 2016-11-03 08:08 UTC
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.25_canary_2016-09-26
**Operating System:** Win10pro
**Backend:** local folder

### Bug description
I have configured my backup to exclude files larger than 200 Mb. I get a bunch of recurring warnings when i backup, which are all from files exceeding that threshold. That makes me think that the message is wrong. (I would really prefer to have no warnings for files have have decided to exclude).

### debug log
```
Failed to process path: C:\Users\ag\Documents\Presentations\~$egrip drone.pptx => The process cannot access the file 'C:\Users\ag\Documents\Presentations\~$egrip drone.pptx' because it is being used by another process., Failed to process path: C:\Users\ag\Documents\Presentations\~$grinsted -time series.pptx => The process cannot access the file 'C:\Users\ag\Documents\Presentations\~$grinsted -time series.pptx' because it is being used by another process., Failed to process path: C:\Users\ag\Documents\Presentations\~$grinsted EGU09 - linkages - shaviv.ppt => The process cannot access the file 'C:\Users\ag\Documents\Presentations\~$grinsted EGU09 - linkages - shaviv.ppt' because it is being used by another process., Failed to process path: C:\Users\ag\Documents\MATLAB\ImGRAFT\repoexclude\extrademos\LC80080062013142LGN01_B8.TIF => constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID, Failed to process path: C:\Users\ag\Documents\MATLAB\ImGRAFT\repoexclude\extrademos\LC80080062014241LGN00_B8.TIF => constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID, Failed to process path: C:\Users\ag\Documents\MATLAB\ImGRAFT\repoexclude\extrademos\LC82330132014105LGN00_B8.TIF => constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID, Failed to process path: C:\Users\ag\Documents\MATLAB\ImGRAFT\repoexclude\extrademos\LC82330132014121LGN00_B8.TIF => constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID, Failed to process path: C:\Users\ag\Documents\MATLAB\ImGRAFT\repoexclude\extrademos\renlandtemp.mat => constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID, Failed to process path: C:\Users\ag\Documents\MATLAB\Assist\meshocean\GMT_intermediate_coast_distance_01d.zip => constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID, Failed to process path: C:\Users\ag\Music\Reason\ReFills\RV7000 mkII patches.rfl => constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID
```

**Comment by kenkendk** [comment] 2016-12-08 10:10
This is a duplicate of #1855, which I just fixed

**Closed by kenkendk** 2016-12-08 10:10 UTC
Labels: bug
