### ISSUE TITLE
Duplicati crashes during startup

### ISSUE THREAD

**Issue by tillulen** [duplicati/duplicati#2562] opened 2017-06-23 15:30 UTC
----------------------------------------

### Version info

**Duplicati Version:** 4.0.30319
**Operating System:** Windows 10 Home
**Backend:**

### Bug description
After installing Duplicati, it crashes every time when I run it. I’m moving this issue from the [chat room](https://gitter.im/duplicati/Lobby?at=594b8451cf9c13503cb0a02e).

### Steps to reproduce
- Switch your Windows locale to Russian (not sure if that's relevant).
- Install Duplicati 2.0.
- Run Duplicati.

**Actual result:** Duplicati silently crashes. In the Windows Event Log, there is a stack trace (see below).
**Expected result:** I expected a new Duplicati tab to open in the web browser and a Duplicati icon to appear in the system tray.

### debug log
```Application: Duplicati.GUI.TrayIcon.exe
Platform version: v4.0.30319
Description. The process was terminated due to an unhandled exception.
Exception Details: System.FormatException
in System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
in System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
in System.Convert.ToInt32(String value, IFormatProvider provider)
in System.Data.SQLite.SQLiteConnection.Open()
in Duplicati.Server.Program.OpenDatabase(IDbConnection con)
in Duplicati.Server.Program.RealMain(String[] args)
Exception Details: System.Exception
in Duplicati.Server.Program.RealMain(String[] args)
Exception Details: System.Exception
in Duplicati.Library.AutoUpdater.UpdaterManager.RunMethod(MethodInfo method, String[] args)
in Duplicati.Library.AutoUpdater.UpdaterManager.<>c__DisplayClass53_0.<RunFromMostRecent>b__0()
in Duplicati.Library.AutoUpdater.UpdaterManager.WrapWithUpdater(AutoUpdateStrategy defaultstrategy, Action wrappedFunction)
in Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(MethodInfo method, String[] cmdargs, AutoUpdateStrategy defaultstrategy)
in Duplicati.GUI.TrayIcon.Program.Main(String[] args)
in System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
in System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
in System.AppDomain.ExecuteAssemblyByName(System.String, System.String[])
in Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(System.Reflection.MethodInfo, System.String[], Duplicati.Library.AutoUpdater.AutoUpdateStrategy)
in Duplicati.GUI.TrayIcon.Program.Main(System.String[])```

**Comment by tillulen** [comment] 2017-06-23 15:36
@kenkendk [wrote](https://gitter.im/duplicati/Lobby?at=594cf17a42d2f6102586686a) in the chat room:

> This build should be the same as the canary build, but adds Version=3 to the SQLite connection string, and should prevent the crash :
> https://dl.dropboxusercontent.com/u/15251537/TestSQLite.zip
> Can you test if it works for you?

I uninstalled Duplicati, unpacked the .zip file and ran TestSQLite\Duplicati.GUI.TrayIcon.exe. It crashed with a different stack trace:

```Application: Duplicati.GUI.TrayIcon.exe
Platform version: v4.0.30319
Description. The process was terminated due to an unhandled exception.
Exception Details: System.Exception
   in Duplicati.Server.Program.GetDatabaseConnection(Dictionary`2 commandlineOptions)
   in Duplicati.Server.Program.RealMain(String[] args)

Exception Details: System.Exception
   in Duplicati.Library.AutoUpdater.UpdaterManager.RunMethod(MethodInfo method, String[] args)
   in Duplicati.Library.AutoUpdater.UpdaterManager.<RunFromMostRecent>c__AnonStorey7.<>m__0()
   in Duplicati.Library.AutoUpdater.UpdaterManager.WrapWithUpdater(AutoUpdateStrategy defaultstrategy, Action wrappedFunction)
   in Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(MethodInfo method, String[] cmdargs, AutoUpdateStrategy defaultstrategy)
   in Duplicati.GUI.TrayIcon.Program.Main(String[] args)
   in System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   in System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   in System.AppDomain.ExecuteAssemblyByName(System.String, System.String[])
   in Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(System.Reflection.MethodInfo, System.String[], Duplicati.Library.AutoUpdater.AutoUpdateStrategy)
   in Duplicati.GUI.TrayIcon.Program.Main(System.String[])```

I am translating parts of the stack trace back into English, so the wording might differ from the original.

**Comment by tillulen** [comment] 2017-06-23 15:39
Am I running the test build correctly?

**Comment by kenkendk** [comment] 2017-06-23 20:48
I think the build has too many moving parts to reliably figure out what goes wrong.
I have taken "just the sqlite stuff" and put it into a binary:
https://dl.dropboxusercontent.com/u/15251537/sqlite-tool.zip

You can run it like this:
```
SQLiteTool.exe "test.sqlite" "select * from sqlite_master"
```

If that fails with a similar error message as Duplicati, try this:
```
SQLiteTool.exe "test.sqlite;Version=3" "select * from sqlite_master"
```

This should hardwire the number `3` into the position that fails in the original message.

**Comment by tillulen** [comment] 2017-06-23 22:43
Unpacked the .zip file, cd’d into the `sqlite-tool` folder and ran the commands in the command line. Here is the output (translated back into English, as usual).

```
λ SQLiteTool.exe "test.sqlite" "select * from sqlite_master"
Opening with connection string: Data Source=test.sqlite

Unhandled exception: System.FormatException: Input string had invalid format.
   in System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   in System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   in System.Convert.ToInt32(String value, IFormatProvider provider)
   in System.Data.SQLite.SQLiteConnection.Open()
   in SQLiteTool.MainClass.Main(String[] args)

λ SQLiteTool.exe "test.sqlite;Version=3" "select * from sqlite_master"
Opening with connection string: Data Source=test.sqlite;Version=3

Unhandled exception: System.FormatException: Input string had invalid format.
   in System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   in System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   in System.Convert.ToInt32(String value, IFormatProvider provider)
   in System.Data.SQLite.SQLiteConnection.Open()
   in SQLiteTool.MainClass.Main(String[] args)
```

Please let me know if you prefer the Event Log stack trace.

**Comment by kenkendk** [comment] 2017-06-24 20:01
It explains clearly where the crash happens, I just need to figure out why it is trying to parse a number there at all.

**Comment by tillulen** [comment] 2017-06-24 20:14
Does it crash in your code or in some third-party library code that Duplicati calls?

**Comment by kenkendk** [comment] 2017-06-24 20:15
It crashes inside the SQLite library code, so it is not in any of "my" code.

Turns out there were a few more places where `ToInt32` is called. Can you try with this:
```
SQLiteTool.exe "test.sqlite;Version=3;Max Pool Size=100;Default Timeout=30;BusyTimeout=0;PrepareRetries=3;ProgressOps=0;Page Size=4096;Max Page Count=0;Cache Size=2000" "select * from sqlite_master"
```

**Comment by tillulen** [comment] 2017-06-24 20:19
Sure. This one does not crash:

```
λ SQLiteTool.exe "test.sqlite;Version=3;Max Pool Size=100;Default Timeout=30;BusyTimeout=0;PrepareRetries=3;ProgressOps=0;Page Size=4096;Max Page Count=0;Cache Size=2000" "select * from sqlite_master"
Opening with connection string: Data Source=test.sqlite;Version=3;Max Pool Size=100;Default Timeout=30;BusyTimeout=0;PrepareRetries=3;ProgressOps=0;Page Size=4096;Max Page Count=0;Cache Size=2000
Setting query: select * from sqlite_master
Execution took: 00:00.002
type    name    tbl_name        rootpage        sql
0 records
```

**Comment by tillulen** [comment] 2017-06-24 20:26
I reduced it to Cache Size:
```
λ SQLiteTool.exe "test.sqlite;Cache Size=2000" "select * from sqlite_master"
Opening with connection string: Data Source=test.sqlite;Cache Size=2000
Setting query: select * from sqlite_master
Execution took: 00:00.001
type    name    tbl_name        rootpage        sql
0 records
```

**Comment by kenkendk** [comment] 2017-06-24 20:31
Nice! The source code actually has `Cache Size=-2000`, can you try with that?

**Comment by tillulen** [comment] 2017-06-24 20:32
```
λ SQLiteTool.exe "test.sqlite;Cache Size=-2000" "select * from sqlite_master"
Opening with connection string: Data Source=test.sqlite;Cache Size=-2000
Setting query: select * from sqlite_master
Execution took: 00:00.016
type    name    tbl_name        rootpage        sql
0 records
```

**Comment by kenkendk** [comment] 2017-06-24 20:32
Actually, it says `-2000.ToString()` in the source, so maybe converting `-2000` to a string in your local gives another result than `"-2000"` ?

**Comment by kenkendk** [comment] 2017-06-24 20:49
Ok, I have these locales that returns another string;
```
ar: ؜-2000
ur: ‎-‎2000
sl: –2000
ps: ‎-‎2000
ar-SA: ؜-2000
ur-PK: ‎-‎2000
sl-SI: –2000
ps-AF: ‎-‎2000
ar-IQ: ؜-2000
ur-IN: ‎-‎2000
ar-EG: ؜-2000
ar-LY: ؜-2000
ar-DZ: ؜-2000
ar-MA: ؜-2000
ar-TN: ؜-2000
ar-OM: ؜-2000
ar-YE: ؜-2000
ar-SY: ؜-2000
ar-JO: ؜-2000
ar-LB: ؜-2000
ar-KW: ؜-2000
ar-AE: ؜-2000
ar-BH: ؜-2000
ar-QA: ؜-2000
```

The ones that does have a leading `-` uses a different character than the english minus symbol.

**Comment by tillulen** [comment] 2017-06-24 20:52
Kenneth, thanks for pinpointing the problem. I think I know what the root cause was.

Some time ago when configuring this machine, I was tinkering with the localization settings and changed the format for negative numbers: instead of the hyphen sign (-), I entered the Unicode minus sign (−). Now that I reset the Region settings to their defaults for Russian (Russia), both SQLiteTool and Duplicati run fine without crashing.

Perhaps here I was being too clever, but I still believe that’s a bug in SQLite and they should use a locale-independent conversion instead of `-2000.ToString()`. Would you like me to report it upstream or would you like to do it yourself?

**Comment by kenkendk** [comment] 2017-06-24 20:54
I just checked the source, and the problem is fixed in the latest release of System.Data.SQLite.
I should update the bundled version of the library.

**Comment by tillulen** [comment] 2017-06-24 20:54
Great! Thank you.

**Closed** 2017-06-27 20:03 UTC
Labels: bug
