### ISSUE TITLE
Cannot restore from another machine

### ISSUE THREAD

**Issue by bmacinnis** [duplicati/duplicati#2739] opened 2017-09-18 20:28 UTC
I stored my backups on the Amazon cloud.  The laptop that I was backing up via Duplicati is fried so I am trying to restore the files on another machine.  I tried with version 2+ (on Windows 10) and it gave me a password/corrupt message - I did not set a password or encryption - so it must be corrupt.  Tried  on an older machine running version 1+ and I cannot see any of the backups.  Note:  I did download the backups from Amazon so they were local before trying on each.

Is there something I need to do in order to get either version seeing the old backup so that I can restore it?

Thanks.

**Comment by kenkendk** [comment] 2017-09-19 10:36
Did you make the backup with Duplicati 1.3.x or 2.0?
The two versions are not compatible, so you must use the same version to restore.

Also, for 2.0 if you are not using encryption, make sure you set the correct encryption method (`--no-encryption` on the commandline).

**Comment by bmacinnis** [comment] 2017-09-20 01:38
Thank you for your reply.   I am not 100% sure what version was installed on the fried laptop.  Is there a way to tell from the file names/attributes?  Also, I tried finding the syntax for windows (on version 2) to run a restore from the command line but did not have any luck.


The files were originally back-upped  to the Amazon Cloud and I downloaded them to my local disk.  

There is a possibility that I put a passphrase because when I run the web app it is saying that either the passphrase is incorrect or the file is corrupt.  Is there anyway to get these files back if I cannot rec all the pass phrase?  Or is there a way to tell if I did put a pass phrase in?  I'm pretty sure that I didn't  - but I set it up many months ago.  I'm willing to donate $100 if you can help me get the files back.


Many thanks,

Robert 




My test commands below:

---------------------------------------------------------------------------------------------------------------------------------------------------------

c:\Program Files\Duplicati 2\Duplicati.CommandLine.exe" --restore

Usage: restore <storage-URL> ["<filename>"] [<options>]

Restores <filename> to its original destination. If <filename> exists already, <filename> is changed to
<filename-timestamp.extension>. To restore all files use "*" or leave empty.

--overwrite=<boolean>
Overwrites existing files.
--restore-path=<string>
Restores files to <restore-path> instead of their original destination. Top folders are removed if possible.
--time=<time>
Restore files that are older than the specified time.
--version=<int>
Restore files from a specific backup.


-----------------------------------------------------------------------------------------------------------------------------------------------------------



C:\duplicati_files>"c:\Program Files\Duplicati 2\Duplicati.CommandLine.exe" --restore *
Command not supported: *


-----------------------------------------------------------------------------------------------------------------------------------------------------------


"c:\Program Files\Duplicati 2\Duplicati.CommandLine.exe" --restore-path="c:\restore"
--restore-path (String): Restore to another folder
By default, files will be restored in the source folders, use this option to restore to another folder


----------------------------------------------------------------------------------------------------------

**Comment by bmacinnis** [comment] 2017-09-20 01:56
Hi - one more question.  What type of encryption is used?


Thanks again for your help,

Robert

**Comment by kenkendk** [comment] 2017-09-20 07:06
You can look at the filenames and see what version you used. But given that you uploaded to ACD, you must have used 2.0, as that was not a supported destination in 1.3.x.

For 1.3.x filenames look like:
<timestamp>-full.vol1.zip.aes

For 2.0 filenames look like:
duplicati-<random>.dblock.zip.aes

If you do not have the .aes, the files are not encrypted, if you do have encrypted files, they can be decrypted with: https://www.aescrypt.com

The commands you have tried are slightly off, you can try something like:

```
"c:\Program Files\Duplicati 2\Duplicati.CommandLine.exe" list amzcd://bucket/folder --authid=<amzauthid> --no-encryption --no-local-db
```

You can get the "authid" value from here:
https://duplicati-oauth-handler.appspot.com

Once the "list" command works, you can do this:

```
"c:\Program Files\Duplicati 2\Duplicati.CommandLine.exe" repair amzcd://bucket/folder --authid=<amzauthid> --no-encryption --db-path=C:\myfolder\restoredb.sqlite
```

This will build a database of the remote files, and allow you to work from that.

To restore, you can do:
```
"c:\Program Files\Duplicati 2\Duplicati.CommandLine.exe" restore amzcd://bucket/folder --authid=<amzauthid> --no-encryption --db-path=C:\myfolder\restoredb.sqlite --restore-target=C:\restored
```

If you don't care for the database, you can skip the repair step and use `--no-local-db` in the restore step instead of supplying the database path.

**Comment by bmacinnis** [comment] 2017-09-20 21:04
First let me thank you for your time - I have tried decrypting the files locally and get this error:


C:\duplicati_files>"c:\Program Files\AESCrypt\aescrypt.exe" -d -o test.dat duplicati-20170411T040000Z.dlist.zip.aes
Enter password:
Error: Message has been altered or password is incorrect


I have tried every password that I have ever used - and still cannot decrypt the file.  What could "Message has been altered"   refer to?


I am going to attached one of the smaller files to see if you have have any better luck.


If for some reason, it is a password issue, is there anyway to decrypt the files?


Thanks again,


Robert

**Comment by kenkendk** [comment] 2017-09-26 20:55
The encryption has no known weak points; if you do not have the password, you cannot decrypt it.

The error message indicates that the message altering protection does not match the contents.
Most likely the cause is an incorrect password, but theoretically it could also be an altered file.

In case it is some weird character set thing, you can also try to use `SharpAESCrypt.exe` (found inside the Duplicati install folder) which does the same as the AESCrypt tool you have downloaded, but uses the exact same code as Duplicati does.

**Comment by warwickmm** [comment] 2020-12-28 23:30
I'm going to close this due to the age.  My guess is that an incorrect password was supplied.

**Closed by warwickmm** 2020-12-28 23:30 UTC

**Comment by bmacinnis** [comment] 2020-12-29 15:04
Yes - I did try what I thought was the correct password, but never had any luck.  Is there another way around this?

Thanks,
Robert

**Comment by warwickmm** [comment] 2020-12-29 16:35
Unfortunately, we might be out of options.  If decrypting doesn't work with Duplicati or third-party tools (https://www.aescrypt.com/), then most likely the password is incorrect.  Without the correct password, decryption is not possible.
