### ISSUE TITLE
backup process that failed with an warning error message but error log not explicit

### ISSUE THREAD

**Issue by vlepetit** [duplicati/duplicati#3639] opened 2019-01-31 13:18 UTC
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.4.5
- **Operating system**: Microsoft Windows NT 10.0.17134.0
- **Backend**: SFTP on linux debian

sysmtem-info.txt:
Duplicati: Duplicati.GUI.TrayIcon, Version=2.0.4.5, Culture=neutral, PublicKeyToken=null (Duplicati.Library.Main, Version=2.0.4.5, Culture=neutral, PublicKeyToken=null)
Autoupdate urls: https://updates.duplicati.com/beta/latest.manifest;https://alt.updates.duplicati.com/beta/latest.manifest
Update folder: C:\ProgramData\Duplicati\updates
Base install folder: C:\Program Files\Duplicati 2
Version name: "2.0.4.5_beta_2018-11-28" (2.0.4.5)
Current Version folder C:\Program Files\Duplicati 2
OS: Microsoft Windows NT 10.0.17134.0
Uname: 
64bit: True (True)
Machinename: xxxxxxxxxxx
Processors: 4
.Net Version: 4.0.30319.42000
Mono: False (0.0) ()
Locale: fr-FR, fr-FR, fr-FR
Date/time strings: dddd d MMMM yyyy - HH:mm:ss
Tempdir: C:\Users\desaleux sylvie\AppData\Local\Temp\
SQLite: 3.19.3 - System.Data.SQLite.SQLiteConnection
SQLite assembly: C:\Program Files\Duplicati 2\SQLite\win64\System.Data.SQLite.dll

## Description

I have a plateforme that create sftp backend user account, duplicati json config file and public/private key autmaticaly.

This work fine for all of my macosx, linux and windows computer users.

But today for one of my new user on windows 10 the first backup and many other backup test failed with warning message and nothing explicit in error message.

I had update .net and vc++2015 but i had the same issue.

So I do not understand where the problem is...

## Steps to reproduce
1. load config file
2. Launch backup
3. and after some time error message come

- **Actual result**:
backup process that failed with Error warning display below of duplicati interface
- **Expected result**:
the backup process ends successfully with no warning error message

## Debug log

DeletedFiles: 0
DeletedFolders: 0
ModifiedFiles: 0
ExaminedFiles: 17
OpenedFiles: 17
AddedFiles: 17
SizeOfModifiedFiles: 0
SizeOfAddedFiles: 11134389
SizeOfExaminedFiles: 11134389
SizeOfOpenedFiles: 11134389
NotProcessedFiles: 0
AddedFolders: 2
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults: null
DeleteResults:
    DeletedSets: []
    Dryrun: False
    MainOperation: Delete
    CompactResults: null
    ParsedResult: Success
    Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)
    EndTime: 31/01/2019 12:51:01 (1548935461)
    BeginTime: 31/01/2019 12:51:01 (1548935461)
    Duration: 00:00:00.0049263
    Messages: [
        2019-01-31 12:50:58 +01 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: L'opération Backup a débuté,
        2019-01-31 12:50:58 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),
        2019-01-31 12:50:58 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (),
        2019-01-31 12:50:59 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b0f4d1455c8f24eb6b01ee46fc7143e65.dblock.zip.aes (10,19 MB),
        2019-01-31 12:51:01 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b0f4d1455c8f24eb6b01ee46fc7143e65.dblock.zip.aes (10,19 MB),
...
    ]
    Warnings: []
    Errors: []
    BackendStatistics:
        RemoteCalls: 8
        BytesUploaded: 10695975
        BytesDownloaded: 10695975
        FilesUploaded: 3
        FilesDownloaded: 3
        FilesDeleted: 0
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 3
        KnownFileSize: 10695975
        LastBackupDate: 31/01/2019 12:50:58 (1548935458)
        BackupListCount: 1
        TotalQuotaSpace: 0
        FreeQuotaSpace: 0
        AssignedQuotaSpace: -1
        ReportedQuotaError: False
        ReportedQuotaWarning: False
        ParsedResult: Success
        Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)
        Messages: [
            2019-01-31 12:50:58 +01 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: L'opération Backup a débuté,
            2019-01-31 12:50:58 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),
            2019-01-31 12:50:58 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (),
            2019-01-31 12:50:59 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b0f4d1455c8f24eb6b01ee46fc7143e65.dblock.zip.aes (10,19 MB),
            2019-01-31 12:51:01 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b0f4d1455c8f24eb6b01ee46fc7143e65.dblock.zip.aes (10,19 MB),
...
        ]
        Warnings: []
        Errors: []
RepairResults: null
TestResults:
    MainOperation: Test
    Verifications: [
        Key: duplicati-20190131T115058Z.dlist.zip.aes
        Value: [],
        Key: duplicati-i1c377421a985471abfa0703dd64cf081.dindex.zip.aes
        Value: [],
        Key: duplicati-b0f4d1455c8f24eb6b01ee46fc7143e65.dblock.zip.aes
        Value: []
    ]
    ParsedResult: Success
    Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)
    EndTime: 31/01/2019 12:51:02 (1548935462)
    BeginTime: 31/01/2019 12:51:01 (1548935461)
    Duration: 00:00:00.9986909
    Messages: [
        2019-01-31 12:50:58 +01 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: L'opération Backup a débuté,
        2019-01-31 12:50:58 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),
        2019-01-31 12:50:58 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (),
        2019-01-31 12:50:59 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b0f4d1455c8f24eb6b01ee46fc7143e65.dblock.zip.aes (10,19 MB),
        2019-01-31 12:51:01 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b0f4d1455c8f24eb6b01ee46fc7143e65.dblock.zip.aes (10,19 MB),
...
    ]
    Warnings: []
    Errors: []
ParsedResult: Success
Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)
EndTime: 31/01/2019 12:51:02 (1548935462)
BeginTime: 31/01/2019 12:50:58 (1548935458)
Duration: 00:00:04.5019853
Messages: [
    2019-01-31 12:50:58 +01 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: L'opération Backup a débuté,
    2019-01-31 12:50:58 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),
    2019-01-31 12:50:58 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (),
    2019-01-31 12:50:59 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b0f4d1455c8f24eb6b01ee46fc7143e65.dblock.zip.aes (10,19 MB),
    2019-01-31 12:51:01 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b0f4d1455c8f24eb6b01ee46fc7143e65.dblock.zip.aes (10,19 MB),
...
]
Warnings: []
Errors: []

**Comment by warwickmm** [comment] 2020-12-13 19:52
There are 2 places that logs reside.  The specific backup logs, and the server logs (About -> Show Log).  Consolidating the two to be more useful to the user is a known issue.  Pull request #4368 also proposes a small improvement to the notification messages.

Due to the age of this issue, I'm guessing it's no longer reproducible so I'm going to close this.  If you are still encountering this problem, please feel free to reopen with more details.

**Closed by warwickmm** 2020-12-13 19:52 UTC
