### ISSUE TITLE
Cannot login, or change password

### ISSUE THREAD

**Issue by Hermonella** [duplicati/duplicati#3793] opened 2019-06-12 06:55 UTC
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5
- **Operating system**: Ubuntu Server 18.04 LTS
- **Backend**: Dropbox

## Description

When i try to log into duplicati i get the prompt that i've used the wrong password. when i try to replace the password (duplicati-server --webservice-password=12345 (Tried with and without sudo)) i get the error:
```
A serious error occurred in Duplicati: System.Exception: Unable to open a socket for listening, tried ports: 8200
  at Duplicati.Server.WebServer.Server..ctor (System.Collections.Generic.IDictionary`2[TKey,TValue] options) [0x00302] in <fe28905ee30b422e8d475f1cfdb85515>:0
  at Duplicati.Server.Program.RealMain (System.String[] _args) [0x00674] in <fe28905ee30b422e8d475f1cfdb85515>:0
```

## Steps to reproduce

1. I do not know. This happened overnight.

- **Actual result**:
When entering password:
`Login failed: Unauthorized`
- **Expected result**:
To be logged in.

**Comment by Hermonella** [comment] 2019-06-12 07:49
Found a solution: Restart the computer fixed it. But restarting it again if this happens again isn't a optimal solution.

**Comment by warwickmm** [comment] 2019-06-16 02:26
Glad you were able to fix it.  I'm going to close this since it cannot be reproduced, but if it happens again please let us know by reopening this issue.

**Closed by warwickmm** 2019-06-16 02:26 UTC
