### ISSUE TITLE
Backup job won't pause

### ISSUE THREAD

**Issue by Gooberpatrol66** [duplicati/duplicati#4370] opened 2020-11-16 15:01 UTC
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.111
- **Operating system**: Gentoo Linux
- **Backend**: Tardigrade

## Description

The backup job won't pause

## Steps to reproduce

1. start duplicati-server
2. open web interface
3. start backup job
4. click pause button

- **Actual result**:
backup continues
- **Expected result**:
backup pauses

**Comment by warwickmm** [comment] 2020-11-16 21:06
Duplicate of #3565.

**Closed by warwickmm** 2020-11-16 21:06 UTC
Labels: duplicate
