### ISSUE TITLE
The backup progress bar is not rendered correctly

### ISSUE THREAD

**Issue by mbrijun** [duplicati/duplicati#1958] opened 2016-09-28 20:47 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.25_canary_2016-09-26
**Operating System:** Windows 10 Pro 64bit
**Backend:** Amazon Cloud Drive

### Bug description
The progress bar of a running backup is totally mangled, as if a template is not rendered correctly. A screenshot is attached.

### Steps to reproduce
- initiate a backup
- on the web interface, click around the main menu on the left, for example "Show Log"
- click on the "Duplicati" word in the upper left hand corner to show running backups
- a badly rendered progress bar is displayed
- the issue is observed with both Edge and Firefox browsers

### Screenshots

![capture](https://cloud.githubusercontent.com/assets/22507450/18931650/f5406cbc-85c4-11e6-86ea-df39f006f04f.PNG)

**Comment by agrajaghh** [comment] 2016-09-28 20:58
closing as duplicate of #1954

**Closed by agrajaghh** 2016-09-28 20:58 UTC
