### ISSUE TITLE
Detected file entries with not associated blocks then Unknown header: 2947418657 then nothing gets restored, please help!

### ISSUE THREAD

**Issue by BackupCorrupt** [duplicati/duplicati#1869] opened 2016-08-01 00:31 UTC
I am using duplicati-2.0.1.17_canary_2016-05-14-x64

I tried to restore all files from the front end, it first gave me "Detected file entries with not associated blocks", then it rebuilt a temp database, then Unknown header: 2947418657, then it was verifying, Verifying was at zero percent, I paused it, I un-paused it, and then it just said module running with no output until it looked like it finished but nothing was restored.

I have some critical completely irreplaceable files for which exists no other source. My first redundancy was my raid array which suffered a double drive failure and I lost the array. Duplicati is my last chance. I'm freaking out =(
##

**Comment by BackupCorrupt** [comment] 2016-08-02 09:59
I managed to recover some files using Duplicati.CommandLine but it ran into the Unknown header error again and many of the files it could not restored.

**Comment by BackupCorrupt** [comment] 2016-08-03 22:39
I decrypted the files using Duplicati.Commandline.RecoveryTool without error. It's been making the index for a couple days now and by my estimation will take another four days to finish.

**Comment by kenkendk** [comment] 2016-08-04 15:37
The header error is new to me, but I think it is caused by corrupt files on the backend.
Did you figure out what files were causing it?

**Comment by BackupCorrupt** [comment] 2016-08-11 11:48
Don't know which files were causing it. How can I determine that?
I under estimated the index time, it's still running.

**Comment by BackupCorrupt** [comment] 2016-08-16 10:28
Indexing finished, said there was one error. Running restore with recovery tool, getting a lot of errors.

**Comment by agrajaghh** [comment] 2016-08-16 11:59
@BackupCorrupt can you please post the error messages?

**Comment by BackupCorrupt** [comment] 2016-08-16 23:51
I tried a repair first but it says "The database was attempted repaired, but the repair did not complete. This database may be incomplete and the repair process is not allowed to alter remote files as that could result in data loss." Then I attempted a compact on the encrypted backups and now if I try a restore from those files it says there are files missing and that I should run repair.
So I can't give you the errors I was getting on the encrypted one.

When I did the recovery tool indexing on the decrypted files it finished and at the end said there was 1 error. It didn't say what the error was. It could be it outputted the error somewhere during the process but I missed it since I wasn't watched the screen the whole time. I tried to find a way to have it output everything to a file but all the ways I found didn't allow for keyboard input so wouldn't work since I needed to provide the password when prompted after running the command. Perhaps someone can tell me how to enter the password in on the command line to avoid the prompt? Or a way to output to a file and screen and take keyboard input.
The Dos window only stores so many lines so I can't scroll up for it either. 

Here is an example of what the recovery tool is giving me on attempting restore of the unecrypted database:
    C:\NVIDIA\nForceWin7Vista64Int\15.57\data1.cab (6.29 MB) 0Failed to read hash: jsKieuC2daE6gP6LuLpY01t75GkF53W0mGc1KS0wmxg=
System.Exception: Unable to locate block with hash: jsKieuC2daE6gP6LuLpY01t75GkF53W0mGc1KS0wmxg=
   at Duplicati.CommandLine.RecoveryTool.Restore.HashLookupHelper.ReadHash(String hash)
   at Duplicati.CommandLine.RecoveryTool.Restore.Run(List`1 args, Dictionary`2 options, IFilter filter)
Failed to read hash: Pu5w+tg4eTFJ8n0S/uPP+5j37c4MdLfSBNZ6kNl9J5k=
System.Exception: Unable to locate block with hash: Pu5w+tg4eTFJ8n0S/uPP+5j37c4MdLfSBNZ6kNl9J5k=
   at Duplicati.CommandLine.RecoveryTool.Restore.HashLookupHelper.ReadHash(String hash)
   at Duplicati.CommandLine.RecoveryTool.Restore.Run(List`1 args, Dictionary`2 options, IFilter filter)

**Comment by BackupCorrupt** [comment] 2016-08-17 01:50
Also I can't get the recovery commandline to put the files anywhere but the original location. The help says to use --targetpath but I'm having zero luck. Whats the correct syntax?
--targetpath d:\restore, --targetpath=d:\restore, --targetpath:d:\restore, none worked for me.

Is that the right command? In the other tool it is --restore-path=d:\restore but I'm not sure that works in that tool either.
_____________________________________________
Also There is an error in the help

It should be Restore not Index. 

Restore
-------
Duplicati.RecoveryTool.exe **index** <localfolder> [version] [options]

Restores all files to their respective destinations. Use --targetpath to choose another folder where the files are restored into.
Use the filters, --exclude, to perform a partial restore.
Version can be either a number, a filename or a date. If omitted the most recent backup is used.

**Comment by BackupCorrupt** [comment] 2016-09-10 18:15
Duplicati.commandline.exe restore was running on the decrypted files for approx two weeks before I had a power outage. Last I checked it was still at the downloading file stage (rebuilding database?) and didn't actually start to restore anything. Now it seems I have corruption in the zip's. Been running zip repair on all the files since yesterday. Other then getting a ups and trying again does anyone have any other ideas?

**Comment by kenkendk** [comment] 2017-02-28 21:47
This seems to be the same as #1877.

If I can get one of the zip files that reports the error, I can do some investigation as to what the problem is.

**Comment by kenkendk** [comment] 2017-03-05 20:11
I think this is the same as:
https://github.com/adamhathcock/sharpcompress/issues/33

Unfortunately, the sample file is no longer available.

**Comment by kenkendk** [comment] 2017-03-13 10:14
@BackupCorrupt: I managed to reproduce a similar sounding error for zip archives larger than 4GiB. Do you recall if the size of the files were larger than 4GiB?

**Comment by kenkendk** [comment] 2017-04-06 08:47
I assume this was caused by zip files larger than 4GiB, so it is fixed with 360a90b2ce7f0523e1b51608ebdac8e87151fcbf (and mitigated with aecb7a7)

**Closed by kenkendk** 2017-04-06 08:47 UTC
Labels: backup corruption, bug
