### ISSUE TITLE
Fatal error backup to Google Drive

### ISSUE THREAD

**Issue by bobkous** [duplicati/duplicati#1393] opened 2015-06-04 14:55 UTC
Hi,

Since 12 days, I am unable to backup to Google Drive. I get the error below:
Fatal error
Google.GData.Client.GDataRequestException: Execution of authentication request returned unexpected result: 404

I did not change anything to either configuration of Duplicati, nor Google Drive.

Thanks in advance for your help.

**Comment by agrajaghh** [comment] 2015-06-04 16:53
duplicate of #1390

**Comment by kenkendk** [comment] 2015-06-22 11:51
I am tracking this in issue #1347 and am almost done with a new Google Drive backend.

**Closed by kenkendk** 2015-06-22 11:51 UTC

**Comment by kenkendk** [comment] 2015-07-02 20:06
If you want to test the preview that is not yet released for automatic update, you can find it here:
http://updates.duplicati.com/preview/duplicati-2.0.0.86_preview_2015-07-02.zip

**Comment by bobkous** [comment] 2015-07-03 19:51
Hi Kenneth,

I downloaded this version, but the previous connection does not work anymore. Do you have some recommendations to restore the previous backup configuration, to prevent a new backup set.

When I simply point to the old folder using the new OAUTH, I get a message that the folder does not exist.


Thanks in advance for your help.






Kind regards,
Bob de Kousemaeker
Blog: http://bobkous.tumblr.com
Facebook, Gmail, LinkedIn, Twitter and Skype: bobkous





Van: Kenneth Skovhede
Verzonden: ‎donderdag‎ ‎2‎ ‎juli‎ ‎2015 ‎22‎:‎06
Aan: duplicati/duplicati
CC: Bob Dekousemaeker





If you want to test the preview that is not yet released for automatic update, you can find it here:
http://updates.duplicati.com/preview/duplicati-2.0.0.86_preview_2015-07-02.zip

**Comment by kenkendk** [comment] 2015-07-04 07:26
To use an existing folder, you need to use the OAuth service with the "Google Docs" button.
The "Google Drive" button uses a slimmed down permission set, such that Duplicati can only access files it create itself. This is better as there is less chance that it will destroy documents if there is some weird bug. However, the previous GoogleDocs backend did not have this limitation, so files created by this backend cannot be seen with the limited acces.

lt;dr: Use the "Google Docs" button here: https://duplicati-oauth-handler.appspot.com

**Comment by bobkous** [comment] 2015-07-04 09:38
Thank you very much. I am back in business again.
