### ISSUE TITLE
Error: SecureChannelFailure (The authentication or decryption has failed.)

### ISSUE THREAD

**Issue by rkarlsba** [duplicati/duplicati#2672] opened 2017-08-29 16:42 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.2
**Operating System:** Debian Stretch
**Backend:** Jotta

### Bug description
Error message: Error: SecureChannelFailure (The authentication or decryption has failed.)

### Steps to reproduce
- No idea

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Crashed

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Works
![skjermbilde 2017-08-29 kl 18 41 38](https://user-images.githubusercontent.com/4253147/29832852-dd64ee92-8ce9-11e7-877e-24dbc9f08cce.png)

**Comment by kenkendk** [comment] 2017-09-01 08:30
Sounds like an SSL/TLS issue, does this help:
https://github.com/duplicati/duplicati/wiki/SSL-TLS-support-in-Mono

**Comment by jpschewe** [comment] 2018-03-18 19:43
I'm running into this same issue and using the TlsTest utility I'm getting a different kind of error
```
FAILED: #-2146233079                                                                      
System.Net.WebException: Error: SecureChannelFailure (The authentication or decryption has
 failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Proto
col.Tls.TlsException: The authentication or decryption has failed.                          at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (System.IAsyncResult async
Result) [0x00040] in <1d0bb82c94e7435eb09324cf5ef20e36>:0                                   at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (System.IAsyncResult ar, System.Boolean ignoreEmpty) [0x00000] in <1d0bb82c94e7435eb09324cf5ef20e36>:0           at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (System.IAsyncResult 
result) [0x00071] in <1d0bb82c94e7435eb09324cf5ef20e36>:0                                    --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (System.IAsyncResult
 result) [0x0003b] in <1d0bb82c94e7435eb09324cf5ef20e36>:0                                  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (System.IAsyncResult
asyncResult) [0x0000c] in <1d0bb82c94e7435eb09324cf5ef20e36>:0                               --- End of inner exception stack trace ---
 at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (System.IAsyncResult
 result) [0x0003b] in <1d0bb82c94e7435eb09324cf5ef20e36>:0                                  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (System.IAsyncResult
asyncResult) [0x0000c] in <1d0bb82c94e7435eb09324cf5ef20e36>:0                               --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.EndRead (System.IAsyncResult asyncResult) [0x00057] in <1d0bb82c94e7435eb09324cf5ef20e36>:0
  at Mono.Net.Security.Private.LegacySslStream.EndAuthenticateAsClient (System.IAsyncResult asyncResult) [0x00011] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at Mono.Net.Security.Private.LegacySslStream.AuthenticateAsClient (System.String targetH
ost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertifi
cates, System.Security.Authentication.SslProtocols enabledSslProtocols, System.Boolean che
ckCertificateRevocation) [0x0000e] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at Mono.Net.Security.MonoTlsStream.CreateStream (System.Byte[] buffer) [0x00044] in <bd4
6d4d4f7964dfa9beea098499ab597>:0
   --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00064]
in <bd46d4d4f7964dfa9beea098499ab597>:0
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <bd46d4d4f7964dfa9beea098499ab5
97>:0
  at TlsTest.GetWebPage (System.String url) [0x000b5] in <ef0b674f44354433abea9f21ff95c135
>:0
  at TlsTest.Main (System.String[] args) [0x002fc] in <ef0b674f44354433abea9f21ff95c135>:0
```

**Comment by jpschewe** [comment] 2018-03-18 19:46
I got around the error by removing the extra security settings on which ciphers to use on my web server.

**Comment by kamilpogo** [comment] 2019-11-05 21:19
I have the same issue with Jottaclould (worked before without any problems). You can reproduce the problem by checking the connection to Jottacloud. It fails with the error "Failed to connect: Error: SecureChannelFailure (The authentication or decryption has failed.)"

**Comment by gibson3659** [comment] 2019-11-06 15:20
I am also experiencing this issue with an encrypted backup to JottaCloud.

**Comment by ts678** [comment] 2019-11-08 22:04
As a guess, Jottacloud may have joined some other services in making TLS 1.0 and TLS 1.1 disallowed because they're insecure. This is seen in Windows in Internet Explorer to https://up.jottacloud.com/jfs while changing the TLS settings. Duplicati can see the same via [--allowed-ssl-versions](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#allowed-ssl-versions) and try backup.

Can @kamilpogo and @gibson3659 please say their OS, and (if relevant) what `mono --version` says? You'll need at least [v4.8](https://www.mono-project.com/docs/about-mono/releases/4.8.0/) to get TLS 1.2, and going to v5 or higher will be a Duplicati requirement soon. None of that applies if you're on fully updated Windows, which gets newest .NET Framework versions.

**Comment by SamiLehtinen** [comment] 2019-11-11 15:57
> what `mono --version` says? 

It seems that Ubuntu 18.04 LTS is using really old mono 4.6.2 updated it and issue got fixed. - Thanks

**Comment by kamilpogo** [comment] 2019-11-12 21:06
Update from mono 4.6.2 to 6.2.0 fixed the problem

**Comment by warwickmm** [comment] 2020-10-18 18:02
Sounds like this was fixed by a mono upgrade.

**Closed by warwickmm** 2020-10-18 18:02 UTC
Labels: mono, ssl/tls issue
