### ISSUE TITLE
ACD - Random "Found xxx remote files that are not recorded in local storage, please run repair" failure messages

### ISSUE THREAD

**Issue by deHoeninger** [duplicati/duplicati#2609] opened 2017-07-23 07:49 UTC
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.72_canary_2017-07-05
**Operating System:** Ubuntu 16.04
**Backend:** ACD

### Bug description
I've five jobs running against ACD as backend, which are scheduled on a daily basis. There are days, where everything is ok and all jobs are finishing ok. But there are days as well, where on a random basis one or more jobs are failing with the following error message:
```
Failed: Found 1 remote files that are not recorded in local storage, please run repair
Details: Duplicati.Library.Interface.UserInformationException: Found 1 remote files that are not recorded in local storage, please run repair
  at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, IBackendWriter log, System.String protectedfile) <0x40d1ad50 + 0x0081f> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.PostBackupVerification () <0x40d683e0 + 0x0017f> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, IFilter filter) <0x40cf7450 + 0x01da3> in <filename unknown>:0 
```
If I run a repair, as suggested, for affected jobs on next day, the repair comand is telling me, that everything is ok and there is nothing to repair. If run no repair, nothing changed, normally a failing job will succeed without any furhter warnings on the next run.

### Steps to reproduce
Appears randomly to all my scheduled backup jobs.

**Actual result:** Randomly failed backup jobs 
**Expected result:** Normal running backup jobs without random failures.

**Comment by kenkendk** [comment] 2017-07-25 06:13
This is an issue with how ACD works. There is a "delay" after each operation where the data is not consistent. You can adjust the parameter `--amzcd-consistency-delay=60s` to wait 60 seconds after each operation before checking it (default is `15s`). If you find that `30s` is sufficient to remove the errors, I will update the default to use that.

**Comment by basilesimon** [comment] 2017-07-25 13:48
@kenkendk I'm experiencing a similar issue, although on a Backblaze b2 remote. Will have a play this evening and post more if that helpful 👌

**Comment by deHoeninger** [comment] 2017-08-11 07:38
Hi @kenkendk,
I'm, currently running with 45s and still got those errors from time to time. I will try it with 60s now.

**Comment by njfox** [comment] 2017-08-24 16:51
I just commented on this issue in #2449 but setting --amzcd-consistency-delay=60s seems to have resolved the issue for now. I will report back if I notice issues in the future.

**Comment by njfox** [comment] 2017-08-25 13:10
Update: issue is still occurring intermittently with a 60s consistency delay.

**Comment by deHoeninger** [comment] 2017-08-26 19:51
I'm experiencing the same thing linke njfox, even with 60 seconds, the failure occures from time to time. Nevertheless, higher values seems to result in another failure:
```Failed: GetResponse timed out
Details: System.Net.WebException: GetResponse timed out ---> System.Net.WebException: Aborted.```

So I would say, the ACD issue is not fixable in that way. Any other ideas?

**Comment by njfox** [comment] 2017-10-19 01:51
@kenkendk do you have any ideas on how to address this issue aside from increasing the consistency delay? I see the 2.0 milestone tag but I wasn't sure if anyone was actively working on this.

**Comment by deHoeninger** [comment] 2017-10-19 10:36
Hi all,
short update from my side. Since one of the last canary updates, all my backups performing well now. No more error message like mentioned before.

Might be related to  2017-09-19 - 2.0.2.7_canary_2017-09-19
* Fixed an issue with AmzCD not honoring the consistency delay in all cases

All jobs are currently configured with --amzcd-consistency-delay=55s, but I suppose, that such a big value is not needed any more since last changes.

Best

**Comment by mackshot** [comment] 2017-10-27 08:15
Hello,
I can confirm that it does not work with an amzcd-consistency-delay of 55s in beta. But with Duplicati - 2.0.2.12_canary_2017-10-20 it works with 55s and also 15s for three days each now.
I like to suggest to set up a default delay for storage engine amazon cloud drive, since otherwise people will over and over again report that issue here.
/Markus

**Comment by warwickmm** [comment] 2019-09-11 04:10
Closing this since the Amazon Cloud Drive API has been discontinued.

**Closed by warwickmm** 2019-09-11 04:10 UTC
Labels: bug, pending user feedback
