### ISSUE TITLE
Duplicati login error

### ISSUE THREAD

**Issue by HennieRoets** [duplicati/duplicati#1394] opened 2015-06-04 15:06 UTC
Has anybody had success in making changes so that we can continue to use Duplicati. The 404 Auth error.

Will someone please explain if Duplicati will fix this or if we have to fix it ourselves.

If so, has anybody managed to fix this? The Facebook page is of no help
##

**Comment by agrajaghh** [comment] 2015-06-04 16:53
duplicate of #1390

**Comment by HennieRoets** [comment] 2015-06-05 12:31
I am still lost. Sorry for not understanding. It seems that a lot is fixing the problem with re writing their code. But I still don't get it. Is there a way to make Duplicati work again in Google Drive, or is this the end of Duplicati connecting to Google Drive? Is there someone that has the source code for Duplicati so we can change it....? I'm lost. The last time I programmed was in VB6....old days. Should we recode Duplicati, or what. Please explain

**Comment by agrajaghh** [comment] 2015-06-05 12:41
The code for duplicati is here in this repo on github (https://github.com/duplicati/duplicati)

I guess it will be fixed sooner or later in duplicati 2.0 when the dev has some time or some one else is submitting a pull request.

**Comment by HennieRoets** [comment] 2015-06-05 12:48
OK. I get it. Thanks a mil for your help.

**Closed** 2018-02-11 02:16 UTC
