### ISSUE TITLE
Setting password for the first time causes never ending failed request loop

### ISSUE THREAD

**Issue by darksworm** [duplicati/duplicati#2844] opened 2017-10-24 09:52 UTC
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1
- **Operating system**: Windows 7 and Windows 10
- **Backend**: N/A

## Description

When first setting a password, when logging in an error pops up: `Failed to get nonce: Too many active login attempts`. The issue is resolved after restarting Duplicati. 

## Steps to reproduce

1. Install Duplicati (or delete duplicati folder from Appdata)
2. Set password in settings
3. Try to log in

- **Actual result**:
An error pops up: `Failed to get nonce: Too many active login attempts`
- **Expected result**:
User successfully logged in

## Screenshots

image-1
![2017-10-24_12-44-29](https://user-images.githubusercontent.com/9987548/31936174-832513b6-b8b9-11e7-822b-edfced2bcae7.gif)
image-2
![qzcbxji](https://user-images.githubusercontent.com/9987548/31936256-b995c6f2-b8b9-11e7-9a1d-4b8d70e0e251.png)

## Notes
After changing the password there seem to be many failed requests to `/login.cgi` and they don't seem to stop (see image-2) but I cannot find where they originate from.
If you already had a password and you unset it, then set it again - this problem does not occur.

**Comment by SandiaScalpel** [comment] 2017-10-29 15:35
This happens to me using Linux Mint as well.

**Comment by janmadera** [comment] 2017-10-30 19:07
Same here using Windows. Just set the password and I'm out. How can I login again?

**Comment by TheFatherMind** [comment] 2017-11-01 05:08
This bug has been around for a while now.  Considering that it totally breaks the product I am surprised it has not been resolved yet.

**Comment by janmadera** [comment] 2017-11-01 07:17
I was able to get in again by restarting the application and connection using localhost instead of a hostname url from remote. I went directly to settings and disabled password auhentication - now I‘m fine again. 

This workaround is another bug.

**Comment by fiver22** [comment] 2017-11-02 15:23
Same; on Ubuntu  16.04. Duplicati version 2.0.2.1_beta_2017-08-01

**Comment by SandiaScalpel** [comment] 2017-11-05 14:01
I agree with @janmadera that the workaround is a bug as well. You certainly
do not want to install as root and enable remote access in the settings
unless you know that have tight control of your port forwarding and trust
everyone on your local network.

**Comment by wgstarks** [comment] 2017-11-09 01:23
Ran right into this issue after installing on a mac. Localhost workaround was no good since I was already using localhost to start with. Had to run the uninstall.sh script, reboot and then reinstall the app to get back in. Not good.

**Comment by kenkendk** [comment] 2017-11-17 14:04
The login guard is kept in memory, so restarting Duplicati should clear it and allow you to log in.

I think the problem is that there is a monitoring thread that keeps the UI updated, and after the password is enabled it hammers the server trying to get the latest state and this triggers the login guard.

**Comment by TheFatherMind** [comment] 2017-11-17 18:09
@kenkendk I think you should read this thread more closely.  (:
For most of us the only way to login is to clear the config folder all together and start fresh.  Restarting anything and everything has had very little results.

**Comment by SandiaScalpel** [comment] 2017-11-23 15:45
@TheFatherMind and @kenkendk 

I had this issue on my Linux Mint laptop for a while. tried rebooting, stopping and restarting the app, etc. and nothing worked. I was always able to get back in opening a terminal and starting a new instance of the app as root, then opening settings and un-checking the password option. Finally, I was able to stop the password lock up behavior by setting a password (it locked up .... something about a nonce) then I restarted duplicati in a terminal - this auto opens the app in a browser on my machine but with a newly designated port than the first (locked-up) instance. Interestingly, the new instance did not request a password. Nevertheless, I then closed both browser instances and cleared my browser cache and then reopened the app in the browser with the second port - it asks for a password this time! I then rebooted my laptop and now when I open duplicati in a browser (just the first instance) it asks for a password.

I don't know if all these micro steps are necessary or if some permutation of the sequence will also work, but this worked for me. Happy to have access to this behind a password - even if there are some issues.

**Comment by kenkendk** [comment] 2017-11-24 12:42
The timeout guard is kept in memory only, but if you keep the browser window open, it will keep pinging and quickly block the restarted instance as well.

Another way to set the password (in case you forgot it, or want to reset it), is to launch the executable with `--webservice-password=newpassword` (use `--webservice-password=` to disable).

**Comment by jamestehgreat** [comment] 2017-12-05 18:35
Just happened after setting a password with a new install on Fedora 27.  I will restart, thanks for the help.

**Comment by Pectojin** [comment] 2018-01-28 16:33
Was a fix for this introduced? When I'm trying to replicate this in Canary_2.0.2.16 it redirects to login and allows me to login without any issues.

**Comment by kenkendk** [comment] 2018-01-29 13:40
I don't think this has been fixed, but I was not able to reproduce myself either.

**Comment by Pectojin** [comment] 2018-02-14 22:08
@kenkendk, we've had success replicating this issue in #3035 

In fact, it kind of seems like it should happen to everyone on their first run if they enable a password.

**Comment by perler** [comment] 2018-02-25 13:36
still there. complete showstopper..

**Comment by Pectojin** [comment] 2018-02-25 13:40
@perler, it really shouldn't be a show stopper. It's annoying but the issue should go away after you restart the GUI trayicon.

In any case, @mnaiman, just made a pull request 42 minutes ago that should resolve both #3035 and this issue. Should be possible to fit it into next release :)

**Comment by perler** [comment] 2018-02-25 13:49
ok, maybe a slight overreaction :) - but I depend on distributing duplicati to the technically uninitiated, so this is very annoying, as it needs a lot of explaining ("what is a 'tray icon'?")

**Comment by Pectojin** [comment] 2018-02-25 13:53
@perler, oh it's definitely annoying and I agree it should have been fixed sooner. Sadly we just didn't know exactly how to replicate it until I stumbled across it a week back.

**Comment by Pectojin** [comment] 2018-03-05 08:29
#3066 was just merged which resolves this issue.

**Closed by Pectojin** 2018-03-05 08:29 UTC
Labels: UI, bug, good first issue, help wanted
