### ISSUE TITLE
Invalid Name & Error Code 3

### ISSUE THREAD

**Issue by saviodsouza** [duplicati/duplicati#1387] opened 2015-05-22 10:51 UTC
Warring messages

Warnings: [Failed to process path: D:\fOLDER NAME\VERY\LONG\PATH\TO\DESTINATION\FILE\FILE.NAME => Invalid name.
.................................................................................
You are currently running Duplicati 2.0.0.85- 2.0.0.85_preview_2015-03-07

Windows server 2008 64 bit with ntfs.

**Comment by agrajaghh** [comment] 2015-05-22 11:12
duplicate of #1380

**Comment by saviodsouza** [comment] 2015-07-06 08:13
some more details

You are currently running Duplicati 2.0.0.87- 2.0.0.87_preview_2015-07-03

--snapshot-policy=required
FilesWithError: 83

Warnings: [Failed to process path: X:\XXXXXX XXXXXXXX XXXXXX\XXXX XXXXXX XXXXXX\XXXXXX XXXXXX\XXXXXXXX & XXXXXX\XXXXXX XXXXXX 201011 XXXXX XXXX\XXXXXXX XXXXXXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX\XXXXXXX 19 XXX\XXXXXX XXXXXXX\XXXXXX (1)\XXXXXX XXXXXX (3)\XXXXXXX XXX XXXXXXXX XX XXXXXXXXX (1).XXX => Invalid name.
Parameter name: name, Failed to process path: X:\XXXXXX XXXXXXXX XXXXXX\XXXX XXXXXX XXXXXX\XXXXXX XXXXXX\XXXXXXXX & XXXXXX\XXXXXX XXXXXX 201011 XXXXX XXXX\XXXXXXX XXXXXXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX\XXXXXXX 19 XXX\XXXXXX XXXXXXX\XXXXXX (1)\XXXXXX XXXXXX (3)\XXXXXXX XXX XXXXXXXX XX XXXXXXXXX (2).XXX => Invalid name.
Parameter name: name, Failed to process path: X:\XXXXXX XXXXXXXX XXlXXX\XXXX XXXXXL XXXXXX\XXXXXL XXXXXX\XXXXXXXX & XXXXXX\XXXXXl XXXXXX 201011 XXXXX XXXX\XXXXXXl XXXXXXXX XXXXXXXXXX XXX XXXXl LXXXlXXXXXX\XXXXXXX 19 XXX\XXXXXX XXXXXXX\XXlXXX (1)\XXXXXX XXlXXX (3)\XXXXXXX XX XXXXXXXX XXXXXXXXXX 200719.XXX => Invalid name.....................


.................code 3., Failed to process path: X:\XXXXXX XXXXXXXX XXXXXX\XXXX XXXXXXXX XXXXXX\XXXXXXXX\XXXXXXXX 2014-2015\XXX\XXX\XXXXXXX XXXXX\XXXXX XXXXX\XXXX XXXXXXXXXXXX 9.7.2014.xXXx => Method failed with unexpected error code 3., Failed to process path: X:\XXXXXX XXXXXXXX XXXXXX\XXXX XXXXXXXX XXXXXX\XXXXXXXX\XXXXXXXX 2014-2015\XXX\XXX\XXXXXXX XXXXX\XXXXX XXXXX\XXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX - XXXXXXX.XXX => Method failed with unexpected error code 3.]
Errors: []

**Closed** 2016-04-03 12:07 UTC
