### ISSUE TITLE
Running duplicati, headless on ubuntu 16.04.01 and getting an error..

### ISSUE THREAD

**Issue by mikedevita** [duplicati/duplicati#2155] opened 2016-12-03 17:13 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.30-1
**Operating System:** Ubuntu x64 server 16.04.01
**Backend:** Amazon Cloud Drive

### Bug description
When running headless i get the following error in the web gui 

```
System.TypeLoadException: Failure has occurred while loading a type.
  at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) <0x41d45900 + 0x00782> in <filename unknown>:0
```

### Steps to reproduce
- start the headless server using systemd script
- login to the web ui
- error is given

My systemd script is like so, i modified `/usr/bin/duplicati` to start the Duplicati.Server.exe instead of the client

```
[Unit]
Description=Duplicati Backup software
After=network.target
[Service]
Environment=INSTALLDIR=/usr/lib/duplicati
Environment=LD_LIBRARY_PATH="${INSTALLDIR}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
Environment=MONO_PATH=$MONO_PATH:${INSTALLDIR}
Environment=EXE_FILE=${INSTALLDIR}/Duplicati.Server.exe
ExecStart=/usr/bin/duplicati --webservice-port=8200 --webservice-interface=192.168.10.100
Restart=on-failure
RestartSec=30

[Install]
WantedBy=multi-user.target
```

**Comment by kenkendk** [comment] 2016-12-07 20:20
I think this has been fixed in the latest canary. It was caused by an attempt to load VSS/HyperV and other MS things on Linux prior to checking if the OS supports it. You can upgrade to the canary, or install `sudo apt install libmono-system-management4.0-cil` which is the library that is loaded before checking that it should ignore the rest.

**Comment by kenkendk** [comment] 2017-04-19 08:01
Closing for lack of feedback and assuming fixed.

**Closed by kenkendk** 2017-04-19 08:01 UTC
Labels: pending user feedback
