### ISSUE TITLE
System.OutOfMemoryException on OSX 10.9, 2.0.1.11

### ISSUE THREAD

**Issue by karlmustman** [duplicati/duplicati#1798] opened 2016-06-07 15:17 UTC
I use 2.0.1.11- 2.0.1.11_experimental_2016-04-08 version on OSX 10.9.5, Mono 4.2.3 (x86). The destination is Amazon Cloud Drive. I have 16G of RAM and ~50% of it is free. When I check in Task Manager, Duplicati uses only up to 1G of RAM. There may be a memory leak because when a smaller  task is finished the app still uses 1G of RAM in idle. OutOfMemory Exception occurs on a task with ~ 40Gb of data and ~11k items. It doesn't occur on smaller tasks (2-3 Gb). 

Here is the exception stack trace:

Out of memory
  at <0x00000 + 0x00000> <unknown method>
  at (wrapper alloc) System.Object:AllocVector (intptr,intptr)
  at SharpCompress.Compressor.PPMd.I1.Allocator.Start (Int32 allocatorSize) <0x8cae328 + 0x0003b> in <filename unknown>:0 
  at SharpCompress.Compressor.PPMd.PpmdProperties.set_AllocatorSize (Int32 value) <0x8cae090 + 0x0008b> in <filename unknown>:0 
  at SharpCompress.Compressor.PPMd.PpmdProperties..ctor (Int32 allocatorSize, Int32 modelOrder, ModelRestorationMethod modelRestorationMethod) <0x8cae048 + 0x0001f> in <filename unknown>:0 
  at SharpCompress.Compressor.PPMd.PpmdProperties..ctor (Int32 allocatorSize, Int32 modelOrder) <0x8cae010 + 0x00027> in <filename unknown>:0 
  at SharpCompress.Compressor.PPMd.PpmdProperties..ctor () <0x8cadfd8 + 0x00023> in <filename unknown>:0 
  at SharpCompress.Writer.Zip.ZipWriter..ctor (System.IO.Stream destination, SharpCompress.Common.CompressionInfo compressionInfo, System.String zipComment) <0x8cade60 + 0x0002b> in <filename unknown>:0 
  at SharpCompress.Writer.WriterFactory.Open (System.IO.Stream stream, ArchiveType archiveType, SharpCompress.Common.CompressionInfo compressionInfo) <0x8cadc90 + 0x00093> in <filename unknown>:0 
  at Duplicati.Library.Compression.FileArchiveZip..ctor (System.String filename, System.Collections.Generic.Dictionary2 options) <0x8cad788 + 0x002ef> in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) <0x289c338 + 0x00033> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) <0x289c338 + 0x0007b> in <filename unknown>:0 
  at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x28f75b8 + 0x000c3> in <filename unknown>:0 
  at System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x371c940 + 0x00037> in <filename unknown>:0 
  at System.RuntimeType.CreateInstanceImpl (BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) <0x28a78f0 + 0x00552> in <filename unknown>:0 `
##

**Comment by kenkendk** [comment] 2017-04-19 08:02
This should be fixed with f9e5eeae0caa3ca238fe1df768b5999b455df024 and looks like a duplicate of #2320

**Closed by kenkendk** 2017-04-19 08:02 UTC
