### ISSUE TITLE
Popup menu on backup entries in 2.0.0.81 unusable on small screens

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#1293] opened 2015-02-11 16:37 UTC
I have a laptop with 768px vertical resolution. Without zooming out on the webpage in my firefox, I can't use the popup menu on backup entries properly, because the first few entries are above the visible area of the web site. See image, where I clicked on the menu for the last entry visible.
![clipboard01](https://cloud.githubusercontent.com/assets/9739281/6151195/9110e5f8-b214-11e4-8910-f20d3a846e82.jpg)

**Comment by agrajaghh** [comment] 2015-02-11 17:18
duplicate of #1183

**Comment by huste** [comment] 2015-02-11 17:58
Sorry, I just looked for "popup" before postinh...

**Comment by agrajaghh** [comment] 2015-02-11 19:08
I guess, it's referenced in the other issue anyway ;)

**Comment by renestach** [comment] 2015-02-28 12:21
Closed as duplicati of #1183.

**Closed by renestach** 2015-02-28 12:21 UTC
