### ISSUE TITLE
Non-RSA SSH key rejected with poor error message

### ISSUE THREAD

**Issue by Baughn** [duplicati/duplicati#2950] opened 2018-01-03 16:13 UTC
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: OS X
- **Backend**: SSH/SFTP

## Description

When given a non-RSA ssh key, in particular a Curve25519 key as generated with `ssh-keygen -t ed-25519`, Duplicati rejects the key with a "Key type is not supported: OPENSSH" error message.

Keys generated with `-t rsa` work as expected, but RSA keys are comparatively massive and increasingly a poor choice.

## Steps to reproduce

1. Generate Curve25519 key
2. Attempt to connect to server using that key
3. ???
4. No profit.

- **Actual result**:
Error message
- **Expected result**:
A working backup, or at least a better error message. Only random guesswork after an hour's googling made me try it with an RSA key; I was on the brink of dropping Duplicati.

**Comment by Pectojin** [comment] 2018-01-06 19:28
I've replicated the issue with an ed25519 key. 

The given error is thrown here in [duplicati/duplicati/blob/master/Duplicati/Library/Backend/SSHv2/SSHv2Backend.cs#L358](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Backend/SSHv2/SSHv2Backend.cs#L358)

> catch (Exception ex)
            {
                throw new UserInformationException(string.Format("Failed to parse the keyfile, check the key format and passphrase. Error message was {0}", ex.Message), ex);
            }

I think it's caused by the Renci.SshNet library `PrivateKeyFile()` method, and the text `Key 'OPENSSH' is not supported` comes directly from `ex.Message`

As far as I can tell the SshNet library only supports RSA and DSA, so options are:
1. Wrap the error message to help users troubleshoot, maybe add some code before hand checking the key type.
2. Find a new ssh library that supports ed25519

**Comment by Pectojin** [comment] 2018-01-27 02:59
Issue #2808 is also talking about ed25519 support in the ssh ssh library. Adding a comment here for reference. 

Even though they're not strictly duplicates they might be resolved by the same change in the future.

**Comment by Kobberholm** [comment] 2018-06-04 04:04
Came here after searching for "duplicati Error message was Key 'OPENSSH' is not supported".
The issue about lack of ECDSA support has been open with SSH.NET for two years without any updates, so it seems unlikely that it will be supported any time soon - if ever.

How about using the WinSCP library instead?
https://winscp.net/eng/docs/library

**Closed** 2021-03-06 13:21 UTC
