### ISSUE TITLE
Official docker image is not including all backends

### ISSUE THREAD

**Issue by Sytten** [duplicati/duplicati#3198] opened 2018-04-28 19:30 UTC
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.6
- **Operating system**: Ubuntu
- **Backend**: OneDriveV2

## Description

The new OneDriveV2 backend that is present in all installations of 2.0.3.6 is not present in the docker image for some reason. Same thing for the SharePoint V2.
I am using the canary tag and I can see in the About that I'm running the latest version.
I suspect that for some reason the version is older that the latest release, because in the latest release I can upload files without any problem using the old backend on linux and it is not the case in the docker.

## Steps to reproduce

1. Launch the docker
2. Try to create a new backup

- **Actual result**:
The new v2 backend for microsoft is not an option
- **Expected result**:
Should be able to create a backup with the v2 backend.

**Comment by JonMikelV** [comment] 2018-05-04 00:58
I can confirm that I'm also not seeing it in my official Docker container on 2.0.3.3 beta, though I do not currently have a non-Docker beta to confirm against.

**Comment by leonghui** [comment] 2018-09-17 02:35
Also reported by other users in the forums:
https://forum.duplicati.com/t/onedrivev2-not-available-as-provider-choice/4100

**Comment by 1n5aN1aC** [comment] 2018-10-31 23:10
Same issue here.

Note that this is a big deal, as per Microsoft documentation, the old API will be depreciated as of **November 1st, 2018**.  That's tomorrow.

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/migrating-from-live-sdk?view=odsp-graph-online

**Comment by ts678** [comment] 2018-11-07 14:44
Where did "December 1st, 2018" appear? On that page it does speak twice of "December 1, 2017". Regardless, the cutoff seems not to have happened per original schedule (or we'd be hurting now).

There are probably two issues getting mixed together in this discussion. First is that OneDriveV2 is (unfortunately) not in a channel besides Canary, regardless of platform or packaging. Confirmed on Windows, but also checking in the 2.0.3.3 Beta sources. Now on to answering how it might roll out:

[Any progress in new beta?](https://forum.duplicati.com/t/any-progress-in-new-beta/5141) describes plans, including new Experimental (between Canary and Beta).

Second issue (actually the original one here) is that Docker build lacks it while other builds have it.  Any Docker users able to see if the .dll is on their system but not in the UI, or to see whether the linuxserver Docker has it (somehow) but official Duplicati doesn't? Unfortunately I don't use Docker, so can't help.

**Comment by leonghui** [comment] 2018-11-09 04:20
Here's a snippet of the backend .dll from the latest canary image (linux-amd64-2.0.3.14_canary_2018-11-08).

![image](https://user-images.githubusercontent.com/6092315/48243110-7dc24880-e419-11e8-908d-9943bf4b450b.png)

**Comment by ts678** [comment] 2018-11-11 23:15
[Release: 2.0.4.1 (experimental) 2018-11-08](https://forum.duplicati.com/t/release-2-0-4-1-experimental-2018-11-08/5235) announced the new Experimental. although I don't think there are any changes for this. I'm worried because I just installed Docker to try the official build, and browser showed these missing, which is worse than I've seen reported, and not all the damage is from Microsoft's push to v2:

Microsoft Office 365 Group
Microsoft OneDrive
Microsoft OneDrive v2
Microsoft SharePoint v2

Before getting to details, anyone else also missing "Microsoft OneDrive"? That could be a rude Beta surprise.

Though it's rather cumbersome, I also retrieved the Server API's systeminfo URL with curl. Result summary is:
"Key": "aftp",
"DisplayName": "Alternative FTP",
"Key": "amzcd",
"DisplayName": "Amazon Cloud Drive",
"Key": "azure",
"DisplayName": "Azure blob",
"Key": "b2",
"DisplayName": "B2 Cloud Storage",
"Key": "box",
"DisplayName": "Box.com",
"Key": "cloudfiles",
"DisplayName": "Rackspace CloudFiles",
"Key": "dropbox",
"DisplayName": "Dropbox",
"Key": "ftp",
"DisplayName": "FTP",
"Key": "file",
"DisplayName": "Local folder or drive",
"Key": "googledrive",
"DisplayName": "Google Drive",
"Key": "gcs",
"DisplayName": "Google Cloud Storage",
"Key": "hubic",
"DisplayName": "HubiC",
"Key": "jottacloud",
"DisplayName": "Jottacloud",
"Key": "mega",
"DisplayName": "mega.nz",
"Key": "openstack",
"DisplayName": "OpenStack Simple Storage",
"Key": "rclone",
"DisplayName": "Rclone",
"Key": "s3",
"DisplayName": "Amazon S3",
"Key": "ssh",
"DisplayName": "SFTP (SSH)",
"Key": "od4b",
"DisplayName": "Microsoft OneDrive for Business",
"Key": "mssp",
"DisplayName": "Microsoft SharePoint",
"Key": "sia",
"DisplayName": "Sia Decentralized Cloud",
"Key": "tahoe",
"DisplayName": "Tahoe-LAFS",
"Key": "webdav",
"DisplayName": "WebDAV",

A non-cumbersome way to see the "Key" fields concatenated is to run Duplicati.CommandLine.BackendTool.exe help. Sometimes it sees the old onedrive, but not newer backends.

Linux (the same one hosting Docker) works fine on Experimental. I did "docker export" to compare to Linux, and found differences (e.g. Docker had some Windows things, but maybe that's for Windows) but nothing clearly related. I also ran the docker Duplicati files on Linux mono and they worked fine. I'd guess that the problem begins in results of the [dynamic loader](https://github.com/duplicati/duplicati/blob/df31769ccee4ee051b7937643119adae66b5cbe4/Duplicati/Library/DynamicLoader/DynamicLoader.cs#L70) process of discovering storage types found in the .dll files. Duplicati.Library.Backend.OneDrive.dll in Docker gives odd results even if it's all by itself (I moved the other backends elsewhere), in which case no storage types are displayed. Moving File back in got just that, with OneDrive still ignored. Trying to get a linuxserver version of this Experimental failed (maybe due to my not knowing how). The most recently uploaded version there still seems to be 2.0.3.3 beta, but I did take that, then tried dropping the new Onedrive dll into it from a downloaded .zip. It didn't show up at first, but after removing B2 it did, then stayed showing after I put B2 back. I haven't tried this yet with the official duplicati Docker. Test results are oddly variable. Anyone seeing any of the items from my "missing items list" at top? Anyone seeing other missing backends besides those? If not, I think it's a one-(rather important)-dll issue.

**Comment by ts678** [comment] 2018-11-12 22:41
There's a manual solution at [OnedriveV2 not available as provider choice](https://forum.duplicati.com/t/onedrivev2-not-available-as-provider-choice/4100/14?u=ts678) and [Release: 2.0.4.2 (experimental) 2018-11-12](https://forum.duplicati.com/t/release-2-0-4-2-experimental-2018-11-12/5266) is out for those preferring to take a fixed image. If you had this issue, please say if these helped.

**Comment by JonMikelV** [comment] 2018-11-13 05:49
I believe one user tried the in-container fix and it sounded like that worked for them.

I (clumsily) updated my container from 2.0.3.3 beta to 2.0.4.2 experimental and that resolved the issue for me

**Comment by JonMikelV** [comment] 2019-01-22 18:51
Closing - resolved as of https://github.com/duplicati/duplicati/releases/tag/v2.0.4.3-2.0.4.3_canary_2018-11-13.

**Closed by JonMikelV** 2019-01-22 18:51 UTC
