### ISSUE TITLE
Duplicati configuration folder got moved during Windows major upgrade 

### ISSUE THREAD

**Issue by sevencastles** [duplicati/duplicati#2428] opened 2017-04-12 08:15 UTC
### Version info
**Duplicati Version:** 2.0.1.53_experimental_2017-03-13
**Operating System:** Windows 10, Version 1703 (Creators Update), SO Build 15063.138

### Bug description
Not sure if it's a Duplicati bug, but I am posting it here anyways. 

I run Duplicati as a service, because I have multiple users running on the OS. After having upgraded Windows 10 to the last "Creators update", I noticed that Duplicati was running with an empty/clean configuration. This is because the upgrade process moved some file/folders to "C:\Windows.old". 

To fix the issue, I moved folder `C:\Windows.old\Windows\System32\config\systemprofile\AppData\Roaming\Duplicati` back to `C:\Windows\System32\config\systemprofile\AppData\Roaming`.

### Steps to reproduce
- Install Duplicati on Windows 10 (prior to Creators Update) and run it as a service
- create some dummy configuration
- upgrade Windows 10 to Creators Update
- check Duplicati configuration, it should be empty

**Comment by gorbiWTF** [comment] 2017-04-12 18:53
See error #1950

**Comment by kenkendk** [comment] 2017-05-04 19:11
Yes, closing as duplicate of #1950

**Closed by kenkendk** 2017-05-04 19:11 UTC
