### ISSUE TITLE
Advanced option "alternate-target-paths" is not present on the UI in some cases

### ISSUE THREAD

**Issue by atestovgit** [duplicati/duplicati#5047] opened 2023-10-21 00:19 UTC
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.7.1_beta_2023-05-25
- **Operating system**: Windows 10 Version 22H2 (Build 19045.3570)
- **Backend**: local

## Description
In some cases the created backup doesn't show added option **alternate-target-paths** on the web UI when Edit the backup 

## Steps to reproduce
1. UI Menu "Add backup" -> "Next" button
2. On the General tab: 
    - Name: "test backup"
    - Click "Generate" link to generate Passphrase
    - Click "Next" button
3. On the "Destination" tab:
    - Click "Manually type path"
    - Folder path: **C:\tmp_dest1\\**
    - Add Advanced option **alternate-target-paths** with value **C:\tmp_dest2\\**
    - Click "Next" button
4. On the "Source data" tab:
    - Add any existent source folder with files e.g. **C:\tmp_source\\**
    - Click "Next" button
5. On the "Schedule" tab:
    - Uncheck "Automatically run backups." checkbox
    - Click "Next" button
6. On the "Options" tab:
    - Click "Save" button
7. Click on the created backup "test backup" and then "Edit" link
8. Click "Destination" tab and then "Advanced options"

- **Actual result**:
**alternate-target-paths** option is not present on the UI
- **Expected result**:
**alternate-target-paths** option is present on the UI with **C:\tmp_dest2\\** value

## Screenshots
![image](https://github.com/duplicati/duplicati/assets/51711036/f160a281-2034-4070-a56d-56c2d81ebc98)

## Notes:
- Although option is not visible on UI, the backup is working as expected.
- Exported json configuration file contains **alternate-target-paths** with correct value
- When fill destination path with **tmp_dest1\\** value (instead of **C:\tmp_dest1\\**) during the new backup creation then **alternate-target-paths** is present on UI as expected
- Although backup is working as expected, after re-saving backup option **alternate-target-paths** will be lost

**Comment by gpatel-fr** [comment] 2023-10-21 14:40
Duplicate of #4553

**Closed by gpatel-fr** 2023-10-21 14:40 UTC
