### ISSUE TITLE
Can't set a password for the web interface.

### ISSUE THREAD

**Issue by dmitryint** [duplicati/duplicati#2199] opened 2016-12-26 07:48 UTC
I have:
- [X] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.36_canary_2016-12-24
**Operating System: debian wheezy**
**Backend: none**

### Bug description
Can't set a password for the web interface.

### Steps to reproduce
- `mono /app/Duplicati.Server.exe --webservice-port=8200 --webservice-interface=* --webservice-password=123456`

**Actual result:** Can't pass the password check. No additional messages, just the password prompt in a loop.
**Expected result:** In version 2.0.1.33_canary_2016-11-27 this problem is not present.

**Comment by deHoeninger** [comment] 2016-12-26 09:10
Hi all,

 
same for me.

 
Von: dmitryint [mailto:notifications@github.com] 
Gesendet: Montag, 26. Dezember 2016 08:49
An: duplicati/duplicati <duplicati@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [duplicati/duplicati] Can't set a password for the web interface. (#2199)

 
I have:

*	[X] searched open and closed issues for duplicates
--------------------------------

Version info

Duplicati Version: 2.0.1.36_canary_2016-12-24
Operating System: debian wheezy
Backend: none


Bug description

Can't set a password for the web interface.


Steps to reproduce
*	mono /app/Duplicati.Server.exe --webservice-port=8200 --webservice-interface=* --webservice-password=123456

Actual result: Can't pass the password check. No additional messages, just the password prompt in a loop.
Expected result: In version 2.0.1.33_canary_2016-11-27 this problem is not present.

**Comment by agrajaghh** [comment] 2016-12-26 23:04
duplicate of #2186 #2200

**Closed by agrajaghh** 2016-12-26 23:04 UTC

**Comment by ifeelingz** [comment] 2017-01-08 19:53
"Server has started and is listening on 127.0.0.1, port 8200"

Can a Public IP ?

Thank you.
