### ISSUE TITLE
scheduler seems not working

### ISSUE THREAD

**Issue by mdsmdsmds** [duplicati/duplicati#1963] opened 2016-09-30 08:44 UTC
2.0.1.26_canary_2016-09-29

If I change schedule option, it always show 
"Next scheduled task: testSet1 Oggi alle 14:00"
... and moreover, it does not start by scheduled in any way...

If needed I can post screencast

**Comment by agrajaghh** [comment] 2016-09-30 10:35
closing as duplicate of #1935

**Closed by agrajaghh** 2016-09-30 10:35 UTC
