### ISSUE TITLE
Login impossible after setting GUI password

### ISSUE THREAD

**Issue by BurninLeo** [duplicati/duplicati#3035] opened 2018-02-14 08:09 UTC
## Environment info
- **Duplicati version**: 2.0.2.19
- **Operating system**: Windows 10
- **Backend**: SFTP

## Description

The new version 2.0.2.19 suggests to set a passwort if using a multi-user environment. It opens the appropriate form in the GUI. After setting a password, a "login failed" message is displayed. Then the login form is displayed (with the password already stored?!).

When I confirm the password or re-type and then confirm, again, a message windows is shown: "Failed to get nonce: Too many active login attempts." The error seems to persist for a few minutes, now...

This error occured after I tried to run the auto-update (which failed, I assume due to insufficient access rights), and then running the MSI to install the new canary version.

**Comment by Pectojin** [comment] 2018-02-14 10:56
I believe #2844 is relevant.
Along with:
https://forum.duplicati.com/t/failed-to-get-nonce-too-many-active-login-attempts-after-setting-user-interface-password/2055
https://forum.duplicati.com/t/login-fails-after-setting-password-mac-osx/1339

It's an issue where the Web UI fails to detect that it needs a password to get resources from the server and instead of then prompting the user to login it just keeps asking the server for the resources until the server locks out the Web UI.

I believe you need to close the open tabs in your browser and restart the Duplicati server.
Alternatively you can start `--webservice-password=newpassword` to set a new password or `--webservice-password=` to disable the password.

**Comment by BurninLeo** [comment] 2018-02-14 11:04
Closing the browser and restarting Duplicati allowed me to login correctly. After that, a new logout and login worked fine. Good, thanks :)

I would apprechiate this being fixed with the next update. You feel some kind of locked out, otherwise.

**Comment by Pectojin** [comment] 2018-02-14 12:08
Yep, it's on the map but both @kenkendk  and I had problems reproducing the problem 2 weeks ago when we last looked into it (with 2.0.2.17).

I'll do some tests with 2.0.2.19 when I get home.

**Comment by BurninLeo** [comment] 2018-02-14 12:43
I also couldn't replicate this within the running 2.0.2.19 (tried to change, remove, and re-set the password).

How can I trigger the message that a password is suggested in a multi-user environment? It may be related to that.

As a workaround, you may consider to add a note: "If this error persists, please quit and restart Duplicati" to the error message "Failed to get nonce: Too many active login attempts." - not a great solution, but extremely helpful for people who are locked out after an update (or whatever conditions).

**Comment by Pectojin** [comment] 2018-02-14 14:38
Hmm, interesting. You may be right that it's related to that multi-user message.

I believe you can re-trigger it by manually editing the SQLite database to remove a value called `has-asked-for-password-protection`. It's in the Duplicati main database, but I can't verify where it is until I get home.

**Comment by Pectojin** [comment] 2018-02-14 15:28
I couldn't help myself and installed Duplicati on a Windows machine at work that has never even seen Duplicati.

I installed the 2.0.2.19 and pressed "yes" right away when prompted for the option to specify a password. I then added the password and saved. It immediately gave me the `Not logged in` message and once I clicked ok I was redirected to the login page...

So no success on replicating this issue on this machine. Maybe it's some ridiculous race condition?

**Comment by Pectojin** [comment] 2018-02-14 22:06
Alright, so just to confirm - If I delete the row `has-asked-for-password-protection` from the `Option` table in the `Duplicati-server.sqlite` database and then start Duplicati it will prompt me with the multi-user message. 

Pressing yes and setting the password causes the issue to happen again, but it won't happen again if I remove password protection and re-add it. 

However, it seems to also happen if I remove the password, restart Duplicati, and then re-add the password. 

So it looks like everyone starting up the Duplicati server and setting the password for the first time should face this issue.

When the password is set it looks like 3 requests are sent (to update local data in the browser) which all get `401 Not logged in` errors. But 3 requests should not be enough to lock you out... I couldn't even trigger the lock out manually by just attempting logins with the wrong password like 100 times in a row.

Additionally, it does not appear to be a problem with the Angular frontend. I've replicated the login process for a [side project](https://github.com/Pectojin/duplicati_client) in Python. So that eliminates the possibility of it being the Web UI not just not authenticating properly against the server. The server decides to lock out all clients and then never (?) recovers unless it's restarted.

**Comment by Pectojin** [comment] 2018-02-14 22:46
Come to think of it... It's the tray icon that can't handle the password...

It's never happened on my headless Ubuntu server - and I can't replicate it when I build the code myself in Visual Studio because it builds without the tray icon. And if I start just the duplicati-server instead of duplicati it doesn't happen anymore... on the machine where I just replicated the problem.

I still get the 3 `401 Not logged in` errors in the Web UI, but it doesn't lock me out.

**Comment by Pectojin** [comment] 2018-02-20 22:45
I narrowed the lock out down to happening in the `PerformRequest` method in [GUI/Duplicati.GUI.TrayIcon/HttpServerConnection.cs#L331](https://github.com/duplicati/duplicati/blob/master/Duplicati/GUI/Duplicati.GUI.TrayIcon/HttpServerConnection.cs#L331). It runs in a `while(true)` loop until it crashes with a WebException from a 503 error.

Inside the `PerformRequest` method there is logic to handle password changes in the Web UI
[GUI/Duplicati.GUI.TrayIcon/HttpServerConnection.cs#L371](https://github.com/duplicati/duplicati/blob/master/Duplicati/GUI/Duplicati.GUI.TrayIcon/HttpServerConnection.cs#L371)

    // Can survive if server password is changed via web ui
    if (Program.databaseConnection.ApplicationSettings.WebserverPasswordTrayIcon != m_password)
        m_password = Program.databaseConnection.ApplicationSettings.WebserverPasswordTrayIcon;

However this code is never run, because it depends on `m_dbPasswordSourceDatabase` being true. 

This value is only true if the trayicon is started with `NOHOSTEDSERVER_OPTION` and `READCONFIGFROMDB_OPTION` commandline options, which the code says is for running the trayicon against an already running server.  The check is here [GUI/Duplicati.GUI.TrayIcon/Program.cs#L156](https://github.com/duplicati/duplicati/blob/master/Duplicati/GUI/Duplicati.GUI.TrayIcon/Program.cs#L156)

It seems that if I remove the check and always have `m_dbPasswordSourceDatabase=true`, then my trayicon recovers without a problem when I add a password.

@kenkendk, perhaps you know of a good reason why this check is there? I'm tempted to just remove it, since it *seems* to resolve the problem.

**Comment by Pectojin** [comment] 2018-02-20 23:06
Hmm, maybe I should ask @mnaiman instead, it seems he commited the code for the check last year.

**Comment by mnaiman** [comment] 2018-02-20 23:20
Hi @Pectojin , how you are running the server? Separate process or inside of trayicon?

**Comment by Pectojin** [comment] 2018-02-20 23:24
Bootstrapped from the trayicon. The only time I run it outside is when I don't start the trayicon :)

**Comment by Pectojin** [comment] 2018-03-05 08:28
#3066 was just merged which resolves this issue.

**Closed by Pectojin** 2018-03-05 08:28 UTC
Labels: bug, reproduced

**Comment by scribblemaniac** [comment] 2022-07-18 02:01
I just encountered the same problem with version 2.0.6.3_beta_2021-06-17 when setting the password and default options for the first time. I was running  the Duplicati server as a Windows service and did have the tray icon running as well (launched with --no-hosted-server). Restarting the system allowed me to log in without the nonce error, and the issue did not occur with any further password changes.
