### ISSUE TITLE
Location of v1 downloads

### ISSUE THREAD

**Issue by john-aws** [duplicati/duplicati#4633] opened 2021-10-30 17:25 UTC
For users that have backups originally made with v1 of duplicati, v2 does not seem to be compatible and will not allow me to restore, or even list, backup filesets. First, is this actually a correct diagnosis or should I expect v2 to be able to restore v1 backups?

Where can v1 binaries be downloaded from? They do not appear to be listed at [releases](https://github.com/duplicati/duplicati/releases). I'd prefer not to have to resort to [FileHippo](https://filehippo.com/download_duplicati/).

**Comment by warwickmm** [comment] 2021-10-30 17:55
You can try the old site here:

https://sites.google.com/a/duplicati.com/duplicati/news/duplicati134available

**Comment by warwickmm** [comment] 2021-10-30 17:56
Duplicate of #3661.

**Closed by warwickmm** 2021-10-30 17:56 UTC

**Comment by hrdwdmrbl** [comment] 2023-12-07 20:03
@warwickmm Link no longer working
