### ISSUE TITLE
Backup of write locked files fails

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#5569] opened 2024-09-23 15:16 UTC
- [x] I have searched open and closed issues for duplicates.
- [x ] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.9.107_canary_2024-09-11
- **Operating system**: Linux
- **Backend**: File

## Description
Backup of write locked files fails.

## Steps to reproduce
Some files in backup source are open by other program for write.
Therefore Duplicati generate following warning 
```
2024-09-23 17:01:03 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: /var/lib/docker/volumes/metadata.db
IOException: The process cannot access the file '/var/lib/docker/volumes/metadata.db' because it is being used by another process.
```

If I use cp command to copy that file, no problem.

I think problem is that line https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Snapshots/SnapshotBase.cs#L83C20-L83C29

Why is source file opened for ReadWrite? Open for Read should be enough to ingest file data to backup.
ReadWrite | 3 | Read and write access to the file. Data can be written to and read from the file. (https://learn.microsoft.com/en-us/dotnet/api/system.io.fileaccess?view=net-8.0)

Thanks

**Comment by kenkendk** [comment] 2024-09-24 07:24
It used to be that the `FileShare.ReadWrite` was the "safe" option in that it does not prevent others from either reading or writing. But I can try to reproduce with that file.

**Comment by mnaiman** [comment] 2024-09-24 07:52
I understand the logic behind. Eg. on heavy writing database file this approach is good for file consistency. It is safest option in terms, that file is not changed during process and therefore is consistent.
It has 2 major drawbacks.

1.  Application that this file belongs in need to open file for write (at same time Duplicati is reading file for backup) fails (this could have impact on other apps running on machine to behave weird and influence production usage) - for small file this would be rare condition, but for bigger and periodic write by owning app....Exception and crash of owning app
2. Because of Duplicati fail to Open file for read, it is not present in backup set at all. Even that file is changed rarely (but 100% of time open for write by owning app) Duplicati fails to backup (my case)

I know, that using LVM and snapshot, this could be somehow prevented, but there will be tremendous amount of users running Linux without LVM.

**Comment by kenkendk** [comment] 2024-09-24 09:45
I am not sure I follow, the idea with `FileAccess.Read` + `FileShare.ReadWrite` should mean "Duplicati only needs read access, any other process can read+write".
Discussion here: https://stackoverflow.com/questions/25097773/system-io-filestream-fileaccess-vs-fileshare

I think this may be related to the .NET8 upgrade where advisory file locking is now supported by .NET, and the writer has requested exclusive access.

Here is [a thread that explains that .NET6+ is now honoring advisory locking](https://github.com/dotnet/runtime/issues/34126).

I think Duplicati should be able to ignore advisory locks during the backup process, as it is meant to work even with files being updated. The workaround for now appears to be setting the environment variable `DOTNET_SYSTEM_IO_DISABLEFILELOCKING=true`

Not sure how to fix it in a more elegant way. We could perhaps use system `open()` calls, but they are a hassle to map effeciently to a .NET `Stream`.

**Comment by mnaiman** [comment] 2024-09-24 10:32
Ah, youre right, I misunderstand FileShare enum.
So point 1 is not valid, but point 2 still is.
I just tried DOTNET_SYSTEM_IO_DISABLEFILELOCKING and problem solved - thanks!

**Comment by ts678** [comment] 2024-09-24 11:50
> It used to be that the FileShare.ReadWrite was the "safe" option in that it does not prevent others from either reading or writing. 

[Creating and Opening Files](https://learn.microsoft.com/en-us/windows/win32/fileio/creating-and-opening-files) might be helpful to understand behavior at the Windows level. There might be some tradeoffs.

[Duplticati and VSS are bad friends](https://forum.duplicati.com/t/duplticati-and-vss-are-bad-friends/7884/39?u=ts678) was me looking at different programs' abilities to copy a locked file.

**Comment by mnaiman** [comment] 2024-09-24 12:21
On Windows it is ok, because VSS is part of every version of Windows and great way of consistent locked read approach.
On Linux without LVM it is more difficult.

**Comment by ts678** [comment] 2024-09-24 13:21
I wouldn't call it completely OK. It's off by default, hard to setup, and adds an annoying freeze to work while it gets going.
Maybe someday the Duplicati installer will offer nicer options. Currently I think either elevation or service are very manual.

**Comment by mnaiman** [comment] 2024-09-24 16:04
Its hard to setup, but its reliable to work. eg service mode. Currently not using service exe(fails to load when checking for update) - using nssm starting Duplicati.Server and it was stable like hell in past years.

**Comment by ts678** [comment] 2024-09-24 19:53
> Its hard to setup

Agree.

> it was stable like hell in past years.

My experience was vastly different. It does work well at solving locked files backup, but adds delays, needs tuning, and may fail.

[snapshot-policy](https://docs.duplicati.com/en/latest/06-advanced-options/#snapshot-policy) setting speaks to fails, as rather than two options, it provides another two which define how to handle a failure.

I have also had to tune the value shown by `vssadmin list shadowstorage`, which is a measly 2% of drive on a fresh install I have.

If something else is using VSS when Duplicati tries, Duplicati fails then does not retry. Some other backup programs retry a little.

I have seen restore failures, when VSS manages to get file backup, then VSS is not used to gather source file blocks for a restore.

There is also a very annoying freeze (not unique to Duplicati VSS) for me (maybe having a hard drive hurts?) when VSS is starting.
My presumption has been that this is related to the I/O freeze/thaw/suspend/resume work that Microsoft talks about in [the docs](https://learn.microsoft.com/en-us/windows/win32/vss/volume-shadow-copy-service-portal).

While attempting to examine the brief system-stops-moving I was thinking of, 2.0.9.107 gave me a different one. Profiling log has

```
2024-09-24 15:00:24 -04 - [Profiling-Timer.Finished-Duplicati.Library.Main.Operation.BackupHandler-PreBackupVerify]: PreBackupVerify took 0:00:00:00.215
2024-09-24 15:01:09 -04 - [Profiling-Timer.Begin-Duplicati.Library.Main.Database.ExtensionMethods-ExecuteReader]: Starting - ExecuteReader: SELECT "ID", "Timestamp" FROM "Fileset" ORDER BY "Timestamp" DESC
```
in one VSS run, then below is the second. Status bar is hanging in Verifying files, but I'm not sure where it is at the gap in the log.
```
2024-09-24 15:08:31 -04 - [Profiling-Timer.Finished-Duplicati.Library.Main.Operation.BackupHandler-PreBackupVerify]: PreBackupVerify took 0:00:00:00.299
2024-09-24 15:09:18 -04 - [Profiling-Timer.Begin-Duplicati.Library.Main.Database.ExtensionMethods-ExecuteReader]: Starting - ExecuteReader: SELECT "ID", "Timestamp" FROM "Fileset" ORDER BY "Timestamp" DESC
```

Take all this as a rebuttal that VSS is completely OK. I'd prefer doing as much as possible to solve things through file I/O modes.

**Comment by kenkendk** [comment] 2024-10-15 09:07
> using nssm starting Duplicati.Server and it was stable like hell in past years

A bit off-topic, but why is this not stable anymore?

**Comment by mnaiman** [comment] 2024-10-21 18:01
@ts678 - Agree with all findings, still better with than without, because if some file is locked VSS is only reliable option. Including SQL databases and hyper-v which are sensitive for data consistency.

@kenkendk - it was stable when there was single exe in process list. later it was changed that first exe is searching if in updates folder is update and then load its. loading takes longer time and it will force service manager fail, that service is not responding within timeout. nssm start itself, notify service manager that it is running and then starting service exe no matter how long it start.
On servers i had this issue, that after reboot sometimes service was not started and therefore no backups which was unacceptable for me.

**Comment by ts678** [comment] 2024-10-21 19:08
> service is not responding within timeout

[A slow service does not start due to time-out error in Windows](https://learn.microsoft.com/en-us/troubleshoot/windows-server/system-management-components/service-not-start-events-7000-7011-time-out-error) might help, but so will 2.0.9.x and its single-process plan.

[Windows Service fails to start #2717](https://github.com/duplicati/duplicati/issues/2717) shows my experience and a milder workaround of delaying the start to quieter time.

> searching if in updates

Although there's a limit on the number of updates kept, having to go through lots of them slows things down even more.

**Comment by kenkendk** [comment] 2024-10-21 19:41
@mnaiman Arh, that was the AutoUpdater? It was a great idea in the design phase, but it gave too many complications.
Luckily, .NET8 builds only have a single binary, so I hope we are "back to stable" again.

On-topic: For the locked files, we went back-and-forth on it, and decided to add yet-another-option: `--ignore-advisory-locking`.

The rationale is that:
1. For most uses, the safest setup is to honor locking and only read files when they are "stable", so by default it will honor locking
2. Some files, like the Docker file you found, will never be unlocked and cannot be safely backed up. A knowledgable user can decide to backup of the contents and deal with situations that may arise if the file is restored from an incomplete snapshot.

You can continue to use `DOTNET_SYSTEM_IO_DISABLEFILELOCKING` but with the updated flag, the locking checks will only be disabled in the backup process, not in the general code (server, database management, etc).

Closing because the topic how has a solution.

**Closed by kenkendk** 2024-10-21 19:41 UTC
Labels: bug

**Comment by mnaiman** [comment] 2024-10-21 19:54
Thanks both!
This option for knowledgeable user is great feature.
Will be using DOTNET flag until version with option will contain certificates fix, which is so far blocker for me to update :)
