### ISSUE TITLE
Errors affected 2 file(s)

### ISSUE THREAD

**Issue by paolomeraviglia** [duplicati/duplicati#2174] opened 2016-12-12 23:00 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.30_experimental_2016-11-03
**Operating System:** debian jessie
**Backend:**

### Bug description
Describe here the issue that you are experiencing.

When backup finish, there are 2 errors:

    Failed to process path: /home/paolo/.config/Duplicati/HDYQUAQWSS.sqlite => Unexpected result count: 0, expected 1,
    Failed to process path: /home/paolo/.config/Duplicati/HDYQUAQWSS.sqlite-journal => Unexpected result count: 0, expected 1

### Steps to reproduce
- Start a backup: wait until it finishes

**Comment by Amandysha** [comment] 2016-12-27 14:02
I'm desperate! I have the same problem in Ubuntu 16.04.

### Version info

**Duplicati Version:** 2.0.1.35_experimental_2016-12-13
**Operating System: *Ubuntu 16.04*
**Backend: *Box.net*


### debug log

Failed to process path: /home/ines/.config/Duplicati/WXSUQZAGUN.sqlite-journal
System.Exception: Unexpected result count: 0, expected 1
  at Duplicati.Library.Main.Database.LocalBackupDatabase.AddBlockset (System.String filehash, Int64 size, Int32 blocksize, IEnumerable`1 hashes, IEnumerable`1 blocklistHashes, System.Int64& blocksetid, IDbTransaction transaction) <0x40d0ef30 + 0x00723> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.AddFileToOutput (Duplicati.Library.Main.BackendManager backend, System.String filename, Int64 size, DateTime lastmodified, IMetahash metadata, IEnumerable`1 hashlist, System.String filehash, IEnumerable`1 blocklisthashes) <0x40d11920 + 0x0007b> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry (ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend, System.String path, FileAttributes attributes) <0x40d032a0 + 0x018c7> in <filename unknown>:0

**Comment by kenkendk** [comment] 2016-12-27 14:04
I think this is a duplicate of #1400 ?

**Comment by Amandysha** [comment] 2016-12-27 14:09
Thanks @kenkendk . Sorry, but I do not understand, can you please explain how to solve this in Linux?

**Comment by kenkendk** [comment] 2016-12-27 15:05
@Amandysha  There is no fix yet, but maybe you can confirm that the issue only affects files that are likely to have changed during the backup?

**Closed by kenkendk** 2016-12-27 15:05 UTC
Labels: bug

**Comment by Amandysha** [comment] 2016-12-27 16:56
Sure @kenkendk , tell me how. I want to help. I tried run backup again and in the end I got the same error: 

Failed to process path: /home/ines/.config/Duplicati/WXSUQZAGUN.sqlite-journal
System.Exception: Unexpected result count: 0, expected 1
  at Duplicati.Library.Main.Database.LocalBackupDatabase.AddBlockset (System.String filehash, Int64 size, Int32 blocksize, IEnumerable`1 hashes, IEnumerable`1 blocklistHashes, System.Int64& blocksetid, IDbTransaction transaction) <0x4132e0a0 + 0x00723> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.AddFileToOutput (Duplicati.Library.Main.BackendManager backend, System.String filename, Int64 size, DateTime lastmodified, IMetahash metadata, IEnumerable`1 hashlist, System.String filehash, IEnumerable`1 blocklisthashes) <0x41331410 + 0x0007b> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry (ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend, System.String path, FileAttributes attributes) <0x41327000 + 0x018c7> in <filename unknown>:0

**Comment by kenkendk** [comment] 2017-01-09 22:37
@Amandysha, if you can try updating to the latest version (`2.0.1.39`):
https://github.com/duplicati/duplicati/releases/tag/v2.0.1.39-2.0.1.39_canary_2017-01-08

And then run the backup again. If you get the error, then please make a bug report, and send it to me, and I will have a look.

**Comment by Amandysha** [comment] 2017-01-10 19:57
10 de ene. de 2017 13:27: Failed while executing "Backup" with id: 3
System.NullReferenceException: Object reference not set to an instance of an object
  at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry (ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend, System.String path, FileAttributes attributes) <0x407990a0 + 0x01fcf> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation (ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend) <0x407988a0 + 0x0063f> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, IFilter filter) <0x407089c0 + 0x016af> in <filename unknown>:0
