### ISSUE TITLE
Recreating database stops at 1.5G

### ISSUE THREAD

**Issue by lynndixon** [duplicati/duplicati#2537] opened 2017-06-12 05:25 UTC
I had previously gotten an error that the database needed repairing, so I attempted a repair, which got stuck and would not budge after 2 days of waiting.

So, I decided to recreate the database.  The original database size was 1.8GB in size.   I have tried twice now to recreate, and both times the process stops once the DB size reaches 1.5GB in size. 

> [root@samba Duplicati]# ll -h
> total 1.5G
> -rw-r--r-- 1 root root 3.0M Jun 11 14:48 BQGUILRGCL.backup
> -rw-r--r-- 1 root root 1.5G Jun 12 00:56 BQGUILRGCL.sqlite
> -rw-r--r-- 1 root root  512 Jun 12 00:59 BQGUILRGCL.sqlite-journal
> drwxr-xr-x 2 root root 4.0K Jun 11 14:38 control_dir_v2
> -rw-r--r-- 1 root root  32K Jun 12 00:33 Duplicati-server.sqlite

The webpanel still shows that Duplicati is trying to recreate the database, but the size does not increase, nor does the time stamp which seems like it has stopped writing to that db file. 

This backup is about 800 GB large, and is several hundred thousand files.  I am using Google Drive as my destination.  

Version:  Duplicati - 2.0.1.61_experimental_2017-05-30
Operating System: Centos 6.9 64bit.

The backup has completed successfully in the past.

**Comment by kenkendk** [comment] 2017-06-12 08:38
Do you see any CPU or disk activity? From the web-UI you can go to the logs and see live log data.
Set the log level to "profiling" to see what happens. My guess is that it is running a query and that query is *really* slow.

**Comment by lynndixon** [comment] 2017-06-12 16:41
I do not see any disk activity related to Duplicati (or mono).  However, the mono process is staying at 100% when I check on top.



I also see these errors in the live log data:

> Jun 12, 2017 10:50 AM: ExecuteNonQuery: INSERT INTO "Block" ("Hash", "Size", "VolumeID") SELECT "FullHash" AS "Hash", "Length" AS "Size", -1 AS "VolumeID" FROM (SELECT "A"."FullHash", "A"."Length", CASE WHEN "B"."Hash" IS NULL THEN '' ELSE "B"."Hash" END AS "Hash", CASE WHEN "B"."Size" is NULL THEN -1 ELSE "B"."Size" END AS "Size" FROM (SELECT DISTINCT "FullHash", "Length" FROM (SELECT "BlockHash" AS "FullHash", "BlockSize" AS "Length" FROM ( 
>  SELECT
>  "E"."BlocksetID",
>  "F"."Index" + ("E"."BlocklistIndex" * 3200) AS "FullIndex",
>  "F"."BlockHash",
>  MIN(102400, "E"."Length" - (("F"."Index" + ("E"."BlocklistIndex" * 3200)) * 102400)) AS "BlockSize",
>  "E"."Hash",
>  "E"."BlocklistSize",
>  "E"."BlocklistHash"
>  FROM
>  (
>  SELECT * FROM
>  (
>  SELECT 
>  "A"."BlocksetID",
>  "A"."Index" AS "BlocklistIndex",
>  MIN(3200 * 32, ((("B"."Length" + 102400 - 1) / 102400) - ("A"."Index" * (3200))) * 32) AS "BlocklistSize",
>  "A"."Hash" AS "BlocklistHash",
>  "B"."Length"
>  FROM 
>  "BlocklistHash" A,
>  "Blockset" B
>  WHERE 
>  "B"."ID" = "A"."BlocksetID"
>  ) C,
>  "Block" D
>  WHERE
>  "C"."BlocklistHash" = "D"."Hash"
>  AND
>  "C"."BlocklistSize" = "D"."Size"
>  ) E,
>  "TempBlocklist-7D5DB3A3493E6548A5AC3C0EB70C9220" F
>  WHERE
>  "F"."BlocklistHash" = "E"."Hash"
>  ORDER BY 
>  "E"."BlocksetID",
>  "FullIndex"
>  ) UNION SELECT "BlockHash", "BlockSize" FROM "TempSmalllist-EBD54775CE14664BBF46B75D3AB7CD67" )) A LEFT OUTER JOIN "Block" B ON "B"."Hash" = "A"."FullHash" AND "B"."Size" = "A"."Length" ) WHERE "FullHash" != "Hash" AND "Length" != "Size" took 00:03:16.406

And this one a few seconds later:

> Jun 12, 2017 10:50 AM: Starting - ExecuteNonQuery: INSERT INTO "BlocksetEntry" ("BlocksetID", "Index", "BlockID") SELECT DISTINCT "H"."BlocksetID", "H"."Index", "H"."BlockID" FROM (SELECT "E"."BlocksetID" AS "BlocksetID", "D"."FullIndex" AS "Index", "F"."ID" AS "BlockID" FROM ( 
>  SELECT
>  "E"."BlocksetID",
>  "F"."Index" + ("E"."BlocklistIndex" * 3200) AS "FullIndex",
>  "F"."BlockHash",
>  MIN(102400, "E"."Length" - (("F"."Index" + ("E"."BlocklistIndex" * 3200)) * 102400)) AS "BlockSize",
>  "E"."Hash",
>  "E"."BlocklistSize",
>  "E"."BlocklistHash"
>  FROM
>  (
>  SELECT * FROM
>  (
>  SELECT 
>  "A"."BlocksetID",
>  "A"."Index" AS "BlocklistIndex",
>  MIN(3200 * 32, ((("B"."Length" + 102400 - 1) / 102400) - ("A"."Index" * (3200))) * 32) AS "BlocklistSize",
>  "A"."Hash" AS "BlocklistHash",
>  "B"."Length"
>  FROM 
>  "BlocklistHash" A,
>  "Blockset" B
>  WHERE 
>  "B"."ID" = "A"."BlocksetID"
>  ) C,
>  "Block" D
>  WHERE
>  "C"."BlocklistHash" = "D"."Hash"
>  AND
>  "C"."BlocklistSize" = "D"."Size"
>  ) E,
>  "TempBlocklist-7D5DB3A3493E6548A5AC3C0EB70C9220" F
>  WHERE
>  "F"."BlocklistHash" = "E"."Hash"
>  ORDER BY 
>  "E"."BlocksetID",
>  "FullIndex"
>  ) D, "BlocklistHash" E, "Block" F, "Block" G WHERE "D"."BlocksetID" = "E"."BlocksetID" AND "D"."BlocklistHash" = "E"."Hash" AND "D"."BlocklistSize" = "G"."Size" AND "D"."BlocklistHash" = "G"."Hash" AND "D"."Blockhash" = "F"."Hash" AND "D"."BlockSize" = "F"."Size" UNION SELECT "Blockset"."ID" AS "BlocksetID", 0 AS "Index", "Block"."ID" AS "BlockID" FROM "Blockset", "Block", "TempSmalllist-EBD54775CE14664BBF46B75D3AB7CD67" S WHERE "Blockset"."Fullhash" = "S"."FileHash" AND "S"."BlockHash" = "Block"."Hash" AND "S"."BlockSize" = "Block"."Size" AND "Blockset"."Length" = "S"."BlockSize" AND "Blockset"."Length" <= 102400 ) H WHERE ("H"."BlocksetID" || ':' || "H"."Index") NOT IN (SELECT ("ExistingBlocksetEntries"."BlocksetID" || ':' || "ExistingBlocksetEntries"."Index") FROM "BlocksetEntry" "ExistingBlocksetEntries" )

The last disk activity I see on the SQLite file is right at 10:47am, which correlates to these log messages.

Here is the output of top showing mono using 100% of one of my CPU's (I have 24 logical available on this machine).
![image](https://user-images.githubusercontent.com/14202086/27044640-4a0172b6-4f6c-11e7-8390-5aa63164a9fa.png)


Currently, the process is still trying "recreating the database" and has been running a very long time, almost 2 days now.

**Comment by kenkendk** [comment] 2017-06-13 08:33
I think this is a duplicate of #2302.

Maybe you can use the workaround in the issue, open the database and apply the index to the "BlocklistHash" table?

**Comment by lynndixon** [comment] 2017-06-14 16:48
Ken,
Unfortunately, that didn't solve my issue.  I have deleted that configuration and decided to try several smaller backup sets, since SQLite seems to have performance issues with very large data structures.  
I'll give this a go and see what happens.

**Closed** 2017-06-15 08:40 UTC
Labels: performance issue

**Comment by kenkendk** [comment] 2017-06-15 10:28
Please re-open if this is not fixed with the latest canary: 
https://github.com/duplicati/duplicati/releases

**Comment by roterBulle** [comment] 2019-02-16 23:26
Hi All,
i currently have a recreate running with a large backup (1TB) in 2GB Blocksize.
Since the recreate hit the 70% it is running really really slow.

Database seems to be not locked ( tried to add the index as mentioned in: https://github.com/duplicati/duplicati/issues/2302 and it tells me that the index is already existing)
SQLite file is almost 2GB in size.

After the first recreate was running for over 10 days, i stopped it and updated from the last beta 2.0.4.5 to Duplicati - 2.0.4.15_canary_2019-02-06 but the issue remains the same.
What i can tell is that he consistently starts to get slow after he hits the 70%.

Attached we see the last execution that completed in the logs running for 14 hours.

Is there anything i can do to help you figuring out what the issue is?
Or any ideas what i coud try?

If i should open a new issue please tell me, but i think the issue is somehow related.

I also found that @JonMikelV  is investigating on that issue in the forum:
https://forum.duplicati.com/t/database-recreate-performance/5999

Maybe he can shed some light on that topic

Thanks.


`16. Febr. 2019 18:49: ExecuteNonQuery: INSERT INTO "Block" ("Hash", "Size", "VolumeID") SELECT "FullHash" AS "Hash", "Length" AS "Size", -1 AS "VolumeID" FROM (SELECT "A"."FullHash", "A"."Length", CASE WHEN "B"."Hash" IS NULL THEN '' ELSE "B"."Hash" END AS "Hash", CASE WHEN "B"."Size" is NULL THEN -1 ELSE "B"."Size" END AS "Size" FROM (SELECT DISTINCT "FullHash", "Length" FROM (SELECT "BlockHash" AS "FullHash", "BlockSize" AS "Length" FROM ( 
 SELECT
 "E"."BlocksetID",
 "F"."Index" + ("E"."BlocklistIndex" * 3200) AS "FullIndex",
 "F"."BlockHash",
 MIN(102400, "E"."Length" - (("F"."Index" + ("E"."BlocklistIndex" * 3200)) * 102400)) AS "BlockSize",
 "E"."Hash",
 "E"."BlocklistSize",
 "E"."BlocklistHash"
 FROM
 (
 SELECT * FROM
 (
 SELECT 
 "A"."BlocksetID",
 "A"."Index" AS "BlocklistIndex",
 MIN(3200 * 32, ((("B"."Length" + 102400 - 1) / 102400) - ("A"."Index" * (3200))) * 32) AS "BlocklistSize",
 "A"."Hash" AS "BlocklistHash",
 "B"."Length"
 FROM 
 "BlocklistHash" A,
 "Blockset" B
 WHERE 
 "B"."ID" = "A"."BlocksetID"
 ) C,
 "Block" D
 WHERE
 "C"."BlocklistHash" = "D"."Hash"
 AND
 "C"."BlocklistSize" = "D"."Size"
 ) E,
 "TempBlocklist-67A230B430CE0840A9FD88F6ABE018DD" F
 WHERE
 "F"."BlocklistHash" = "E"."Hash"
 ORDER BY 
 "E"."BlocksetID",
 "FullIndex"
 ) UNION SELECT "BlockHash", "BlockSize" FROM "TempSmalllist-AB21E48B925B6E4085B7DBEEE0712FA8" )) A LEFT OUTER JOIN "Block" B ON "B"."Hash" = "A"."FullHash" AND "B"."Size" = "A"."Length" ) WHERE "FullHash" != "Hash" AND "Length" != "Size" took 0:14:10:11.807
16. Febr. 2019 04:39: Starting - ExecuteNonQuery: INSERT INTO "Block" ("Hash", "Size", "VolumeID") SELECT "FullHash" AS "Hash", "Length" AS "Size", -1 AS "VolumeID" FROM (SELECT "A"."FullHash", "A"."Length", CASE WHEN "B"."Hash" IS NULL THEN '' ELSE "B"."Hash" END AS "Hash", CASE WHEN "B"."Size" is NULL THEN -1 ELSE "B"."Size" END AS "Size" FROM (SELECT DISTINCT "FullHash", "Length" FROM (SELECT "BlockHash" AS "FullHash", "BlockSize" AS "Length" FROM ( 
 SELECT
 "E"."BlocksetID",
 "F"."Index" + ("E"."BlocklistIndex" * 3200) AS "FullIndex",
 "F"."BlockHash",
 MIN(102400, "E"."Length" - (("F"."Index" + ("E"."BlocklistIndex" * 3200)) * 102400)) AS "BlockSize",
 "E"."Hash",
 "E"."BlocklistSize",
 "E"."BlocklistHash"
 FROM
 (
 SELECT * FROM
 (
 SELECT 
 "A"."BlocksetID",
 "A"."Index" AS "BlocklistIndex",
 MIN(3200 * 32, ((("B"."Length" + 102400 - 1) / 102400) - ("A"."Index" * (3200))) * 32) AS "BlocklistSize",
 "A"."Hash" AS "BlocklistHash",
 "B"."Length"
 FROM 
 "BlocklistHash" A,
 "Blockset" B
 WHERE 
 "B"."ID" = "A"."BlocksetID"
 ) C,
 "Block" D
 WHERE
 "C"."BlocklistHash" = "D"."Hash"
 AND
 "C"."BlocklistSize" = "D"."Size"
 ) E,
 "TempBlocklist-67A230B430CE0840A9FD88F6ABE018DD" F
 WHERE
 "F"."BlocklistHash" = "E"."Hash"
 ORDER BY 
 "E"."BlocksetID",
 "FullIndex"
 ) UNION SELECT "BlockHash", "BlockSize" FROM "TempSmalllist-AB21E48B925B6E4085B7DBEEE0712FA8" )) A LEFT OUTER JOIN "Block" B ON "B"."Hash" = "A"."FullHash" AND "B"."Size" = "A"."Length" ) WHERE "FullHash" != "Hash" AND "Length" != "Size"`
