### ISSUE TITLE
Backup to OneDrive v2 fails with Exceptions: AggregateException, FileNotFoundException, TimeoutException

### ISSUE THREAD

**Issue by habakuk007** [duplicati/duplicati#4073] opened 2020-01-27 20:39 UTC
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Windows 10, 64 bit
- **Backend**: OneDrive v2

## Description
Every backup fails. At the beginning with no to few files it worked, but now after adding many files I get exception every times the backup is scheduled. 

## Steps to reproduce

1. Create Backup Job (OneDrive v2, Encrypted)
2. Run it

- **Actual result**:
An exception message is sent by mail
- **Expected result**:
Clean Backup is created

## Debug log
[Duplicati.log](https://github.com/duplicati/duplicati/files/4119245/Duplicati.log)

**Comment by habakuk007** [comment] 2020-01-27 20:41
Maybe https://github.com/duplicati/duplicati/issues/3945 is related

**Comment by ts678** [comment] 2020-01-28 23:35
> System.TimeoutException: HTTP timeout 00:01:40 exceeded.
   bei Duplicati.Library.OAuthHttpClient.<SendAsync>d__5.MoveNext()

Try raising [--http-operation-timeout](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#http-operation-timeout). OneDrive uses the .NET Framework default of 100 seconds, which might not be enough for the upload speed. A timeout is more likely under 2.0.5.1 because uploads use 

```
  --asynchronous-concurrent-upload-limit (Integer): The number of concurrent
    uploads allowed
    When performing asynchronous uploads, the maximum number of concurrent
    uploads allowed. Set to zero to disable the limit.
    * default value: 4
```

**Comment by habakuk007** [comment] 2020-01-29 13:34
Hello @ts678, 
thanks for your answer. I changed the timeout to 5 minutes in one job and 7 minutes in another backup job, but still get these errors.

One job is for 17509 files (57.43 GB) and the other is for 172 files (580 MB) and both fail...

[2020-01-29-ExceptionFor172FileJob.txt](https://github.com/duplicati/duplicati/files/4128238/2020-01-29-ExceptionFor172FileJob.txt)
[2020-01-29ExceptionFor17500filesJob.txt](https://github.com/duplicati/duplicati/files/4128239/2020-01-29ExceptionFor17500filesJob.txt)

**Comment by ts678** [comment] 2020-01-30 16:19
At least yours looks like your timeout setting is being respected. Mine is not, which is very strange...
Testing with old Duplicati releases that used to hit it will no longer hit it. Windows 10, fully updated.

The other thing going wrong is the missing temp file in the open issue you cited. I have no theories.
I worry about antivirus on Windows systems especially, but wouldn't a deletion usually make noise?

If you're able to try debug at the file level, you could install [Sysinternals Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to monitor `C:\Users\XXX\AppData\Local\Temp\dup-` file activity.

**Comment by habakuk007** [comment] 2020-01-30 22:31
Hello @ts678,

I watched it with Process Monitor. 

I got this exception during the process (like above):

    Failed: Mindestens ein Fehler ist aufgetreten.
    Details: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.AggregateException: Die Datei "C:\Users\XXX\AppData\Local\Temp\dup-d35336c3-0b9f-4d54-ade2-8b668448737b" konnte nicht gefunden werden. ---> System.IO.FileNotFoundException: Die Datei "C:\Users\Stefan\AppData\Local\Temp\dup-d35336c3-0b9f-4d54-ade2-8b668448737b" konnte nicht gefunden werden.

Only the process `Duplicati.GUI.TrayIcon.exe` used the file and finally deleted it (SetDispositionInformationEx):

    22:47:39,0810230	Duplicati.GUI.TrayIcon.exe	9112	SetDispositionInformationEx	C:\Users\Stefan\AppData\Local\Temp\dup-d35336c3-0b9f-4d54-ade2-8b668448737b	SUCCESS	Flags: FILE_DISPOSITION_DELETE, FILE_DISPOSITION_POSIX_SEMANTICS, FILE_DISPOSITION_FORCE_IMAGE_SECTION_CHECK
    22:47:39,0811116	Duplicati.GUI.TrayIcon.exe	9112	CloseFile	C:\Users\Stefan\AppData\Local\Temp\dup-d35336c3-0b9f-4d54-ade2-8b668448737b	SUCCESS	
    23:02:53,3571110	Duplicati.GUI.TrayIcon.exe	9112	CreateFile	C:\Users\Stefan\AppData\Local\Temp\dup-d35336c3-0b9f-4d54-ade2-8b668448737b	NAME NOT FOUND	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Open No Recall, Attributes: n/a, ShareMode: Read, AllocationSize: n/a
    23:02:59,7692544	Duplicati.GUI.TrayIcon.exe	9112	CreateFile	C:\Users\Stefan\AppData\Local\Temp\dup-d35336c3-0b9f-4d54-ade2-8b668448737b	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a

[ProcessMonitorLog.txt](https://github.com/duplicati/duplicati/files/4136542/ProcessMonitorLog.txt)

**Comment by ts678** [comment] 2020-01-31 01:35
Thanks for the logs. I'm not as good at reading these as I'd like to be, but this looks like a file was made, not written to, deleted, then expected (resulting in the FileNotFoundException). The earlier Duplicati.log looks like SpillCollectorProcess was the reader, which I think means DataBlockProcessor sent the file but

https://github.com/duplicati/duplicati/blob/cfbb0addd48dce103863ceb9ac6b098033df5e79/Duplicati/Library/Main/Operation/Backup/DataBlockProcessor.cs#L129-L133

seems like it shouldn't be sending out empty volumes. I don't know this code very well, but I also found:

[Allow removal of VolumeWriterBase temp files.](https://github.com/duplicati/duplicati/commit/daf0311bf86957ae5f2faa87352bbeca16d6ca39) in 2.0.4.16 removed a mysterious protection of temp files which was introduced in 2017. This is beyond my skills, but let me ask if @warwickmm has any thoughts.

Meanwhile, I wonder if @habakuk007 has seen Process Monitor log some non-empty files being written, left alone, and read later. Knowing what non-failure looks like, does a failure look different _before_ failure?

SpillCollector runs late in the backup to collect not-yet-filled files that weren't pushed into the upload by the concurrent processors, which reminds me that setting [--concurrency-compressors](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#concurrency-compressors) to different values (including 1) might change the problem nature. Beyond that, I don't have a suggestion for workaround...

**Comment by warwickmm** [comment] 2020-01-31 02:21
> I changed the timeout to 5 minutes in one job and 7 minutes in another backup job, but still get these errors.
> 
> One job is for 17509 files (57.43 GB) and the other is for 172 files (580 MB) and both fail...

I wonder if the code is not recovering gracefully from http timeouts.  In all of your logs, I see some sort of `TimeoutException`:
```
---> (Interne Ausnahme #0) System.TimeoutException: HTTP timeout 00:07:00 exceeded.
```

Do you get the `FileNotFoundException` if you use a different backend?

Also, just making sure that you don't have some setting like this enabled?
![image](https://user-images.githubusercontent.com/17345532/73507254-3f51da00-438d-11ea-8574-6ea4ecff844f.png)

**Comment by warwickmm** [comment] 2020-01-31 04:34
Pull request #3778 fixed an issue where the `TimeoutException` was not being thrown correctly.  It's possible that there's a situation where this exception is not handled properly.

**Comment by habakuk007** [comment] 2020-01-31 09:45
Hello @ts678,

> Thanks for the logs. I'm not as good at reading these as I'd like to be, but this looks like a file was made, not written to, deleted, then expected (resulting in the FileNotFoundException). 

The file had many write and read log entries but I stripped them away (to see the create and delete entries). I should have mentioned that. If you need it I can record another log with all entries.

From @warwickmm 
> Also, just making sure that you don't have some setting like this enabled? 

The "Storage sense" is not enabled and the only process who "used" and deleted (`SetDispositionInformationEx`) the file was `Duplicati.GUI.TrayIcon.exe`.

**Comment by warwickmm** [comment] 2020-02-01 04:52
Do you have any other non-default options set, such as `--block-size`, `--dblock-size`, etc.?

**Comment by habakuk007** [comment] 2020-02-01 09:52
> Do you have any other non-default options set,

The http-timeout is the only option I have set.

**Comment by warwickmm** [comment] 2020-02-01 21:04
Unfortunately, I'm unable to reproduce this.  My OneDrive backups complete without any issue.

There is another OneDrive user that encountered an HTTP `TimeoutException` below.  Increasing the timeout to 10 minutes appears to have resolved the issue.  Perhaps the exact value depends on the quality of the network connection:

https://forum.duplicati.com/t/2-0-5-101-canary-2020-01-23-the-channel-backendrequests-is-retired-with-onedrive-v2/9037

Regarding the `FileNotFoundException`, whenever I force an HTTP `TimeoutException`, the exception properly halts the backup and the timeout error is displayed (not a file not found error):

![image](https://user-images.githubusercontent.com/17345532/73598793-95d82900-44f1-11ea-9537-51b37011c738.png)

**Comment by habakuk007** [comment] 2020-02-02 21:43
Hi @warwickmm 

I created another job with the same parameters (http timeout 5 minutes) but fewer files (18 files, 37 MB) and that worked:

[DuplicatiLog.txt](https://github.com/duplicati/duplicati/files/4145417/DuplicatiLog.txt)

The other backup jobs (17509 files with 57.43 GB and 172 files with 580 MB) still show the same errors.

**Comment by warwickmm** [comment] 2020-02-02 22:49
580 MB is not very large.  What's the quality of your network connection?  Can you try that again with a 10 minute timeout limit?

**Comment by habakuk007** [comment] 2020-02-03 14:28
I changed the timeout to 10 minutes, but now I get an ` Detected non-empty blocksets with no associated blocks!` error every time I try to start the backup (immediately after the start) for the backup job with the 580 MB data.

Normally I don't have any problems with my internet connection - it has about 1 Mbit/s  upload capacity and 16  Mbit/s download.

[Duplicati.log](https://github.com/duplicati/duplicati/files/4148341/Duplicati.log)

**Comment by warwickmm** [comment] 2020-02-04 02:52
> it has about 1 Mbit/s upload capacity

This is likely the problem.  With the default 50 MB dblock file size, maxing out a 1 Mbit/s connection would take over 6 minutes.  I'm not sure if it will help, but you can also try setting the `asynchronous-concurrent-upload-limit` option to `1` to see if that improves things.

> but now I get an Detected non-empty blocksets with no associated blocks! error

Does this occur on a brand new backup with the large timeout?  Or using an existing backup configuration that failed on an earlier attempt?

**Comment by habakuk007** [comment] 2020-02-12 21:27
I would say that 1 Mbit/s upload is standard in Germany. 

I got the non-empty blocksets on an existing backup that failed before. 

**I added a new backup job and set the timeout to 5 h and now it works. (for the 172 files with 580 MB) ** 

That leads me to the question weather the short timeout make sense at all? I remember that in other applications (ftp, scp, sftp, torrents, ...) it is no problem to upload big files over hours...

And I'm a little bit worried about the "non-empty blocksets" problem - does that mean that my backups can become corrupt at every moment?

Regards!
   Stefan

**Comment by warwickmm** [comment] 2020-02-13 02:09
> And I'm a little bit worried about the "non-empty blocksets" problem - does that mean that my backups can become corrupt at every moment?

This error appears to happen when backups are interrupted.  A [fix](https://github.com/duplicati/duplicati/pull/4042) for one cause of this did not make it into version 2.0.5.1, but was included in version 2.0.5.100.

**Comment by habakuk007** [comment] 2020-02-13 08:46
Another note: I added another backup job with a WebDav backend and I didn't have to change the `http-operation-timeout` - it worked out of the box.

**Comment by ts678** [comment] 2020-02-13 20:19
> This error appears to happen when backups are interrupted.

[CheckingErrorsForIssue1400 and FoundIssue1400Error test case, analysis, and proposal #3868](https://github.com/duplicati/duplicati/issues/3868) getting a [fix which may have gaps]( https://github.com/duplicati/duplicati/pull/3872#issuecomment-525759357) is another possibility. This is a consistency failure, so may have multiple causes.

If you're interrupting backups, that cause is more likely. If you're backing up files that grow and shrink a lot during backup (backup of your user profile would do this, due to the Duplicati database), the partial-fix theory gets support but is disproven if you use VSS to freeze things, e.g. [--snapshot-policy](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#snapshot-policy)=required.

Do any of these scenarios apply?

**Comment by habakuk007** [comment] 2020-02-14 07:59
Thanks for your answer!

I don't think that any "dynamic files" were included in this backups (onyl files and images, without system files and without hidden files) - but they were interrupted by http-operation-timeouts...

For now this issues is fixed for me (I probably do not use OneDrive v2 any more) and already deleted this backup sets...

**Comment by warwickmm** [comment] 2020-02-15 05:15
Thanks.  I will close this issue but feel free to re-open it if you think there's work that can be done.

**Closed by warwickmm** 2020-02-15 05:15 UTC
