### ISSUE TITLE
`__MonoCS__` can no longer be relied upon as of Mono 5.0

### ISSUE THREAD

**Issue by Ajedi32** [duplicati/duplicati#3656] opened 2019-02-09 05:29 UTC
Various parts of Duplicati currently rely on the `__MonoCS__` symbol being defined during preprocessing. For example:

* [`Duplicati/Library/Modules/Builtin/CheckMonoSSL.cs#L58-L62`](https://github.com/duplicati/duplicati/blob/fd37a1384c2cb4eede8907ceb863286d4a205dd8/Duplicati/Library/Modules/Builtin/CheckMonoSSL.cs#L58-L62)
* [`Duplicati/GUI/Duplicati.GUI.TrayIcon/Program.cs#L46-L55`](https://github.com/duplicati/duplicati/blob/fd37a1384c2cb4eede8907ceb863286d4a205dd8/Duplicati/GUI/Duplicati.GUI.TrayIcon/Program.cs#L46-L55)

This is an artifact from the mcs compiler, which defined this symbol automatically and was used in Mono prior to version 5.0. As of 5.0 however, Mono uses the csc compiler [which does not define this symbol](https://www.mono-project.com/docs/about-mono/releases/5.0.0/#csc):

> Note: `mcs` defined the `__MonoCS__` symbol and some users incorrectly used it to conditionally compile code specific to Mono. This is considered bad practice and won’t work anymore now that `csc` is the default compiler. You can detect [whether you’re running on Mono at runtime](https://www.mono-project.com/docs/faq/technical/#how-can-i-detect-if-am-running-in-mono) instead.

It was previously discovered that this update broke the build on MonoDevelop (see #3648), but given the reliance on this symbol in other parts of the code I'm concerned the change might have had other unanticipated effects.

It seems like [`build-release.sh#L141`](https://github.com/duplicati/duplicati/blob/fd37a1384c2cb4eede8907ceb863286d4a205dd8/build-release.sh#L141) does manually define the symbol as of fc5b2097e1d45fbb376a00d38b47b17963b3b687 so it may be that this change isn't relevant outside MonoDevelop, but I'm not familiar enough with Duplicati's codebase to make that determination for myself, so I'm raising this issue just to be sure.

Do any parts of Duplicati need to be modified to account for the fact that the `__MonoCS__` preprocessor symbol is no longer defined automatically during compilation on Mono?

**Comment by verhoek** [comment] 2019-02-09 16:46
Thanks for raising this issue. Afaik it compiles fine but code with __MonoCS__ is not compiled by default (using monodevelop), as can be expected from what you posted. It looks like setting the ENABLE_GTK flag has the same effect as __MonoCS__  (same holds for WINDOWSGTK). For building and releasing the binaries it's important to enable such parts, and there it's set. 

Also, if it would work still in legacy mode and compile __MonoCS__ conditioned code, it's actually not clear that this should imply building GTK stuff. 
Maybe we can just get rid of __MonoCS__. @warwickmm @kenkendk what do you think?

**Comment by warwickmm** [comment] 2019-02-09 18:00
Given that Mono discourages the use of `__MonoCS__` and both `msbuild` and `xbuild` no longer define this symbol, it seems that we are not capturing the original intended behavior.  I think it makes sense to revisit the usages and remove/replace them as necessary.

**Comment by warwickmm** [comment] 2020-05-30 17:19
Fixed by pull request #4213.

**Closed by warwickmm** 2020-05-30 17:19 UTC
Labels: mono
