### ISSUE TITLE
Feature Request - Upload to multiple locations

### ISSUE THREAD

**Issue by simonjtaylor212** [duplicati/duplicati#1411] opened 2015-07-07 20:51 UTC
Hi

I would really like to be able to upload one backup to two destinations - for example a NAS and Google Drive

Thanks
##

**Comment by barsthebars** [comment] 2015-07-07 21:21
+1

**Comment by Aeyoun** [comment] 2015-11-11 17:50
+1, see also [Horcrux](http://chrispoole.com/project/general/horcrux/).

**Comment by Pectojin** [comment] 2018-02-11 02:43
Closing since it's a duplicate of 234

**Closed by Pectojin** 2018-02-11 02:43 UTC
