### ISSUE TITLE
FULL restore folders are empty

### ISSUE THREAD

**Issue by izabelcka** [duplicati/duplicati#1316] opened 2015-03-03 12:17 UTC
Some folders have data, and some do not. HELP!

**Comment by agrajaghh** [comment] 2015-03-03 12:30
Look like duplicate of #1314 / #1308 

hard to say with this detailed bug report :laughing:

**Comment by izabelcka** [comment] 2015-03-03 12:36
what information do you need to make a proper analysis

**Comment by agrajaghh** [comment] 2015-03-03 12:57
Is it the same problem as in #1314 / #1308?

**Closed** 2015-03-04 18:26 UTC
