### ISSUE TITLE
Settings page "OK" and "Cancel" buttons not fully visible (Chrome)

### ISSUE THREAD

**Issue by sklein** [duplicati/duplicati#3122] opened 2018-03-23 20:03 UTC
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.1
- **Operating system**: Windows 7 Pro SP1
- **Backend**: Wasabi

## Description

Using Chrome Version 65.0.3325.181 (Official Build) (64-bit) the OK and Cancel buttons are cut off by the page footer. Works fine with Firefox 59.0 64-bit.

## Screenshots

![duplicati bug 20180323](https://user-images.githubusercontent.com/1835090/37850920-302f08cc-2e9a-11e8-825d-c7a1251afd60.png)

**Comment by mr-flibble** [comment] 2018-03-23 20:31
Hello, I think this is duplicate of issue  https://github.com/duplicati/duplicati/issues/3083

**Comment by Pectojin** [comment] 2018-03-23 23:43
I've copied the info over to #3083 so we can close this issue and keep the discussion and troubleshooting centralized in one issue.

**Closed by Pectojin** 2018-03-23 23:43 UTC
