### ISSUE TITLE
Memory leak with ACD-Backend

### ISSUE THREAD

**Issue by BlackEdder0815** [duplicati/duplicati#2320] opened 2017-02-14 10:58 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.46
**Operating System:** Linux ARM
**Backend:** ACD

### Bug description
When I use the ACD-Backend, it seams, that Duplicati have some kind of memory leak.
I started duplicati-server 5 days ago and had a memory-usage of 77mb res, 144mb virt.
After a few (empty) backup-runs, the memory increased to 113mb res, 249mb virt.
Now, 5 days later, (every night a few backups are running), I got a memory usage of 1047mb res, 1318mb 
virt.
I also faced the problem, that when I initially run a big backup with a few GB of data, duplicati simply quits.
Without any error in the log or in the standard-out. My assumption is, that duplicati crashes because of an out-of-memory error.
I never faced any memory-problems when using the file-backend (and using the fuse-driver for ACD-connection)
Maybe someone can confirm this behavior?
Maybe this behavior is related to #1071 ?

### Steps to reproduce
- start duplicati server
- configure a backup with ACD-Backend
- lets run the backup a few times (also with some new data)
- check the memory-usage from time to time (when duplicati idles)

**Actual result:** Duplicati is consuming more and more memory
**Expected result:** Duplicati runs with a more or less stable memory-usage. Shure, it can and should increase the memory while it is working, but should free this, when it is back in idle state.

### Screenshots
09. Feb. 2017 11:49
![2017-02-09 11_49_16-sona patson2_](https://cloud.githubusercontent.com/assets/25084261/22926371/95c6f044-f2ac-11e6-9ec6-df7517d697f1.png)

09. Feb. 2017 12:09
![2017-02-09 12_09_34-sona patson2_](https://cloud.githubusercontent.com/assets/25084261/22926379/9afc88bc-f2ac-11e6-8438-b6a207db26e9.png)

09. Feb. 2017 13:17
![2017-02-09 13_17_32-sona patson2_](https://cloud.githubusercontent.com/assets/25084261/22926383/9db4c7b8-f2ac-11e6-8797-ffc8980babf1.png)

14. Feb. 2017 11:39
![2017-02-14 11_39_53-sona patson2_](https://cloud.githubusercontent.com/assets/25084261/22926386/a380dcc2-f2ac-11e6-8e75-62a044fef6c4.png)

**Comment by Marra-CZ** [comment] 2017-02-14 22:27
Same problem here.

**Duplicati Version:** 2.0.1.47
**Operating System:** Windows 7 64bit
**Backend:** ACD

Initial backup of 1,44 TB crashes because of an out-of-memory error.
Screenshot after 15 minutes.
![duplicati_acd_problem](https://cloud.githubusercontent.com/assets/25780240/22952131/11e18432-f30c-11e6-9f97-b6f07cebe892.png)

After same hours it consumes whole memory (16GB).

I tried different versions of duplicati and different options while i starting Duplicati.CommandLine.exe but it behaves always the same.

**Comment by kenkendk** [comment] 2017-02-26 22:50
The only thin that seems to be consuming memory in the backend is the "filecache", which is a mapping between file names and AMZCD file ids.

@Marra-CZ, since you are on Windows, perhaps you can use the CLR profiler to see where the memory is used:
https://msdn.microsoft.com/en-us/library/ff650691.aspx

**Comment by Marra-CZ** [comment] 2017-03-17 22:04
I used CLR profiler which created 48 GB log file :smile: 
What exactly do you want to know from CLR profiler? I have no experience with it, so i just take screenshot from time line.
![duplicati memory](https://cloud.githubusercontent.com/assets/25780240/24064603/b514a172-0b65-11e7-80cf-6a8ab08b0550.png)

**Comment by kenkendk** [comment] 2017-03-17 22:13
Thanks!

It has been a while since I used the CLR profiler, but clearly there is a _very_ large concentration of `System.Byte[]` data (99%).

I recall somewhere in CLR, you can click to see where the data is allocated. Can you find somewhere that is called the "Allocation Graph" ? You should be able to spot the very large `System.Byte[]` allocation and see where it is allocated (class name and method name).

There is a guide here that explains how to trace it:
http://geekswithblogs.net/robp/archive/2009/03/13/speedy-c-part-4-using---and-understanding---clr.aspx

**Comment by Marra-CZ** [comment] 2017-03-17 22:50
Here is allocation graph for the previous picture:
[allocation graph for Objects at 9799 sec.txt](https://github.com/duplicati/duplicati/files/851936/allocation.graph.for.Objects.at.9799.sec.txt)

and picture of surviving objects
![surviving objects](https://cloud.githubusercontent.com/assets/25780240/24065539/2fd7986e-0b6c-11e7-9201-95d96dadcbb3.png)
and their allocation graph
[allocation graph for surviving objects.txt](https://github.com/duplicati/duplicati/files/851939/allocation.graph.for.surviving.objects.txt)

**Comment by kenkendk** [comment] 2017-03-17 23:24
All these allocations are within the runtime libraries for communicating with the server. 
How large were the files you are transferring (i.e. the volume size, aka `dblock-size`)?

**Comment by Marra-CZ** [comment] 2017-03-18 13:08
Yes I'm using 500MB dblock-size. It seems to upload faster with bigger dblock-size. I tried smaller size but it doesn't help...

**Comment by ksarnelli** [comment] 2017-03-22 02:24
Is there an ETA on a fix?  I just started using Duplicati a few hours ago and Duplicati.Server.exe is using 15.6 GB of RAM (out of 16GB) in my VM.  I'm backing up to ACD with blocksize=1M and dblock-size=500M.

**Comment by ElRico** [comment] 2017-04-13 09:03
I'm seeing the same issue on my RAM constraint NAS with blocksize=100M and dblock-size=1G. On my beefier desktop PC Duplicati is also using several GB of RAM, but since the overall system memory is larger it never crashed. Based on what I saw on the Desktop though, I have a feeling that the memory use is correlated with the file size Duplicati is currently working on. That is if it's adding large files to the dblock, it uses lots of RAM, but not as much if it's working on small files.

**Comment by kenkendk** [comment] 2017-04-17 19:45
I think I have finally found the cause of this.
According to this very old post, the input data is buffered in memory:
https://blogs.msdn.microsoft.com/johan/2006/11/15/are-you-getting-outofmemoryexceptions-when-uploading-large-files/

The solution is to set `AllowWriteStreamBuffering = false` and it should then work. I will make a new build with that option set on the requests.

**Comment by Marra-CZ** [comment] 2017-04-17 21:09
After quick test it looks good. I'm going to leave it uploading/backuping overnight and will see.

More than 10 years old post and it is still actual, cool... :-D

**Comment by trinhit** [comment] 2017-04-26 11:16
Could you please make a newest build for Windows? The latest version for Windows is still 2.0.1.53. Thanks!

**Comment by kenkendk** [comment] 2017-04-26 11:26
@trinhit I hide the canary versions here (including Windows builds): https://github.com/duplicati/duplicati/releases

**Comment by mmiat** [comment] 2017-05-13 18:38
Windows 2008 R2
Duplicati v52 and v55
it upload to ACD, no errors
but ram used by Duplicati.Server.exe is at 20GB (!!!)

**Comment by kenkendk** [comment] 2017-05-18 12:26
@mmiat You need to use v2.0.1.57 or later.
No reports of this still being an issue with that version (so far).

If anyone still sees the issue with the latest canary, let me know.

**Comment by kenkendk** [comment] 2017-08-02 07:18
Closing and assuming fixed

**Closed by kenkendk** 2017-08-02 07:18 UTC
Labels: amzcd, bug
