### ISSUE TITLE
Restoring from a multi-drive backup to a non-original location fails

### ISSUE THREAD

**Issue by ingul-buz** [duplicati/duplicati#2306] opened 2017-02-04 23:43 UTC
I have:
- [ x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.45_experimental_2017-02-03
**Operating System:** Windows 7 x64
**Backend:**

### Bug description
Restoring multiple files that are backed up from different drives (i.e. they have different Windows drive letters) fails, as it seems that Duplicati tries to create paths including the drive letter **_and colon_**, which of course is not allowed in Windows.

This only happens if you try to restore to a non-original location, and more that one file from multiple drives. Several files from _a single drive_ can be restored ok even to a non-original location, as well as files from multiple drives to _the original locations_.

### Steps to reproduce
- Select "Restore files..." from any backup that includes files from multiple drives
- In the file selector mark at least two files from different drives and press "Continue"
- Select "Pick location" and choose a folder other than the original ones
- Press "Restore"

**Actual result:** Duplicati claims that "Your files and folders have been restored successfully", but actually they haven't, and there are warnings in the log:

Warnings: [
    Creating missing folder C:\Users\ib\Documents\F:\XYZ for  file C:\Users\ib\Documents\F:\XYZ\Pic1.jpg,
    Failed to patch file: "C:\Users\ib\Documents\F:\XYZ\Pic1.jpg", message: The given path's format is not supported., message: The given path's format is not supported. => The given path's format is not supported.,
    Creating missing folder C:\Users\ib\Documents\G:\Keep for  file C:\Users\ib\Documents\G:\Keep\Pic2.JPG,
    Failed to patch file: "C:\Users\ib\Documents\G:\Keep\Pic2.JPG", message: The given path's format is not supported., message: The given path's format is not supported. => The given path's format is not supported.,
...
]

**Expected result:** Files from multiple drives should be restored even to non-original locations. I recall that in earlier versions folders were created using the relevant drive letters without the colon, which seems to be the obvious problem here.

### debug log

{"ClassName":"System.NotSupportedException","Message":"The given path's format is not supported.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":" at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)\r\n at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n at Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)\r\n at Duplicati.Library.Main.Operation.RestoreHandler.DoRun(LocalDatabase dbparent, IFilter filter, RestoreResults result)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nEmulateFileIOPermissionChecks\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Security.Permissions.FileIOPermission\nVoid EmulateFileIOPermissionChecks(System.String)","HResult":-2146233067,"Source":"mscorlib","WatsonBuckets":null}

**Comment by 0xattr** [comment] 2017-03-12 13:55
I have the same problem.

bit awkward to include this kind of bug in the software lol

**Comment by albertony** [comment] 2017-03-20 13:29
I tried to reproduce this on latest master without any luck. Could it be fixed now, possibly by the commit af14151d91615e8ba14d790a83218ac85c10912e fixing issue #2367? That fix seems to be part of the latest canary (v2.0.1.52-2.0.1.52_canary_2017-03-13) so can be retested there as well.

**Comment by ingul-buz** [comment] 2017-03-20 17:41
@albertony, you seem to be right. I tested with the 2.0.1.52_canary, and files from different drives were restored to a non-original location correctly. I guess it's probably due to the commit you mentioned, although I didn't dig deeper into that.

The appropriately constructed paths can also be seen in a warning this operation produces:

```
Warnings: [
    Creating missing folder C:\Users\ib\Documents\F\XYZ for  file C:\Users\ib\Documents\F\XYZ\Pic1.jpg,
    Creating missing folder C:\Users\ib\Documents\G\Keep for  file C:\Users\ib\Documents\G\Keep\Pic2.JPG
]
```
I'm not sure whether restoring to a non-original location should produce a _warning_ though. The result is what's expected to happen in this case anyway.

**Closed** 2017-03-20 17:52 UTC
Labels: bug, minor change

**Comment by albertony** [comment] 2017-03-20 17:53
Yes, it seems it produces such warnings whenever it needs to create a folder during restore. I am not sure I understand why this is necessary, but I was thinking @kenkendk had his reasons.. ;)

**Comment by kenkendk** [comment] 2017-03-21 09:54
The restore operation was originally written to restore everything. In this case, the folders should be created before files are put into it. Rather than fail if this is not the case, there is a warning that "something is not quite right".

But in the case of a partial restore, the warnings should go away, or a pre-step should create the required folders.
