### ISSUE TITLE
Warning on symbolic links

### ISSUE THREAD

**Issue by bouthors** [duplicati/duplicati#3670] opened 2019-02-21 08:24 UTC
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: debian 9.7
- **Backend**: Jottacloud

## Description
It seems symbolic links are not fully supported by duplicati.
I got warning for each of them:
Duplicati.Library.Main.Operation.Backup.MetadataGenerator.Metadata-MetadataProcessFailed]: Failed to process metadata for "xxx", storing empty metadata,

What are the consequences of this warning ?

## Steps to reproduce
Create a symbolic link with Linux or Mac try to make a backup.

- **Actual result**:
Warning as above.
- **Expected result**:
No Warnings, all links included in the backup.

**Comment by warwickmm** [comment] 2019-02-22 02:43
Unfortunately, I'm unable to reproduce this.  Can you provide any more details about your configuration?  Do you have any advanced options set?

Even better would be if you could describe a minimal working example.  For example, something like:
1. Create source files by executing
```
$ mkdir source
$ cd source
$ echo hello > hello
$ ln -s hello link
```
2. Configure a backup with `source` as the source and all the default options.
3. Run a backup.
4. ...

**Comment by broeselbude** [comment] 2019-03-17 10:50
Get similar warnings while backup from a Windows 10 network drive n: of a fritzbox to a ftps server:

2019-03-17 11:40:04 +01 - [Warning-Duplicati.Library.Main.Operation.Backup.MetadataGenerator.Metadata-MetadataProcessFailed]: Failed to process metadata for "N:\", storing empty metadata
2019-03-17 11:40:05 +01 - [Warning-Duplicati.Library.Main.Operation.Backup.MetadataGenerator.Metadata-MetadataProcessFailed]: Failed to process metadata for "N:\K1200S_RDC_Hinterrad.JPG", storing empty metadata
2019-03-17 11:40:05 +01 - [Warning-Duplicati.Library.Main.Operation.Backup.MetadataGenerator.Metadata-MetadataProcessFailed]: Failed to process metadata for "N:\readme.txt", storing empty metadata

**Comment by warwickmm** [comment] 2019-03-19 02:41
@broeselbude, although you're getting the same warnings, this issue appears to concern Linux/Mac platforms and symbolic links.  Can you create a new issue with more details about you're configuration and steps to reproduce the issue?

**Comment by warwickmm** [comment] 2019-03-19 02:42
Closing this as we cannot reproduce this.  @bouthors, if you can provide more details or an example to help us track down the cause, please feel free to reopen this issue.

**Closed by warwickmm** 2019-03-19 02:42 UTC
Labels: pending user feedback
