### ISSUE TITLE
Expecting Incremental Backup -- getting complete?

### ISSUE THREAD

**Issue by pdhixenbaugh** [duplicati/duplicati#3805] opened 2019-06-29 19:05 UTC
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: Windows 10
- **Backend**: A raspberry pi with a usb drive attached (connected via VPN and SMB/Samba)

## Description

I expect duplicati to make a complete backup the first time, and then make incremental backups after that. My drive is 100 GB, and every time I back up, duplicati copies 100 GB. This happens whether it's a local backup, or a remote backup.

## Steps to reproduce

1. Create a backup
2. Backup again (with minimal changes made to files)

- **Actual result**:
Duplicati copies 100 GB to destination

- **Expected result**:
Duplicati should check which files have been changed, and only copy the differences.

## Debug log

Three Logs are attached below:

1
```
May 30, 2019 11:52 AM: Result
DeletedFiles: 0

DeletedFolders: 0

ModifiedFiles: 0

ExaminedFiles: 158359

OpenedFiles: 0

AddedFiles: 0

SizeOfModifiedFiles: 0

SizeOfAddedFiles: 0

SizeOfExaminedFiles: 117758373787

SizeOfOpenedFiles: 0

NotProcessedFiles: 0

AddedFolders: 0

TooLargeFiles: 0

FilesWithError: 0

ModifiedFolders: 0

ModifiedSymlinks: 0

AddedSymlinks: 0

DeletedSymlinks: 0

PartialBackup: False

Dryrun: False

MainOperation: Backup

CompactResults: null

DeleteResults:

    DeletedSets: []

    Dryrun: False

    MainOperation: Delete

    CompactResults: null

    ParsedResult: Success

    Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)

    EndTime: 5/30/2019 11:51:28 AM (1559231488)

    BeginTime: 5/30/2019 11:51:20 AM (1559231480)

    Duration: 00:00:07.5634863

    Messages: [

        2019-05-30 10:34:00 -04 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started,

        2019-05-30 10:34:18 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),

        2019-05-30 10:35:03 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (4.12 KB),

        2019-05-30 11:51:21 -04 - [Information-Duplicati.Library.Main.Operation.DeleteHandler:RetentionPolicy-StartCheck]: Start checking if backups can be removed,

        2019-05-30 11:51:21 -04 - [Information-Duplicati.Library.Main.Operation.DeleteHandler:RetentionPolicy-FramesAndIntervals]: Time frames and intervals pairs: 7.00:00:00 / 1.00:00:00, 28.00:00:00 / 7.00:00:00, 365.00:00:00 / 31.00:00:00,

...

    ]

    Warnings: []

    Errors: []

    BackendStatistics:

        RemoteCalls: 5

        BytesUploaded: 0

        BytesDownloaded: 62716427

        FilesUploaded: 0

        FilesDownloaded: 3

        FilesDeleted: 0

        FoldersCreated: 0

        RetryAttempts: 0

        UnknownFileSize: 0

        UnknownFileCount: 0

        KnownFileCount: 4222

        KnownFileSize: 110484628320

        LastBackupDate: 5/29/2019 10:12:52 AM (1559139172)

        BackupListCount: 4

        TotalQuotaSpace: 4000650883072

        FreeQuotaSpace: 3629204467712

        AssignedQuotaSpace: -1

        ReportedQuotaError: False

        ReportedQuotaWarning: False

        ParsedResult: Success

        Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)

        Messages: [

            2019-05-30 10:34:00 -04 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started,

            2019-05-30 10:34:18 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),

            2019-05-30 10:35:03 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (4.12 KB),

            2019-05-30 11:51:21 -04 - [Information-Duplicati.Library.Main.Operation.DeleteHandler:RetentionPolicy-StartCheck]: Start checking if backups can be removed,

            2019-05-30 11:51:21 -04 - [Information-Duplicati.Library.Main.Operation.DeleteHandler:RetentionPolicy-FramesAndIntervals]: Time frames and intervals pairs: 7.00:00:00 / 1.00:00:00, 28.00:00:00 / 7.00:00:00, 365.00:00:00 / 31.00:00:00,

...

        ]

        Warnings: []

        Errors: []

RepairResults: null

TestResults:

    MainOperation: Test

    Verifications: [

        Key: duplicati-20190425T033500Z.dlist.zip

        Value: [],

        Key: duplicati-i841c73eb937c4a648b9d74d221cf5eab.dindex.zip

        Value: [],

        Key: duplicati-b1ce642c647e340cbace2beb9c3329d8f.dblock.zip

        Value: []

    ]

    ParsedResult: Success

    Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)

    EndTime: 5/30/2019 11:52:43 AM (1559231563)

    BeginTime: 5/30/2019 11:52:36 AM (1559231556)

    Duration: 00:00:07.0037229

    Messages: [

        2019-05-30 10:34:00 -04 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started,

        2019-05-30 10:34:18 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),

        2019-05-30 10:35:03 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (4.12 KB),

        2019-05-30 11:51:21 -04 - [Information-Duplicati.Library.Main.Operation.DeleteHandler:RetentionPolicy-StartCheck]: Start checking if backups can be removed,

        2019-05-30 11:51:21 -04 - [Information-Duplicati.Library.Main.Operation.DeleteHandler:RetentionPolicy-FramesAndIntervals]: Time frames and intervals pairs: 7.00:00:00 / 1.00:00:00, 28.00:00:00 / 7.00:00:00, 365.00:00:00 / 31.00:00:00,

...

    ]

    Warnings: []

    Errors: []

ParsedResult: Success

Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)

EndTime: 5/30/2019 11:52:43 AM (1559231563)

BeginTime: 5/30/2019 10:34:00 AM (1559226840)

Duration: 01:18:43.2206095

Messages: [

    2019-05-30 10:34:00 -04 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started,

    2019-05-30 10:34:18 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),

    2019-05-30 10:35:03 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (4.12 KB),

    2019-05-30 11:51:21 -04 - [Information-Duplicati.Library.Main.Operation.DeleteHandler:RetentionPolicy-StartCheck]: Start checking if backups can be removed,

    2019-05-30 11:51:21 -04 - [Information-Duplicati.Library.Main.Operation.DeleteHandler:RetentionPolicy-FramesAndIntervals]: Time frames and intervals pairs: 7.00:00:00 / 1.00:00:00, 28.00:00:00 / 7.00:00:00, 365.00:00:00 / 31.00:00:00,

...

]

Warnings: []

Errors: []
```
2

```
May 29, 2019 11:38 AM: Result
DeletedFiles: 0

DeletedFolders: 0

ModifiedFiles: 1

ExaminedFiles: 158359

OpenedFiles: 1

AddedFiles: 0

SizeOfModifiedFiles: 3971053

SizeOfAddedFiles: 0

SizeOfExaminedFiles: 117758373787

SizeOfOpenedFiles: 3971053

NotProcessedFiles: 0

AddedFolders: 0

TooLargeFiles: 0

FilesWithError: 0

ModifiedFolders: 0

ModifiedSymlinks: 0

AddedSymlinks: 0

DeletedSymlinks: 0

PartialBackup: False

Dryrun: False

MainOperation: Backup

CompactResults:

    DeletedFileCount: 0

    DownloadedFileCount: 0

    UploadedFileCount: 0

    DeletedFileSize: 0

    DownloadedFileSize: 0

    UploadedFileSize: 0

    Dryrun: False

    MainOperation: Compact

    ParsedResult: Success

    Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)

    EndTime: 5/29/2019 11:38:38 AM (1559144318)

    BeginTime: 5/29/2019 11:38:34 AM (1559144314)

    Duration: 00:00:03.8534196

    Messages: [

        2019-05-29 10:12:52 -04 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started,

        2019-05-29 10:13:11 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),

        2019-05-29 10:13:11 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (4.12 KB),

        2019-05-29 11:38:13 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-bde3b428b1b1e457f82b8742f357e8850.dblock.zip (1.10 MB),

        2019-05-29 11:38:18 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-bde3b428b1b1e457f82b8742f357e8850.dblock.zip (1.10 MB),

...

    ]

    Warnings: []

    Errors: []

    BackendStatistics:

        RemoteCalls: 8

        BytesUploaded: 14175832

        BytesDownloaded: 65428699

        FilesUploaded: 3

        FilesDownloaded: 3

        FilesDeleted: 0

        FoldersCreated: 0

        RetryAttempts: 0

        UnknownFileSize: 0

        UnknownFileCount: 0

        KnownFileCount: 4222

        KnownFileSize: 110484628320

        LastBackupDate: 5/29/2019 10:12:52 AM (1559139172)

        BackupListCount: 4

        TotalQuotaSpace: 4000650883072

        FreeQuotaSpace: 3629200273408

        AssignedQuotaSpace: -1

        ReportedQuotaError: False

        ReportedQuotaWarning: False

        ParsedResult: Success

        Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)

        Messages: [

            2019-05-29 10:12:52 -04 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started,

            2019-05-29 10:13:11 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),

            2019-05-29 10:13:11 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (4.12 KB),

            2019-05-29 11:38:13 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-bde3b428b1b1e457f82b8742f357e8850.dblock.zip (1.10 MB),

            2019-05-29 11:38:18 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-bde3b428b1b1e457f82b8742f357e8850.dblock.zip (1.10 MB),

...

        ]

        Warnings: []

        Errors: []

DeleteResults:

    DeletedSets: []

    Dryrun: False

    MainOperation: Delete

    ParsedResult: Success

    Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)

    EndTime: 5/29/2019 11:38:38 AM (1559144318)

    BeginTime: 5/29/2019 11:38:25 AM (1559144305)

    Duration: 00:00:12.8697260

    Messages: [

        2019-05-29 10:12:52 -04 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started,

        2019-05-29 10:13:11 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),

        2019-05-29 10:13:11 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (4.12 KB),

        2019-05-29 11:38:13 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-bde3b428b1b1e457f82b8742f357e8850.dblock.zip (1.10 MB),

        2019-05-29 11:38:18 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-bde3b428b1b1e457f82b8742f357e8850.dblock.zip (1.10 MB),

...

    ]

    Warnings: []

    Errors: []

RepairResults: null

TestResults:

    MainOperation: Test

    Verifications: [

        Key: duplicati-20190529T141252Z.dlist.zip

        Value: [],

        Key: duplicati-i0023d4819eba44feab6fece0643d4738.dindex.zip

        Value: [],

        Key: duplicati-b693dfddf44a8462687d4760cd3b1855b.dblock.zip

        Value: []

    ]

    ParsedResult: Success

    Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)

    EndTime: 5/29/2019 11:38:41 AM (1559144321)

    BeginTime: 5/29/2019 11:38:41 AM (1559144321)

    Duration: 00:00:00.6517715

    Messages: [

        2019-05-29 10:12:52 -04 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started,

        2019-05-29 10:13:11 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),

        2019-05-29 10:13:11 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (4.12 KB),

        2019-05-29 11:38:13 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-bde3b428b1b1e457f82b8742f357e8850.dblock.zip (1.10 MB),

        2019-05-29 11:38:18 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-bde3b428b1b1e457f82b8742f357e8850.dblock.zip (1.10 MB),

...

    ]

    Warnings: []

    Errors: []

ParsedResult: Success

Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)

EndTime: 5/29/2019 11:38:41 AM (1559144321)

BeginTime: 5/29/2019 10:12:52 AM (1559139172)

Duration: 01:25:49.4203720

Messages: [

    2019-05-29 10:12:52 -04 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started,

    2019-05-29 10:13:11 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),

    2019-05-29 10:13:11 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (4.12 KB),

    2019-05-29 11:38:13 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-bde3b428b1b1e457f82b8742f357e8850.dblock.zip (1.10 MB),

    2019-05-29 11:38:18 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-bde3b428b1b1e457f82b8742f357e8850.dblock.zip (1.10 MB),

...

]

Warnings: []

Errors: []
```

3

```
May 21, 2019 12:45 PM: Result
DeletedFiles: 1831

DeletedFolders: 229

ModifiedFiles: 228

ExaminedFiles: 158359

OpenedFiles: 27835

AddedFiles: 27607

SizeOfModifiedFiles: 4423880

SizeOfAddedFiles: 17618823037

SizeOfExaminedFiles: 117758536595

SizeOfOpenedFiles: 18817865555

NotProcessedFiles: 0

AddedFolders: 10951

TooLargeFiles: 0

FilesWithError: 0

ModifiedFolders: 0

ModifiedSymlinks: 0

AddedSymlinks: 0

DeletedSymlinks: 0

PartialBackup: False

Dryrun: False

MainOperation: Backup

CompactResults:

    DeletedFileCount: 0

    DownloadedFileCount: 0

    UploadedFileCount: 0

    DeletedFileSize: 0

    DownloadedFileSize: 0

    UploadedFileSize: 0

    Dryrun: False

    MainOperation: Compact

    ParsedResult: Success

    Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)

    EndTime: 5/21/2019 12:45:20 PM (1558457120)

    BeginTime: 5/21/2019 12:45:17 PM (1558457117)

    Duration: 00:00:03.2089570

    Messages: [

        2019-05-21 11:18:13 -04 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started,

        2019-05-21 11:18:28 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),

        2019-05-21 11:18:28 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (3.74 KB),

        2019-05-21 11:24:33 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b505ca80beea649f88d3f8e112beb832d.dblock.zip (50.00 MB),

        2019-05-21 11:24:38 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b505ca80beea649f88d3f8e112beb832d.dblock.zip (50.00 MB),

...

    ]

    Warnings: []

    Errors: []

    BackendStatistics:

        RemoteCalls: 397

        BytesUploaded: 10239563566

        BytesDownloaded: 65467386

        FilesUploaded: 391

        FilesDownloaded: 3

        FilesDeleted: 1

        FoldersCreated: 0

        RetryAttempts: 0

        UnknownFileSize: 0

        UnknownFileCount: 0

        KnownFileCount: 4219

        KnownFileSize: 110470452488

        LastBackupDate: 5/21/2019 11:18:13 AM (1558451893)

        BackupListCount: 3

        TotalQuotaSpace: 4000650883072

        FreeQuotaSpace: 3629214453760

        AssignedQuotaSpace: -1

        ReportedQuotaError: False

        ReportedQuotaWarning: False

        ParsedResult: Success

        Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)

        Messages: [

            2019-05-21 11:18:13 -04 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started,

            2019-05-21 11:18:28 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),

            2019-05-21 11:18:28 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (3.74 KB),

            2019-05-21 11:24:33 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b505ca80beea649f88d3f8e112beb832d.dblock.zip (50.00 MB),

            2019-05-21 11:24:38 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b505ca80beea649f88d3f8e112beb832d.dblock.zip (50.00 MB),

...

        ]

        Warnings: []

        Errors: []

DeleteResults:

    DeletedSets: [

        Item1: 1

        Item2: 4/25/2019 7:29:59 AM (1556191799)

    ]

    Dryrun: False

    MainOperation: Delete

    ParsedResult: Success

    Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)

    EndTime: 5/21/2019 12:45:20 PM (1558457120)

    BeginTime: 5/21/2019 12:45:08 PM (1558457108)

    Duration: 00:00:11.8729881

    Messages: [

        2019-05-21 11:18:13 -04 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started,

        2019-05-21 11:18:28 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),

        2019-05-21 11:18:28 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (3.74 KB),

        2019-05-21 11:24:33 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b505ca80beea649f88d3f8e112beb832d.dblock.zip (50.00 MB),

        2019-05-21 11:24:38 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b505ca80beea649f88d3f8e112beb832d.dblock.zip (50.00 MB),

...

    ]

    Warnings: []

    Errors: []

RepairResults: null

TestResults:

    MainOperation: Test

    Verifications: [

        Key: duplicati-20190521T151813Z.dlist.zip

        Value: [],

        Key: duplicati-i21471a6d2884439ea1aeb9150cb750a8.dindex.zip

        Value: [],

        Key: duplicati-bdd156c4e33bb4dd9bac3256e54ed1b65.dblock.zip

        Value: []

    ]

    ParsedResult: Success

    Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)

    EndTime: 5/21/2019 12:45:30 PM (1558457130)

    BeginTime: 5/21/2019 12:45:29 PM (1558457129)

    Duration: 00:00:00.9477193

    Messages: [

        2019-05-21 11:18:13 -04 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started,

        2019-05-21 11:18:28 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),

        2019-05-21 11:18:28 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (3.74 KB),

        2019-05-21 11:24:33 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b505ca80beea649f88d3f8e112beb832d.dblock.zip (50.00 MB),

        2019-05-21 11:24:38 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b505ca80beea649f88d3f8e112beb832d.dblock.zip (50.00 MB),

...

    ]

    Warnings: []

    Errors: []

ParsedResult: Success

Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28)

EndTime: 5/21/2019 12:45:30 PM (1558457130)

BeginTime: 5/21/2019 11:18:13 AM (1558451893)

Duration: 01:27:16.8214508

Messages: [

    2019-05-21 11:18:13 -04 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started,

    2019-05-21 11:18:28 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),

    2019-05-21 11:18:28 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (3.74 KB),

    2019-05-21 11:24:33 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b505ca80beea649f88d3f8e112beb832d.dblock.zip (50.00 MB),

    2019-05-21 11:24:38 -04 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-b505ca80beea649f88d3f8e112beb832d.dblock.zip (50.00 MB),

...

]

Warnings: []

Errors: []
```

**Comment by ts678** [comment] 2019-06-30 03:09
The logs look to me like "copy the differences". Where are later "copies 100 GB to destination"?

May 21, 2019 12:45 PM: Result
BytesUploaded: 10239563566

May 29, 2019 11:38 AM: Result
BytesUploaded: 14175832

May 30, 2019 11:52 AM: Result
BytesUploaded: 0

Expected "check which files have been changed" from above non-upload was logged as below:

~~~
OpenedFiles: 0

AddedFiles: 0
~~~

This won't even create an (unchanged) backup version without [--upload-unchanged-backups](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#upload-unchanged-backups).

Does this resolve the issue? If not, please help me see the log lines that show 100 GB uploads.

**Comment by warwickmm** [comment] 2020-08-15 22:57
Closing this since it can't be reproduced.  Duplicati should only being uploading changed blocks, not the entire source.

**Closed by warwickmm** 2020-08-15 22:57 UTC
Labels: pending user feedback
