### ISSUE TITLE
Backup very slow (Amazon Cloud Drive)

### ISSUE THREAD

**Issue by deHoeninger** [duplicati/duplicati#1893] opened 2016-08-15 08:37 UTC
I have:
- [x] searched open and closed issues for duplicates

---
### Version info

**Duplicati Version:** 2.0.1.18_canary_2016-08-10
**Operating System:** Ubuntu 14.04
**Backend:** amzcd
### Bug description

I have just switched from Google Drive to Amazon Cloud Drive as backup storage by creating a brand new backup job, so no history or old files. Total amount of data approx. 250GB, a few hundred thousand files.
Now, after more than two days, there are still 154GBs to go, only 95GB were uploaded so far. According to the backend storage, only 50MB were remotely stored every 1-3 minutes.
Duplicati itself is running on a 8 core Unix system with a 100MBit Connection, constantly using 2 cpu cores fulltime since two days.
Any ideas why performance is so low?
### Steps to reproduce

n/a

**Actual result:** Low backup speed
**Expected result:** Faster backup. Should be possible to backup a few GB per hour over a 100 MBit Connection.
### Screenshots

n/a
### debug log

My configuration:

```
    "Settings": [
      {
        "Filter": "",
        "Name": "encryption-module",
        "Value": "aes",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "compression-module",
        "Value": "zip",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "dblock-size",
        "Value": "50mb",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "keep-time",
        "Value": "12M",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "passphrase",
        "Value": "xxx",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--aes-set-threadlevel",
        "Value": "4",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--auto-cleanup",
        "Value": "true",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--compression-module",
        "Value": "7z",
        "Argument": null
      },
```
##

**Comment by agrajaghh** [comment] 2016-08-15 10:17
did you try it without `--compression-module 7z`?

**Comment by santaclause88** [comment] 2016-08-17 00:02
I also have the same issue. Backing up 7.2TB and have only got through about 300 gigs in 3 days. 

Where are the logs stored on linux so I can see whats going on?

Running 16.04.1

**Comment by deHoeninger** [comment] 2016-08-17 08:58
Hi @agrajaghh.
I've recreated the Backup-Job with zip compression module and its indeed faster. It took round about two days now, doing the initial backup of 260GB (approx. 300k files). So more or less 8-9GB per hour.
Thats still not very fast, or is my assumption wrong?
Best Jan

**Comment by agrajaghh** [comment] 2016-08-17 13:50
1,5 MB/s sounds already better, I'm not sure what the bottleneck is. Maybe @kenkendk knows if there is a problem or if this is "expected behaviour"

**Comment by GarlandM** [comment] 2016-09-07 20:08
I want to comment on this and add that I am having the same issue. It's been almost 24 hours and I'm only a few hundred GB finished out of multiple TB. There is no way I could do a full daily.

**Comment by agrajaghh** [comment] 2016-09-08 09:08
@GarlandM what is your exact speed? what backend are you using? What compression method? What encryption method?

**Comment by n1koo** [comment] 2016-10-02 03:04
Same issue here. Very inconsistent upload speeds (maxing at 50Mbps, but usually ~10Mbps). 

```
--encryption-module="aes" --compression-module="zip" --dblock-size="50mb"
```  in settings.  

Can also go to zero for long (eg. minutes). CPU usage hovering around 0% when nothing is being upload and 100-200% (8 core box) when stuff is being uploaded.

Running on Ubuntu 16.04, 8 (real) cores, 100Mbps upload

One of the things I noticed is some talk about changing endpoints to EU (if you are located there) for a boost: https://github.com/yadayada/acd_cli/issues/181  I dont think duplicati supports this right now? Judging from the AWS connections I see i'm using US endpoints right now

**Comment by thomas15v** [comment] 2016-12-03 08:56
I don't know if it reduces efficiency, but if you set the block size to 1gb it flies

**Comment by agrajaghh** [comment] 2016-12-12 20:39
> I don't know if it reduces efficiency, but if you set the block size to 1gb it flies

the downside with a blocksize of 1gb is that you can't really take advantage of data deduplication

**Comment by asselin** [comment] 2017-02-23 18:10
I think part of the issue might be that there is a 15s delay between uploads of blocks to ACD.  amzcd-consistency-delay is set to 15s, and the code enforces that delay between PUT operations. @kenkendk Is that correct behavior?  I know S3 has eventual consistency for overwrite PUTS and DELETEs, but I would think that you could send PUT after PUT without any delay.

**Comment by Ciiss0u** [comment] 2017-03-13 11:19
Hi, 

I'm also using ACD backend and encounter very slow backup tasks, seems to be due to delay between each PUT and the too small size of uploaded volumes (50Mb).

If i set --dblock-size="500mb" or anything higher than 50MB, nothing is uploaded and Duplicati will crash.

I've tried with/without options listed above but nothing to get it working :

`mono "/usr/lib/duplicati/Duplicati.CommandLine.exe" backup "amzcd://Backups/NAS/OS/?authid=AUTHID" "/boot/" "/bin/" "/etc/" "/home/" "/initrd.img" "/initrd.img.old" "/lib/" "/lib64/" "/live-build/" "/opt/" "/root/" "/sbin/" "/srv/" "/usr/" "/vmlinuz" "/var/" "/vmlinuz.old" " --backup-name="NAS-OS_ACD" --dbpath="/mnt/DATA/backups/Duplicati/DB/OS-ACD.duplicati.sqlite" --encryption-module="aes" --compression-module="zip" --dblock-size="500MB" --keep-time="2Y" --passphrase="PASSPHRASE" --snapshot-policy="Auto" --usn-policy="off" --hardlink-policy="All" --symlink-policy="Store" --index-file-policy="Full" --number-of-retries="25" --retry-delay="15s" --asynchronous-upload-folder="/mnt/DATA/backups/Duplicati/TMP/" --throttle-upload="15MB" --disable-module="console-password-input" `

Is the Duplicati backend for putting files to ACD accessible for manually testing ? 
With ACD_CLI I'm able to upload big files without problem.

**Comment by rkleineisel** [comment] 2017-04-04 21:19
I have no problems making 90 GB backups to ACD with dblock-size=500mb using 2.0.1.53 on Fedora 25.

**Comment by Ciiss0u** [comment] 2017-04-05 00:34
What options are you using ? I've also tried on windows, and with the docker image intersoftlabs/duplicati but can't make It working with more than 50GB dblock-size :/

**Comment by rkleineisel** [comment] 2017-04-10 10:37
mono "/usr/lib/duplicati/Duplicati.CommandLine.exe" backup
"amzcd://duplicati/home?authid=XXXXXXXXXXXXXXXXXXXXXXX&accept-any-ssl-certificate=true"
"/home/" --backup-name="Home2Amazon"
--dbpath="/root/.config/Duplicati/FUCZEMYYZA.sqlite"
--encryption-module="aes" --compression-module="zip"
--dblock-size="500MB" --keep-time="3Y" --passphrase="XXXXXXXXXX"
--log-file="/var/log/duplicati-home" --tempdir="/tmp/"
--log-level="Warning" --exclude-files-attributes="temporary"
--disable-module="console-password-input" --exclude="[/home/*/.cache/]"
--exclude="[/home/*/.thumbnails/]"

**Comment by Ciiss0u** [comment] 2017-04-14 16:41
Thanks ! 
I've tried adding accept-any-ssl It but nothing better for me

**Comment by Vrumfondel** [comment] 2017-04-20 07:15
Even it is not really related to the defect:
In my opinion the root-problem is not Duplicati, it is ACD as such.
After trying multiple different approaches to use ACD for backups I finally gave up on it.
The limitations caused by the (meanwhile closed) API are simply not acceptable for a half-ways 'home professional' backup solution. (15sec wait-time between two file deletes ??? So that means, deleting like 16000 files (which you easily get with 50MB junk size) takes 66 hrs ???)
I really tried all the options currently available for Linux - but nothing really works.

As a conclusion: "Unlimited storage" sounds great - until you figure out that there is no real good way to get the data on the drive or back from it ....

**Comment by shoeper** [comment] 2017-04-20 09:46
> 15sec wait-time between two file deletes

Is it wait time or is deleting just very slow? In the second case one could use heavy multithreading. E.g. using a threadpool with 100 threads for deleting the files. The same could help to upload faster.

**Comment by asselin** [comment] 2017-04-20 14:08
@Vrumfondel @shoeper ACD is based on AWS's S3 storage, which has a read-after-write consistency delay, meaning that after you perform a write operation, for some period of time afterwards, if you issue a read, you might get back the old data.  This is likely because they replicate and load balance S3 across data centers.  So, no you don't have to wait 15 seconds between deletes, you can issue them all in a big batch back to back, then perform ONE wait to make sure everything is consistent.  In my usage, I've dropped the wait time to 6 seconds and everything works well.

**Comment by shoeper** [comment] 2017-04-20 15:08
Thanks for explaining. So it looks like Duplicati is just not using the batch mode.

**Comment by mhellmeier** [comment] 2017-04-20 16:50
Same problem here. I also got a very low upload speed. I have tried it with `--dblock-size="500mb"` and `--dblock-size="50mb"` on Ubuntu 16.04 LTS and Duplicati 2.0.1.53_experimental_2017-03-13.

As @Ciiss0u said, ACD_CLI works great. Problem must be in Duplicati.
Hope to see a fix soon.

**Comment by kenkendk** [comment] 2017-04-21 10:57
@asselin Thanks for the suggestion with doing back-to-back deletes.
I have implemented this idea in 015a923, such that repeated operations of the same type (e.g. repeated uploads or repeated deletes) does not trigger the wait.

**Comment by asselin** [comment] 2017-04-21 15:51
@kenkendk Nice!  

I have a couple of observations looking at the PR.

- https://github.com/duplicati/duplicati/commit/015a92343fa0dc092511e24936ddbc2a8db467ad#diff-bc643ce00b28104d072528f2a3736312R401 The `Delete` method calls `EnforceConsistencyDelay` with `RemoteOperation.Put` instead of `RemoteOperation.Delete`.
- I believe you could eliminate some more waits with a couple of more lines in `EnforceConsistencyDelay`.  I'm not a C# programmer, so this is my best guess at a patch:

```
private void EnforceConsistencyDelay(RemoteOperation lastop)
        {
            if (m_lastOperation == RemoteOperation.First)
                m_lastOperation = lastop;
                 
            if (lastop == m_lastOperation)
                return;

            m_lastOperation = lastop;

            // Add this
            if (lastop == RemoteOperation.Put || lastop == RemoteOperation.Delete)
                return;

            var wait = m_waitUntil - DateTime.Now;
            if (wait.Ticks > 0)
                System.Threading.Thread.Sleep(wait);
}
```

My reasoning: 
- You never need to wait to do a Put.
- Duplicati won't try to delete a file that it just uploaded (if this isn't true, then the line I added should only have the Put operation on it).

As an ACD user, thanks a bunch for adding your patch-- this is an update I'm looking forward to installing!

**Comment by kenkendk** [comment] 2017-04-24 08:39
Unfortunately, you need to wait for a `Put`. to known if the file already exists. If it exists, you need to update it, otherwise you get two files with the same name. For `Delete` you need to wait because you need the fileID before you issue a delete.

**Comment by warwickmm** [comment] 2019-12-01 17:40
Closing this since Amazon Cloud Drive support has been discontinued.

**Closed by warwickmm** 2019-12-01 17:40 UTC
Labels: amzcd, enhancement
