### ISSUE TITLE
URL encoded authid fails oauth

### ISSUE THREAD

**Issue by tfaris** [duplicati/duplicati#1736] opened 2016-04-29 00:56 UTC
I exported my backup job as Command-line from the web GUI, and when actually running it on the command line it fails oauth. The authid apparently contains a colon, which was converted to a "%3A" in the storage URL. If I replace the %3A with an actual colon, the command works.

Running Windows 10, Duplicati 2.0.1.14- 2.0.1.14_canary_2016-04-21, and using Amazon Cloud Drive.

```
Fatal error
System.Exception: Failed to authorize using the OAuth service: Invalid authid in query. If the problem persists, try generating a new authid token from: https://duplicati-oauth-handler.appspot.com?type=amzcd ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
   at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
   at Duplicati.Library.JSONWebHelper.GetResponse(AsyncHttpRequest req, Object requestdata)
   at Duplicati.Library.JSONWebHelper.ReadJSONResponse[T](AsyncHttpRequest req, Object requestdata)
   at Duplicati.Library.OAuthHelper.GetTokenResponse[T]()
   at Duplicati.Library.OAuthHelper.get_AccessToken()
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.BackendManager.List()
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
```
##

**Comment by ts678** [comment] 2024-01-23 23:14
Not reproducible in current release. Maybe this was fixed. Amazon Cloud Drive is gone. I tested backup with OneDrive authid.
An actual colon is also accepted, in place of the %3A from the export. Please post if there still seems to be a problem with this.

**Comment by tfaris** [comment] 2024-01-24 15:28
Since Amazon Cloud Drive no longer exists I'm sure this issue can be closed. I switched to a different backend many years ago.

**Comment by ts678** [comment] 2024-01-25 18:31
Thanks for the reply. Closing.

**Closed** 2024-01-25 18:32 UTC
Labels: bug, minor change
