### ISSUE TITLE
Linux  -   limono2.0-cil dependancy for duplicati

### ISSUE THREAD

**Issue by glannes31** [duplicati/duplicati#1844] opened 2016-07-08 13:26 UTC
Hello,

I can't  launch Duplicati on Linux ( Lubuntu,Fedora,Ubuntu) . It's say that's the dependancy is not resolved. 

I can't download libmono2.0-cil . i have already installed mono-complete and mono-runtime

![duplicati_linux](https://cloud.githubusercontent.com/assets/20032648/16689011/1c660386-4521-11e6-8dc5-6b8beb0ec9d4.PNG)

**Comment by glannes31** [comment] 2016-07-11 07:57
Could you help me ?

**Comment by jcsogo** [comment] 2016-07-19 22:05
It seems that the package is not correctly built and the dependencies declared. There is no libmono2.0-cil package in Debian/Ubuntu and that is why the dependency is not satisfied. These [helper scripts](http://pkg-mono.alioth.debian.org/cli-policy/ch-appendix.html) should be used to ensure the right dependencies are carried.

**Comment by G4Zz0L1** [comment] 2016-08-02 09:35
I can confirm this issue, under Linux Mint 18 Sarah, mono's default version is 4.2.1 while for duplicati we have:
http://packages.ubuntu.com/wily/libmono2.0-cil
that requires (one of them)
http://packages.ubuntu.com/wily/libmono-corlib2.0-cil
that requires mono-runtime < 3.2.9

I don't know if the issue is with something part of mono-runtime, or the libmono-corlib2.0-cil, but i can't downgrade them, nor i can't install duplicati after a fresh install.

**Comment by danielblues** [comment] 2016-08-03 14:33
Same issue with ubuntu 16.04.

**Comment by kenkendk** [comment] 2016-08-03 16:51
Yes, the package has ben renamed from `libmono2.0-cil` to `libmono-2.0-1`.
I have fixed this in source, but I have not yet built a new package.
I expect a new build early next week.

**Comment by glannes31** [comment] 2016-08-03 16:57
i forgot to precise the version: ubuntu 16.04

**Comment by kenkendk** [comment] 2016-08-31 08:54
This should be fixed with the 2.0.1.19 build and newer.

**Closed by kenkendk** 2016-08-31 08:54 UTC
