### ISSUE TITLE
Command Line Scripts from v2.0.2.12 go no longer

### ISSUE THREAD

**Issue by Photographix** [duplicati/duplicati#2907] opened 2017-11-23 10:29 UTC
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: v2.0.2.13-2.0.2.13_canary_2017-11-22
- **Operating system**: WinSvr 2012 R2
- **Backend**: ACD, Jotta

## Description
batch scripts working with version 2.0.2.12 and report an Phassphrase error on v2.0.2.13
`Duplicati.CommandLine.exe backup "amzcd://6c2wKPndUChcP6?authid=bcf4b2d01bc0400c7:5_vU!A" "\\aio-pod\abc\\" --auto-cleanup="true" --number-of-retries="5" --retry-delay="10s" --use-block-cache="false" --backup-name="AIO-documents>ACD" --dbpath="C:\Users\Administrator\AppData\Roaming\Duplicati\ABC.sqlite" --encryption-module="aes" --compression-module="zip" --dblock-size="300MB" --keep-time="5W" --passphrase="ABC.amos" --disable-module="console-password-input" --exclude=".zfs\\" --log-file=Logging\Documents\Documents-acd-bkp.log --log-level="Information" `

- **Actual result**:
`Verschlüsselungspassphrase eingeben:
System.InvalidOperationException: Schlüssel können nicht gelesen werden, wenn ke
ine der Anwendungen eine Konsole besitzt, oder wenn die Konsoleneingabe aus eine
r Datei umgeleitet wurde. Verwenden Sie Console.Read.
   bei System.Console.ReadKey(Boolean intercept)
   bei Duplicati.Library.Modules.Builtin.ConsolePasswordInput.ReadPassphraseFrom
Console(Boolean confirm)
   bei Duplicati.Library.Modules.Builtin.ConsolePasswordInput.Configure(IDiction
ary2 commandlineOptions)
   bei Duplicati.Library.Main.Controller.SetupCommonOptions(ISetCommonOptions re
sult, String[]& paths, IFilter& filter)
   bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths,
 IFilter& filter, Action1 method)
   bei Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter f
ilter)
   bei Duplicati.CommandLine.Commands.Backup(TextWriter outwriter, Action1 setu
p, List1 args, Dictionary2 options, IFilter filter)
   bei Duplicati.CommandLine.Program.RunCommandLine(TextWriter outwriter, TextWr
iter errwriter, Action1 setup, String[] args)
Drücken Sie eine beliebige Taste . . .`
- **Expected result**:
Script run as before

## Screenshots
![2017-11-23 11_20_23-tools - remote desktop connection manager v2 7](https://user-images.githubusercontent.com/16647382/33168395-1486ef16-d041-11e7-9379-2b9f7cc0c903.png)

**Comment by kenkendk** [comment] 2017-11-24 13:05
In 2.0.1.13, there is a change in how commandline parameters are passed around, so I am guessing this is the cause.
The error reads that the passphrase could not be read, but the passphrase module is disabled so it should not even be invoked.

Are there special characters in the passphrase that could cause this (assuming the passphrase you posted is not the real one) ?

**Comment by Photographix** [comment] 2017-11-24 15:56
Hello the passwords during similar to "Brent5.3Onward.Civil12". It's not the real password. Only numbers, upper and lower case letters and dots.

**Comment by kenkendk** [comment] 2017-12-09 20:27
I have been holding back the next experimental due to this error, but I am thinking that this has actually been fixed in 2.0.2.13.

I think you see this error beause you originally installed v2.0.2.12 and then you updated to 2.0.2.13 (really to any version) and this triggers a bug in passing the commandline arguments.

Is this how it happened, or do you have a clean install of 2.0.2.13?

Btw, you can set `--verbose` to see how Duplicati has parsed your commandline input.

**Comment by basrieter** [comment] 2017-12-09 21:06
Is there something that people have 2.0.2.13 installed can verify?

**Comment by kenkendk** [comment] 2017-12-09 21:34
Yes, you should be able to do something like:
```
Duplicati.CommandLine.exe nothing --opt1="123.456" --verbose
```

If it works, you will see something like:
```
Input command: nothing
Input arguments:

Input options:
opt1: 123.456
verbose:

Command not supported: nothing
```

If it does not work, you will see the inputs and fields are offset in weird ways.
If you try it, make sure to also run:
```
Duplicati.Library.AutoUpdater.exe
```

And check which base versions and current version you are running with.

**Comment by basrieter** [comment] 2017-12-09 21:42
I think the output is OK for me:

```
C:\ProgramData\Duplicati\updates\2.0.2.13>Duplicati.Library.AutoUpdater.exe
Usage:
        Duplicati.Library.AutoUpdater.exe [LIST|VERIFY|CHECK|INSTALL|HELP]

Environment variables:

AUTOUPDATER_Duplicati_SKIP_UPDATE - Disables updates completely
AUTOUPDATER_Duplicati_POLICY - Choose how to handle updates, valid settings: CheckBefore, CheckDuring, CheckAfter, InstallBefore, InstallDuring, InstallAfter, Never
AUTOUPDATER_Duplicati_URLS - Use alternate updates urls
AUTOUPDATER_Duplicati_CHANNEL - Choose different channel than the default Canary, valid settings: Stable,Beta,Experimental,Canary,Nightly,Debug

Updates are downloaded from: https://updates.duplicati.com/canary/latest.manifest;https://alt.updates.duplicati.com/canary/latest.manifest
Updates are installed in: C:\ProgramData\Duplicati\updates\2.0.2.13\updates
The base version is "2.0.2.13_canary_2017-11-22" (2.0.2.13) and is installed in: C:\ProgramData\Duplicati\updates\2.0.2.13
This version is "2.0.2.13_canary_2017-11-22" (2.0.2.13) and is installed in: C:\ProgramData\Duplicati\updates\2.0.2.13


C:\ProgramData\Duplicati\updates\2.0.2.13>Duplicati.CommandLine.exe nothing --opt1="123.456" --verbose
Input command: nothing
Input arguments:

Input options:
opt1: 123.456
verbose:
```

**Comment by Photographix** [comment] 2017-12-11 06:15
Hello and good morning,
the error also occurs with a fresh duplicati-2.0.2.13_canary_2017-11-22-x64. msi installation. 

Uninstall old v2.2.0.12
directory empty
install new v2.2.0.13
Error exists 
![2017-12-11 07_10_31- remote desktop connection manager v2 7](https://user-images.githubusercontent.com/16647382/33818011-f72cfd92-de42-11e7-954f-f501b1ba4ab6.png)

**Comment by kenkendk** [comment] 2017-12-11 10:18
Ok, the test command you tried seems to work as expected.
I assume that you mean that the original script still fails? Can you add --verbose to the script for the command that fails and see where the reported parsed input is broken?

**Comment by Photographix** [comment] 2017-12-12 06:11
Good morning, 
the same script with version 2.0.2.2.12 and with version 2.0.2.13 (some parts are blackened)

v2.0.2.12

![2017-12-12 06_48_33-2 0 2 12 - remote desktop connection manager v2 7](https://user-images.githubusercontent.com/16647382/33869664-536dce3e-df0a-11e7-868e-58a0d2cd749a.png)

v2.0.2.13
![2017-12-12 06_57_38-2 0 2 13 - remote desktop connection manager v2 7](https://user-images.githubusercontent.com/16647382/33869667-587847ce-df0a-11e7-896a-585df986f530.png)

echo cmd line

![2017-12-12 07_04_42- remote desktop connection manager v2 7](https://user-images.githubusercontent.com/16647382/33869839-4bfbfcc4-df0b-11e7-8782-6dcea81d224c.png)

can it be that in version 2.0.2.13 the sign (") drawing is interpreted differently?

**Comment by kenkendk** [comment] 2017-12-20 21:31
I can now reproduce this issue. It has something to do with the double trailing slash somehow escaping the `"`.

I will try to fix the problem now.

**Closed** 2017-12-22 09:06 UTC
Labels: bug

**Comment by kenkendk** [comment] 2017-12-26 08:51
@Photographix Can you re-rest with 2.0.2.14 and report the results

**Comment by Photographix** [comment] 2017-12-27 11:21
Hello, I have no problems with version 2.0.2.14 and my old scripts are working again.
Thanks for the good work
