### ISSUE TITLE
proxy support ?

### ISSUE THREAD

**Issue by sander76** [duplicati/duplicati#1123] opened 2014-08-28 11:43 UTC
I've seen posts regarding proxy support. But not really sure whether it is included already in the 2.0 version of duplicati...

Sander.
##

**Comment by Guillaume00** [comment] 2017-04-23 14:13
+1 for this feature

**Comment by Pectojin** [comment] 2018-02-11 02:56
Closing as duplicate of #290

**Closed by Pectojin** 2018-02-11 02:56 UTC
