### ISSUE TITLE
No restoring screen after press "Restore"

### ISSUE THREAD

**Issue by blueberry6401** [duplicati/duplicati#1791] opened 2016-06-02 03:41 UTC
I'm using v2.0.1.17-2.0.1.17_canary_2016-05-14, and after press Restore, screen is unchanged, there is no "restoring screen" or whatever that let me know the restoring is started, although files are being restored and the progress is shown at main duplicati's screen.
My backup is on Google Drive.
![2016-06-02_102514](https://cloud.githubusercontent.com/assets/7337535/15733138/394e1a50-28ad-11e6-8210-93c6465a9667.png)

**Comment by agrajaghh** [comment] 2016-06-02 08:37
closing as duplicate of #1629

**Closed by agrajaghh** 2016-06-02 08:37 UTC
