### ISSUE TITLE
Send backups to multiple destinations

### ISSUE THREAD

**Issue by robbat2** [duplicati/duplicati#1265] opened 2015-01-26 21:58 UTC
I'd like to be able to send backups to multiple destinations, ideally with different retention parameters.

Example:
- Run a backup of folder X ONCE
- Send it locally to another server, retain 1 month 
- Send it to Amazon S3, retain for 6 months

The key thing is that it's backup once, upload two or more times.
##

**Comment by Guddler** [comment] 2015-02-23 16:37
+1 - need the same thing, but actually for me with the same retention. I just need to backup to S3, plus have an additional copy on an "in-house" machine in case S3 should no longer be there one day. As unlikely as that may sound, any good backup strategy should still cope with the scenario when something is out of your direct control.

**Comment by ironjohn** [comment] 2015-05-07 18:36
+1 and this has already been requested in issue #479 (plus a few others).

**Comment by simonjtaylor212** [comment] 2015-07-07 20:52
+1 too

**Comment by barsthebars** [comment] 2015-07-07 21:22
+1

**Comment by scspijker** [comment] 2015-07-24 15:55
:+1:

**Comment by masgo** [comment] 2015-11-17 02:18
Would it make a big difference of having two backup jobs for the same folders? one for each destination? - ok, obviously the files will not be mixable ... but is there any other drawback?

**Comment by robbat2** [comment] 2015-11-17 06:55
@masgo any computation done for the backup needs to be done twice with that solution.

**Comment by bensoibj** [comment] 2016-04-08 15:59
+1 (and also for #479 ).

**Comment by frostasm** [comment] 2017-10-13 14:31
+1

**Comment by Pectojin** [comment] 2018-02-11 02:45
Closing this issue since it's a duplicate of issue 234. I know we all want it but one issue will cause less confusion.

**Closed by Pectojin** 2018-02-11 02:45 UTC
Labels: enhancement
