### ISSUE TITLE
S3 compatible target fails on Linux but works on Windows

### ISSUE THREAD

**Issue by FreeMinded** [duplicati/duplicati#3019] opened 2018-02-08 11:48 UTC
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Linux (Ubuntu 16.04)
- **Backend**: S3 compatible (cloudscale.ch)

## Description
Connecting to a S3 compatible object storage fails on a Linux Client with the following error message: "Failed to connect: A WebException with status SendFailure was thrown. "
The exact same settings work on a Windows Client.

## Steps to reproduce
1. Setup new backup on a Linux client to S3 compatible Storage 
2. Connection test fails
3. Try the same on a Windows client
4. Connection test works

- **Actual result**:
Error: "Failed to connect: A WebException with status SendFailure was thrown."

- **Expected result**:
Connection successfull

## Debug log
```
8. Febr. 2018 12:29: Request for http://localhost:8200/api/v1/remoteoperation/test gave error
Amazon.Runtime.AmazonServiceException: A WebException with status SendFailure was thrown. ---> System.Net.WebException: Error: SendFailure (Error writing headers) ---> System.Net.WebException: Error writing headers ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.
  at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (IAsyncResult asyncResult) <0x41e5e4b0 + 0x0010b> in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (IAsyncResult ar, Boolean ignoreEmpty) <0x41e5e3f0 + 0x0002b> in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (IAsyncResult result) <0x41e59450 + 0x0022f> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Net.WebConnection.EndWrite (System.Net.HttpWebRequest request, Boolean throwOnError, IAsyncResult result) <0x41d96440 + 0x00207> in <filename unknown>:0 
  at System.Net.WebConnectionStream+<SetHeadersAsync>c__AnonStorey1.<>m__0 (IAsyncResult r) <0x41d95a70 + 0x00143> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x41db3980 + 0x001a7> in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () <0x41e53500 + 0x0005a> in <filename unknown>:0 
  at Amazon.Runtime.Internal.HttpRequest.GetResponse () <0x41ff7e10 + 0x00043> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Amazon.Runtime.Internal.WebExceptionHandler.HandleException (IExecutionContext executionContext, System.Net.WebException exception) <0x41ff8c60 + 0x0026f> in <filename unknown>:0 
  at Amazon.Runtime.Internal.ExceptionHandler`1[T].Handle (IExecutionContext executionContext, System.Exception exception) <0x41ff8bd0 + 0x0007e> in <filename unknown>:0 
  at Amazon.Runtime.Internal.ErrorHandler.ProcessException (IExecutionContext executionContext, System.Exception exception) <0x41ff8720 + 0x001ec> in <filename unknown>:0 
  at Amazon.Runtime.Internal.ErrorHandler.InvokeSync (IExecutionContext executionContext) <0x41ff4de0 + 0x00067> in <filename unknown>:0 
  at Amazon.Runtime.Internal.PipelineHandler.InvokeSync (IExecutionContext executionContext) <0x41fe49b0 + 0x00034> in <filename unknown>:0 
  at Amazon.Runtime.Internal.CallbackHandler.InvokeSync (IExecutionContext executionContext) <0x41fe4b90 + 0x00023> in <filename unknown>:0 
  at Amazon.Runtime.Internal.PipelineHandler.InvokeSync (IExecutionContext executionContext) <0x41fe49b0 + 0x00034> in <filename unknown>:0 
  at Amazon.Runtime.Internal.Signer.InvokeSync (IExecutionContext executionContext) <0x41feb520 + 0x00027> in <filename unknown>:0 
  at Amazon.Runtime.Internal.PipelineHandler.InvokeSync (IExecutionContext executionContext) <0x41fe49b0 + 0x00034> in <filename unknown>:0 
  at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync (IExecutionContext executionContext) <0x41feaa00 + 0x00027> in <filename unknown>:0 
  at Amazon.Runtime.Internal.PipelineHandler.InvokeSync (IExecutionContext executionContext) <0x41fe49b0 + 0x00034> in <filename unknown>:0 
  at Amazon.Runtime.Internal.RetryHandler.InvokeSync (IExecutionContext executionContext) <0x41fea6b0 + 0x0008f> in <filename unknown>:0 
```

**Comment by gaudenz** [comment] 2018-02-08 13:11
I had the same issue. This is probably caused by the server not allowing any non Elliptic Curve Diffie-Hellmann algorithms for SSL. See https://bugzilla.xamarin.com/show_bug.cgi?id=26658

This should be resolved as of mono 4.8. But the latest version available in either Ubuntu or Debian is 4.6.

I was able to solve the issue using the upstream mono packages from http://www.mono-project.com/download/

The Xamarin bug report also contains hints on how to circumvent the issue by using an alternative HTTP client implementation.

**Comment by FreeMinded** [comment] 2018-02-08 13:19
@gaudenz thanks for the workaround!

**Comment by kenkendk** [comment] 2018-02-09 10:43
Ok, I will close as it is fixed by upgrading Mono and because I cannot fix it in Duplicati.

**Closed by kenkendk** 2018-02-09 10:43 UTC
