### ISSUE TITLE
Deleted files are not completely deleted from the database causing it to grow large

### ISSUE THREAD

**Issue by Adam777Z** [duplicati/duplicati#3865] opened 2019-08-19 12:21 UTC
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.22_canary_2019-06-30
- **Operating system**: Windows
- **Backend**: local

## Description

I've noticed that the local database files are growing larger over time and don't shrink after deleting files. The vacuum command helps some, but they're still quite large.

I looked inside a database to find out why it's so large and found that the _Remotevolume_ table contains a lot of entries with _State_ of _Deleted_. Other entries have a _State_ of _Verified_.

I looked for a way to compact the database and delete the Deleted entries using Duplicati but found no way to do it.

It looks like Duplicati doesn't completely delete the deleted files from the database which causes it to grow large over time. This is a serious issue because this means that the database will just grow over time and waste storage space with no way to stop it, other than re-creating it, which takes time.

Why are these Deleted entries not completely deleted and cleaned up? Is there a reason?

Would manually deleting those entries in the database cause issues?

I've found no indication that those entries are required (they're deleted files after all) but hopefully someone (a developer of Duplicati) can answer this question.

## Steps to reproduce

1. Create a new backup, set _Backup retention_ to _Keep a specific number of backups_ and enter 1 and run it
2. Delete or exclude some files from the backup and run the backup again
3. Check the database of the backup: in the _Remotevolume_ table there are entries with _State_ of _Deleted_

- **Actual result**:
Deleted files are not completely deleted from the database, causing it to grow large and waste storage space over time
- **Expected result**:
Deleted files are completely deleted from the database so it doesn't waste storage space by growing unnecessarily large over time

**Comment by BlueBlock** [comment] 2019-08-21 04:07
I think there is a grace period before the remote volume files are actually deleted.

**Comment by Pectojin** [comment] 2019-08-21 08:10
Remote volumes are only deleted when all files inside them are marked deleted or when duplicati decides to compact them.

And compaction will happen on volumes where a significant amount of the volume consists of files marked for deletion.

**Comment by Adam777Z** [comment] 2019-08-21 14:25
Yes, there is _DeleteGraceTime_ in the _Remotevolume_ table, and all entries with _State_ of _Deleted_ have it. Entries with _State_ of _Verified_ have _0_ for _DeleteGraceTime_.

I looked into the database of an old Backup and the oldest entries with _State_ of _Deleted_ have _DeleteGraceTime_ of over a year old.

And clicking on _Compact now_ finishes instantly.

This makes me think that all of those volumes were deleted in the destination long ago, and only their entries remain. I checked a few volumes on the destination and indeed, they don't exist.

So while apparently the Deleted entries seem to serve a purpose, the original issue still remains: they are not completely deleted/cleaned up from the database.

Hopefully someone with more knowledge on this can clarify this.

**Comment by Adam777Z** [comment] 2019-08-28 10:15
I looked into the database of the old Backup again and checked the latest _Deleted_ entry on the destination and it's also deleted there.

So perhaps the _DeleteGraceTime_ indicates when it was deleted, and not when it should be deleted?

The only entries that have the _DeleteGraceTime_ set are the ones with _State_ of _Deleted_.

If there's really no reason to store all deleted volumes in the local database (which seems to be the case), then it should be easy to fix this: just delete the entry instead of marking it as _Deleted_.

**Comment by Adam777Z** [comment] 2019-09-07 13:17
Maybe @kenkendk could provide some insight?

**Comment by Adam777Z** [comment] 2019-09-07 13:19
This issue seems to be related: #2426

**Comment by Adam777Z** [comment] 2019-09-07 13:25
As a test I restored all files from the old Backup then ran an SQL command that deleted all _Deleted_ entries in the database, then ran the vacuum command, then restored all files again and compared the contents. They're exactly the same. This means and also confirms that the _Deleted_ entries serve no purpose and are not needed, they can be safely deleted and should be deleted by Duplicati automatically.

Then I ran another backup and restore and it all worked without any errors or warnings, too. Everything seems to be working perfectly.

**Comment by BlueBlock** [comment] 2019-09-07 14:06
Thanks for the details. Can you share some of the timestamps in the db for items marked for delete?

**Comment by Adam777Z** [comment] 2019-09-07 14:23
They're already deleted but from what I've seen all of them were in the past and corresponded to the time the files were deleted from the destination.

**Comment by BlueBlock** [comment] 2019-09-07 15:02
> They're already deleted but from what I've seen all of them were in the past and corresponded to the time the files were deleted from the destination.

What would estimate were the ages? days? months? Thanks.

**Comment by Adam777Z** [comment] 2019-09-07 15:07
In the old Backup's database the oldest entries with _State_ of _Deleted_ had _DeleteGraceTime_ of over a year old.

**Comment by BlueBlock** [comment] 2019-09-07 19:09
> In the old Backup's database the oldest entries with _State_ of _Deleted_ had _DeleteGraceTime_ of over a year old.

Thanks.  I'll look at reproducing the issue.

**Comment by BlueBlock** [comment] 2019-09-07 19:31
So it looks like the grace time is 2 hours. The ticks is being used which is not unix time.

For example, 2 hours from now is:
1567891656

Currently the ticks is:
637034883238371438
08/29/20186833804 @ 12:57am (UTC)

A bit in the future.

**Comment by BlueBlock** [comment] 2019-09-07 21:23
Fixed.
https://github.com/duplicati/duplicati/pull/3894

**Comment by warwickmm** [comment] 2019-09-07 22:46
Thanks @BlueBlock.  We typically close an issue after the pull request has been merged.  To avoid confusion, I'm going to re-open this.  We can close it once the changes from #3894 are in the `master` branch.

**Comment by warwickmm** [comment] 2019-09-17 19:13
Fixed in pull request #3894.

**Comment by Adam777Z** [comment] 2019-09-18 09:28
I tested the new version and the fix doesn't work.

From what I see, because of the change from Ticks to Unix time, the comparison won't work for old entries because a Tick is a bigger number than a Unix time number that's used for the comparison (current time in Unix time number), and even then, for new entries using the Unix time it doesn't work. Must be a bug somewhere.

In my opinion, to fix this, there should be no comparison for _DeleteGraceTime_, that only stores when it was deleted from the destination. That should make it work with old database entries and new ones.

And then to truly fix this, there's no need to mark the entry as deleted - after the volume was deleted from the destination it should be deleted from the database immediately.
In this case some cleanup code is still required for old databases, for those updating from an older version, so the first fix need to be kept.

**Comment by BlueBlock** [comment] 2019-09-21 14:34
> I tested the new version and the fix doesn't work.

Thanks. Fixed in PR https://github.com/duplicati/duplicati/pull/3922

**Closed** 2019-09-24 03:53 UTC
Labels: fixed, local database issue
