### ISSUE TITLE
Debian 12 Testing Install Fail

### ISSUE THREAD

**Issue by awptechnologies** [duplicati/duplicati#5138] opened 2024-04-02 07:46 UTC
Package dependencies don't allow me to install. duplicati: Depends: libappindicator0.1-cil but it is not installable or libappindicator3-0.1-cil but it is not installable or libayatana-appindicator1 but it is not installableDepends: gtk-sharp2

**Comment by ts678** [comment] 2024-04-02 15:53
I don't have any Debian, but can collect information that might help some expert, if it turns out that one is required.

The subject line is a little ambiguous. Is this Debian 12 which is Debian Stable, or Debian Testing which is Debian 13?

What tool are you using or are you willing to use? The posted output looks kind of run-together. Can it look better?
Sometimes putting triple backticks above and below a paste of multiple lines is helpful to make it display like original.

[Packages](https://www.debian.org/distrib/packages) at Debian is a resource to help sort this out for various versions. I tried a search simply for appindicator, as
variations exist (and I think you're showing three there, but I'm not sure why the third is not happy on your system).

On original output, does it look like the last option can't find gtk-sharp2? Any idea why? Does system have graphics?

What Duplicati version is this? Have others been tried? There was supposed to have been a Debian 12 bookworm fix:

[ allow install on Debian bookworm using libayatana-appindicator1 shim #4902 ](https://github.com/duplicati/duplicati/pull/4902) with some notes about Debian's limits.

**Comment by ts678** [comment] 2024-04-02 18:59
Another possibility is that change below will stop this issue. I think it moves to Avalonia for appindicator, but still needs graphics.

[Battle plan for migrating to .Net8](https://forum.duplicati.com/t/battle-plan-for-migrating-to-net8/17482/70?u=ts678)

> My current builds are using self-contained so there are actually no additional dependencies for the binary packages, except for the GUI parts on Linux.

**Comment by awptechnologies** [comment] 2024-04-02 19:24
its Debian 12 testing. And i dual boot so i went back to windows therefor the error i sent is copied from my browser search history. 
I run dedicated graphics on this machine an amd rx7900xtx.
Im not sure about the gtk-sharp2 i will try to install again and re-post the actual output.
I tried installing the latest version. The .deb file the duplicati website suggested.

**Comment by awptechnologies** [comment] 2024-04-02 19:28
Version of Duplicati: duplicati_2.0.7.1-1_all.deb

Command i tried to install (on my system my user has alias to add sudo to any apt command): apt install ./duplicati_2.0.7.1-1_all.deb

Error When trying to install:

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'duplicati' instead of './duplicati_2.0.7.1-1_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 duplicati : Depends: libappindicator0.1-cil but it is not installable or
                      libappindicator3-0.1-cil but it is not installable or
                      libayatana-appindicator1 but it is not installable
             Depends: gtk-sharp2 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by awptechnologies** [comment] 2024-04-03 05:06
This is debian testing. 

In system properties it lists this as the os: Debian GNU/Linux trixie/sid

I will try to take a look at this when i boot back into linux. What are my next steps if its not already installed on system?

**Comment by awptechnologies** [comment] 2024-04-03 15:09
how do i install duplicati without the dependencies? i don't mind not having app tray.

**Comment by ts678** [comment] 2024-04-03 15:27
> how do i install duplicati without the dependencies?

You can try your own web search, but here's one idea:

[Make apt install ignore missing packages](https://unix.stackexchange.com/questions/722595/make-apt-install-ignore-missing-packages)

[https://manpages.debian.org/testing/apt/apt-get.8.en.html](https://manpages.debian.org/testing/apt/apt-get.8.en.html) is your apt-get man page.
I'm not sure I see `-m, --ignore-missing` on the apt man page, but maybe there's a way to add that on it also.

[How do I use apt *without* fixing unmet dependencies in unrelated packages?](https://askubuntu.com/questions/1426199/how-do-i-use-apt-without-fixing-unmet-dependencies-in-unrelated-packages) goes a different way, with warnings.

I am not a Debian expert. If you get nervous about harm, you can always install Duplicati from its `.zip` offering.

**Comment by awptechnologies** [comment] 2024-04-04 05:37
Im stuck i guess i just have to wait until project is updated with supported packages or until debian includes the missing packages. i have no idea how to build from source or install from zip.

**Comment by kenkendk** [comment] 2024-04-04 07:56
@awptechnologies

An easy installation with zip is essentially `apt install mono-complete`, then unzip the project and run:
```
mono Duplicati.CommandLine.exe
```
(Don't worry about the .exe part, it works on Linux as well)

As mentioned this will not give you the TrayIcon (`mono Duplicati.GUI.TrayIcon.exe`) as that requires a UI library that seems to have disappeared.

Instructions for installing Mono on Debian 10 are here:
https://www.mono-project.com/download/stable/#download-lin-debian

I think the mono project itself is getting stale, which is why we are switching to a non-Mono based build system.
 I hope to have a preliminary .deb package ready soon, that does not require mono or the other missing libraries.

**Comment by awptechnologies** [comment] 2024-04-09 03:10
i had to do mono Duplicati.Service.exe to get it to work. How do i automatically start this in the background on system startup

**Comment by awptechnologies** [comment] 2024-04-09 05:46
I used a bashscript to start the service Duplicati.Server.exe and ran that bash script with a systemd service. I unzipped all files into a folder Duplicati in /usr/lib and everything is working correctly other then the trayicon. Which i care nothing about.

**Comment by kenkendk** [comment] 2024-04-09 05:52
Thanks for reporting your solution!

The `systemd` service can be copied [from the source code](https://github.com/duplicati/duplicati/blob/master/Installer/debian/debian/duplicati.service) if you prefer not having a custom script.

I am also working on a [new debian package](https://forum.duplicati.com/t/early-preview-of-net8-based-packages-codename-debug-2-0-8-100/17693). It is in very early testing, but if you have time to test it, that would be great.

**Comment by awptechnologies** [comment] 2024-04-16 19:46
tell me how i would be more then happy duplicati has saved my life. for some reason windows doesn't support webdav by default in file explorer at least my setup. And duplicati does it no problem. Great for offsite backups to my house.

**Comment by ts678** [comment] 2024-04-16 22:17
> tell me how i would be more then happy

Assuming you mean testing, the provided link leads to the initial new Debian package. Watch forum, but its third release is:

[Early preview of .Net8 builds, codename `2.0.8.105`](https://forum.duplicati.com/t/early-preview-of-net8-builds-codename-2-0-8-105/17779)

and for some of us, it's come a long way (although it's still in early preview testing, so please be careful what you do with it).

**Comment by awptechnologies** [comment] 2024-04-17 07:38
Do i just need to stop my systemd service or do i need to remove all files as well? i unziped everything into a folder /usr/lib/Duplicati? is this for sure going to give me at least basic functionality before i undo everything?

**Comment by ts678** [comment] 2024-04-17 22:51
> i unziped everything into a folder /usr/lib/

You should ask your questions (and give feedback) in the forum if possible. I'd have thought you'd be testing the `.deb` file which was intended to be used on Debian systems without having to do odd things like install the systemd bits (not in /usr/lib) yourself.

> is this for sure going to give me at least basic functionality before i undo everything?

If you're concerned about it not working, then save what you did so you can put it back. Nobody else has likely tested your case, however the dependencies are fewer now, your missing ones are no longer dependencies (ask `apt` if you like), so it might install.

**Comment by ts678** [comment] 2024-04-18 14:29
A more conservative test (given that this is a very new very unproven debug version) is to start test with what you already set up, simply trying it out alongside the current installation. I updated the forum topic with my results. Basic backup and restore worked.

If you start Duplicati as you, it will have a different set of jobs, config in ~/.config/Duplicati, and of course won't have root powers. Should be enough there to give it a whirl, but I think the original goal was to see if the regular install method worked. There might be a problem getting the systemd unit file in the right place (see forum), but you already had to solve that for the current release.

**Comment by awptechnologies** [comment] 2024-04-23 14:45
So far testing seems to be working on debian sid. I have the task bar icon backups are working everything seems to be good. The only question i have is auto start. By default it did not automatically start so i just added it to my startup apps and everything seems to be good. Is this normal? Or should duplicati be set to start automatically by default?

**Comment by ts678** [comment] 2024-04-24 00:13
[Early preview of .Net8 builds, codename `2.0.8.105`](https://forum.duplicati.com/t/early-preview-of-net8-builds-codename-2-0-8-105/17779/10?u=ts678)

> On a different topic, I did a .deb. install, systemctl couldn’t find the unit file, and I’m trying to troubleshoot.

and the answer was to `systemctl enable duplicati` but I'm not certain what the current Beta release does.
Admittedly User Manual's [Installing Duplicati on Linux](https://docs.duplicati.com/en/latest/02-installation/#installing-duplicati-on-linux) does say `sudo systemctl enable duplicati.service`

**Comment by awptechnologies** [comment] 2024-04-27 18:14
seems like there is an issue with the toolbar icon in testing. The open pause and close options are not there i see the duplicati logo but when clicking it i can mouse over options but it doesnt show the actual names. Also sometimes when i click on open it opens but most of the time it does not. The main functionality seems to work. Backups work automatically just the icon issue.

**Comment by WeiMXi** [comment] 2024-04-30 03:05
I have same problem
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux trixie/sid
Release:	n/a
Codename:	trixie
```
```
$ sudo dpkg -i duplicati_2.0.7.1-1_all.deb
正在选中未选择的软件包 duplicati。
(正在读取数据库 ... 系统当前共安装有 321838 个文件和目录。)
准备解压 duplicati_2.0.7.1-1_all.deb  ...
正在解压 duplicati (2.0.7.1-1) ...
dpkg: 依赖关系问题使得 duplicati 的配置工作不能继续：
 duplicati 依赖于 libappindicator0.1-cil | libappindicator3-0.1-cil | libayatana-appindicator1；然而：
  未安装软件包 libappindicator0.1-cil。
  未安装软件包 libappindicator3-0.1-cil。
  未安装软件包 libayatana-appindicator1。
 duplicati 依赖于 gtk-sharp2；然而：
  未安装软件包 gtk-sharp2。

dpkg: 处理软件包 duplicati (--install)时出错：
 依赖关系问题 - 仍未被配置
正在处理用于 desktop-file-utils (0.27-1) 的触发器 ...
正在处理用于 mailcap (3.70+nmu1) 的触发器 ...
在处理时有错误发生：
 duplicati
 ```

**Comment by awptechnologies** [comment] 2024-05-12 16:09
Where do we find the updated dev versions as they are released?

**Comment by ts678** [comment] 2024-07-13 13:14
[Install fails on Ubuntu 24.04 LTS - unmet dependencies #5178](https://github.com/duplicati/duplicati/issues/5178#issuecomment-2141012912), which sounds very similar to this issue, made the report:

> Reporting successful install of v2.0.9.100_canary_2024-05-30 on Ubuntu 24.04 without any additional dependencies.

If anyone here would be willing to try, Canary [releases](https://github.com/duplicati/duplicati/releases) are out. Currently the latest one is [2.0.9.101_canary_2024-06-27](https://github.com/duplicati/duplicati/releases/tag/v2.0.9.101_canary_2024-06-27)

**Comment by kenkendk** [comment] 2024-08-13 11:48
I am closing this as the canary builds install fine on Debian 12: https://updates.duplicati.com/canary

**Closed by kenkendk** 2024-08-13 11:48 UTC
