### ISSUE TITLE
error message : "Value cannot be null. Parameter name: key"

### ISSUE THREAD

**Issue by arnauldb** [duplicati/duplicati#1923] opened 2016-09-06 16:19 UTC
hello,

thanks for duplicati...when I try to run duplicati 2.0.1.20_canary_2016-09-01 to back up to google drive, I have this error message "Value cannot be null. Parameter name: key" . It worked fine yesterday though...thks for any help.

---------------------------------------

### Version info

**Duplicati Version:2.0.1.20_canary
**Operating System:Ubuntu Mate

### Screenshots

![1](https://cloud.githubusercontent.com/assets/13196747/18281744/4fbd00ce-745e-11e6-8e43-4aea4d082ab1.png)

----------------------------------------

log

Sep 6, 2016 6:24 PM: Request for http://127.0.0.1:8200/api/v1/backup/7/log?pagesize=100 gave error
Sep 6, 2016 6:24 PM: Reporting error gave error
Sep 6, 2016 6:06 PM: Request for http://127.0.0.1:8200/api/v1/backup/7/log?pagesize=100 gave error
Sep 6, 2016 6:06 PM: Reporting error gave error
Sep 6, 2016 6:06 PM: Failed while executing "Backup" with id: 7
Sep 6, 2016 5:59 PM: Failed while executing "Backup" with id: 7
Sep 6, 2016 5:59 PM: Failed while executing "Backup" with id: 7
Sep 6, 2016 5:54 PM: Request for http://127.0.0.1:8200/api/v1/serverstate/?lasteventid=313&longpoll=true&duration=299s gave error
Sep 6, 2016 5:54 PM: Request for http://127.0.0.1:8200/api/v1/serverstate?longpoll=true&lasteventid=313&format=json&duration=5m gave error
Sep 6, 2016 5:54 PM: Reporting error gave error
Sep 6, 2016 5:54 PM: Request for http://127.0.0.1:8200/api/v1/notification/1 gave error
Sep 6, 2016 5:54 PM: Reporting error gave error
Sep 6, 2016 5:54 PM: Reporting error gave error
Sep 6, 2016 5:53 PM: Failed to import backup
Sep 6, 2016 5:51 PM: Failed while executing "Backup" with id: 6
Sep 6, 2016 5:51 PM: Request for http://127.0.0.1:8200/api/v1/backup/6/log?pagesize=100 gave error
Sep 6, 2016 5:51 PM: Reporting error gave error
Sep 6, 2016 5:50 PM: Request for http://127.0.0.1:8200/api/v1/backup/6/log?pagesize=100 gave error
Sep 6, 2016 5:50 PM: Reporting error gave error
Sep 6, 2016 5:50 PM: Failed while executing "Backup" with id: 6
Sep 6, 2016 5:47 PM: Failed while executing "Backup" with id: 5
Sep 6, 2016 5:47 PM: Failed while executing "Backup" with id: 5
Sep 6, 2016 5:46 PM: Failed while executing "Repair" with id: 5
Sep 6, 2016 5:46 PM: Request for http://127.0.0.1:8200/api/v1/backup/5/log?pagesize=100 gave error
Sep 6, 2016 5:46 PM: Reporting error gave error
Sep 6, 2016 5:46 PM: Failed while executing "Backup" with id: 5
Sep 6, 2016 5:45 PM: Request for http://127.0.0.1:8200/api/v1/backup/5/log?pagesize=100 gave error
Sep 6, 2016 5:45 PM: Reporting error gave error
Sep 6, 2016 5:45 PM: Failed while executing "Backup" with id: 5
Sep 6, 2016 5:31 PM: Failed while executing "Backup" with id: 4
Sep 6, 2016 5:24 PM: Failed while executing "Backup" with id: 4
Sep 6, 2016 5:24 PM: Error in worker
Sep 6, 2016 5:22 PM: Failed while executing "Backup" with id: 4
Sep 6, 2016 5:10 PM: Failed while executing "Backup" with id: 4
Sep 6, 2016 4:53 PM: Failed while executing "Backup" with id: 4
Sep 6, 2016 4:28 PM: Failed while executing "Backup" with id: 4
Sep 6, 2016 3:53 PM: Failed while executing "Backup" with id: 4
Sep 6, 2016 3:07 PM: Failed while executing "Backup" with id: 4
Sep 4, 2016 1:13 AM: Error in updater
Sep 4, 2016 1:13 AM: Error in updater
Sep 4, 2016 1:12 AM: Failed while executing "Backup" with id: 4

**Comment by arnauldb** [comment] 2016-09-06 16:41
update : 

If I unchecked the following, see screenshot below, it is working again...no more error message.
![selection_002](https://cloud.githubusercontent.com/assets/13196747/18282444/71af7060-7461-11e6-9ac7-0473c4ef0c7c.jpg)

**Comment by kenkendk** [comment] 2016-09-13 07:24
I think this is a duplicate of #1913

**Closed by kenkendk** 2016-09-13 07:24 UTC

**Comment by kenkendk** [comment] 2016-10-27 11:15
This should be fixed in 2.0.1.29:
https://github.com/duplicati/duplicati/releases
