### ISSUE TITLE
Unsupported compression module: zip

### ISSUE THREAD

**Issue by rdae** [duplicati/duplicati#2425] opened 2017-04-10 01:42 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.55_canary_2017-04-06
**Operating System:** Windows 8.1 Enterprise N
**Backend:** Amazon Drive

### Bug description
All my backups suddenly started to fail with "Unsupported compression module: zip" on run (nearly instantly).

### Steps to reproduce
- Run backup or wait for scheduled run.

**Actual result:** Error window with Show and Dismiss saying "Unsupported compression module: zip"
**Expected result:** Backup runs as normal.

### Screenshots
N/A

### debug log
**Apr 9, 2017 9:28 PM: Failed while executing "Backup" with id: 14**
```
Duplicati.Library.Interface.UserInformationException: Unsupported compression module: zip
   at Duplicati.Library.Main.Volumes.VolumeWriterBase..ctor(Options options, DateTime timestamp)
   at Duplicati.Library.Main.Volumes.FilesetVolumeWriter..ctor(Options options, DateTime timestamp)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

**Sample Backup Configuration**
```json
{
  "CreatedByVersion": "2.0.1.55",
  "Schedule": {
    "ID": 4,
    "Tags": [
      "ID=14"
    ],
    "Time": "2017-04-10T06:00:00Z",
    "Repeat": "1D",
    "LastRun": "2017-04-09T06:00:00Z",
    "Rule": "AllowedWeekDays=Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
    "AllowedDays": [
      "mon",
      "tue",
      "wed",
      "thu",
      "fri",
      "sat",
      "sun"
    ]
  },
  "Backup": {
    "ID": "14",
    "Name": "REDACTED",
    "Tags": [],
    "TargetURL": "REDACTED",
    "DBPath": "REDACTED\\REDACTED.sqlite",
    "Sources": [
      "REDACTED",
      "REDACTED",
      "REDACTED"
    ],
    "Settings": [
      {
        "Filter": "",
        "Name": "encryption-module",
        "Value": "gpg",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "compression-module",
        "Value": "zip",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "dblock-size",
        "Value": "375MB",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "keep-time",
        "Value": "12M",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "passphrase",
        "Value": "REDACTED",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--blocksize",
        "Value": "3MB",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--gpg-encryption-command",
        "Value": "--symmetric",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--gpg-encryption-switches",
        "Value": "--cipher-algo AES256",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--prefix",
        "Value": "REDACTED",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--tempdir",
        "Value": "Z:\\duplicati",
        "Argument": null
      }
    ],
    "Filters": [],
    "Metadata": {
      "LastDuration": "00:18:09.1348367",
      "LastStarted": "20170406T060000Z",
      "LastFinished": "20170406T061809Z",
      "LastBackupDate": "20170312T060000Z",
      "BackupListCount": "2",
      "TotalQuotaSpace": "0",
      "FreeQuotaSpace": "0",
      "AssignedQuotaSpace": "-1",
      "TargetFilesSize": "15542234029",
      "TargetFilesCount": "84",
      "TargetSizeString": "14.47 GB",
      "SourceFilesSize": "16542033161",
      "SourceFilesCount": "1529",
      "SourceSizeString": "15.41 GB",
      "LastBackupStarted": "20170406T060000Z",
      "LastBackupFinished": "20170406T061809Z",
      "LastErrorDate": "20170410T012844Z",
      "LastErrorMessage": "Unsupported compression module: zip"
    },
    "IsTemporary": false
  },
  "DisplayNames": {
    "REDACTED": "REDACTED",
    "REDACTED": "REDACTED",
    "REDACTED": "REDACTED"
  }
}
```

**Comment by MrCodeB** [comment] 2017-04-11 04:03
same here

**Comment by mmiat** [comment] 2017-04-11 08:14
me too after upgrade

**Comment by ReneHezser** [comment] 2017-04-12 10:37
I've got the same problem. Running on Windows 10

**Comment by kenkendk** [comment] 2017-04-13 12:45
I've tested on OSX and Linux without errors.
All reports here seems to mention Windows, so it could be something related to the updated zip library.

**Comment by rdae** [comment] 2017-04-19 04:24
A manual reinstall from the re-downloaded .exe seems to have fixed the issue (after repairing a few backups).

**Comment by MrCodeB** [comment] 2017-04-19 19:02
@rdae Thanks! That worked for me too. After reinstallation everything is fine :-)

**Comment by NitroTwiek** [comment] 2017-04-20 15:20
It looks like "SharpCompress.dll", which is present in the zip, is missing from the msi. I had been having this same issue on both Windows 7 and Windows 10 PCs that used the msi to install and after copying that missing dll from the zip file to the installation directory, backups proceed without error.

**Comment by kenkendk** [comment] 2017-04-21 09:29
@NitroTwiek That would explain it, thanks!

**Comment by kenkendk** [comment] 2017-04-21 09:42
The `SharpCompress.dll` is present in all zip and msi files. 

Also, if the problem occurs after the update this is strange as the update does not use the msi, but downloads the zip and puts it into the update directory.

Also, if the file is missing from the msi, re-installing should not work.

**Comment by NitroTwiek** [comment] 2017-04-21 10:32
@kenkendk In my specific case, I'm not using the built in updating agent, but the .msi through a couple different deployment methods. Also in my case, reinstalling with the .msi did not correct the issue. It was the absence/presence of `SharpCompress.dll` that cause/fixed the issue in all cases for me. It shouldn't make any difference, but all of my installations use the following switches during installation: `/quiet /qn /norestart`

**Comment by kenkendk** [comment] 2017-04-21 10:36
@NitroTwiek Any chance that `SharpCompress.dll` is flagged by antivirus and removed during installation?

Normally I use the `SharpCompress.dll`without modifications, but this time I had to include some fixes for creating zip files larger than 4GiB, so maybe that trips something that a known file is suddenly different (and has my signing key instead of the normal one).

**Comment by mmiat** [comment] 2017-04-21 11:54
i've re-installed Duplicati .55 from msi, and the checked from zip
the 2 SharpCompress.dll are different

**Comment by kenkendk** [comment] 2017-04-21 12:02
@mmiat I just checked, my extracted `SharpCompress.dll` files have md5 sum `3b3b0051027fd99681bad4aff7593ab6` for both MSI and zip.

**Comment by NitroTwiek** [comment] 2017-04-21 12:39
@kenkendk I can't rule it out for sure since all the workstations involved do have AV running, but I don't think `SharpCompress.dll` is being caught. It's not showing up in the quarantine logs in McAfee/VirusScan Enterprise (running on the Windows 7 PCs) or Windows Defender (running on the Windows 10 PCs).

I think I figured out why my particular installations were failing, and as usual, idiot user at fault. All of my installations were using the .msi in an unattended fashion, either through deployment scripts or chocolatey. Which means that duplicati was still **running** when the .msi package was executed on those workstations. I've just A/B tested both deployment methods on my Windows 7 and Windows 10 PCs and every time the .msi is executed while 2.0.1.53 or 2.0.1.54 is running, `SharpCompress.dll` fails to install, and every time duplicati is killed/shutdown before installing, `SharpCompress.dll` is present. The only thing that isn't explained is the instance or two in my earlier testing when installing the .msi on a workstation where duplicati had previously been removed.

@rdae @MrCodeB Were you using chocolatey or some other deployment for the msi? If so, is it possible duplicati was running when upgrading to 2.0.1.55?

@mmiat I'm also getting `3B3B0051027FD99681BAD4AFF7593AB6` for `SharpCompress.dll` for both the (successful) install using the msi and the zip

**Comment by rdae** [comment] 2017-04-22 01:11
@NitroTwiek Nope, simple .msi download and double-click... It may have been possible that Duplicati was running since trying to Download/Install from the popup saying asking to upgrade seems to never say "complete" although the version may bump. On the re-install I made sure that Duplicati was closed.

**Comment by cyann** [comment] 2017-05-10 11:14
Chocolatey users: quit Duplicati, and reinstall with:
```choco install duplicati --force```

**Comment by mabrahamsen** [comment] 2017-06-01 19:25
Hi, I get the same issue.

Someone asked for a fusion log. I get this during startup. (see below).

I am not using Azure storage, and no clue if this is the core problem and if the exception is just a bit off. But, it is worth noting that the SharpCompress assembly in the .61 package has version 0.0.0.0. I have multiple applications with SharpCompress, so perhaps I am getting the wrong version loaded.


*** Assembly Binder Log Entry  (6/1/2017 @ 9:17:40 PM) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Program Files\Duplicati 2\Duplicati.GUI.TrayIcon.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Data.Services.Client, Version=5.6.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files/Duplicati 2/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = Duplicati.GUI.TrayIcon.exe
Calling assembly : Microsoft.WindowsAzure.Storage, Version=7.2.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files\Duplicati 2\Duplicati.GUI.TrayIcon.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.Data.Services.Client, Version=5.6.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Program Files/Duplicati 2/Microsoft.Data.Services.Client.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Duplicati 2/Microsoft.Data.Services.Client/Microsoft.Data.Services.Client.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Duplicati 2/Microsoft.Data.Services.Client.EXE.
LOG: Attempting download of new URL file:///C:/Program Files/Duplicati 2/Microsoft.Data.Services.Client/Microsoft.Data.Services.Client.EXE.
LOG: All probing URLs attempted and failed.

**Comment by mabrahamsen** [comment] 2017-06-01 19:43
Hi all.

I downloaded the version of OData from Nuget, that used this dll and added the correct versions of:
Microsoft.Data.Services.Client.dll
Microsoft.Data.Edm.dll

And my client is working again.

These files were removed since the .53 setup.

**Comment by kenkendk** [comment] 2017-06-02 12:32
Very peculiar, but the file `Microsoft.Data.Edm.dll` is missing in build `2.0.1.60` but present in `2.0.1.59`.

I think this is somehow caused by the change from `xbuild` to `msbuild`:
https://github.com/duplicati/duplicati/commit/fc5b2097e1d45fbb376a00d38b47b17963b3b687

Missing these files should not cause problem loading the zip library, it should only affect the loading of the Azure backend.

It is possible that the version stamp `0.0.0.0` is causing some of the problems. The latest canary is back on the official SharpCompress.dll library, so that part is hopefully fixed.

**Comment by emaktech** [comment] 2017-06-02 17:18
I updated to the latest version through the Windows msi installer on the website (2.0.1.61 experimental) and this happened as well.

Windows 10 with no AV (only standard Defender).

Downloading the zip package, moving SharpCompress.dll into the install directory (it was missing) and restarting Duplicati worked fine.

**Comment by mabrahamsen** [comment] 2017-06-03 21:00
@kenkendk, I did a 2 second code review, and from what I can figure out is that any load exception during plugin load is squashed, and the load is aborted for additional plugins. This would be able to give you a zip is missing, even though the azure dll is the culprit.
Perhaps this works for some users, because the folder you do GetFiles on is sorted differently in some cases. Once again, a theory.
But, my conclusion is that I don’t find it completely unlikely that the plugin loader will fail on the missing azure dll, and then not be able to read the zip plugin and provide you with the mentioned exception.
On top of this, as you seem well aware, a version of 0.0.0.0 is not a good thing 😉

**Comment by kenkendk** [comment] 2017-06-03 21:06
@mabrahamsen I assume you are looking at this:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/DynamicLoader/DynamicLoader.cs#L105

The backend modules are loading in a different generic instance than the compression modules, so I cannot see how they interfere. Also, the try/catch should proceed with loading the libraries even if one library fails to load? Am I missing something?

**Comment by kenkendk** [comment] 2017-06-03 21:17
I updated the Windows Azure packages and that seems to have fixed the missing `OData` other libraries.

**Comment by mabrahamsen** [comment] 2017-06-03 22:12
@kenkendk, you are correct. In my initial review I misread it. It should indeed continue looping after a failure.

I am not at all familiar with this code, I just noticed it was looping over every dll in a set of folders looking for a specific interface. So, it didn't seem to care about whether it was a compression plugin during load. Once again, I am on thin ice with this codebase!

**Comment by kees-z** [comment] 2017-06-06 19:22
Same symptoms as @emaktech: fresh install (2.0.1.61) from msi package on Win10. Backup fails, SharpCompress.dll was not present. Extracted the dll from the msi package using 7Zip and restarted the Windows Service (installed Duplicati as a service, Duplicati runs in portable mode).
Gave it another try and everything is working fine. For me it seems that the installer 'forgets' to copy SharpCompress.dll to the installation folder.

**Comment by kenkendk** [comment] 2017-06-15 07:43
Has this problem shown up with the latest canary? It now has the latest Azure libraries and the official SharpCompress.dll ?

**Comment by jeffman78** [comment] 2017-06-16 06:44
I'm running on Win7 and same problem with a 2.0.1.61 from msi package. Backup fails. After copying SharpCompress.dll from the .zip package and restarted duplicati backup is working fine.

**Comment by l3d00m** [comment] 2017-06-22 12:05
2.0.1.61 on Windows 10, getting the error:

```
Fatal error
Duplicati.Library.Interface.UserInformationException: Unsupported compression module: zip
   at Duplicati.Library.Main.Volumes.VolumeWriterBase..ctor(Options options, DateTime timestamp)
   at Duplicati.Library.Main.Volumes.FilesetVolumeWriter..ctor(Options options, DateTime timestamp)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
```

**Comment by l3d00m** [comment] 2017-06-22 12:10
Just installed `2.0.1.67_canary_2017-06-21`, the problem does not occur there for me.

**Comment by kenkendk** [comment] 2017-06-28 20:59
Ok, I am thinking this is now fixed (still not sure what caused it, but it must be related to my custom SharpCompress build).

**Closed by kenkendk** 2017-06-28 20:59 UTC
Labels: bug
