### ISSUE TITLE
Centralized management

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#602] opened 2014-08-05 09:25 UTC
_From [archi...@gmail.com](https://code.google.com/u/100613989659193537529/) on April 04, 2012 05:31:01_

How are you using Duplicati now? backup systems to Google Docs and centralized sftp cluster How would you like it to work? Centralized management for multiple hosts (i.e. SMB office environment) Are there special considerations to this request? Windows and/or web interface Additional information: great v2 option!

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=602_
##

**Comment by rbeede** [comment] 2016-10-31 16:29
It would be useful to be able to distribute central managed backup jobs from a Duplicati server to endpoints.

1. Admin can run silent installer of Duplicati (via SCCM, GPO, etc.) that carries configuration that says:  On startup of endpoint system (and this Duplicati) connect to https://mycentralduplicati.example.com/REST/endpoint_checkin.do

2. Admin has central Duplicati job policy server where they define a global standard backup job or custom jobs for each endpoint (by endpoint hostname & id).

3.  Admin via central Duplicati server can see backup job histories for all endpoints.

4.  A backup job pushed from a central server should have a unique password created for each backup job on each endpoint or support using a GPG key belonging to the individual.

5.  A backup job pushed from a central server may need credentials for the corresponding backup destination (not necessarily the same as the Duplicati central server).   These credentials should be prompted from the user and stored only on the endpoint.   Example:  Global job for all endpoints is setup to backup every day to Google Drive.   Upon first run Duplicati prompts the user to associate their endpoint Duplicati to their AuthID (OAuth) for their Google Drive.

So the global backup job definition was pushed from the Duplicati central server but needs the endpoint user to fill-in some details.

**Comment by GeoffMaciolek** [comment] 2017-08-26 21:43
Hey - I think this is essentially a duplicate of #2411 - maybe one should be closed?

**Comment by Pectojin** [comment] 2018-02-09 14:46
@GeoffMaciolek, I agree. The other one has way more engagement and covers the same topic.

**Closed by Pectojin** 2018-02-09 14:46 UTC
Labels: enhancement, imported
