### ISSUE TITLE
send-mail has not worked since 2.0.1.17

### ISSUE THREAD

**Issue by RightOnTrack** [duplicati/duplicati#2060] opened 2016-10-28 12:58 UTC
I have:
- [X ] searched open and closed issues for duplicates
tried both pop and email server settings

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.29
**Operating System:**Win 10
**Backend:**Backblaze B2

### Bug description
send-mail is still not working. This has not worked since 2.0.1.17 You can refer to https://github.com/duplicati/duplicati/issues/1948 for more info.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### debug log

No "Failed to send email" is present in the live log

**Comment by agrajaghh** [comment] 2016-10-28 15:04
closing as duplicate of #1948

**Closed by agrajaghh** 2016-10-28 15:04 UTC
