### ISSUE TITLE
Editing scheduled runtime - not reflected in scheduled task list.

### ISSUE THREAD

**Issue by Upland** [duplicati/duplicati#2028] opened 2016-10-18 11:10 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.27  - _canary_2016-10-14
**Operating System:** Win 10
**Backend:**Ubuntu 16

### Bug description
Editing the Scheduled Run Time ... the time is not reflected in the "Next Scheduled Run" displayed.

It is saved as the new time - if the backup is edited again - the new time is there.

It does not run at the new time. 

(not sure you need any more info ... below)

### Steps to reproduce

Set a backup to be run daily at 14:00 ... 14:00 was displayed as next scheduled run.
Edited 14:00 to 13:30

**Actual result:**  Still displays 14:00 as next scheduled run time. Refreshed page - still did not change to 13:30

Did not run at 13:30

**Expected result:** 
Err .. should have displayed next scheduled run as being the new time ... ie 13:30 ... and should have run at 13:30.

**Comment by agrajaghh** [comment] 2016-10-18 12:26
closing as duplicate of #1935

**Closed by agrajaghh** 2016-10-18 12:26 UTC
