### ISSUE TITLE
Exclude sqlite db?

### ISSUE THREAD

**Issue by jvook** [duplicati/duplicati#1860] opened 2016-07-21 18:50 UTC
I run a backup including my duplicati db, which gives file acccess errors.  Should I be excluding this directory?  It seems like something I'd want to have backed up in case of a total loss, but it always gives error so maybe I'm not getting it anyway.

Should I be excluding %APPDATA%\Roaming\Duplicati\ ?

**Comment by huste** [comment] 2016-08-02 14:21
IMO, Duplicati should by itsel exclude files that it is using to manage backup. You can always restore the file database from a backup. The only thing you can't restore is the desciption of the backup job.  I always export my backup jobs to a text file and those can be backed up.

Or can you restore the backup job descriptions?

It would be a nice feature if duplicati had a single-click export all backup jobs UI.

**Comment by kenkendk** [comment] 2016-08-03 17:03
@jvook: Yes, you should exclude that folder.

@huste: I agree it should itself exclude that folder.

**Comment by huste** [comment] 2016-08-12 21:41
Duplicate of #1757.
This one should be closed.

**Closed** 2016-08-13 13:23 UTC
Labels: duplicate
