### ISSUE TITLE
After setting UI password I can't login

### ISSUE THREAD

**Issue by nickbe** [duplicati/duplicati#2202] opened 2016-12-27 01:43 UTC
I enter the password  - nothing happens....
what now? How do I recover or disable the UI password?

**Comment by agrajaghh** [comment] 2016-12-27 10:43
duplicate of #2186 #2200

**Closed by agrajaghh** 2016-12-27 10:43 UTC

**Comment by nickbe** [comment] 2016-12-27 14:11
Applied all fixes but I still can't login.

**Comment by kenkendk** [comment] 2016-12-27 15:03
I have added an updated version 2.0.1.38 now, that you can install to fix this issue.
You can either install via the installers:
https://github.com/duplicati/duplicati/releases/tag/v2.0.1.38-2.0.1.38_canary_2016-12-27

Or use the built-in updater.
If you need to access the user interface, you can either delete the 2.0.1.36 build from the Updates folder, and start with 2.0.1.35 or you can use the commandline option --webservice-password= to set a blank password.

**Comment by nickbe** [comment] 2016-12-28 03:11
Thanks. I've updated manually and login works again.
