### ISSUE TITLE
Error with Debian mono 5.18

### ISSUE THREAD

**Issue by achims311** [duplicati/duplicati#3620] opened 2019-01-22 21:36 UTC
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5-1
- **Operating system**: Debian unstable (mono 5.18)
- **Backend**: all/none

## Description

when starting duplicati it always generates a crash.
using the duplicati-server manually (not via systemd) I get the following stacktrace

## Steps to reproduce

1. update to latest debian mono packages (version 5.18)
2. duplicati-server --log-level=debug --log-file=/tmp/dupli

- **Actual result**:
Unable to start up, perhaps another process is already running?
Error message: System.InvalidOperationException: object_op ---> System.BadImageFormatException: Method has no body
  at System.IO.CoreFX.FileSystemWatcher.StartRaisingEvents () [0x00024] in <a9a08e39ba304bd0a84c49bd158dfc02>:0 
  at System.IO.CoreFX.FileSystemWatcher.StartRaisingEventsIfNotDisposed () [0x0001c] in <a9a08e39ba304bd0a84c49bd158dfc02>:0 
  at System.IO.CoreFX.FileSystemWatcher.set_EnableRaisingEvents (System.Boolean value) [0x0002a] in <a9a08e39ba304bd0a84c49bd158dfc02>:0 
  at (wrapper remoting-invoke-with-check) System.IO.CoreFX.FileSystemWatcher.set_EnableRaisingEvents(bool)
  at System.IO.CoreFXFileSystemWatcherProxy.<StartDispatching>m__0 (System.IO.CoreFX.FileSystemWatcher internal_fsw, System.IO.FileSystemWatcher fsw) [0x00048] in <a9a08e39ba304bd0a84c49bd158dfc02>:0 
  at System.IO.CoreFXFileSystemWatcherProxy.Operation (System.Action`4[T1,T2,T3,T4] map_op, System.Action`2[T1,T2] object_op, System.Object handle, System.Action`2[T1,T2] cancel_op) [0x001d3] in <a9a08e39ba304bd0a84c49bd158dfc02>:0 
   --- End of inner exception stack trace ---
  at System.IO.CoreFXFileSystemWatcherProxy.Operation (System.Action`4[T1,T2,T3,T4] map_op, System.Action`2[T1,T2] object_op, System.Object handle, System.Action`2[T1,T2] cancel_op) [0x001f8] in <a9a08e39ba304bd0a84c49bd158dfc02>:0 
  at System.IO.CoreFXFileSystemWatcherProxy.StartDispatching (System.Object handle) [0x00007] in <a9a08e39ba304bd0a84c49bd158dfc02>:0 
  at System.IO.FileSystemWatcher.Start () [0x00024] in <a9a08e39ba304bd0a84c49bd158dfc02>:0 
  at System.IO.FileSystemWatcher.set_EnableRaisingEvents (System.Boolean value) [0x00049] in <a9a08e39ba304bd0a84c49bd158dfc02>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileSystemWatcher.set_EnableRaisingEvents(bool)
  at Duplicati.Server.SingleInstance..ctor (System.String basefolder) [0x000ee] in <fe28905ee30b422e8d475f1cfdb85515>:0 
  at Duplicati.Server.Program.RealMain (System.String[] _args) [0x00307] in <fe28905ee30b422e8d475f1cfdb85515>:0 

- **Expected result**:
no stack trace..

## Debug log

log-file exists, but is empty

**Comment by Pectojin** [comment] 2019-01-23 00:11
Sounds like the same issue as #3572.

If you can downgrade to mono 5.16 that may fix your issue.

The Duplicati docker image is running Debian 8.11 with Mono 5.16.0.179, for reference.

**Comment by achims311** [comment] 2019-01-23 05:37
Yes you are right, the stracktrace is the same.
Interesting is thediff, for macOS not even 5.16 is working fine, but in debian it is.
Unfortunatly 5.16 never migrated to testing, and unstable only has 5.18 now, so switching back to 5.16 will be quite difficult(possible with the snapshops, but..)

**Comment by drwtsn32x** [comment] 2019-01-24 05:42
I've also been hit by this with Duplicati 2.0.4.5.

I run Debian testing and mono was recently upgraded to 5.18.0.240, along with three or four dozen related supporting packages.  I'm not even sure it's possible for me to go back to the version I had before.

Any ideas?

**Comment by drwtsn32x** [comment] 2019-01-24 15:32
Doesn't look like their repository has packages specifically for Debian testing (buster / 10).  I see Debian 9 (stretch) and some older ones.

**Comment by drwtsn32x** [comment] 2019-01-24 18:47
Ok I tested with Debian 9/stretch packages and it worked on Debian testing/10/buster.

**Comment by achims311** [comment] 2019-01-25 05:40
I "only" found these as vs-strech.
So which version did you really install (exact version number)?
something like "5.??.0.????-0xamarin4+debian9b1"

**Comment by achims311** [comment] 2019-01-28 21:42
Some thing did not work out yet with this set-up but I worked around it by "holding" certain packages.

But, now I've got he first debian software package which requires 5.18 to get installed.
Sure I could start building this package locally or find any other workaround, but still I think the bug is still open, this software does not work under the latest debian packages (5.18)

**Comment by drwtsn32x** [comment] 2019-01-28 23:32
Yeah you might have to Hold the 5.16 packages if you are trying to install something else that requires 5.18.  I'm guessing the "pinning" trick doesn't work in that case.  I am not in that situation so haven't run into it myself.

I think it's agreed here that Duplicati should be made compatible with 5.18.  Or maybe mono 5.18 behavior is actually a bug and will be fixed in a future version of Mono.

**Comment by achims311** [comment] 2019-01-29 05:35
Who could confirm on which side the issue is on mono or duplicati side?

**Comment by warwickmm** [comment] 2019-02-22 03:31
Possibly related:

https://github.com/mono/mono/issues/12557

**Comment by warwickmm** [comment] 2019-02-23 20:26
Supposedly this is fixed in the latest Debian packages.  Would someone running Debian be willing to upgrade and confirm that issue is resolved?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920531

**Comment by mathbr** [comment] 2019-02-23 21:17
Yes, I can confirm that Duplicati works fine again on Debian with mono packages in version 5.18.0.240+dfsg-2.

**Comment by warwickmm** [comment] 2019-02-23 21:19
Thanks @mathbr.  I'm going to go ahead and close this as it's an issue with Debian that has since been resolved.

**Closed by warwickmm** 2019-02-23 21:19 UTC
Labels: mono

**Comment by achims311** [comment] 2019-02-23 23:32
Thanks, works as well for me.

From the changelog I assume it was this issue:
* [fcb8084] Add missing libmono-system-native (Closes: [#920531](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920531))
