### ISSUE TITLE
Backup (or exclude) Files with only .dot Extention

### ISSUE THREAD

**Issue by Photographix** [duplicati/duplicati#3839] opened 2019-07-29 08:07 UTC
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.4.22
- **Operating system**: Windows Server 2019
- **Backend**: Jotta

## Description
Backup or omit files that have **only** one dot (.) extension -> MyFile.

## Steps to reproduce
1. create a file with only one point as extention
2. try a backup of this file

- **Actual result**:
System.IO.FileNotFoundException
- **Expected result**:
Backup from file 
or or the possibility to skip them via filter

## Screenshots
![2019-07-29 09_15_20-Window](https://user-images.githubusercontent.com/16647382/62029609-5bf53580-b1e3-11e9-8e8b-677ea09199cc.png)

## Debug log
`2019-07-29 01:45:39 +02 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: Die Operation Backup wurde gestartet
2019-07-29 01:54:01 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  ()
2019-07-29 01:54:05 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (13,45 KB)
2019-07-29 02:28:09 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-FileAccessError]: Error reported while accessing file: \\aio-pod\Anika\BKP-WhatsApp\Media\WhatsApp Documents\Sent\DOC-20180611-WA0009.
System.IO.FileNotFoundException: Die Datei "\\aio-pod\Anika\BKP-WhatsApp\Media\WhatsApp Documents\Sent\DOC-20180611-WA0009" konnte nicht gefunden werden.
Dateiname: "\\aio-pod\Anika\BKP-WhatsApp\Media\WhatsApp Documents\Sent\DOC-20180611-WA0009"
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.GetAttributes(String path)
   bei Duplicati.Library.Common.IO.SystemIOWindows.PathTooLongFuncWrapper[T](Func`2 nativeIOFunc, Func`2 alternativeIOFunc, String path, Boolean prefixWithUnc)
   bei Duplicati.Library.Utility.Utility.<EnumerateFileSystemEntries>d__20.MoveNext()
2019-07-29 02:28:09 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-FileAccessError]: Error reported while accessing file: \\aio-pod\Anika\BKP-WhatsApp\Media\WhatsApp Audio\Sent\AUD-20170926-WA0018.
System.IO.FileNotFoundException: Die Datei "\\aio-pod\Anika\BKP-WhatsApp\Media\WhatsApp Audio\Sent\AUD-20170926-WA0018" konnte nicht gefunden werden.
Dateiname: "\\aio-pod\Anika\BKP-WhatsApp\Media\WhatsApp Audio\Sent\AUD-20170926-WA0018"
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.GetAttributes(String path)
   bei Duplicati.Library.Common.IO.SystemIOWindows.PathTooLongFuncWrapper[T](Func`2 nativeIOFunc, Func`2 alternativeIOFunc, String path, Boolean prefixWithUnc)
   bei Duplicati.Library.Utility.Utility.<EnumerateFileSystemEntries>d__20.MoveNext()
2019-07-29 02:28:09 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-FileAccessError]: Error reported while accessing file: \\aio-pod\Anika\BKP-WhatsApp\Media\WhatsApp Audio\Sent\AUD-20171015-WA0044.
System.IO.FileNotFoundException: Die Datei "\\aio-pod\Anika\BKP-WhatsApp\Media\WhatsApp Audio\Sent\AUD-20171015-WA0044" konnte nicht gefunden werden.
Dateiname: "\\aio-pod\Anika\BKP-WhatsApp\Media\WhatsApp Audio\Sent\AUD-20171015-WA0044"
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.GetAttributes(String path)
   bei Duplicati.Library.Common.IO.SystemIOWindows.PathTooLongFuncWrapper[T](Func`2 nativeIOFunc, Func`2 alternativeIOFunc, String path, Boolean prefixWithUnc)
   bei Duplicati.Library.Utility.Utility.<EnumerateFileSystemEntries>d__20.MoveNext() .... and following`

**Comment by BlueBlock** [comment] 2019-07-29 20:37
I can reproduce this issue.

It is not easy to create Windows file with just a dot(.) but it can be done:

**Comment by BlueBlock** [comment] 2019-07-29 20:51
I can reproduce this issue.

It is not easy to create Windows file with just a dot(.) but it can be done:
dir>"\\?\C:\temp\test."

The problem seems to be that Windows doesn't natively handle files ending in a dot. I also tried AlphaFS and got the same exception. GetAttributes() is stripping the ending period.

The period is stripped with and without UNC prefixed.

My test file is "1.bc."

I added an empty catch() to let the alternative method to get tested. you can see the dot gets stripped.

<img width="1218" alt="Capture" src="https://user-images.githubusercontent.com/476010/62081611-00499d00-b221-11e9-9851-ba9e27147a68.PNG">

**Comment by warwickmm** [comment] 2019-07-30 03:59
Is this an invalid filename in Windows?  From https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions:

> Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".

**Comment by warwickmm** [comment] 2019-07-30 04:02
Similar issue reported [here](https://github.com/duplicati/duplicati/issues/3642).

**Comment by Photographix** [comment] 2019-07-30 04:09
Thank you for reproducing it. The file is on a SMB server. But it's really a bug in the file extension of another application. I already tried to exclude the dot extension but failed.

**Comment by BlueBlock** [comment] 2019-07-30 08:02
The underlying issue is that file enumeration is finding the file but other IO methods cannot handle the filename.

This is an issue on all .net frame works 4.6.1 and earlier.

I tested GetAttributes() in .net core and .net 4.6.2 and they handle the ending period fine.

The .net 4.6.2 framework made a good number of changes. 

I'm hoping we'll be moving ahead to the 4.6.2 framework and this issue will be resolved.

p.s. @warwickmm  One unrelated change for .net 4.6.2 is that handling of long paths (256+) is now on by default and handled well. This might mean AlphaFS would no longer be needed at that point.

**Comment by warwickmm** [comment] 2019-07-31 02:23
That would be great.  I'm not sure if AlphaFS is providing any other functionality for us, but it would be nice to remove unnecessary dependencies.

**Comment by BlueBlock** [comment] 2019-07-31 02:38
> That would be great. I'm not sure if AlphaFS is providing any other functionality for us, but it would be nice to remove unnecessary dependencies.

We'll have to review if AlphaFS is getting us anything but it only seems to be there for when paths are too long.

**Comment by ts678** [comment] 2019-07-31 13:46
Regarding AlphaFS, it'd be good to see if AlphaVSS can run without that. If not, how do we get VSS?

Regarding pathname oddities:

[File path formats on Windows systems](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#trimming-characters) talks about trailing periods (usually trimmed off) and spaces.

I only had that page open because I was looking at [Cannot see UNC paths on the restore screen](https://forum.duplicati.com/t/cannot-see-unc-paths-on-the-restore-screen/7624/8?u=ts678), and trying to see if I could come up with a simpler local test case by using \\\\?\\ (then I also discovered \\\\.\\) but AlphaFS was blocking at least one of those (suggested by the error message being in its source).

**Comment by BlueBlock** [comment] 2019-07-31 15:32
> Regarding AlphaFS, it'd be good to see if AlphaVSS can run without that. If not, how do we get VSS?
> 
> Regarding pathname oddities:
> 
> [File path formats on Windows systems](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#trimming-characters) talks about trailing periods (usually trimmed off) and spaces.
> 
> I only had that page open because I was looking at [Cannot see UNC paths on the restore screen](https://forum.duplicati.com/t/cannot-see-unc-paths-on-the-restore-screen/7624/8?u=ts678), and trying to see if I could come up with a simpler local test case by using \\?\ (then I also discovered \\.\) but AlphaFS was blocking at least one of those (suggested by the error message being in its source).

So this is my understanding for the paths.. pre-4.6.2 in order to work with long paths you pre-pend \\?\ to the path. So with 4.6.2 this convention may not be needed any longer.. need to test it.

If AlphaVSS requires AlphaFS that would be ok. It's more so we can remove all the alternate function logic from the Windows IO class so long as System.IO is sufficient for everything.. need to investigate it further on what other value AlphaFS might be adding.

**Comment by BlueBlock** [comment] 2019-07-31 19:39
Just moving to .net 4.6.2 isn't going to resolve this issue. File.Exists() fails with the ending period.

**Closed** 2020-07-26 00:48 UTC
Labels: windows
