### ISSUE TITLE
does not work in the restoration of the original folder

### ISSUE THREAD

**Issue by gromka** [duplicati/duplicati#1755] opened 2016-05-08 20:24 UTC
Hello team!
It does not work in the restoration of the original folder (i use hubic), but when you select a destination folder (i select original folder path and check pick location radio button), the file is recovered without any problems.

[bugreport.zip](https://github.com/duplicati/duplicati/files/254093/bugreport.zip)

**Comment by bensoibj** [comment] 2016-05-10 08:33
Already reported in #1624 "can't restore to original location".

**Comment by kenkendk** [comment] 2016-05-18 22:18
Yes, duplicate of #1624 which is now fixed.

**Closed by kenkendk** 2016-05-18 22:18 UTC
