### ISSUE TITLE
Python2.7 Cannot find the specified file

### ISSUE THREAD

**Issue by wheelq** [duplicati/duplicati#4698] opened 2022-03-27 12:03 UTC
After latest OS update Duplicati no longer starts.
I am using pyenv, with python 2.7, but the duplicati binary file expects python 2.7 to be in /usr/bin/python2.7, which is no longer part of OS environment

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.6.3_beta
- **Operating system**: OS Monterey 12.3 (21E230)
- **pyenv**: pyenv 2.2.5

## Description
```
cd /Applications/Duplicati.app/Contents/MacOS
./duplicati
Unexpected error: System.ComponentModel.Win32Exception (0x80004005): ApplicationName='/usr/bin/python2.7', CommandLine='"/Applications/Duplicati.app/Contents/Resources/OSXTrayHost/osx-trayicon-rumps.py"', CurrentDirectory='', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x0029f] in <832126c1e4b54a95ae8a221a8efc5bdd>:0
  at System.Diagnostics.Process.Start () [0x0003a] in <832126c1e4b54a95ae8a221a8efc5bdd>:0
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001b] in <832126c1e4b54a95ae8a221a8efc5bdd>:0
  at Duplicati.GUI.TrayIcon.RumpsRunner.Restart () [0x0005c] in <6e36e7ed2eef42d9b373fa3f5cb969f7>:0
  at Duplicati.GUI.TrayIcon.RumpsRunner.Init (System.String[] args) [0x0000c] in <6e36e7ed2eef42d9b373fa3f5cb969f7>:0
  at Duplicati.GUI.TrayIcon.Program.StartTray (System.String[] _args, System.Collections.Generic.Dictionary`2[TKey,TValue] options, System.String toolkit, Duplicati.GUI.TrayIcon.HostedInstanceKeeper hosted, System.String password, System.Boolean saltedpassword) [0x000eb] in <6e36e7ed2eef42d9b373fa3f5cb969f7>:0
```
## Steps to reproduce
```
cd /Applications/Duplicati.app/Contents/MacOS
./duplicati
```

- **Actual result**:
```
Unexpected error: System.ComponentModel.Win32Exception (0x80004005): ApplicationName='/usr/bin/python2.7', CommandLine='"/Applications/Duplicati.app/Contents/Resources/OSXTrayHost/osx-trayicon-rumps.py"', CurrentDirectory='', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x0029f] in <832126c1e4b54a95ae8a221a8efc5bdd>:0
  at System.Diagnostics.Process.Start () [0x0003a] in <832126c1e4b54a95ae8a221a8efc5bdd>:0
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001b] in <832126c1e4b54a95ae8a221a8efc5bdd>:0
  at Duplicati.GUI.TrayIcon.RumpsRunner.Restart () [0x0005c] in <6e36e7ed2eef42d9b373fa3f5cb969f7>:0
  at Duplicati.GUI.TrayIcon.RumpsRunner.Init (System.String[] args) [0x0000c] in <6e36e7ed2eef42d9b373fa3f5cb969f7>:0
  at Duplicati.GUI.TrayIcon.Program.StartTray (System.String[] _args, System.Collections.Generic.Dictionary`2[TKey,TValue] options, System.String toolkit, Duplicati.GUI.TrayIcon.HostedInstanceKeeper hosted, System.String password, System.Boolean saltedpassword) [0x000eb] in <6e36e7ed2eef42d9b373fa3f5cb969f7>:0
```

**Comment by warwickmm** [comment] 2022-03-27 18:12
Can you try setting the environment variable `RUMPS_PYTHON` to be the path to your python 2.7 executable?

This is a duplicate of issue #4668, so please join the discussion there.

**Closed by warwickmm** 2022-03-27 18:12 UTC
Labels: duplicate, MacOS
