### ISSUE TITLE
Google Drive Path - Failed to connect

### ISSUE THREAD

**Issue by WonderingDane** [duplicati/duplicati#4271] opened 2020-07-28 21:02 UTC
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Ubuntu 18.04 (Docker Container)
- **Backend**: Google Drive

## Description

I am trying to backup to Google Drive, which actually work just fine, if I leave "Path on server" blank and let Duplicati use the root of my Google Drive.

If I put in a path, I will get the error: "Failed to connect:".

I've tried using "/Backups", "Backups" and a folder name that doesn't exist "Duplicati". I've tried with small letters.

## Steps to reproduce

1. Choose Google Drive as storage type
2. Insert a path. Get error.
3. Leave it blank and no error.

**Comment by warwickmm** [comment] 2020-08-01 20:46
Is your AuthID correct? When you enter a path that doesn't exist, it should ask if you want to create the folder:

![image](https://user-images.githubusercontent.com/17345532/89110203-3c4bab00-d3fd-11ea-87e9-4568dea93100.png)

**Comment by WonderingDane** [comment] 2020-08-01 20:48
It doesn't ask me if I want to create a folder if I put in a path.
If I do not put in a path, it works and it puts the backup files in the root of my Google drive.

**Comment by warwickmm** [comment] 2020-08-01 20:53
Which Docker container and what browser are you using?  Can you try it with a new AuthID?

**Comment by WonderingDane** [comment] 2020-08-01 20:57
I'm using https://hub.docker.com/r/linuxserver/duplicati and Chrome.

I just tried using Firefox and creating a new AuthID. No luck, except the error message is a bit longer now "Failed to connect: _Internal Server Error_".

**Comment by warwickmm** [comment] 2020-08-01 21:00
I'm unable to reproduce this.  If you log into Google Drive directly, do you have permissions to create a folder?

**Comment by warwickmm** [comment] 2020-08-01 21:01
Are you willing to try the official docker here?

https://hub.docker.com/r/duplicati/duplicati

**Comment by WonderingDane** [comment] 2020-08-01 21:32
The documentation for the official container is extremely vague...

I get the error "The host header sent by the client is not allowed", which I guess is because by default, it doesn't allow remote access. I tried using webservice-interface=* and webservice-allowed-hostnames=*. Doesn't work.

**Docker-compose**
>   duplicati:
    image: duplicati/duplicati
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - webservice-interface=*
      - webservice-allowed-hostnames=*
    volumes:
        - ${USERDIR}/docker/duplicati:/data
        - ${USERDIR}/media:/source
    restart: unless-stopped
    networks:
      - traefik_proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=backup"
      - "traefik.frontend.rule=Host:backup.${DOMAINNAME}"
      - "traefik.port=8200"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=northdroid.dk"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

**Comment by warwickmm** [comment] 2020-08-01 21:38
I don't use the Docker image, so I'm not very familiar with the configuration.  @drwtsn32x, have you encountered any issues like this?

**Comment by drwtsn32x** [comment] 2020-08-01 22:21
@WonderingDane go to the container using an IP address instead of hostname. Once you get there you can go to Settings and type in hostnames that you want to allow.  This is what I did with the official docker container.

**Comment by warwickmm** [comment] 2020-08-09 19:04
@WonderingDane, you might have better luck posting this in the forums to see if anyone else has encountered this issue.

https://forum.duplicati.com/

Since we can't reproduce this, I'm going to close this.  Feel free to provide a link here to the forum post.  If we find that there's an improvement that we can make to the code, we can reopen this issue.

**Closed by warwickmm** 2020-08-09 19:04 UTC

**Comment by Ryonez** [comment] 2021-03-05 02:17
I've just come across this issue, exact same problem.
@warwickmm

**Comment by warwickmm** [comment] 2021-03-05 16:29
@Ryonez, my recommmendation would be to:
1. Search the [forums](https://forum.duplicati.com/) for possible related issues/solutions.
2. Create a new forum post with steps to reproduce the error, and include as much detail as you can about your setup (OS, version of duplicati, etc.) and the error message.
3. If we determine that there are code changes that need to be made, we can then create a new GitHub issue here.
