### ISSUE TITLE
Edited configurations not saved

### ISSUE THREAD

**Issue by 13am** [duplicati/duplicati#2900] opened 2017-11-18 08:25 UTC
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: duplicati-2.0.2.1-2.0.2.1_beta_20170801.noarch
- **Operating system**: Fedora 27
- **Backend**:Local folder

## Description

When I edit a configuration, I cannot save the changes.

## Steps to reproduce

1. Create a new configuration.
2. Save.
3. Add a new file to sources to be backed up.
4. Click on the 'save' button.

- **Actual result**:
Nothing happens, changes not saved.
- **Expected result**:
Changes to be saved and the new file to be included in the sources to be backed up.

**Comment by 13am** [comment] 2017-11-18 08:26
Tried both Firefox and Chrome to access the UI with the same results.

**Comment by silversword411** [comment] 2017-11-20 16:54
I think this is a duplicate of: https://github.com/duplicati/duplicati/issues/2019

**Comment by 13am** [comment] 2017-11-21 09:13
Looks like it is. It's unclear to me whether this is related to the html UI or to the backup system itself?

**Comment by silversword411** [comment] 2017-11-21 16:56
Happy to troubleshoot/debug if you have some suggestions/directions

**Comment by kenkendk** [comment] 2017-11-22 10:33
Can one of you enable the "Developer console" in the browser and see if there is an error happening when saving?

**Comment by 13am** [comment] 2017-11-22 19:20
Clicking the save button results in this error coming to the console:

```
angular.js:12330 TypeError: Cannot read property 'Key' of undefined
    at n.builduri (backupEditUri.js:23)
    at checkForValidBackupDestination (EditBackupController.js:363)
    at EditBackupController.js:437
    at checkForChangedPassphrase (EditBackupController.js:357)
    at n.$scope.save (EditBackupController.js:436)
    at fn (eval at compile (angular.js:13145), <anonymous>:4:203)
    at f (angular.js:23298)
    at n.$eval (angular.js:15846)
    at n.$apply (angular.js:15945)
    at HTMLInputElement.<anonymous> (angular.js:23303)
    at HTMLInputElement.dispatch (jquery.min.js:3)
    at HTMLInputElement.r.handle (jquery.min.js:3)
```
I'm happy to provide any additional info you might need.

**Comment by 13am** [comment] 2017-11-22 19:22
I see "checkForChangedPassphrase" in there. I do have encryption on but did not change the passphrase, just added a single file to the sources.

**Comment by warwickmm** [comment] 2018-11-25 04:40
I'm unable to reproduce this in version v2.0.4.4-2.0.4.4_canary_2018-11-14.  I was able to:
1. Create a backup of a single file.  The backup runs successfully.
2. Add another file to the backup.  The backup runs successfully.
3. Add a folder to the backup.  The backup runs successfully.

Is anyone still experiencing this?

**Comment by warwickmm** [comment] 2018-12-01 17:53
I'm assuming this has been fixed, since I can't reproduce it.  If someone finds that the problem still persists, please re-open this issue.

**Closed by warwickmm** 2018-12-01 17:53 UTC
Labels: bug

**Comment by mathbr** [comment] 2019-09-16 13:28
Yes, I am seeing this issue right now. Due do this I am unable to add a source path to an existing backup config:

```
angular.js:12330 TypeError: Cannot read property 'Key' of undefined
    at n.builduri (backupEditUri.js:23)
    at checkForValidBackupDestination (EditBackupController.js:391)
    at EditBackupController.js:465
    at checkForChangedPassphrase (EditBackupController.js:385)
    at n.$scope.save (EditBackupController.js:464)
    at fn (eval at compile (angular.js:13145), <anonymous>:4:203)
    at f (angular.js:23298)
    at n.$eval (angular.js:15846)
    at n.$apply (angular.js:15945)
    at HTMLInputElement.<anonymous> (angular.js:23303)
```

I am using version `2.0.4.23_beta_2019-07-14`.

**Comment by mathbr** [comment] 2019-09-16 13:31
Apparently this is the same issue as #2982 as I was able to get it working by clearing the browser cache for Duplicati.
