### ISSUE TITLE
Gamer friendly mode ?

### ISSUE THREAD

**Issue by Slider-Override** [duplicati/duplicati#2625] opened 2017-08-04 07:42 UTC
<Hi,
First, i run Duplicati on a special Server in my LAN, ^_^
Is it possible to get a feature for gamers :-), if the job is running the Internet Line is total overload?
If I set a limit like just 10Mbit of my 20Mbit upload, it's still the same, Online gaming is not possible
Not sure how duplicati handle the upload process, but it looks there are thousands of upload connections.
It will be nice if we can set a limit on this as well, to have for example not 100x 2KB/s more like 2x 100kb/s.
I think this will not kill the line so much, the bandwidth limit works, but it limits not the connections.

Another request is is it possible to add a scheduled time for the bandwidth limit, like overnight no limit of the line and on day time enable the limit > 

----------------------------------------

### Version info

**Duplicati Version: duplicati-2.0.2.1_beta_2017-08-01
**Operating System: Windows Server 2016 
**Backend: Google Drive

### Steps to reproduce
- Start a Job

**Comment by kenkendk** [comment] 2017-08-06 15:54
If you want a "10MBit" upload, you need to set the throttle to `10/8 = 1,25 MByte/s` or `1280 KByte/s` to be exact (1 byte = 8 bits).

There should only be a single upload connection, if you see more connections, this is an error.

**Comment by Slider-Override** [comment] 2017-08-06 16:05
I know I can throttle it to 10 Mbit, but Problem on this is it works, speed
is just 10Mbit, but all games get very bad connection at this moment, it's
not that it gets a high ping, but it feels like a delay of 2 secs. So I
think there are many many connections to like Google drive, and this makes
the issue, not the bandwidth.

Is there a way to limit the connections as well ?



Am 06.08.2017 17:54 schrieb "Kenneth Skovhede" <notifications@github.com>:

If you want a "10MBit" upload, you need to set the throttle to 10/8 = 1,25
MByte/s or 1280 KByte/s to be exact (1 byte = 8 bits).

There should only be a single upload connection, if you see more
connections, this is an error.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/duplicati/duplicati/issues/2625#issuecomment-320515248>,
or mute the thread

**Comment by kenkendk** [comment] 2017-08-07 08:21
The transfer to Google is using a single connection, so I am not sure what else can be done.
If you see multiple connections, that is an error.

**Comment by masgo** [comment] 2017-08-10 09:06
This sounds like the problem is your home router in combination with poor programmed games (which is true for the network code of most of today's games).

It could be that your router gives UDP traffic a lower priority than TCP traffic. This is in general a good ideal for office environments and many router do this in their default setting. BUT many games use UDP connections while duplicati uses mostly TCP connections.

Also if your game and duplicati both use TCP, depending on the implementation (which is determined by the operating system) you might see different behaviors for concurrent flows. 

It is also a common misconception that you can fully utilize the bandwidth of your connection. If you do only one (or a few) steady streams of data, you might achieve nearly 100% of your bandwidth, but if have multiple connections which produce burst loads (both the case for duplicati and most games) then utilizing even 50% of your bandwidth might be difficult. So you need to set an even greater limit.

If your router allows to prioritize traffic, then go ahead and give the server traffic a very low priority and the game traffic a very high priority. This might help. 


You could also use a run-before-required script in duplicati which could check (for example) if your gaming pc is turned on and if it is duplicati would not run. Or something similar.

**Comment by warwickmm** [comment] 2020-10-18 17:56
Closing this since I don't think there's anything for us to do here.

**Closed by warwickmm** 2020-10-18 17:56 UTC
Labels: documentation
