### ISSUE TITLE
HELP!!! constantly error checking the code phrase

### ISSUE THREAD

**Issue by rdbox** [duplicati/duplicati#3721] opened 2019-04-07 21:08 UTC
I have a disaster. Your system broke all my backups are constantly failing.

Failed to decrypt data (invalid code phrase?): Message has been altered, do not trust content

**I trust very important and valuable data to your backup program, and they make traps I can not take more data.
My password is 100% correct**

I can't do anything now what is it ??? everything was fine and suddenly something happened.
What with you developers ???? I'm in panic

**Comment by warwickmm** [comment] 2020-08-16 04:18
Closing this since it's no longer reproducible.  The "Failed to decrypt data (invalid code phrase?): Message has been altered, do not trust content" error can occur when the backend files become corrupted, or due to an old bug in Duplicati's throttling option that has now been fixed.

If this is still an issue, feel free to reopen and provide logs and steps to reproduce the problem.

**Closed by warwickmm** 2020-08-16 04:18 UTC
