### ISSUE TITLE
Amazon Cloud Drive PUT fails and memory use grows until Duplicati process is OOM killed

### ISSUE THREAD

**Issue by ElRico** [duplicati/duplicati#2432] opened 2017-04-13 22:11 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.53_experimental_2017-03-13
**Operating System:** QNAP firmware 4.2.4 Build 20170313
**Mono:** QMono 4.6.2.7
**Backend:** Amazon Cloud Drive

### Bug description
When I run a backup on my NAS with blocksize 100MB and dblock-size 1GB, after a few minutes Duplicati will throw the errors in the debug log section below. At the same time, memory use of the process starts to grow rapidly, until RAM and swap are full and the process is OOM killed. My NAS has 1GB RAM and 500MB swap space. This is possibly related to #2320.

### Steps to reproduce
- Configure a backup with blocksize 100M and dblock-size 1G
- Start the backup
- Wait a few minutes

**Actual result:** The Duplicati process is terminated by the OOM killer and the backup fails.
**Expected result:** The backup completes successfully.

### debug log
I grabbed these logs from the live logs section of the webinterface, using the profiling setting. When the process was killed, I didn't have access to the logs anymore. That is why they are incomplete. These messages repeat a few times.

```
Apr 13, 2017 11:44 PM: Backend event: Put - Started: duplicati-ba83268943ebb4a4dbfa7a16b03a2d2bb.dblock.zip.aes (965.31 MB)
Apr 13, 2017 11:44 PM: Starting - RemoteOperationPut
Apr 13, 2017 11:43 PM: Renaming "duplicati-b0cfa9416453d4a8e8de143e11060abc3.dblock.zip.aes" to "duplicati-ba83268943ebb4a4dbfa7a16b03a2d2bb.dblock.zip.aes"
Apr 13, 2017 11:43 PM: Backend event: Put - Rename: duplicati-ba83268943ebb4a4dbfa7a16b03a2d2bb.dblock.zip.aes (965.31 MB)
Apr 13, 2017 11:43 PM: Backend event: Put - Rename: duplicati-b0cfa9416453d4a8e8de143e11060abc3.dblock.zip.aes (965.31 MB)
Apr 13, 2017 11:43 PM: Backend event: Put - Retrying: duplicati-b0cfa9416453d4a8e8de143e11060abc3.dblock.zip.aes (965.31 MB)
Apr 13, 2017 11:43 PM: Operation Put with file duplicati-b0cfa9416453d4a8e8de143e11060abc3.dblock.zip.aes attempt 3 of 5 failed with message: Request was cancelled.
{"ClassName":"System.Net.WebException","Message":"Request was cancelled.","Data":null,"InnerException":{"ClassName":"System.IO.IOException","Message":"Cannot close the stream until all bytes are written","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":null,"RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146232800,"Source":null},"HelpURL":null,"StackTraceString":"  at System.Net.WebConnectionStream.Close () [0x00183] in <bd46d4d4f7964dfa9beea098499ab597>:0 \n  at System.IO.Stream.Dispose () [0x00000] in <a8460a77e67a430a8486a9751162e5f4>:0 \n  at Duplicati.Library.JSONWebHelper.PostMultipart (System.String url, System.Action`1[T] setup, Duplicati.Library.MultipartItem[] parts) [0x00188] in <12df122f04f04e1e978b6a375232e42b>:0 \n  at Duplicati.Library.JSONWebHelper.PostMultipartAndGetJSONData[T] (System.String url, System.Action`1[T] setup, Duplicati.Library.MultipartItem[] parts) [0x00000] in <12df122f04f04e1e978b6a375232e42b>:0 \n  at Duplicati.Library.Backend.AmazonCloudDrive.AmzCD.Put (System.String remotename, System.IO.Stream stream) [0x000e9] in <66cde89d638e4535b17f88d44474e11a>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233079,"Source":"System"}
```

**Comment by kenkendk** [comment] 2017-04-19 07:49
Closing as duplicate of #2320

**Closed by kenkendk** 2017-04-19 07:49 UTC
