### ISSUE TITLE
Amazon Cloud Drive: Error 429, "Too Many Requests"

### ISSUE THREAD

**Issue by ItEndsWithTens** [duplicati/duplicati#2129] opened 2016-11-17 01:24 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.30
**Operating System:** Windows 10 64-bit, version 1607
**Backend:** AmzCD

### Bug description
Occasionally, over the past couple of weeks, when running a backup targeting the Amazon Cloud Drive backend, the backup will fail with an error message:

`System.Net.WebException: The remote server returned an error: (429) Too Many Requests.`

I'm sorry to say that I don't have a repro for this, since it's only happened twice in as many weeks and I can't discern the conditions that led to it. Also, I've found that waiting until the next day is usually enough to get the backup to finish properly. I wanted to report it anyway, though, just to get some more information if possible. From what I've read, error 429 might apply to all users of the application using the Amazon API, in this case Duplicati. Is that correct, or is it an error that's exclusive to me, the individual user? As you can see, the error returned by the "remote server" doesn't provide much detail.

Furthermore, is there any set of best practices for Amazon Cloud Drive (or other backends, for that matter) that would help alleviate this? Setting a bandwidth throttle, or perhaps changing the block size? I left the backup settings at their defaults, including the block size of 50MB, and I'm considering increasing that to 200MB (the backup in question is ~370GB, with a great number of large files), would that in fact quarter the number of requests to the remote server as I expect it to?

I have no development experience with Amazon's APIs, and although I'll be happy to try the change myself, a backup that large may take a while to complete, so I thought it would be wise to ask the actual project developers for some feedback in the meantime. :)

**Comment by deHoeninger** [comment] 2016-11-17 08:35
I can say, that I have the same issue from time to time.

**Comment by SamuelBolduc** [comment] 2016-11-22 14:06
I also have this issue, and in my case it makes my backup almost impossible to complete. 

I uploaded half of my 7TB of data, but every time I encounter this error Duplicati stops and waits for next scheduled backup to resume. The problem is scanning my local files takes Duplicati at least a full two days (normal?) so in the end my server spends 95% of the time checking the files and 5% actually backing up before crashing again.

Wouldn't it be possible to retry a few times, maybe wait a few minutes and try again, so that we don't have to rescan all the files every time?

**Comment by klammbueddel** [comment] 2017-01-07 23:37
Since my backup now grew to over 1TB and about 50K files onto the cloud drive I now run into this error continously. I dig into the code and assume, that the loop in the List function of AmzCD.cs is not throttled and causes the error. 200 results are fetched for each loop which causes ~ 250 API requests without any throttelling.

I'd like to send a PR to fix this, but I am not sure on how to solve this the duplicaty way. I thought about handling the 429 Error in the List function itself and performing a retry. Or add some throtteling to the loop? The retrial mechanism of the BackendManager does not do the job, since it only repeats the high level List function. Maybe someone educated could give me a hint? Is their any duplicaty way to implement throtteling?

Thanks!

**Comment by kenkendk** [comment] 2017-01-08 12:19
@klammbueddel , you have hit into an underlying assumption that is now broken :).

I assumed that the list operation would be a simple "list" that returns the filename.
But since you see 250 requests, that assumption no longer holds.

The `List` method in Duplicati is simple, because of this assumption, but I don't think it can stay that way.

As you suggest, it would be possible to fix inside the Amazon Cloud Drive backend, with a backoff/retry system. I think this would not be great, because the UI cannot signal the backend to stop, so it would appear to hang from the user perspective.

For this reason, I think it would be better if the `BackendManager` could do the `List` operation, but with paged results (i.e. the paging done by the backend is visible to `BackendManager`).

Perhaps something like this:
```
public interface IPagingBackend : IBackend
{
    IPageResults List(IPageResults previous);
}

public interface IPageResults
{
    IEnumerable<FileEntry> Items { get; }
    bool More { get; }
}
```

The `BackendManager` can then use this, like:
```
IPageResults pg = null;
var list = new List<FileEntry>();
while(pg == null || !pg.More)
{
   pg = backend.List(pg);
   list.AddRange(pg.Items);
}
```

And of course the `BackendManager` should support retries, and perhaps use a `FileBackedList` to avoid storing large chunks of results in memory.

Does this make sense? Is it something you can work with?

**Comment by deHoeninger** [comment] 2017-01-12 20:59
Hi all,

meanwhile I'm running into the same issue. Duplicati can't finish my backup, due to the describe issue "too many requests"

My backup:
Letzte erfolgreiche Sicherung:
    letzten Freitag um 20:29 Uhr (dauerte 16:29:03)
Nächste geplante Ausführung:
    morgen um 04:00 Uhr
Quelle:
    279,98 GB
Sicherung:
    1,40 TB / 125 Versionen

**Comment by klammbueddel** [comment] 2017-01-12 22:05
@kenkendk: The suggestion you made sounds like a good idea. I already started implementation but do lack some time to get a fast PR on track.

@deHoeninger: As a hotfix you can try to raise the retrial limit. I made the experience that after ~25 trials the requests went through. Not nice, but not backing up is even worse.

@kenkendk: I assume their is same way to set the retrial limit in the application?

**Comment by kenkendk** [comment] 2017-01-19 14:37
Yes, you can control retry logic with `--number-of-retries=25` and `--retry-delay=10s`.

**Comment by kenkendk** [comment] 2017-01-19 14:39
But in this case, it will probably not work as the list operation itself is retried, not the individual list requests (i.e. you start on page zero each time).

**Comment by klammbueddel** [comment] 2017-01-29 23:23
Hi Kenneth, I implemented the interface as suggested (#2291) but am kinda stuck on how to integrate it with the BackendManager. Maybe you can give some more hints or take over from here? Where exactly in the BackendManager should the interface check and implementation switch take place? The Operations (Put, Get, List, etc) are all atomic, our new paged List is not. So where to place the paging loop to make the generic backoff work?

From my perspective it would be much easier to keep the old interface and make the backoff an implementation detail of the backend, but I can see your points against that.

**Comment by klammbueddel** [comment] 2017-01-29 23:30
> But in this case, it will probably not work as the list operation itself is retried, not the individual list requests (i.e. you start on page zero each time).

It does work in practice. If retried long enough the List operation will finally pass through. But we should consider to increase the default retrial count, since the "Put" operation runs into this issue, too. As stated earlier it might happen that >25 retrials are necessary.

**Comment by carldebilly** [comment] 2018-02-16 18:45
I got the same problem using OpenStack Storage on OVH cloud services.

* Is there a way Replicati can use the `Retry-After` header when this happend?
* Maybe Replicati should use the headers `X-RateLimit-Limit`, `X-RateLimit-Remaining` & `X-RateLimit-Reset`?

Carl.

**Comment by warwickmm** [comment] 2019-12-01 17:49
Closing this since the Amazon Cloud Drive API has been discontinued.

https://forum.duplicati.com/t/amazon-cloud-drive-discontinued/7391

**Closed by warwickmm** 2019-12-01 17:49 UTC
Labels: amzcd, bug
