### ISSUE TITLE
During restore: arbitrary bandwith application only on first   dblock.zip.aes restoring

### ISSUE THREAD

**Issue by mdsmdsmds** [duplicati/duplicati#2890] opened 2017-11-11 17:43 UTC
Duplicati - 2.0.2.12_canary_2017-10-20
Windows Server 2012 R2

On master app settings, I've only
--throttle-upload=40KB
and no other bandwith limitation policy. So, what I expect is that during restore from my SFTP server non bandwith limitation should be applied. And this is almost true except for the first ....dblock.zip.aes.

This is really bizzarre. The first download goes at exact then 40KB [limit set for uplod :)) not download]
Then, the others are downloaded with, correctly, no band limit.

In fact then first file arrive in 43 minutes, the others each in less than 1 minute.

Look at partial log here:
[partLog.txt](https://github.com/duplicati/duplicati/files/1463950/partLog.txt)

**Comment by JonMikelV** [comment] 2018-06-14 19:02
The comment for this is that it "Fixes part of #2890" - what else needs to be resolved?  Or is this fixed as of 2.0.3.3 beta 2018-04-02?  https://forum.duplicati.com/t/release-2-0-3-3-beta-2018-04-02/3083

**Comment by warwickmm** [comment] 2020-03-05 06:53
Some inconsistencies with throttling should be fixed by pull request #4127.  I can't reproduce this issue where only the first dblock file is throttled, so I'm going to close this.  If this is still an issue, please feel free to reopen this.

**Closed by warwickmm** 2020-03-05 06:53 UTC
Labels: bug
