### ISSUE TITLE
Unexpected number of remote volumes marked as deleted. (test case)

### ISSUE THREAD

**Issue by ts678** [duplicati/duplicati#5097] opened 2024-02-11 02:29 UTC
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.7.100 Canary, but I doubt it's new
- **Operating system**: Windows 10
- **Backend**: Local folder, but likely N/A

## Description

Recreate with error on corrupted dlist can get this in a later backup, so basically it requires pressing on despite the recreate error.
[Error on linux mint](https://forum.duplicati.com/t/error-on-linux-mint/17407) was the model here. This test case is likely not the only one, but it's reproducible so the failure can be studied.

## Steps to reproduce

1. AES encryption, upload-unchanged-backups, keep 2 versions, optionally number-of-retries=0 if you want to avoid retry wait.
1. Backup a short text file twice.
1. Hex edit the second dlist, changing a character. Aiming for middle of binary part is good.
1. Recreate and get an Error:
[Error-Duplicati.Library.Main.AsyncDownloader-FailedToRetrieveFile]: Failed to retrieve file duplicati-20240211T020908Z.dlist.zip.aes
CryptographicException: Failed to decrypt data (invalid passphrase?): Message has been altered, do not trust content
Job log gets this Warning:
[Warning-Duplicati.Library.Main.Operation.RecreateDatabaseHandler-FileProcessingFailed]: Failed to process file: duplicati-20240211T020908Z.dlist.zip.aes
CryptographicException: Failed to decrypt data (invalid passphrase?): Message has been altered, do not trust content
Database Remotevolume row for corrupted dlist is likely `Uploaded` with a NULL for `Hash`.
1. Backup anyway.

- **Actual result**:
Unexpected number of remote volumes marked as deleted. Found 0 filesets, but 1 volumes
The error persists through additional backups, though numbers rise by 1 for every attempt.
- **Expected result**:
Unclear how much better is possible given the not quite right database that recreate left us.

The damaged dlist is understandably not in the Fileset table, so can't be deleted by usual means.
Deleting its Remotevolume table row along with the dlist itself in the Destination seems to work.
Alternatively, the Destination deletion (or hiding, by changing prefix) and recreate will likely work.

Alternative topic title might have talked about how one corrupt dlist breaks recreate and backup.
Getting back on track might be pretty easy even with no extra logging. Delete bad file, start over.

## Screenshots

From recreate:

![image](https://github.com/duplicati/duplicati/assets/40771998/4a0d7278-f2b8-4fe1-a559-1e0e02c09559)

From backup:

![image](https://github.com/duplicati/duplicati/assets/40771998/472e6266-c1a1-4071-a322-3ac14b6eaf8a)

**Comment by Jojo-1000** [comment] 2024-05-11 20:14
Thanks to the reproduction steps, I was able to analyze the cause of the error:

What happens in Recreate:
1. Add all files to the Remotevolume table as Uploaded
2. Any files which are successfully downloaded and decrypted are changed to Verified and the Hash field is set
3. An entry in the Fileset table is created with the VolumeID, the contained data is inserted in the FileLookup table

Since Step 3 does not run for the corrupted dlist, there exists no Fileset table reference to it.

At the start of Backup, the state is changed from Uploaded to Verified after the file size was checked.

At the end of Backup:
1. A Delete operation is started to remove the oldest version
2. This calls `LocalDeleteDatabase.DropFilesetsFromTable` to clear the unnecessary entries
3. The relevant entry is deleted from the Fileset table
4. Entries in other tables that no longer refer to a valid fileset are deleted. At this point all blocks only used in the corrupted version would be marked as deleted and free to compact.
5. Any filelist volumes that are not needed (and have state Uploaded/Verified/Temporary) are set to Deleting in the Remotevolume table, to trigger deleting the files
6. A sanity check confirms that the number of filelist volumes marked for deletion is the same as the number of removed filesets, probably to prevent bugs from wiping the database

The assumption for 6 is that every fileset should have one volume, but in this case there is one extra volume that is not referenced anywhere. The transaction fails, so it is reverted and nothing is deleted. The delete operation only starts after the main backup is already commited, so the new files are not lost. The backup saved the new files, but the old versions stay indefinitely.

I see multiple ways to fix this, but I am not sure which is best:
1. Remove the check in 6, because the underlying assumption is not true (probably not a good idea)
2. In 5, only delete the volumes that are explicitly removed from the Fileset table, so it would leave the NULL entry and the corrupted file will just stick around. It would also leave other unreferenced volumes, but all of those cases would cause this same error
3. Mark the database as not fully recreated, so the user can't continue any backups. This would be annoying, as all other versions are fine. This would force the user to manually delete the broken file and run recreate again
4. Remove the broken file from the Remotevolume table, so the next backup will fail with extra remote files. This would force a manual repair before the next backup

The question is, should the broken file be left and ignored in future backups, or should it be removed (automatically or manually)? The referenced data would risk deletion after the first compact in either case.

It would also be more user-friendly to explicitly state in the error message that the relevant backup version is corrupted and will be lost if they continue without fixing it.

**Comment by ts678** [comment] 2024-05-13 16:48
> Thanks to the reproduction steps, I was able to analyze the cause of the error

Thanks for pursuing, and I'd note that it's not clear if the repro fits actual cases. Still, it adds insight, and that's generally good.

> LocalDeleteDatabase.DropFilesetsFromTable

This was one of my suspects for one of the annoying rare hard-on-user failures. Likely it was "Unexpected difference in fileset".
Seemed like it required removing the wrong thing. This is where things get removed. I was testing out foreign key constraints, because they're a way to keep things consistent. I found some questionable orderings, but the transaction relaxes ordering -- unless the transaction doesn't really work, e.g. some other thread commits. Regardless, I had tool issues, so stopped that test.

Some of my work there (and notes here) remind me of my recent editorial about the special cases, and failed assumption risks.

Possibly one reason foreign keys aren't in use already is the special cases, but they aren't THAT bad. I hit these (quoting notes).

```
-- FileLookup.BlocksetID to Blockset.ID (No, because of the -100 and -200)
-- Block.VolumeID to Remotevolume.ID (No, because of -1 for 0 length)
```

Getting back on topic, this is another that probably needs more expertise than I have, but I'll get deeper into it at some point.
Hopefully we'll hear from the maintainer when that's possible.

**Comment by kenkendk** [comment] 2024-11-01 16:11
I am leaning most towards solution 3: mark the database broken and prevent new backups.
While the setup here is staged, a real setup where files change on the remote side should require manual intervention.

I think a more elegant fix would be to mark the remote file as "Damaged" so the backup can be used once the damaged files are removed from the remote destination.

**Comment by kenkendk** [comment] 2024-11-01 16:27
It looks like this has been fixed somwhere between now and when the issue was created.
I added a test case as described by @ts678 and it correctly refuses to continue the backup.
Closing this issue as the original issue has "a solution", but feel free to re-open if you either disagree or see something that is not covered by the fix.
My PR that adds just the test: #5629

**Closed by kenkendk** 2024-11-01 16:27 UTC
