### ISSUE TITLE
Failed to connect: Logon failure: unknown user name or bad password.

### ISSUE THREAD

**Issue by abrow169** [duplicati/duplicati#3288] opened 2018-06-21 19:13 UTC
- [ X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3
- **Operating system**: Winodws 7
- **Backend**: local folder or drive

## Description
Recently we changed passwords for our admin accounts and now duplicati says that the FTP folder does not exist. I tried to edit the configuration and I updated the password in the "Destination" section. It tells me that the FTP folder does not exist and asks if I want to make a new one. I said "yes" and then it tells me "Failed to connect: Logon failure: unknown user name or bad password."
How can I login again?

## Steps to reproduce
1. Change the password on the FTP host computer. 
2. Cry

I don't like playing with duplicati on my own because I know something bad will happen. So far, I just deleted the backup on the GUI (not the FTP folder) and tried to make a new one, but it still can't login in. 

## Screenshots

![image](https://user-images.githubusercontent.com/36893503/41740280-829dde6e-7565-11e8-9512-7787cf08fa75.png)

## Debug log

![image](https://user-images.githubusercontent.com/36893503/41740343-b2ac004a-7565-11e8-97b9-52d254e6e7c8.png)

**Comment by kees-z** [comment] 2018-06-21 19:49
In the screenshot above I see you chose "Local folder or drive" as storage type.
If you haven't done this already, change it to "FTP" or "FTP (Alternative)".

The server address is hidden by the popup containing the error message, but must be supplied without the `ftp://` prefix.

**Comment by abrow169** [comment] 2018-06-22 17:43
Sorry about the confusion.
We used to have FTP, but since we have so many computers, it began bottlenecking the backups and slowing everything down.
We began using the local folder or drive and it was working well till this password issue.

**Comment by verhoek** [comment] 2018-07-17 19:54
I cannot reproduce this. What user/pass do you see if you try to get the commandline version of the backup job?

**Comment by warwickmm** [comment] 2020-08-17 02:41
Closing this since it can't be reproduced.  If you're still having this issue, please feel free to reopen this.

**Comment by warwickmm** [comment] 2020-08-17 02:41
Closing this since it can't be reproduced.  If you're still having this issue, please feel free to reopen this.

**Closed by warwickmm** 2020-08-17 02:41 UTC
