### ISSUE TITLE
"Error writing Request"

### ISSUE THREAD

**Issue by bwa-** [duplicati/duplicati#2409] opened 2017-03-28 20:10 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:**  2.0.1.53_experimental_2017-03-13
**Operating System:** Arch Linux
**Backend:** Amazon Cloud Drive

### Bug description
I've been getting Errors "Error writing request" for some days (see stacktrace below). This only applies to some of my backups and I cannot figure out what causes it.
Two things have happened in the last couple of days: 
a) the disk containing the databases and temp dir was full and had to be cleaned up. I do not know if the errors started when the disk ran out of space.
b) I changed the options of my backups reducing the LZMA thread count and the asynchronous upload limit.

I have:

- Restarted the duplicati service 
- Recreated the databases
- Verified the files
- Checked whether the connection to ACD works (and generated new AuthIDs)
- Updated and rebooted the server

None of which has had any effect.

What happens is the following: The backup starts and generates the first volume to be uploaded:

`28. Mrz. 2017 21:49: Backend event: Put - Started: duplicati-b4fa7aec604de439f8ad62160476ca447.dblock.7z.gpg (97.55 MB)`

There it hangs and the upload never starts (checked traffic on my router).

What follow is this:

`28. Mrz. 2017 21:54: RemoteOperationPut took 00:05:16.107`

`
28. Mrz. 2017 21:54: Operation Put with file duplicati-b4fa7aec604de439f8ad62160476ca447.dblock.7z.gpg attempt 5 of 5 failed with message: Error writing request
{"ClassName":"System.IO.IOException","Message":"Error writing request","Data":null,"InnerException":{"NativeErrorCode":10058,"ClassName":"System.Net.Sockets.SocketException","Message":"The socket has been shut down","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"  at System.Net.WebConnection.EndWrite (System.Net.HttpWebRequest request, System.Boolean throwOnError, System.IAsyncResult result) [0x000ad] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 \n  at System.Net.WebConnectionStream.WriteAsyncCB (System.IAsyncResult r) [0x00013] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2147467259,"Source":"System"},"HelpURL":null,"StackTraceString":"  at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry (Duplicati.Library.Snapshots.ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend, System.String path, System.IO.FileAttributes attributes) [0x00011] in <ab9099cf669b4a44ac3d8ab46230146c>:0 \n  at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation (Duplicati.Library.Snapshots.ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend) [0x001b5] in <ab9099cf669b4a44ac3d8ab46230146c>:0 \n  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter) [0x0069d] in <ab9099cf669b4a44ac3d8ab46230146c>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146232800,"Source":"Duplicati.Library.Main"}`

### Steps to reproduce
- unknown

**Actual result:** Error
**Expected result:** No error. (- :

### debug log

[bugreport.zip](https://github.com/duplicati/duplicati/files/876949/bugreport.zip)

**Comment by kenkendk** [comment] 2017-04-03 08:28
It looks like a network error, where the connection is closed for some reason (remote server, dropped line, local OS closing, etc.)

**Comment by wintersolutions** [comment] 2017-04-04 14:53
So I have the same issue. I tried out the current master and it started uploading. Then I started the `Duplicati - 2.0.1.52_canary_2017-03-13` service again and added a completely new backup. Used the following settings:

* Filesize 50 MB
* Accept any SSL certificate
* Keep forever

Currently the first version is uploading files again, something that did not happen since 1 month. I can't tell if the next incremental backup will work but the initial one is uploading now for me.

System `4.9.20-1-MANJARO #1 SMP PREEMPT Fri Mar 31 17:49:34 UTC 2017 x86_64 GNU/Linux`

**Comment by kenkendk** [comment] 2017-04-05 10:10
@wintersolutions It could very well be the size... if the server rejects files larger than a certain size, or has a timeout that prevents the upload from completing, you could get the error shown here.

**Comment by bwa-** [comment] 2017-04-05 14:35
@kenkendk @wintersolutions The volume size does seem to be a factor here. I have changed the size from 125MB to 25MB for two backups and that seems to have fixed the issue. After that I tried again with 75MB volume size and got the same error as before.

This is on a 10Mbps upstream to ACD. Maybe the timeout values of their API have changed or something similar?

I have changed my other backups to also use smaller volume sizes, now. I will report back once they are done.

**Comment by bwa-** [comment] 2017-04-07 14:03
@kenkendk I have not experienced the error again since I lowered the volume size. What I do experience now, though, is a drastically slower upload performance because of the gaps between volumes.
I can see on my router Web UI that it takes about two times the time it takes to upload one 25MB volume until the next one starts. So if the upload of 25MB takes about 25 seconds, another 50 seconds pass before the next volume upload starts. This is the reason I increased volume size in the first place - it closed the gaps between uploads somewhat.

Is there any way to eliminate the gaps between volume uploads?

**Comment by TheCake21** [comment] 2017-04-10 12:13
As I'm also affected by this issue I did some testing. I can confirm that this issue only effects Amazon Cloud Drive on Linux, Google Drive on Linux is fine and Amazon Cloud Drive on Windows is also fine. As 200mb blocks is my default backup setting I can confirm that it was fine in the past.

**Comment by pitkley** [comment] 2017-04-10 15:55
I have been experiencing the same issue as well, and can confirm what @TheCake21 said: ACD under Windows is fine, ACD under Linux **with Mono 4.8** is not. The suggestion of downgrading to 4.6 was the solution for me, I'm seeing no issues with 200 MB chunks.

**Comment by PizzaPill** [comment] 2017-08-26 13:47
I've used @TheCake21 s solution successfully for the last months. I was getting erros recently and tried a upgrade to mono 5 and it works flawlessly now. So if you have your mono version pinned you can probably update it again.

2.0.2.1_beta_2017-08-01
Mono JIT compiler version 5.0.0 (Stable 5.0.0.100/9667aa6 Wed Jul 12 17:00:30 UTC 2017)
Linux 4.4.82-1-MANJARO #1 SMP PREEMPT Sun Aug 13 20:15:33 UTC 2017 x86_64 GNU/Linux

**Comment by warwickmm** [comment] 2019-12-01 17:50
Closing this since the Amazon Cloud Drive API has been discontinued.

https://forum.duplicati.com/t/amazon-cloud-drive-discontinued/7391

**Closed by warwickmm** 2019-12-01 17:50 UTC
Labels: amzcd, bug
