### ISSUE TITLE
AWS simple test faild

### ISSUE THREAD

**Issue by remydev** [duplicati/duplicati#1865] opened 2016-07-25 18:54 UTC
Hi,
I wish get out from Hubic, this is not a good and secure service.

So i tried AWS S3 with glacier.

On the computer I want to save , I did a first test.
The recovery of the backup does not work I have the following message
"No backup at the specified date '

The following options are used
 Hidden files
 System files
 Temporary files

If I conducted a new test without these options, any changes to files on amazon S3 is realized

Another case, if I test recovery backup on another computer , I get the following error :
" Failed to connect : The request we Calculated signing does not match the signatures you Provided Check your key and signing method . . "

I confirm that I can see the 3 files as described here: http: //www.duplicati.com/news/howtouseglaciertostorebackups
##

**Comment by remydev** [comment] 2016-07-28 19:06
I have got 2 bugreport file with 2 very simple test

message error : 
- Found 3 remote files that are not recorded in local storage, please run repair (when i backup)
- Detected file entries with not associated blocks (when i restore)


[bugreport (1).zip](https://github.com/duplicati/duplicati/files/389153/bugreport.1.zip)
[bugreport.zip](https://github.com/duplicati/duplicati/files/389152/bugreport.zip)

**Comment by kenkendk** [comment] 2016-08-27 14:01
Try to use a new folder to store the backups.
Duplicati checks what files are in the remote folder and complains if you manually add/remove files.

For the restore on the new computer, this means that a new backup will not work before you run the "repair" command. This command will figure out that you are working with an existing backup and sync the remote to the local database, and then let you continue backup (and restore).

If you just want to restore, there is an option to restore without syncing first, just click the "restore backup" menu to the left.

The "Calculated signing ... " error message is usually caused by your computer clock not being correct.

Hope that answers your questions.

**Comment by agrajaghh** [comment] 2016-12-07 20:40
closing for now, please comment if you are still having issues

**Closed by agrajaghh** 2016-12-07 20:40 UTC
Labels: Pending information
