### ISSUE TITLE
Duplicati 2.0.0.81 / Snapshot & Encryption not working with file: backup (on network drive)

### ISSUE THREAD

**Issue by HaraldOnline** [duplicati/duplicati#1292] opened 2015-02-11 11:28 UTC
I'm not sure whether it's "by design" ... Since I wasn't able to backup using ftp: (error with regards to passive mode) I used file:// to access the backup server (file://\\backupXXX.onlinehome-server.info\bak5208YYY\dupli).
I got "Warnings: [The supplied option ----snapshot-policy is not supported and will be ignored]". Also encryption (AES Default) wasn't supported.

Without snapshots the backup isn't really useful for me since open MS SQL Server databases have to be saved.

System is W2008R2 server.

**Comment by kenkendk** [comment] 2015-02-16 09:52
This is a duplicate of issue #1287, and has been fixed with 2.0.0.82, which is now available.

**Closed by kenkendk** 2015-02-16 09:52 UTC
Labels: duplicate
