### ISSUE TITLE
Error : Connection lost

### ISSUE THREAD

**Issue by CooperBarrett** [duplicati/duplicati#1934] opened 2016-09-18 13:30 UTC
_I am French and I use google translation, I hope you understand me_

----------------------------------------

### Version info

**Duplicati Version:** v2.0.1.22-2.0.1.22_experimental_2016-09-12
**Operating System:** Mac OSX 10.11.6 (El Capitan)
**Backend:**

### Bug description
I can not connect, systematic error message:
Connection lost
The connection to the server is lost, Attempting again in 00: xx

Screenshot:
![](https://lut.im/kbzROekTeb/QpSkLA4L0JVWW0qD)

### Steps to reproduce

- Installation of **Duplicati v2.0.1.22-2.0.1.22_experimental_2016-09-12**
- Error at launch: _Requires Duplicati the Mono Framework 2.8 or later_
- Download and install **Mono 4.6.0**
- Duplicati launches into the browser but error: _Connection lost
The connection to the server is lost, Attempting again in 00: xx_

[EDIT]
Message of the error behind the first :
_Failed to read localizations_
[End EDIT]
- Attempted resettlement but still the same error.

Thank you in advance for your help

**Comment by glannes31** [comment] 2016-09-19 08:23
I have the same issue!

**Comment by glannes31** [comment] 2016-09-19 08:44
I changed the MAC Language in English(USA), i have the same problem.

**Comment by CooperBarrett** [comment] 2016-09-19 11:04
@glannes31 

> I changed the MAC Language in English(USA), i have the same problem.

And it solved the problem ? 
I hope this is not the only solution I see myself as ill spend my MAC in English...
thanks for your return

**Comment by glannes31** [comment] 2016-09-19 11:06
@CooperBarrett  je dis que j'ai le même problème malgres mon changement de langue , j'espère qu'ils se saisiront vite de ce souci.

**Comment by glannes31** [comment] 2016-09-19 11:07
@kenkendk I am very frustrated by this error

**Comment by CooperBarrett** [comment] 2016-09-19 11:11
@glannes31 

Ah ok thank you, I also hope that a solution will be found

**Comment by kenkendk** [comment] 2016-09-19 13:40
Could one of you use the developer tools in the browser (CMD+ALT+I in chrome, F12 in IE) and see if there are error messages in the console? Also, can you look at the "Network" tab to see if there are load failures?

**Comment by glannes31** [comment] 2016-09-19 14:05
@kenkendk  I have an ERR_CONNECTION_REFUSED . that sat it's angular.min.js on line 108

**Comment by CooperBarrett** [comment] 2016-09-19 14:13
For me : 

**2 Errors in Console :** 

`"Error: [$compile:tpload] http://errors.angularjs.org/1.4.3/$compile/tpload?p0=templates%2Fhome.html&p1=0&p2=
J/<@http://127.0.0.1:8200/ngax/scripts/angular/angular.min.js:6:416
e/<@http://127.0.0.1:8200/ngax/scripts/angular/angular.min.js:146:48
f/<@http://127.0.0.1:8200/ngax/scripts/angular/angular.min.js:120:182
jf/this.$get</n.prototype.$eval@http://127.0.0.1:8200/ngax/scripts/angular/angular.min.js:134:489
jf/this.$get</n.prototype.$digest@http://127.0.0.1:8200/ngax/scripts/angular/angular.min.js:132:1
jf/this.$get</n.prototype.$apply@http://127.0.0.1:8200/ngax/scripts/angular/angular.min.js:135:267
l@http://127.0.0.1:8200/ngax/scripts/angular/angular.min.js:87:150
F@http://127.0.0.1:8200/ngax/scripts/angular/angular.min.js:91:187
Sf/</e@http://127.0.0.1:8200/ngax/scripts/angular/angular.min.js:92:271

_If I develop the tab_

"angular.min.js:108:318
e/<()angular.min.js:108
Ze/this.$get</<()angular.min.js:80
f/<()angular.min.js:120
jf/this.$get</n.prototype.$eval()angular.min.js:134
jf/this.$get</n.prototype.$digest()angular.min.js:132
jf/this.$get</n.prototype.$apply()angular.min.js:135
l()angular.min.js:87
F()angular.min.js:91
Sf/</e()`

`L’utilisation de « getPreventDefault() » est obsolète. Utiliser « defaultPrevented » à la place.`
Translation : 
`The use of "getPreventDefault ()" is obsolete. Use "DefaultPrevented" instead.`

_If I develop the tab_

`GET XHR http://127.0.0.1:8200/api/v1/serverstate/
GET XHR http://127.0.0.1:8200/api/v1/serverstate/
GET XHR http://127.0.0.1:8200/api/v1/serverstate/
GET XHR http://127.0.0.1:8200/api/v1/serverstate/
...`

_If I develop the tab_

![](https://lut.im/rAJJaJy5Cs/Yc2MXfF3jTYbJULb)

I am enclosing a comprehensive screen capture to make it clearer : 

![](https://lut.im/Jj5pCzbN2p/byf8cYomMFaa4ZkW)

At the "Network" tab, I do not know what to get you, so I put you a screenshot :
![](https://lut.im/Ek95EsADBP/fSPN0XTZ0HSFtgc7)

Thanks for your help, I hope I was clear enough ...

**Comment by kenkendk** [comment] 2016-09-19 20:07
Ok, I installed a French OSX and found the issue.

For some reason it attempts to use the Cocoa toolkit to host the trayicon on OSX, which causes it to crash. If I manually change to using RUMPS it works.

**Comment by kenkendk** [comment] 2016-09-19 20:11
Are you running 32bit OSX ?

**Comment by glannes31** [comment] 2016-09-20 06:22
Hello @kenkendk , for me it's an intel core i7 so 64 bit .

**Comment by kenkendk** [comment] 2016-09-20 07:42
I forgot, the problem is with 32bit mono.

You can see which you have by running this on a commandline: `mono --version`.

New mono packages are 64bit by default.

**Comment by glannes31** [comment] 2016-09-20 09:28
My mono version is 4.6 so it's the latest and it's x86.....

**Comment by glannes31** [comment] 2016-09-20 09:35
I uninstall it and reinstall it , i have always x86  version

**Comment by kenkendk** [comment] 2016-09-20 09:41
You are correct, I also have the x86 version, I have x64 from homebrew.

**Comment by glannes31** [comment] 2016-09-20 09:44
@kenkendk I am available for any test that if you want ;-)

**Comment by glannes31** [comment] 2016-09-20 12:42
@kenkendk Do you have an idea when Duplicati will be updated ?

**Comment by CooperBarrett** [comment] 2016-09-20 13:43
I'm late but : 
Version OSX : 64 bits
Version Mono : x86

**Comment by agrajaghh** [comment] 2016-09-20 14:40
@glannes31 I guess https://github.com/duplicati/duplicati/commit/ec4cf69aa91456777137d1c85501b25679f8f0fa will fix it, you have to wait for the next release

**Comment by kenkendk** [comment] 2016-09-21 07:13
@CooperBarrett : Yes, same issue, 32bit mono is the problem.

**Comment by kenkendk** [comment] 2016-09-21 07:14
Fixed with ec4cf69

**Closed by kenkendk** 2016-09-21 07:14 UTC

**Comment by kenkendk** [comment] 2016-09-21 12:54
New canary build available that should fix it:
https://github.com/duplicati/duplicati/releases

**Comment by abpostelnicu** [comment] 2016-12-23 09:53
I must reopen this issue since for me is present:
Duplicati Server: Debian Jessie 64bit
Duplicati Version: 2.0.1.35_experimental_2016-12-13
Client: Safari macOS

The issue is intermittent, after it appears if i reload the page it disappears and i can continue working on the page but it doesn't recover by auto connecting once the error was popped.
