### ISSUE TITLE
Duplicati is destroying executable files on restore operation

### ISSUE THREAD

**Issue by cosmopol** [duplicati/duplicati#4338] opened 2020-10-06 14:51 UTC
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Win 8.1 Pro 64-bit
- **Backend**: SD card 32GB

## Description

Executable files are corrupted and crash the system on invocation

## Steps to reproduce

The Quantum xTalk executable is one example of a half-corrupted file that was OK on backup, but got destroyed on restore!
"5-00555-14_xTalk-6.7.0.0_QUANTUM_Setup.exe"

- **Actual result**:
exe file corruption!
- **Expected result**:
No exe file corruption!

## Debug log

(There was no error message posted nowhere!)

**Comment by warwickmm** [comment] 2020-10-06 23:45
Closing as a duplicate of #4339.

**Closed by warwickmm** 2020-10-06 23:45 UTC
Labels: duplicate
