### ISSUE TITLE
"Smart backup retention" causes error: Retention value must be more than 5 minutes

### ISSUE THREAD

**Issue by BurninLeo** [duplicati/duplicati#3010] opened 2018-02-06 09:27 UTC
## Environment info
- **Duplicati version**: 2.0.2.17 (32 bit)
- **Operating system**: Windows 10 (64 bit)
- **Backend**: SFTP

## Description

Trying to use the brand new "Smart backup retention" on a newly defined backup.

When clicking "Speichern" this triggers an error: "Retention value must be more than 5 minutes".

## Screenshots

![screenshot-2018-2-6 duplicati](https://user-images.githubusercontent.com/15062876/35851411-39f55888-0b28-11e8-9965-66f1b9fee468.png)

**Comment by Pectojin** [comment] 2018-02-06 23:19
This one seems odd. I couldn't replicate it on 2.02.17, I didn't even get a warning if i used custom retention and intentionally set it below 5 minutes.

**Comment by TekkiWuff** [comment] 2018-02-07 22:54
I also cannot replicate this, but the error message results from the `keep-time` option:
https://github.com/duplicati/duplicati/blob/4abc2f832f7069abe4e3cf2104ce238bd36bf152/Duplicati/Server/Database/Connection.cs#L388-L395

Have you selected `Smart backup retention` right away when you came to the last page in the wizzard or have tried any other retention options, espcially the `Delete backups that are older than` option before?

**Comment by BurninLeo** [comment] 2018-02-08 11:55
I had selected the "smart backup retention" immediately (just read about this cool new feature on the website before the installation).

**Comment by TekkiWuff** [comment] 2018-02-08 21:04
Hm. Are you still getting this error, when you try to create a new backup or was it a one time hiccup?

If you still get the error when creating a new backup, could you check the data that is being send to Duplicati once you press "Speichern"?

For example in Firefox you'd open the web developer console (CTRL+SHIFT+I), change to the network tab and then hit "Speicher" in the Duplicati Interface.
After that you should find a `PUT` request. Select it and select the parameter tab on the right. Scroll down till you see `Settings` and expand all numbers. Is there a `keep-time` option and/or a `retention-policy` option?
Here is a screenshot as example:
![debugbackupsettings](https://user-images.githubusercontent.com/31596699/35998106-f34e9f0c-0d1b-11e8-99c6-177505390494.PNG)

**Comment by BurninLeo** [comment] 2018-03-01 13:04
Sorry for the delay. I wasn't ablte to replicate the issue, any more in version 2.0.2.19. I could also change the fixed backup retention to smart backup retention for the existing backups.

If the issue wasn't solved by the new version, it might be due to the fact that other backups were already configured when I created the new one. The issue had originally appeared in a blank installation of duplicati.

If nobody else encounters that issue, I assume, this can be closed.

**Comment by TekkiWuff** [comment] 2018-03-04 15:31
Alright, closing this for now, since I also cannot reproduce it even with a clean installation. Maybe the change in 2.0.2.19 actually fixed it.
If somebody else comes across this error again, please consider trying to obtain the data being send to Duplicati as described futher above.

**Closed by TekkiWuff** 2018-03-04 15:31 UTC

**Comment by rodbauer** [comment] 2018-04-03 00:27
I also got this on a new backup with 2.0.3.3 to a networked NAS.

Error was "Retention value must be more than 5 minutes". I couldn't save until I changed to "Keep all backups."

After running the backup I tried to switch to Smart Backup Retention. It let me save, but the option wasn't saved. Backup option was the same as before the save. I also can't save a custom backup retention, but can save the other options.

I discovered that it behaves correctly in Firefox but not in Chrome (both latest on latest macOS). I can save Smart Backup Retention on Firefox, look at the same job in Chrome, and it doesn't show Smart Backup Retention as being saved (even after reloading). I quit Chrome, restarted it, and loaded the same job and it doesn't reflect the save made in Firefox. It shows "Keep all backups."

Chrome Version 65.0.3325.181 (Official Build) (64-bit)
Firefox 59.0.2 64-bit
macOS 10.13.4

**Comment by SamSirry** [comment] 2018-04-03 01:01
Hi rodbauer,
Yes, this fix was mentioned here: https://github.com/duplicati/duplicati/issues/3045#issuecomment-366542506
And that thread said that this matter has been fixed already, so please make sure you're using the latest version. And also clear your browser's cache because I've noticed the cache causing a lot of strange things some times (in older versions. am not sure about the new ones)

**Comment by Cyberwizzard** [comment] 2018-05-05 09:38
I found this issue because I also got the "Retention value must be more than 5 minutes" error.

Switching to "Keep all backups" allowed me to save the new backup job but editing it will not let me switch to the Smart policy; upon "saving" it goes back to the Home screen, but editing the backup job shows that it did not switch to the Smart policy. I tried switching to keeping 1 backup and that setting was saved; it seems it specifically does not want to save the Smart policy.

I am using Chrome 66.0.3359.139 (Official Build) (64-bit) (cohort: Stable) and Duplicati - 2.0.3.3_beta_2018-04-02.

Opening the same page in Firefox allows me to switch to the Smart policy and save correctly.

So this seems to be a scripting bug which specifically affects Chrome.
