### ISSUE TITLE
Duplicati crashed from the launch of the application.

### ISSUE THREAD

**Issue by oceanos59** [duplicati/duplicati#2034] opened 2016-10-19 17:47 UTC
Hi i am on Debian and i have this bug:
```
Server has started and is listening on 127.0.0.1, port 8200
(Duplicati.GUI.TrayIcon:15841): WARNING : Unknown icon format, bitcount = 21060, compression = 65536
Request error:
Crash!
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: A null reference or invalid value was found [GDI+ status: InvalidParameter]
at System.Drawing.GDIPlus.CheckStatus (Status status) <0x41bb3470 + 0x0015f> in <filename unknown>:0
at System.Drawing.Image.CreateFromHandle (IntPtr handle) <0x41bb32e0 + 0x00027> in <filename unknown>:0
at System.Drawing.Image.LoadFromStream (System.IO.Stream stream, Boolean keepAlive) <0x41bb08c0 + 0x00033> in <filename unknown>:0
at System.Drawing.Image.FromStream (System.IO.Stream stream) <0x41bb08a0 + 0x0000f> in <filename unknown>:0
at Duplicati.GUI.TrayIcon.ImageLoader.LoadImage (System.String filename) <0x41bb0610 + 0x000ef> in <filename unknown>:0
at Duplicati.GUI.TrayIcon.ImageLoader.get_StatusMenuIcon () <0x41bb04d0 + 0x00013> in <filename unknown>:0
at Duplicati.GUI.TrayIcon.GtkRunner+MenuItemWrapper.GetIcon (MenuIcons icon) <0x41bb0090 + 0x00163> in <filename unknown>:0
at Duplicati.GUI.TrayIcon.GtkRunner+MenuItemWrapper..ctor (System.String text, MenuIcons icon, System.Action callback, IList1 subitems) <0x41ba5410 + 0x0015b> in <filename unknown>:0 at Duplicati.GUI.TrayIcon.GtkRunner.CreateMenuItem (System.String text, MenuIcons icon, System.Action callback, IList1 subitems) <0x41ba5390 + 0x00057> in <filename unknown>:0
at Duplicati.GUI.TrayIcon.TrayIconBase.BuildMenu () <0x41ba5060 + 0x000b2> in <filename unknown>:0
at Duplicati.GUI.TrayIcon.TrayIconBase.Init (System.String[] args) <0x41ba4ec0 + 0x00017> in <filename unknown>:0
at Duplicati.GUI.TrayIcon.GtkRunner.Init (System.String[] args) <0x41b9f120 + 0x00027> in <filename unknown>:0
at Duplicati.GUI.TrayIcon.Program.RealMain (System.String[] _args) <0x41a04650 + 0x00bbd> in <filename unknown>:0
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x41a03060 + 0x000b7> in <filename unknown>:0
--- End of inner exception stack trace ---
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x41a03060 + 0x00123> in <filename unknown>:0
at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) <0x419399e0 + 0x0002a> in <filename unknown>:0
at Duplicati.Library.AutoUpdater.UpdaterManager.RunMethod (System.Reflection.MethodInfo method, System.String[] args) <0x41a02cb0 + 0x00089> in <filename unknown>:0
Unhandled Exception:
System.ArgumentException: A null reference or invalid value was found [GDI+ status: InvalidParameter]
Server stack trace:
at Duplicati.Library.AutoUpdater.UpdaterManager.RunMethod (System.Reflection.MethodInfo method, System.String[] args) <0x41a02cb0 + 0x00357> in <filename unknown>:0
at Duplicati.Library.AutoUpdater.UpdaterManager+<RunFromMostRecent>cAnonStorey7.<>m0 () <0x41a02c70 + 0x0001f> in <filename unknown>:0
at Duplicati.Library.AutoUpdater.UpdaterManager.WrapWithUpdater (AutoUpdateStrategy defaultstrategy, System.Action wrappedFunction) <0x41a026a0 + 0x00342> in <filename unknown>:0
at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent (System.Reflection.MethodInfo method, System.String[] cmdargs, AutoUpdateStrategy defaultstrategy) <0x419ee000 + 0x0025b> in <filename unknown>:0
at Duplicati.GUI.TrayIcon.Program.Main (System.String[] args) <0x41926de0 + 0x00053> in <filename unknown>:0
at (wrapper managed-to-native) System.AppDomain:ExecuteAssembly
at (wrapper managed-to-native) System.AppDomain:ExecuteAssembly (System.AppDomain,System.Reflection.Assembly,string[])
at System.AppDomain.ExecuteAssemblyInternal (System.Reflection.Assembly a, System.String[] args) <0x41936f00 + 0x00054> in <filename unknown>:0
at System.AppDomain.ExecuteAssemblyByName (System.String assemblyName, System.String[] args) <0x41936d60 + 0x0003c> in <filename unknown>:0
at (wrapper remoting-invoke-with-check) System.AppDomain:ExecuteAssemblyByName (string,string[])
at (wrapper xdomain-dispatch) System.AppDomain:ExecuteAssemblyByName (object,byte[]&,byte[]&,string,string[])
Exception rethrown at [0]:
at (wrapper xdomain-invoke) System.AppDomain:ExecuteAssemblyByName (string,string[])
at (wrapper remoting-invoke-with-check) System.AppDomain:ExecuteAssemblyByName (string,string[])
at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent (System.Reflection.MethodInfo method, System.String[] cmdargs, AutoUpdateStrategy defaultstrategy) <0x41e484a0 + 0x0072c> in <filename unknown>:0
at Duplicati.GUI.TrayIcon.Program.Main (System.String[] args) <0x41de1d50 + 0x00053> in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: A null reference or invalid value was found [GDI+ status: InvalidParameter]
Server stack trace:
at Duplicati.Library.AutoUpdater.UpdaterManager.RunMethod (System.Reflection.MethodInfo method, System.String[] args) <0x41a02cb0 + 0x00357> in <filename unknown>:0
at Duplicati.Library.AutoUpdater.UpdaterManager+<RunFromMostRecent>cAnonStorey7.<>m0 () <0x41a02c70 + 0x0001f> in <filename unknown>:0
at Duplicati.Library.AutoUpdater.UpdaterManager.WrapWithUpdater (AutoUpdateStrategy defaultstrategy, System.Action wrappedFunction) <0x41a026a0 + 0x00342> in <filename unknown>:0
at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent (System.Reflection.MethodInfo method, System.String[] cmdargs, AutoUpdateStrategy defaultstrategy) <0x419ee000 + 0x0025b> in <filename unknown>:0
at Duplicati.GUI.TrayIcon.Program.Main (System.String[] args) <0x41926de0 + 0x00053> in <filename unknown>:0
at (wrapper managed-to-native) System.AppDomain:ExecuteAssembly (System.AppDomain,System.Reflection.Assembly,string[])
at System.AppDomain.ExecuteAssemblyInternal (System.Reflection.Assembly a, System.String[] args) <0x41936f00 + 0x00054> in <filename unknown>:0
at System.AppDomain.ExecuteAssemblyByName (System.String assemblyName, System.String[] args) <0x41936d60 + 0x0003c> in <filename unknown>:0
at (wrapper remoting-invoke-with-check) System.AppDomain:ExecuteAssemblyByName (string,string[])
at (wrapper xdomain-dispatch) System.AppDomain:ExecuteAssemblyByName (object,byte[]&,byte[]&,string,string[])
Exception rethrown at [0]:
at (wrapper xdomain-invoke) System.AppDomain:ExecuteAssemblyByName (string,string[])
at (wrapper remoting-invoke-with-check) System.AppDomain:ExecuteAssemblyByName (string,string[])
at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent (System.Reflection.MethodInfo method, System.String[] cmdargs, AutoUpdateStrategy defaultstrategy) <0x41e484a0 + 0x0072c> in <filename unknown>:0
at Duplicati.GUI.TrayIcon.Program.Main (System.String[] args) <0x41de1d50 + 0x00053> in <filename unknown>:0
```

Thank you for your help :) .

**Comment by agrajaghh** [comment] 2016-10-19 19:34
@oceanos59 which version are you running?

**Comment by oceanos59** [comment] 2016-10-20 07:59
@agrajaghh Hi, sorry to miss it :/ . The version of my duplicati is 2.0.1.28.

**Comment by G4Zz0L1** [comment] 2016-10-20 16:06
Yep, i can confirm this, same story here with the v2.0.1.28 just installed (it's going on from the .27, actually)

`No LSB modules are available.
Server has started and is listening on 127.0.0.1, port 8200

** (Duplicati.GUI.TrayIcon:14042): WARNING **: Unknown icon format, bitcount = 21060, compression = 65536
Request error: 
Crash! 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: A null reference or invalid value was found [GDI+ status: InvalidParameter]
  at System.Drawing.GDIPlus.CheckStatus (Status status) <0x40d32d20 + 0x0015f> in <filename unknown>:0 
  at System.Drawing.Image.CreateFromHandle (IntPtr handle) <0x40d32b90 + 0x00027> in <filename unknown>:0 
  at System.Drawing.Image.LoadFromStream (System.IO.Stream stream, Boolean keepAlive) <0x40d30f20 + 0x00033> in <filename unknown>:0 
  at System.Drawing.Image.FromStream (System.IO.Stream stream) <0x40d30f00 + 0x0000f> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.ImageLoader.LoadImage (System.String filename) <0x40d30c70 + 0x000ef> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.ImageLoader.get_StatusMenuIcon () <0x40d30b30 + 0x00013> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.GtkRunner+MenuItemWrapper.GetIcon (MenuIcons icon) <0x40d306f0 + 0x00163> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.GtkRunner+MenuItemWrapper..ctor (System.String text, MenuIcons icon, System.Action callback, IList`1 subitems) <0x40d2d780 + 0x0015b> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.GtkRunner.CreateMenuItem (System.String text, MenuIcons icon, System.Action callback, IList`1 subitems) <0x40d2d700 + 0x0004f> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.TrayIconBase.BuildMenu () <0x40d2d3e0 + 0x000af> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.TrayIconBase.Init (System.String[] args) <0x40d2d250 + 0x00017> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.GtkRunner.Init (System.String[] args) <0x40d2b0a0 + 0x00027> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.Program.RealMain (System.String[] _args) <0x40b75b90 + 0x00bc1> in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x40b745a0 + 0x000b7> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x40b745a0 + 0x00123> in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) <0x40aa9ff0 + 0x0002a> in <filename unknown>:0 
  at Duplicati.Library.AutoUpdater.UpdaterManager.RunMethod (System.Reflection.MethodInfo method, System.String[] args) <0x40b741f0 + 0x00089> in <filename unknown>:0 

Unhandled Exception:
System.ArgumentException: A null reference or invalid value was found [GDI+ status: InvalidParameter]

Server stack trace: 
  at Duplicati.Library.AutoUpdater.UpdaterManager.RunMethod (System.Reflection.MethodInfo method, System.String[] args) <0x40b741f0 + 0x00357> in <filename unknown>:0 
  at Duplicati.Library.AutoUpdater.UpdaterManager+<RunFromMostRecent>c__AnonStorey7.<>m__0 () <0x40b741b0 + 0x0001f> in <filename unknown>:0 
  at Duplicati.Library.AutoUpdater.UpdaterManager.WrapWithUpdater (AutoUpdateStrategy defaultstrategy, System.Action wrappedFunction) <0x40b73be0 + 0x00342> in <filename unknown>:0 
  at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent (System.Reflection.MethodInfo method, System.String[] cmdargs, AutoUpdateStrategy defaultstrategy) <0x40b5f0c0 + 0x00273> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.Program.Main (System.String[] args) <0x40ab7df0 + 0x00053> in <filename unknown>:0 
  at (wrapper managed-to-native) System.AppDomain:ExecuteAssembly (System.AppDomain,System.Reflection.Assembly,string[])
  at System.AppDomain.ExecuteAssemblyInternal (System.Reflection.Assembly a, System.String[] args) <0x40ab7b60 + 0x00054> in <filename unknown>:0 
  at System.AppDomain.ExecuteAssemblyByName (System.String assemblyName, System.String[] args) <0x40ab79c0 + 0x0003c> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain:ExecuteAssemblyByName (string,string[])
  at (wrapper xdomain-dispatch) System.AppDomain:ExecuteAssemblyByName (object,byte[]&,byte[]&,string,string[])

Exception rethrown at [0]: 

  at (wrapper xdomain-invoke) System.AppDomain:ExecuteAssemblyByName (string,string[])
  at (wrapper remoting-invoke-with-check) System.AppDomain:ExecuteAssemblyByName (string,string[])
  at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent (System.Reflection.MethodInfo method, System.String[] cmdargs, AutoUpdateStrategy defaultstrategy) <0x410194a0 + 0x0072c> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.Program.Main (System.String[] args) <0x40fb2d50 + 0x00053> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: A null reference or invalid value was found [GDI+ status: InvalidParameter]

Server stack trace: 
  at Duplicati.Library.AutoUpdater.UpdaterManager.RunMethod (System.Reflection.MethodInfo method, System.String[] args) <0x40b741f0 + 0x00357> in <filename unknown>:0 
  at Duplicati.Library.AutoUpdater.UpdaterManager+<RunFromMostRecent>c__AnonStorey7.<>m__0 () <0x40b741b0 + 0x0001f> in <filename unknown>:0 
  at Duplicati.Library.AutoUpdater.UpdaterManager.WrapWithUpdater (AutoUpdateStrategy defaultstrategy, System.Action wrappedFunction) <0x40b73be0 + 0x00342> in <filename unknown>:0 
  at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent (System.Reflection.MethodInfo method, System.String[] cmdargs, AutoUpdateStrategy defaultstrategy) <0x40b5f0c0 + 0x00273> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.Program.Main (System.String[] args) <0x40ab7df0 + 0x00053> in <filename unknown>:0 
  at (wrapper managed-to-native) System.AppDomain:ExecuteAssembly (System.AppDomain,System.Reflection.Assembly,string[])
  at System.AppDomain.ExecuteAssemblyInternal (System.Reflection.Assembly a, System.String[] args) <0x40ab7b60 + 0x00054> in <filename unknown>:0 
  at System.AppDomain.ExecuteAssemblyByName (System.String assemblyName, System.String[] args) <0x40ab79c0 + 0x0003c> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain:ExecuteAssemblyByName (string,string[])
  at (wrapper xdomain-dispatch) System.AppDomain:ExecuteAssemblyByName (object,byte[]&,byte[]&,string,string[])

Exception rethrown at [0]: 

  at (wrapper xdomain-invoke) System.AppDomain:ExecuteAssemblyByName (string,string[])
  at (wrapper remoting-invoke-with-check) System.AppDomain:ExecuteAssemblyByName (string,string[])
  at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent (System.Reflection.MethodInfo method, System.String[] cmdargs, AutoUpdateStrategy defaultstrategy) <0x410194a0 + 0x0072c> in <filename unknown>:0 
  at Duplicati.GUI.TrayIcon.Program.Main (System.String[] args) <0x40fb2d50 + 0x00053> in <filename unknown>:0`

**Comment by agrajaghh** [comment] 2016-10-20 16:13
@kenkendk I guess its because we switched from png to ico: 
https://github.com/duplicati/duplicati/commit/28e103539499e4a9a4f0f90a35b8c98c6a51f2fa

Should we switch back to png or just include png files for linux?

**Comment by G4Zz0L1** [comment] 2016-10-21 06:51
I've the same exact error with the latest experimental (v2.0.1.22), I don't think it's that commit, dunno...

**Comment by G4Zz0L1** [comment] 2016-10-24 07:00
Sorry for the question, I've read the other issue, but I don't understand what's the fix. I've reinstalled it many times, without results.

**Comment by agrajaghh** [comment] 2016-10-24 09:14
> Sorry for the question, I've read the other issue, but I don't understand what's the fix. I've reinstalled it many times, without results.

sorry, there is not fix yet...

**Comment by G4Zz0L1** [comment] 2016-10-24 15:06
Oh, my fault then, I've thought that the other guy has fixed it...    :P

**Comment by kenkendk** [comment] 2016-10-26 21:13
This is a duplicate of #1710

**Closed** 2016-10-27 06:50 UTC
Labels: bug
