### ISSUE TITLE
Unable to backup to SFTP

### ISSUE THREAD

**Issue by Inglebard** [duplicati/duplicati#3776] opened 2019-05-24 15:16 UTC
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5
- **Operating system**: Windows 7
- **Backend**: SFTP

## Description

The backup always failed. (Failed to process file)

## Steps to reproduce
- Create a backup task with SFTP backend
- No need to add encryption or additional option
- launch task

- **Actual result**:
``` Backup started at 24/05/2019 16:42:44
Checking remote backup ...
  Listing remote folder ...
Scanning local files ...
  720 files need to be examined (57,00 MB)
  261 files need to be examined (12,82 MB)
  222 files need to be examined (0 octets)
  Uploading file (16,71 MB) ...
  0 files need to be examined (0 octets)
  Uploading file (16,71 MB) ...
  Uploading file (16,71 MB) ...
  Uploading file (16,71 MB) ...
  Uploading file (16,71 MB) ...
  Uploading file (43,04 KB) ...
Checking remote backup ...
  Listing remote folder ...
  Deleting file duplicati-bb9227f4a2a3147a7be07b5a9df283647.dblock.zip ...
  Deleting file duplicati-bc0fab688feb04dc8991e37d4f76f1cec.dblock.zip ...
  Deleting file duplicati-bbf251650e9174320b1364d4e36cf4b6d.dblock.zip ...
  Deleting file duplicati-b235e69aea9684b8591837ed8b9c41597.dblock.zip ...
  Deleting file duplicati-b3c5c9128acc4424bbb0c67ee64dfb831.dblock.zip ...
  Uploading file (43,04 KB) ...
Verifying remote backup ...
Remote backup verification completed
  Downloading file (43,04 KB) ...
  Uploading file (43,04 KB) ...
  Downloading file (43,04 KB) ...
  Uploading file (43,04 KB) ...
  Downloading file (43,04 KB) ...
  Uploading file (43,04 KB) ...
  Downloading file (43,04 KB) ...
  Downloading file (43,04 KB) ...
Failed to process file duplicati-20190524T144246Z.dlist.zip => No such file
  Duration of backup: 00:01:50
  Remote files: 6
  Remote size: 43,04 KB
  Total remote quota: 0 octets
  Available remote quota: 0 octets
  Files added: 498
  Files deleted: 0
  Files changed: 0
  Data uploaded: 43,04 KB
  Data downloaded: 0 octets
Backup completed successfully!
Return code: 3
```

- **Expected result**:
Success

## Additionnal informations

The SFTP server is proftpd on Ubuntu 18.04.
I can see on the SFTP server, files being created/writed/deleted. At the end of the backup there is only one file left (~44kB).
If I use FTP, it works.

**Comment by warwickmm** [comment] 2019-05-26 22:51
I don't have any issues using SFTP with versions 2.0.4.5 or 2.0.4.18 on Linux.  I'm not sure what can be causing uploaded files to be deleted.   Can you confirm that this is happening on the initial backup and no custom/advanced configuration settings (such as retention policy) are being set?

**Comment by Inglebard** [comment] 2019-05-27 07:21
Hi,
Yes, this happens on initial backup without retention policy.
How can I enable "Debug" mode to get more informations ?

**Comment by Inglebard** [comment] 2019-05-27 13:37
Ok, so I find the issue.
My SFTP server use port 21. For an unknown reason Windows Firewall is the reason of this issue.
I need to disable it. If anyone knows why, I'm ready to listen.

**Comment by warwickmm** [comment] 2019-05-27 16:29
I'm not very familiar with Windows, so unfortunately I can't help much.  Perhaps this link might be helpful:

https://superuser.com/questions/1341418/cant-connect-via-ssh-from-windows-10

Since it sounds like the problem was due to a firewall configuration, I'm going to go ahead and close this issue.  Feel free to reopen this if you find that the issue is not resolved.

**Closed by warwickmm** 2019-05-27 16:29 UTC
Labels: not reproducible, pending user feedback

**Comment by ts678** [comment] 2019-05-27 16:37
Disabling Windows Firewall has directions on the Internet, but probably also cautions advising against it. Ordinarily I'd have expected SFTP to be on port 22. Port 21 would be for FTP. Can you move your SFTP? 

[ProFTPD module mod_sftp](http://www.proftpd.org/docs/contrib/mod_sftp.html) Using Port 22.
[Configure ProFTPd for SFTP on CentOS](https://linuxadmin.io/configure-proftpd-sftp-centos/) Using Port 2222.

As a guess on the "Deleting" done to 5 files seen in log, those might be the same files seen "Uploading", if something went wrong on the upload. Errors do rename and retry for up to 5 tries by default. You can set [--console-log-level](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#console-log-level)=retry to see more output from a CLI-style run. For GUI use [live log](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#viewing-the-duplicati-server-logs) or set up a log file.

Note that Duplicati calls SFTP "[SSH](https://duplicati.readthedocs.io/en/latest/05-storage-providers/#sftp-ssh)", referring to what's underneath. Don't confuse SFTP with [FTPS](https://duplicati.readthedocs.io/en/latest/05-storage-providers/#ftp) which is totally different. That would be on port 21 (because it's based on FTP) but with TLS encryption for security.

**Comment by Inglebard** [comment] 2019-05-27 18:26
Yes, it's SFTP and not FTPS. I manually change the port to 21.
I will try to change port to see if it can help.
Thanks for the answers.
