### ISSUE TITLE
Browser does not display all options of a second backup task

### ISSUE THREAD

**Issue by 8139david** [duplicati/duplicati#1315] opened 2015-03-03 12:11 UTC
I've tried Duplicati 2 on Firefox and Chrome, on Windows 8.1.
I've created 2 backup tasks.
When I click on the menu of the first task, everything is displayed.
But I click on the menu of the second task (which is below), only part of the menu is displayed. And there seems to be no way to get to see the parts that are hidden.

**Comment by agrajaghh** [comment] 2015-03-03 12:28
Is this the same problem as in #1183 ?

**Comment by 8139david** [comment] 2015-03-03 14:51
Yes.

**Comment by agrajaghh** [comment] 2015-03-03 16:12
I guess you can close this issue then. @rocifier had a fix for this issue, lets hope he'll create a PR soon ;)

**Comment by renestach** [comment] 2015-03-03 19:22
Duplicate of #1183

**Closed by renestach** 2015-03-03 19:22 UTC
