### ISSUE TITLE
Restoration state text goes on top of header in restore section

### ISSUE THREAD

**Issue by darksworm** [duplicati/duplicati#2845] opened 2017-10-24 14:07 UTC
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1
- **Operating system**: Windows 10
- **Backend**: N/A

## Description

Replace me

## Steps to reproduce

1. Start backup restoration
2. Resize browser window (not sure if neccessary)
3. Scroll down

- **Actual result**:
Text shows up on top of header
- **Expected result**:
Text gets hidden under header

## Screenshots

![2017-10-24_17-04-23](https://user-images.githubusercontent.com/9987548/31947680-9252a9c4-b8dd-11e7-9412-e57a09db9339.gif)

**Comment by kenkendk** [comment] 2017-11-17 14:02
Thanks for the illustration! It leaves no doubt to what the problem is 😄

**Comment by kenkendk** [comment] 2018-01-18 11:56
This was fixed with 4f1b1a1

**Closed by kenkendk** 2018-01-18 11:56 UTC
Labels: UI, bug, good first issue, help wanted, minor change
