### ISSUE TITLE
Unable to reset a backup or create new backup with the same name.

### ISSUE THREAD

**Issue by Tralen** [duplicati/duplicati#2644] opened 2017-08-15 16:28 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:**  2.0.1.72_canary_2017-07-05
**Operating System:** Arch Linux
**Backend:** ACD/Jottacloud

### Bug description
I decided to change the backend for my backups from ACD to Jottacloud, but I'm unable to make the backup "start over", that is, forget the history and begin from version 1 with the new backend. Even if I export the configuration, delete the backup, and recreate it, it still remembers the history of the previous one. ~~It seems the only way to achieve this is to create a backup with a new name.~~

The recreated backup also seems to be left in an inconsistent state, as if part of it's data has in fact been deleted. If I try to see the logs, for instance, I get the following error: `Failed to connect: SQLite error
 no such table: LogData`

### Steps to reproduce
- Export the backup's configuration.
- Delete the backup.
- Create a new backup with the same name.

**Actual result:** The deleted backup will resurrect with the full history as if it had not been deleted.
**Expected result:** There should be a way of "resetting" a backup and starting it over, or at least the deletion of a backup should be complete and persistent, so you can recreate it.

### Edit
I noticed that changing the name won't help. The only way I found to erase the history is to export as a json file and delete the relevant entries before importing. The database seems to be deleted properly,

**Comment by kenkendk** [comment] 2017-08-23 08:46
What is the "history" that you see?

The "delete" removes the data from the database, but you will still have files stored on the remote destination.

**Comment by Tralen** [comment] 2017-08-23 20:13
My presumption was that if I recreate a backup I deleted by importing it's configuration, it should not remember properties like "Last successful run", number of versions and size. These values are not part of the configuration proper, but a kind of history of the backup.

Since I had changed to a new backend, having the transient data from the previous backup displayed on reimporting gives the impression that Duplicati will continue the backup from the position it last stopped in the previous backend, which is impossible and suggests the backup is bound to fail.

I don't know how Duplicati will handle the situation, I guess it will start over regardless and the information is just a harmless residue from reconfiguring the same backup, but it does give the impression that the same backup cannot be started over.

The issue I'm reporting, then, is a usability issue, that the backup should be created clean, and that configuration should have no history stored, in those terms, lest becomes impossible to repurpose the same configuration file.

**Comment by Tralen** [comment] 2017-08-27 19:29
Today I tried simply changing the backend and letting Duplicati restart the backup from scratch. It detects that there are no files in the new backend and fails. Attempting to recreate and repair the database also fails. So the whole process of exporting, deleting, reimporting is currently necessary to reuse your configurations in a new backend.

I guess the point of this issue is that there is no easy way of telling Duplicati:
     "I know there are no files there, I changed the backend, please start from scratch."

**Comment by denyeo** [comment] 2017-10-19 12:06
I've run into the same issue. I changed backends and deleted the old archive files on the destination, but I can't seem to re-use the same backup task with the new destination (it just says "verifying remote files"). I guess I'll just have to re-create the backup from scratch.

**Comment by Tralen** [comment] 2017-10-19 17:28
Yes, the best way of repurposing the configuration that I found is:

1. Export the configuration as JSON.
2. Delete the local database.
3. Delete the backup in Duplicati.
4. Delete the "metadata" section in the JSON file, including the closing `}.`. Should be lines 64 to 81.
5. Import the JSON file as a new backup. The same name can be used.
6. Configure the backup for the new backend (this can be done before the export as well).

I wish we had a `Reset Backup` option in the advanced section to make this easier.

**Comment by MvdO** [comment] 2018-01-16 14:15
Same issue, I love Duplicati but I just can't create a new backup all over, keeps giving errors like above.
It's such a advanced software but simply creating a new backup is not possible!

**Comment by Skydiver84de** [comment] 2018-08-21 06:30
Yes same for me. This reset backup option would be a great improvement!

**Comment by ts678** [comment] 2018-08-21 22:47
I think most or all of this is fixed, so some retesting would be in order. The "Last successful run" and similar metadata issues were fixed by @Pectojin in [#2986](https://github.com/duplicati/duplicati/pull/2986) which was merged on Jan 28, 2018. I haven't searched history, but I think there's a discussion here or the forum where someone said that an import always gets a new database. That seems like it should solve the original mention about inconsistent state of the backup.

I just tested on Windows 10 using a more conservative order of export, import, rename, change destination, and save. Came up saying "Last successful backup: Never - Run now". Ran fine. Deleted the original job then renamed the new one onto its name. Repeating the exact original post sequence didn't seem possible, but I might be trying it differently. Reusing the name just gave me a blank job to fill out. Confirmed, though, that database path (visible under Database) is different every time. The one bug was that the old database didn't actually get deleted (even though I left the box checked for that), so it wastes space and might confuse user.

As a side note, many people prefer NOT to start again, but to move destination files to the new destination. There are some notes on migration in the forum.

**Comment by Pectojin** [comment] 2018-08-21 23:01
Can confirm. Always creates a new database. And even the log data in the "main database" is related to a new auto-incremented ID for every new backup. 

Unless you check the import metadata box there should be no data from the old backup job referenced in the new backup job.

The issue with the old database not being deleted is tracked here #3072, but it hasn't seemed to gather a lot of attention since it does nothing but waste local disk space.

**Closed** 2018-08-21 23:04 UTC
Labels: pending user feedback
