### ISSUE TITLE
Failed: 400 - bad_request: invalid sha1

### ISSUE THREAD

**Issue by ormanya** [duplicati/duplicati#2795] opened 2017-10-04 17:20 UTC
- [ X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.9_canary_2017-10-01
- **Operating system**: MacOS High Sierra
- **Backend**: Backblaze B2

## Description

Back fails with following error
`System.Exception: 400 - bad_request: invalid sha1: 15E018BCC3B1B2D382ACB76478ED0E03A4B633DA000000000000000000000000
  at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry (Duplicati.Library.Snapshots.ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend, System.String path, System.IO.FileAttributes attributes) [0x0000e] in <4b690539f7f14b1e8efc3ce9f9bbe28b>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation (Duplicati.Library.Snapshots.ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend) [0x0018a] in <4b690539f7f14b1e8efc3ce9f9bbe28b>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter) [0x008a5] in <4b690539f7f14b1e8efc3ce9f9bbe28b>:0 
  at Duplicati.Library.Main.Controller+<>c__DisplayClass16_0.<Backup>b__0 (Duplicati.Library.Main.BackupResults result) [0x004fc] in <4b690539f7f14b1e8efc3ce9f9bbe28b>:0 
  at Duplicati.Library.Main.Controller.RunAction[T] (T result, System.String[]& paths, Duplicati.Library.Utility.IFilter& filter, System.Action1[T] method) [0x0014b] in <4b690539f7f14b1e8efc3ce9f9bbe28b>:0 
  at Duplicati.Library.Main.Controller.Backup (System.String[] inputsources, Duplicati.Library.Utility.IFilter filter) [0x00068] in <4b690539f7f14b1e8efc3ce9f9bbe28b>:0 
  at Duplicati.Server.Runner.Run (Duplicati.Server.Runner+IRunnerData data, System.Boolean fromQueue) [0x00458] in <540981e70e7e4ba0aaa1a4be2d71e65a>:0 `

## Steps to reproduce

Not sure. It happens to me every time I try to run my Backblaze B2 backup

- **Actual result**:
Backup fails
- **Expected result**:
Backup succeeds

**Comment by NoLooseEnds** [comment] 2017-10-04 21:40
Same issue as mine? #2791

**Comment by kenkendk** [comment] 2017-10-10 13:35
This is caused by the update to using AppleCC for hashing:
https://forum.duplicati.com/t/400-bad-request-invalid-sha1/907/2?u=kenkendk

It was fixed with 78c5bdac0c79e70f7bd2b0b07562aa63ae481982

**Closed by kenkendk** 2017-10-10 13:35 UTC

**Comment by devonhollowood** [comment] 2018-03-09 03:37
Is there a workaround for this, besides switching to the `experimental` channel? I'd like to keep my backups more stable if possible, but I run into this issue for every backup on Mac OS.
