### ISSUE TITLE
Duplicati help <option> crashing on Mono 4.4.2

### ISSUE THREAD

**Issue by kakoskin1** [duplicati/duplicati#2134] opened 2016-11-20 13:16 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:**  2.0.1.32_canary_2016-11-12
**Operating System:** Fedora 25, 
**Mono versio:** 4.4.2-1.fc25  

### Bug description
Command duplicati-cli crashes when called without any arguments or with help <option>. This works in Fedora 24 with Mono 4.2.4. 

### Steps to reproduce
- duplicati-cli
or
- duplicati-cli help <option>

**Expected result:** Help text displayed without crash report.

**Actual result:** 

```
$ duplicati-cli

See duplicati.commandline.exe help <topic> for more information.
  General: example, changelog
  Commands: backup, find, restore, delete, compact, test, compare, repair,
  affected
  Debugging: debug, logging, create-report, test-filters, system-info
  Targets: aftp, amzcd, azure, b2, box, cloudfiles, dropbox, ftp, file, gcs,
  googledrive, hubic, mega, onedrive, openstack, s3, ssh, od4b, mssp, tahoe,
  webdav
  Modules: aes, gpg, zip, 7z, console-password-input, mssql-options,
  hyperv-options, http-options, sendmail, runscript, sendxmpp, check-mono-ssl
  Formats: date, time, size, encryption, compression
  Advanced: mail, advanced, returncodes, filter, <option>

http://www.duplicati.com/              Version:  - 2.0.1.32_canary_2016-11-12




* Assertion: should not be reached at sgen-scan-object.h:101

Stacktrace:


Native stacktrace:

	Duplicati.CommandLine(+0xc3794) [0x55f7840e2794]
	/lib64/libpthread.so.0(+0x115c0) [0x7f6cc22b75c0]
	/lib64/libc.so.6(gsignal+0x9f) [0x7f6cc1cfe92f]
	/lib64/libc.so.6(abort+0x16a) [0x7f6cc1d0052a]
	Duplicati.CommandLine(+0x272499) [0x55f784291499]
	Duplicati.CommandLine(+0x27272c) [0x55f78429172c]
	Duplicati.CommandLine(+0x2728c3) [0x55f7842918c3]
	Duplicati.CommandLine(+0x22fa82) [0x55f78424ea82]
	Duplicati.CommandLine(+0x220f16) [0x55f78423ff16]
	Duplicati.CommandLine(+0x221f5c) [0x55f784240f5c]
	Duplicati.CommandLine(+0x22234a) [0x55f78424134a]
	Duplicati.CommandLine(+0x224af6) [0x55f784243af6]
	Duplicati.CommandLine(+0x2250a7) [0x55f7842440a7]
	Duplicati.CommandLine(+0x1d02da) [0x55f7841ef2da]
	Duplicati.CommandLine(+0x26af4a) [0x55f784289f4a]
	/lib64/libpthread.so.0(+0x76ca) [0x7f6cc22ad6ca]
	/lib64/libc.so.6(clone+0x5f) [0x7f6cc1dd0f6f]

Debug info from gdb:

[New LWP 4747]
[New LWP 4748]
[New LWP 4785]
[New LWP 4786]
[New LWP 4787]
[New LWP 4789]
warning: File "/usr/bin/mono-sgen-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/lib/golang/src/runtime/runtime-gdb.py".
To enable execution of this file add
	add-auto-load-safe-path /usr/bin/mono-sgen-gdb.py
line to your configuration file "/home/huginn/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/huginn/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
warning: File "/usr/bin/mono-sgen-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/lib/golang/src/runtime/runtime-gdb.py".
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007f6cc1cfed16 in sigsuspend () from /lib64/libc.so.6
  Id   Target Id         Frame 
* 1    Thread 0x7f6cc2dd7780 (LWP 4746) "mono" 0x00007f6cc1cfed16 in sigsuspend () from /lib64/libc.so.6
  2    Thread 0x7f6cbabff700 (LWP 4747) "mono" 0x00007f6cc22b3460 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  3    Thread 0x7f6cb9068700 (LWP 4748) "Finalizer" 0x00007f6cc22b5957 in do_futex_wait.constprop () from /lib64/libpthread.so.0
  4    Thread 0x7f6cb8055700 (LWP 4785) "mono" 0x00007f6cc22b3809 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  5    Thread 0x7f6cb39ff700 (LWP 4786) "Threadpool work" 0x00007f6cc22b3809 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  6    Thread 0x7f6cb37fe700 (LWP 4787) "Threadpool work" 0x00007f6cc22b3809 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  7    Thread 0x7f6cb19ff700 (LWP 4789) "Unload thread f" 0x00007f6cc22b6fdb in waitpid () from /lib64/libpthread.so.0

Thread 7 (Thread 0x7f6cb19ff700 (LWP 4789)):
#0  0x00007f6cc22b6fdb in waitpid () from /lib64/libpthread.so.0
#1  0x000055f7840e2870 in mono_handle_native_sigsegv ()
#2  <signal handler called>
#3  0x00007f6cc1cfe92f in raise () from /lib64/libc.so.6
#4  0x00007f6cc1d0052a in abort () from /lib64/libc.so.6
#5  0x000055f784291499 in monoeg_log_default_handler ()
#6  0x000055f78429172c in monoeg_g_logv ()
#7  0x000055f7842918c3 in monoeg_assertion_message ()
#8  0x000055f78424ea82 in drain_gray_stack ()
#9  0x000055f78423ff16 in finish_gray_stack ()
#10 0x000055f784240f5c in major_finish_collection ()
#11 0x000055f78424134a in major_do_collection ()
#12 0x000055f784243af6 in sgen_perform_collection ()
#13 0x000055f7842440a7 in sgen_gc_collect ()
#14 0x000055f7841ef2da in unload_thread_main ()
#15 0x000055f784289f4a in inner_start_thread ()
#16 0x00007f6cc22ad6ca in start_thread () from /lib64/libpthread.so.0
#17 0x00007f6cc1dd0f6f in clone () from /lib64/libc.so.6

Thread 6 (Thread 0x7f6cb37fe700 (LWP 4787)):
#0  0x00007f6cc22b3809 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000055f7841da9ab in worker_thread ()
#2  0x000055f7841d51d6 in start_wrapper ()
#3  0x000055f784289f4a in inner_start_thread ()
#4  0x00007f6cc22ad6ca in start_thread () from /lib64/libpthread.so.0
#5  0x00007f6cc1dd0f6f in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7f6cb39ff700 (LWP 4786)):
#0  0x00007f6cc22b3809 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000055f7841da9ab in worker_thread ()
#2  0x000055f7841d51d6 in start_wrapper ()
#3  0x000055f784289f4a in inner_start_thread ()
#4  0x00007f6cc22ad6ca in start_thread () from /lib64/libpthread.so.0
#5  0x00007f6cc1dd0f6f in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7f6cb8055700 (LWP 4785)):
#0  0x00007f6cc22b3809 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000055f784288a7d in mono_thread_info_sleep ()
#2  0x000055f7841d991e in monitor_thread ()
#3  0x000055f7841d51d6 in start_wrapper ()
#4  0x000055f784289f4a in inner_start_thread ()
#5  0x00007f6cc22ad6ca in start_thread () from /lib64/libpthread.so.0
#6  0x00007f6cc1dd0f6f in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7f6cb9068700 (LWP 4748)):
#0  0x00007f6cc22b5957 in do_futex_wait.constprop () from /lib64/libpthread.so.0
#1  0x00007f6cc22b5a04 in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
#2  0x00007f6cc22b5aaa in sem_wait@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
#3  0x000055f7841f67bb in finalizer_thread ()
#4  0x000055f7841d51d6 in start_wrapper ()
#5  0x000055f784289f4a in inner_start_thread ()
#6  0x00007f6cc22ad6ca in start_thread () from /lib64/libpthread.so.0
#7  0x00007f6cc1dd0f6f in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7f6cbabff700 (LWP 4747)):
#0  0x00007f6cc22b3460 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000055f78425863f in thread_func ()
#2  0x00007f6cc22ad6ca in start_thread () from /lib64/libpthread.so.0
#3  0x00007f6cc1dd0f6f in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f6cc2dd7780 (LWP 4746)):
#0  0x00007f6cc1cfed16 in sigsuspend () from /lib64/libc.so.6
#1  0x000055f7842219e2 in suspend_thread ()
#2  0x000055f784221b9f in suspend_handler ()
#3  <signal handler called>
#4  0x00007f6cc22b345e in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#5  0x000055f78425ee9c in _wapi_handle_timedwait_signal_handle ()
#6  0x000055f784275432 in wapi_WaitForSingleObjectEx ()
#7  0x000055f7841f255f in mono_domain_try_unload ()
#8  0x000055f7841f2644 in mono_domain_unload ()
#9  0x00000000410070e9 in ?? ()
#10 0x00007f6cbad6b0d8 in ?? ()
#11 0x00007f6cbad66d70 in ?? ()
#12 0x00007f6cbac00618 in ?? ()
#13 0x00007f6cbac00340 in ?? ()
#14 0x00007f6cbadf43e8 in ?? ()
#15 0x000055f786610e50 in ?? ()
#16 0x000055f786910b60 in ?? ()
#17 0x00007ffcdb8b1210 in ?? ()
#18 0x00007ffcdb8b0fc0 in ?? ()
#19 0x0000000041006c68 in ?? ()
#20 0x00007f6cbad66d98 in ?? ()
#21 0x0000000040eb11e8 in ?? ()
#22 0x00007ffcdb8b10e0 in ?? ()
#23 0x00007f6cbad523c0 in ?? ()
#24 0x00007ffcdb8b10e8 in ?? ()
#25 0x00007f6cbadf43e8 in ?? ()
#26 0x00007f6cbadf43e8 in ?? ()
#27 0x0000000000000001 in ?? ()
#28 0x0000000000000000 in ?? ()

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Aborted (luotiin core-tiedosto)

```

**Comment by kakoskin1** [comment] 2016-11-20 13:28
This seems to be related to https://github.com/duplicati/duplicati/issues/1892. I hit the crash in same operations that have high change of hitting 1892 and USAGEREPORTER_Duplicati_LEVEL=none duplicati-cli. Unlike 1892 this crash seems to happen consistently.

**Comment by kenkendk** [comment] 2016-12-01 22:21
There is a chance this will be fixed with 2c5d95385f670e599e8fcf3168f3c630cf724b18 as I re-wrote the way it handles the uploads, but I am not sure since I have not been able to reproduce locally.

**Comment by kenkendk** [comment] 2016-12-01 22:22
If this is still a problem, I think I can add a delay to the initial attempt to upload a report, such that it does not happen on exit for "fast" operations.

**Comment by kakoskin1** [comment] 2016-12-05 21:45
I tested version 2.0.1.34_canary_2016-12-05 and didn't see this any more. I'd say that this is fixed.

**Comment by agrajaghh** [comment] 2016-12-06 21:53
thanks for reporting back 😊

**Closed by agrajaghh** 2016-12-06 21:53 UTC
