### ISSUE TITLE
Status window info has extra line breaks and doesn't show fully

### ISSUE THREAD

**Issue by archon810** [duplicati/duplicati#3485] opened 2018-11-10 20:29 UTC
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: v2.0.4.1-2.0.4.1_experimental_2018-11-08
- **Operating system**: OpenSuse 42.3
- **Backend**: Box

## Description

When performing a backup, duplicati shows the backup name and then the rest of the progress is hidden because of line breaks. I can see the data update using Chrome dev tools - see the screenshot. Why are there all these line breaks?

## Steps to reproduce

1. Start backup.

- **Actual result**:
backup name is visible and then the rest is truncated
- **Expected result**:
backup name followed by status info

## Screenshots

![image](https://user-images.githubusercontent.com/469543/48305667-ebd34200-e4e3-11e8-9c30-4c272df5b1ec.png)

**Comment by warwickmm** [comment] 2018-12-02 18:17
Users are [reporting](https://forum.duplicati.com/t/line-break-in-top-status-window-in-chrome/5353) that this is possibly a Chrome-specific issue..

**Comment by KommX** [comment] 2018-12-02 19:41
I can reproduce with Chrome and duplicati 2.0.4.5_beta_2018-11-28.

**Comment by Pectojin** [comment] 2018-12-03 00:08
I've never been able to replicate this with Chrome on MacOS. I'm wondering if it's OS or resolution specific.

**Comment by warwickmm** [comment] 2018-12-03 00:39
Would someone be able to verify that the issue persists even after clearing the browser cache?

**Comment by hausmonarch** [comment] 2018-12-03 14:51
Clearing the browser cache (or at least having devtools open with "Disable Cache" set and F5 reloading) did the trick. Thank you. Maybe some kind of expires header can be added in future updates; the Duplicati GUI is so minimal that reloading isn't really an issue, and since it is a very informational page (particularly the header) I think I wouldn't really want anything cached anyway.

**Comment by Pectojin** [comment] 2018-12-03 15:11
#3515 should address this.

**Comment by warwickmm** [comment] 2018-12-04 01:58
Ok, I'm going to close this then.  Until the changes from pull request #3515 make it into a release, users should try clearing their browser cache.  If that doesn't resolve the issue, then please let us know by re-opening this issue.

**Closed by warwickmm** 2018-12-04 01:58 UTC
Labels: UI, bug
