### ISSUE TITLE
"constraint failed" error

### ISSUE THREAD

**Issue by kees-z** [duplicati/duplicati#2277] opened 2017-01-23 08:31 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.35
**Operating System:** Windows 10
**Backend:** WebDAV

### Bug description
From time to time I get error messages in one or more backup tasks. The message is "constraint error". I get tons of messages and in the result log I see some of them in the section Warnings.
I have no clue what causes these messages.
I suppose the remote files are still reliable, because nothing changed to the source files since the last backup and no remote files seem to be deleted.
But what is the reason for these "constraint failed" messages? Problems with reading the source files? Problems with accessing the sqlite database? Something else?

I get lots of these messages:

_Failed to process path: D:\Path\To\A\File\Filename.ext
System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID
   bij System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   bij System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   bij System.Data.SQLite.SQLiteDataReader.NextResult()
   bij System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   bij System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   bij System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   bij Duplicati.Library.Main.Database.LocalBackupDatabase.AddUnmodifiedFile(Int64 fileid, DateTime lastmodified, IDbTransaction transaction)
   bij Duplicati.Library.Main.Operation.BackupHandler.AddUnmodifiedFile(Int64 oldId, DateTime lastModified)
   bij Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)_

And the Results file looks like this:

_DeletedFiles: 0
DeletedFolders: 0
ModifiedFiles: 0
ExaminedFiles: 18103
OpenedFiles: 823
AddedFiles: 0
SizeOfModifiedFiles: 0
SizeOfAddedFiles: 0
SizeOfExaminedFiles: 4381088076
SizeOfOpenedFiles: 2311703327
NotProcessedFiles: 0
AddedFolders: 0
TooLargeFiles: 0
FilesWithError: 6493
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults: null
DeleteResults:
    DeletedSets: []
    Dryrun: False
    MainOperation: Delete
    CompactResults: null
    EndTime: 23-1-2017 01:09:31
    BeginTime: 23-1-2017 01:09:28
    Duration: 00:00:02.7719880
    BackendStatistics:
        RemoteCalls: 23
        BytesUploaded: 0
        BytesDownloaded: 526650865
        FilesUploaded: 0
        FilesDownloaded: 21
        FilesDeleted: 0
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 1663
        KnownFileSize: 43562694707
        LastBackupDate: 4-1-2017 17:09:37
        BackupListCount: 1
        TotalQuotaSpace: 0
        FreeQuotaSpace: 0
        AssignedQuotaSpace: -1
RepairResults: null
TestResults:
    MainOperation: Test
    Verifications: [
        Key: duplicati-20170104T160937Z.dlist.zip.aes
        Value: [],
        Key: duplicati-i107355c87b30405995acb283eb43facc.dindex.zip.aes
        Value: [],
        Key: duplicati-i1bf91b8dfaf444b18ea76a6281a7fae8.dindex.zip.aes
        Value: [],
        Key: duplicati-i4f0717ce23284ed19a453253df533c4e.dindex.zip.aes
        Value: [],
        Key: duplicati-i7ebc78a617f649c58ab426187d76ef10.dindex.zip.aes
        Value: [],
...
    ]
    EndTime: 23-1-2017 01:11:28
    BeginTime: 23-1-2017 01:09:39
    Duration: 00:01:48.3746030
EndTime: 23-1-2017 01:11:28
BeginTime: 23-1-2017 01:07:26
Duration: 00:04:02.4261257
Messages: [
    No remote filesets were deleted,
    removing file listed as Temporary: duplicati-b7d2ef31dd1cf448f982ebb1fe178b302.dblock.zip.aes,
    removing file listed as Temporary: duplicati-ie012b513780e437488429e1e17c02f7d.dindex.zip.aes
]
Warnings: [
    Failed to process path: D:\Folder\Subfolder\Subfolder\File.ext => constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID,
    Failed to process path: D:\Folder\Subfolder2\Subfolder2\Subfolder2\File2.ext => constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID,
    Failed to process path: D:\Folder\Subfolder3\Subfolder3\File3.ext => constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID,
    Failed to process path: D:\Folder\Subfolder4\Subfolder4\Subfolder4\Subfolder4\File4.ext => constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID,
    Failed to process path: D:\Folder\Subfolder5\Subfolder5\File5.txt => constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID,
...
]
Errors: []_

**NOTE:**
As described in issue #2257, the result code in the email I get is "Successful", should be "Warning".

**Comment by kenkendk** [comment] 2017-01-23 10:09
I think this is a duplicate of #1855 which has been fixed in the latest canary build.

**Comment by kees-z** [comment] 2017-01-23 10:21
Indeed. Overlooked that one. When searching, I only found issues with this message when restoring data without a local database. But #1855 seems to be exactly the same issue.

**Closed** 2017-01-23 10:25 UTC
