### ISSUE TITLE
Restore to original location failed

### ISSUE THREAD

**Issue by madmax0307** [duplicati/duplicati#1774] opened 2016-05-18 08:00 UTC
If I select the Option "Original location" to restore a file, nothing will be restored. Only if I select "Pick location" the file will be restored to the selected location also if the location is the original location.

**Comment by robsonsobral** [comment] 2016-05-18 13:48
duplicate of #1624

**Comment by kenkendk** [comment] 2016-05-18 22:18
#1624 should now be fixed

**Closed by kenkendk** 2016-05-18 22:18 UTC
