### ISSUE TITLE
Duplicati 2: Add icon for web interface

### ISSUE THREAD

**Issue by Nutomic** [duplicati/duplicati#1076] opened 2014-08-05 20:04 UTC
At the moment, it's blank in Firefox 31 with Duplicati 2.0.0.53- 2.0_preview_2014-07-25.

**Comment by rocifier** [comment] 2015-01-18 05:44
Duplicate of https://github.com/duplicati/duplicati/issues/1129

**Closed** 2015-01-20 10:18 UTC
