### ISSUE TITLE
@reboot systemd starts but without .config Ubuntu 20.04

### ISSUE THREAD

**Issue by BoarderEB** [duplicati/duplicati#4264] opened 2020-07-24 11:48 UTC
Hi 

the systemd duplicati service starts after reboot but without configuration.  Likewise, new backup jobs have not the options for encryption and there is no storage type in the backup destination in the unconfigured start.

A _sudo service duplicati stop && sudo duplicati start_ brings back the normal run with the config.

To the Unit I have added _After=mono-xsp4.service_ but unfortunately this was not the solution.
```
$ cat /etc/systemd/system/duplicati.service
[Unit]
Description=Duplicati web-server
After=network.target mono-xsp4.service

[Service]
Nice=19
IOSchedulingClass=idle
EnvironmentFile=-/etc/default/duplicati
ExecStart=/usr/bin/duplicati-server $DAEMON_OPTS
Restart=always

[Install]
WantedBy=multi-user.target
```

```
$ apt-cache policy duplicati 
duplicati:
  Installed: 2.0.5.1-1


  Candidate: 2.0.5.1-1
  Version table:
 *** 2.0.5.1-1 100
        100 /var/lib/dpkg/status
```
![Encrypt](https://user-images.githubusercontent.com/36758401/88389172-3aa73500-cdb6-11ea-9729-72e9231f22f2.png)
![StorageType](https://user-images.githubusercontent.com/36758401/88389157-367b1780-cdb6-11ea-93c1-26e825331d5e.png)

**Comment by BoarderEB** [comment] 2020-07-31 07:31
Even with a _sudo service duplicati stop && sudo service duplicati start_ don't help every time. Someone ideas?

**Comment by warwickmm** [comment] 2020-08-01 21:07
What version of mono are you using?

**Comment by BoarderEB** [comment] 2020-08-03 08:44
Hi, it is 6.10.0.104:

```
$apt-cache policy mono-runtime
mono-runtime:
  Installed: 6.10.0.104-0xamarin16+ubuntu2004b1
  Candidate: 6.10.0.104-0xamarin16+ubuntu2004b1
  Version table:
 *** 6.10.0.104-0xamarin16+ubuntu2004b1 500
        500 https://download.mono-project.com/repo/ubuntu stable-focal/main arm64 Packages
        100 /var/lib/dpkg/status
```

```
$apt-cache policy mono-devel 
mono-devel:
  Installed: 6.10.0.104-0xamarin16+ubuntu2004b1
  Candidate: 6.10.0.104-0xamarin16+ubuntu2004b1
  Version table:
 *** 6.10.0.104-0xamarin16+ubuntu2004b1 500
        500 https://download.mono-project.com/repo/ubuntu stable-focal/main arm64 Packages
        100 /var/lib/dpkg/status
```

**Comment by warwickmm** [comment] 2020-08-09 19:05
Have you tried posting in the forum?

https://forum.duplicati.com/

**Comment by warwickmm** [comment] 2020-08-15 20:16
Closing this because it isn't reproducible.  You might try posting in the forums to see if someone else has encountered this.  The following post sounds related:

https://forum.duplicati.com/t/no-encryption-options-available-in-gui/1728

**Closed by warwickmm** 2020-08-15 20:16 UTC
