### ISSUE TITLE
error "Expected hash not equal to calculated hash" when backing up to s3 compatible storage

### ISSUE THREAD

**Issue by pawan-idrive** [duplicati/duplicati#3465] opened 2018-11-02 05:38 UTC
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: Windows 10
- **Backend**: Swift Object storage

## Description
I am trying to connect to s3 compatible storage ( backed storage is openstack swift object storage),  what I have noticed, I am able to make connection, but data gets upload partially and I get this error **Expected hash not equal to calculated hash**.
Interestingly, If I use signatureversion as 2, everything works good, and, If I use other clients e.g. cyberduck, I am able to connect with signatureversion 4 and all operations are working good.
I have noticed, there is one similar issue #2641 present, but, I didn't find any update over there.

## Steps to reproduce

1. I can send connection details over email, as storage is not available publicly now

- **Actual result**:
**error "Expected hash not equal to calculated hash"**
- **Expected result**:
There should not be any error, data should get uploaded

## Screenshots
N/A
## Debug log
```
2018-11-02 05:04:53Z - Profiling: Starting - ExecuteScalarInt64: SELECT Count(*) FROM "BlocklistHash"
2018-11-02 05:04:53Z - Profiling: ExecuteScalarInt64: SELECT Count(*) FROM "BlocklistHash" took 00:00:00.000
2018-11-02 05:04:53Z - Profiling: Starting - ExecuteScalarInt64: SELECT Count(*) FROM (SELECT DISTINCT "BlocksetID", "Index" FROM "BlocklistHash")
2018-11-02 05:04:53Z - Profiling: ExecuteScalarInt64: SELECT Count(*) FROM (SELECT DISTINCT "BlocksetID", "Index" FROM "BlocklistHash") took 00:00:00.000
2018-11-02 05:04:53Z - Profiling: Starting - ExecuteScalarInt64: SELECT COUNT(*) FROM (SELECT * FROM (SELECT "N"."BlocksetID", (("N"."BlockCount" + 3200 - 1) / 3200) AS "BlocklistHashCountExpected", CASE WHEN "G"."BlocklistHashCount" IS NULL THEN 0 ELSE "G"."BlocklistHashCount" END AS "BlocklistHashCountActual" FROM (SELECT "BlocksetID", COUNT(*) AS "BlockCount" FROM "BlocksetEntry" GROUP BY "BlocksetID") "N" LEFT OUTER JOIN (SELECT "BlocksetID", COUNT(*) AS "BlocklistHashCount" FROM "BlocklistHash" GROUP BY "BlocksetID") "G" ON "N"."BlocksetID" = "G"."BlocksetID" WHERE "N"."BlockCount" > 1) WHERE "BlocklistHashCountExpected" != "BlocklistHashCountActual")
2018-11-02 05:04:53Z - Profiling: ExecuteScalarInt64: SELECT COUNT(*) FROM (SELECT * FROM (SELECT "N"."BlocksetID", (("N"."BlockCount" + 3200 - 1) / 3200) AS "BlocklistHashCountExpected", CASE WHEN "G"."BlocklistHashCount" IS NULL THEN 0 ELSE "G"."BlocklistHashCount" END AS "BlocklistHashCountActual" FROM (SELECT "BlocksetID", COUNT(*) AS "BlockCount" FROM "BlocksetEntry" GROUP BY "BlocksetID") "N" LEFT OUTER JOIN (SELECT "BlocksetID", COUNT(*) AS "BlocklistHashCount" FROM "BlocklistHash" GROUP BY "BlocksetID") "G" ON "N"."BlocksetID" = "G"."BlocksetID" WHERE "N"."BlockCount" > 1) WHERE "BlocklistHashCountExpected" != "BlocklistHashCountActual") took 00:00:00.000
2018-11-02 05:04:53Z - Profiling: Starting - ExecuteScalarInt64: SELECT COUNT(*) FROM "File" WHERE "BlocksetID" != ? AND "BlocksetID" != ? AND NOT "BlocksetID" IN (SELECT "BlocksetID" FROM "BlocksetEntry")
2018-11-02 05:04:53Z - Profiling: ExecuteScalarInt64: SELECT COUNT(*) FROM "File" WHERE "BlocksetID" != ? AND "BlocksetID" != ? AND NOT "BlocksetID" IN (SELECT "BlocksetID" FROM "BlocksetEntry") took 00:00:00.000
2018-11-02 05:04:53Z - Profiling: VerifyConsistency took 00:00:00.000
2018-11-02 05:04:53Z - Profiling: Starting - Uploading a new fileset
2018-11-02 05:04:53Z - Profiling: Starting - CommitUpdateRemoteVolume
2018-11-02 05:04:53Z - Profiling: CommitUpdateRemoteVolume took 00:00:00.131
2018-11-02 05:04:53Z - Profiling: Starting - CommitUpdateRemoteVolume
2018-11-02 05:04:53Z - Profiling: CommitUpdateRemoteVolume took 00:00:00.147
2018-11-02 05:04:53Z - Profiling: Uploading a new fileset took 00:00:00.295
2018-11-02 05:04:53Z - Profiling: Starting - Async backend wait
2018-11-02 05:04:54Z - Profiling: RemoteOperationPut took 00:00:01.335
2018-11-02 05:04:54Z - Warning: Operation Put with file duplicati-b9c5caa80bd4c402f91894d44eef925fc.dblock.zip attempt 1 of 5 failed with message: Expected hash not equal to calculated hash
Amazon.Runtime.AmazonClientException: Expected hash not equal to calculated hash
   at Amazon.S3.Internal.AmazonS3ResponseHandler.CompareHashes(String etag, Byte[] hash)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.ProcessResponseHandlers(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)
   at Amazon.S3.AmazonS3Client.PutObject(PutObjectRequest request)
   at Duplicati.Library.Backend.S3.Put(String remotename, Stream input)
   at Duplicati.Library.Main.BackendManager.DoPut(FileEntryItem item)
   at Duplicati.Library.Main.BackendManager.ThreadRun()
```

**Comment by verhoek** [comment] 2018-11-04 11:56
Maybe we should update the AWSSDK library.
In the past there was an issue https://github.com/aws/aws-sdk-net/issues/474 that got fixed, 
I guess it is in version 3.3.17 used by Duplicati.

@kenkendk : 
What about updating?
Why isn't objectAddRequest.FilePath used and let the aws library take care of things, but instead duplicati opens a stream and passes that to the object?

**Comment by Pectojin** [comment] 2018-11-04 12:00
It seems like 3.3.17 was released in late 2016, https://github.com/aws/aws-sdk-net/releases/tag/3.3.17.0

So to get that fix we'll need to update to a newer AWSSDK version. The fix isn't available before version 3.3.56.1.

**Comment by verhoek** [comment] 2018-11-04 12:12
Actually it's 3.3.17.10 which I could only track down in https://github.com/aws/aws-sdk-net/blob/master/SDK.CHANGELOG.md which is a year old, but more than that I couldn't find. Yes, maybe the fix isn't in there at all.

**Comment by Pectojin** [comment] 2018-11-04 12:16
Hmm, okay, slightly different release. The commit is not tagged into any 3.3.17.X release, though. 

I don't think we have it.
<img width="991" alt="screenshot 2018-11-04 at 13 14 16" src="https://user-images.githubusercontent.com/1561484/47963970-9efaf180-e033-11e8-9449-fdcfff33fc74.png">

**Comment by Pectojin** [comment] 2018-11-04 13:49
I upgraded the 3 AWSSDK packages. It compiles and I'm currently running some manual tests against my minio backend.

    AWSSDK.Core version="3.3.29.3"
    AWSSDK.IdentityManagement version="3.3.7.18"
    AWSSDK.S3 version="3.3.26.5"

I don't know if it will resolve this issue, but it's a start.

**Comment by Pectojin** [comment] 2018-11-04 15:01
Okay, so everything looks good when I use the new packages, I made a pull request for the SDK upgrade.

I don't know how to reproduce the issue, though.

**Comment by verhoek** [comment] 2018-11-04 19:06
Great. It would be nice to have automated integration tests for these services (not only S3) with a technical user account, maybe on a private instance running minio you mentioned in the other issue. 
I cannot test either I'd first have to setup an account or instance on s3.

**Comment by pawan-idrive** [comment] 2018-11-05 02:33
Thanks guys for looking into it, as, I had mentioned in the issue, if s3 credentials are required for my cluster, please drop me an email at pawan.gupta@idrive.com, and, I could provide all required details.

**Comment by kenkendk** [comment] 2018-11-08 08:20
@verhoek Yes, I have considered that for some time, but it is quite a large task setting up (and maintaining) different test servers with SFTP, FTP, S3 etc.

It is possible to store "encypted" credentials on Travis, such that only tests that I submit can access them, and they are not displayed in the logs. With this, it is possible to have backend tests as part of the normal testing setup.

One way could be to have a constant-on test server (say on Digital Ocean) and then run each service in a docker container which would allow us to test different versions.

**Comment by rahulsinghidrive** [comment] 2018-11-12 14:07
I tried building `duplicati` from latest master branch code. I am able to build in both release and debug mode without any errors, but in case of release I am not able to run the application. Please test and update.

**Comment by Pectojin** [comment] 2018-11-12 15:56
Testing in Debug mode should be sufficient, I'm not aware of any issues being replicable only in release mode.

Additionally, the change is in v2.0.3.14, v2.0.4.1, and v2.0.4.2 so you can test those without building any source.

**Comment by pawan-idrive** [comment] 2018-11-13 08:03
I think, we can close this issue now, as with master branch code in debug mode it is working as expected. Also tested with v2.0.3.14 and found it to be working in case of uploads

**Comment by Pectojin** [comment] 2018-11-13 08:09
Ok, we can reopen the issue if it turns out to still be occurring.

**Closed by Pectojin** 2018-11-13 08:09 UTC
Labels: backend issue, bug
