### ISSUE TITLE
2 Job icons instead of 1

### ISSUE THREAD

**Issue by NickPyz** [duplicati/duplicati#3151] opened 2018-04-04 14:14 UTC
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: Duplicati - 2.0.3.4_canary_2018-04-02
- **Operating system**: Windows 10 - 64 bit
- **Backend**: All

## Description

There used to be 1 blue icon beside each job on the web UI. Now there are 2. Seems redundant.

## Steps to reproduce

1. Upgrade version 
2. Open web UI
![chrome_2018-04-04_10-00-45](https://user-images.githubusercontent.com/7215081/38312873-d7326178-37f0-11e8-8efb-d742f2260936.png)

**Comment by kees-z** [comment] 2018-04-04 18:05
This is a known issue:
https://forum.duplicati.com/t/release-2-0-3-4-canary-2018-04-02/3084/2

Looks like it's fixed already and will become available in the next Canary: https://github.com/duplicati/duplicati/commit/e738d9286ac5e956a2c02ac17d3ffa5a6039e109

**Comment by SanduRajapakse** [comment] 2018-04-04 18:05
I am having difficulty reproducing this issue. 

Also on Duplicati - 2.0.3.4_canary_2018-04-02.
Can you try clearing your browser's cache and see if this persists. Also, can you share your page source code?

**Comment by NickPyz** [comment] 2018-04-04 19:55
@kees-z 
Thanks for pointing out that it's a reported issue, and that a fix to style.css is on the way.

@SanduRajapakse 

Not sure why you're not seeing the bug. Perhaps it's depends on the browser. In any event, let's see if Kenneth's fix does the trick for those who are experiencing double icons.

**Comment by SanduRajapakse** [comment] 2018-04-04 21:33
@NickPyz Yep, that's it. I just checked on Firefox and see the issue. It is not reproducible in Chrome. 

AFAIK it is because of the icon for the state is being displayed alongside the regular item icon. I assume it is supposed to be one or the other.

Hopefully, the fix addresses that. Shouldn't be too difficult.

**Comment by Pectojin** [comment] 2018-04-05 17:45
Yes, this is fixed in e738d9286ac5e956a2c02ac17d3ffa5a6039e109. 

I just built from source to verify and it does indeed work as intended. So by 2.0.3.5 it will be fixed.

Now we just have to wait, but this issue is *resolved*

**Closed by Pectojin** 2018-04-05 17:45 UTC
